import { DOCUMENT } from '@angular/common';
import { Component, inject, signal, type OnDestroy } from '@angular/core';
import { TngCodeBlockComponent } from '@tailng-ui/components';
import {
  TngMenu,
  TngMenuGroupLabel,
  TngMenuItem,
  TngMenuSelectEvent,
  TngMenuSeparator,
  TngMenubar,
  TngMenubarItem,
} from '@tailng-ui/primitives';
import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import {
  observeDocsCodeThemeChanges,
  resolveDocsCodeBlockTheme,
} from '../../../../../../shared/util';
import { stackblitzTailwindUrl, stackblitzVanillaUrl } from '../../menubar.util';

function createCodeTabs(
  baseName: string,
  tsCode: string,
  htmlCode: string,
  cssCode: string,
): readonly DocsExampleCodeTab[] {
  return Object.freeze([
    { value: 'ts', label: 'TS', language: 'ts', title: `${baseName}.component.ts`, code: tsCode },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: `${baseName}.component.html`,
      code: htmlCode,
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: `${baseName}.component.css`,
      code: cssCode,
    },
  ]);
}

@Component({
  selector: 'app-headless-menubar-overview-page',
  imports: [
    TngCodeBlockComponent,
    TngMenu,
    TngMenuGroupLabel,
    TngMenuItem,
    TngMenuSeparator,
    TngMenubar,
    TngMenubarItem,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
  ],
  templateUrl: './menubar-overview-page.component.html',
  styleUrls: ['./menubar-overview-page.component.css'],
})
export class HeadlessMenubarOverviewPageComponent implements OnDestroy {
  private readonly documentRef = inject(DOCUMENT);

  public readonly codeBlockTheme = signal<'github-dark' | 'github-light'>(
    resolveDocsCodeBlockTheme(this.documentRef),
  );
  private readonly colorSchemeObserver = observeDocsCodeThemeChanges(
    this.documentRef,
    this.codeBlockTheme,
  );

  protected readonly stackblitzVanillaUrl = stackblitzVanillaUrl;
  protected readonly stackblitzTailwindUrl = stackblitzTailwindUrl;

  protected readonly plainCommand = signal('No command yet');
  protected readonly tailwindCommand = signal('No command yet');

  protected readonly importCode = [
    "import {",
    '  TngMenubar,',
    '  TngMenubarItem,',
    '  TngMenu,',
    '  TngMenuItem,',
    '  TngMenuGroupLabel,',
    '  TngMenuSeparator,',
    "} from '@tailng-ui/primitives';",
    '',
  ].join('\n');

  protected readonly usageCode = [
    '<div tngMenubar aria-label="Workspace commands">',
    '  <div class="menubar-item-shell">',
    '    <div tngMenu #workspaceCommandsFileMenu="tngMenu" aria-label="File menu">',
    '      <div tngMenuGroupLabel>File</div>',
    '      <button type="button" tngMenuItem tngMenuItemValue="Create document">New</button>',
    '      <button type="button" tngMenuItem tngMenuItemValue="Open document">Open</button>',
    '    </div>',
    '    <button type="button" tngMenubarItem [tngMenubarMenu]="workspaceCommandsFileMenu">File</button>',
    '  </div>',
    '</div>',
    '',
  ].join('\n');

  protected readonly plainCodeTabs = createCodeTabs(
    'headless-menubar-overview-plain',
    [
      "import { Component, signal } from '@angular/core';",
      'import {',
      '  TngMenu,',
      '  TngMenuGroupLabel,',
      '  TngMenuItem,',
      '  TngMenuSelectEvent,',
      '  TngMenuSeparator,',
      '  TngMenubar,',
      '  TngMenubarItem,',
      "} from '@tailng-ui/primitives';",
      '',
      '@Component({',
      '  standalone: true,',
      '  imports: [TngMenu, TngMenuGroupLabel, TngMenuItem, TngMenuSeparator, TngMenubar, TngMenubarItem],',
      "  templateUrl: './headless-menubar-overview-plain.component.html',",
      "  styleUrl: './headless-menubar-overview-plain.component.css',",
      '})',
      'export class HeadlessMenubarOverviewPlainComponent {',
      "  protected readonly overviewPlainLastCommand = signal('No command yet');",
      '',
      '  protected onOverviewPlainCommandSelect(event: TngMenuSelectEvent): void {',
      '    this.overviewPlainLastCommand.set(String(event.value));',
      '  }',
      '',
      '  protected onOverviewPlainLeafCommandSelect(value: string): void {',
      '    this.overviewPlainLastCommand.set(value);',
      '  }',
      '}',
      '',
    ].join('\n'),
    [
      '<section class="headless-menubar-overview-plain-card">',
      '  <span class="headless-menubar-overview-plain-kicker">Workspace commands</span>',
      '  <p class="headless-menubar-overview-plain-copy">Keep top-level actions visible while menus own the deeper command tree.</p>',
      '',
      '  <div class="headless-menubar-overview-plain-stage">',
      '    <div tngMenubar aria-label="Workspace commands" class="headless-menubar-overview-plain-shell">',
      '      <div class="headless-menubar-overview-plain-item-shell">',
      '        <div tngMenu #overviewPlainFileMenu="tngMenu" aria-label="File menu" class="headless-menubar-overview-plain-menu" (tngMenuSelect)="onOverviewPlainCommandSelect($event)">',
      '          <div tngMenuGroupLabel class="headless-menubar-overview-plain-group">File</div>',
      '          <button type="button" tngMenuItem tngMenuItemValue="Create document">New</button>',
      '          <button type="button" tngMenuItem tngMenuItemValue="Open document">Open</button>',
      '          <button type="button" tngMenuItem tngMenuItemValue="Save document">Save</button>',
      '        </div>',
      '        <button type="button" tngMenubarItem [tngMenubarMenu]="overviewPlainFileMenu">File</button>',
      '      </div>',
      '',
      '      <div class="headless-menubar-overview-plain-item-shell">',
      '        <div tngMenu #overviewPlainEditMenu="tngMenu" aria-label="Edit menu" class="headless-menubar-overview-plain-menu" (tngMenuSelect)="onOverviewPlainCommandSelect($event)">',
      '          <div tngMenuGroupLabel class="headless-menubar-overview-plain-group">Edit</div>',
      '          <button type="button" tngMenuItem tngMenuItemValue="Undo change">Undo</button>',
      '          <button type="button" tngMenuItem tngMenuItemValue="Redo change">Redo</button>',
      '          <div tngMenuSeparator class="headless-menubar-overview-plain-separator"></div>',
      '          <button type="button" tngMenuItem tngMenuItemValue="Find in page">Find</button>',
      '        </div>',
      '        <button type="button" tngMenubarItem [tngMenubarMenu]="overviewPlainEditMenu">Edit</button>',
      '      </div>',
      '',
      '      <button type="button" tngMenubarItem (click)="onOverviewPlainLeafCommandSelect(\'Help\')">Help</button>',
      '    </div>',
      '  </div>',
      '',
      '  <p class="headless-menubar-overview-plain-state">Last command: <strong>{{ overviewPlainLastCommand() }}</strong></p>',
      '</section>',
      '',
    ].join('\n'),
    [
      '.headless-menubar-overview-plain-card {',
      '  display: grid;',
      '  gap: 0.85rem;',
      '  width: min(100%, 24rem);',
      '  margin-inline: auto;',
      '  padding: 1rem;',
      '  border: 1px solid #cbd5e1;',
      '  border-radius: 1.2rem;',
      '  background: #ffffff;',
      '  color: #0f172a;',
      '  box-shadow: 0 16px 34px rgba(15, 23, 42, 0.08);',
      '}',
      '.headless-menubar-overview-plain-kicker {',
      '  color: #64748b;',
      '  font-size: 0.78rem;',
      '  font-weight: 700;',
      '  letter-spacing: 0.08em;',
      '  text-transform: uppercase;',
      '}',
      '.headless-menubar-overview-plain-copy {',
      '  margin: 0;',
      '  color: #475569;',
      '  line-height: 1.6;',
      '}',
      '.headless-menubar-overview-plain-stage {',
      '  position: relative;',
      '  display: grid;',
      '  justify-items: start;',
      '  align-content: start;',
      '}',
      '.headless-menubar-overview-plain-shell {',
      '  display: inline-flex;',
      '  gap: 0.45rem;',
      '  min-height: 2.7rem;',
      '  padding: 0.32rem;',
      '  border: 1px solid #cbd5e1;',
      '  border-radius: 0.95rem;',
      '  background: linear-gradient(180deg, #ffffff 0%, #f8fafc 100%);',
      '  box-shadow: 0 8px 22px -18px rgba(15, 23, 42, 0.26), 0 10px 32px -24px rgba(15, 23, 42, 0.18);',
      '}',
      '.headless-menubar-overview-plain-item-shell { position: relative; }',
      '.headless-menubar-overview-plain-shell [tngMenubarItem] {',
      '  min-width: 3.3rem;',
      '  min-height: 2.05rem;',
      '  padding: 0.46rem 0.9rem;',
      '  border: 0;',
      '  border-radius: 0.62rem;',
      '  background: transparent;',
      '  color: #0f172a;',
      '  font: inherit;',
      '  font-size: 0.95rem;',
      '  font-weight: 600;',
      '  cursor: pointer;',
      '}',
      '.headless-menubar-overview-plain-shell [tngMenubarItem]:is(:hover, :focus-visible) {',
      '  outline: none;',
      '  background: rgba(37, 99, 235, 0.1);',
      '}',
      '.headless-menubar-overview-plain-shell [tngMenubarItem][tabindex="0"] {',
      '  color: #1d4ed8;',
      '  background: rgba(37, 99, 235, 0.16);',
      '  box-shadow: inset 0 0 0 1px rgba(37, 99, 235, 0.22);',
      '  outline: none;',
      '}',
      '.headless-menubar-overview-plain-shell [tngMenubarItem][aria-expanded="true"] {',
      '  color: #1d4ed8;',
      '  background: rgba(37, 99, 235, 0.16);',
      '}',
      '.headless-menubar-overview-plain-menu {',
      '  position: absolute;',
      '  top: calc(100% + 0.45rem);',
      '  left: 0;',
      '  z-index: 30;',
      '  min-width: 13.8rem;',
      '  padding: 0.45rem;',
      '  border: 1px solid #cbd5e1;',
      '  border-radius: 0.82rem;',
      '  background: #ffffff;',
      '  box-shadow: 0 16px 30px -22px rgba(15, 23, 42, 0.35);',
      '}',
      '.headless-menubar-overview-plain-menu[hidden] { display: none !important; }',
      '.headless-menubar-overview-plain-menu[data-state="open"] { display: grid; gap: 0.24rem; }',
      '.headless-menubar-overview-plain-group {',
      '  padding: 0.25rem 0.45rem;',
      '  color: #64748b;',
      '  font-size: 0.72rem;',
      '  font-weight: 700;',
      '  letter-spacing: 0.08em;',
      '  text-transform: uppercase;',
      '}',
      '.headless-menubar-overview-plain-separator {',
      '  height: 1px;',
      '  margin: 0.2rem 0.35rem;',
      '  background: rgba(148, 163, 184, 0.45);',
      '}',
      '.headless-menubar-overview-plain-menu [tngMenuItem] {',
      '  display: flex;',
      '  justify-content: space-between;',
      '  min-height: 2rem;',
      '  padding: 0.4rem 0.62rem;',
      '  border: 0;',
      '  border-radius: 0.58rem;',
      '  background: transparent;',
      '  color: #0f172a;',
      '  font: inherit;',
      '  font-size: 0.86rem;',
      '  font-weight: 550;',
      '  text-align: left;',
      '  cursor: pointer;',
      '}',
      '.headless-menubar-overview-plain-menu [tngMenuItem]:hover {',
      '  background: rgba(15, 23, 42, 0.06);',
      '}',
      '.headless-menubar-overview-plain-menu [tngMenuItem][data-active],',
      '.headless-menubar-overview-plain-menu [tngMenuItem][aria-expanded="true"] {',
      '  color: #1d4ed8;',
      '  background: rgba(37, 99, 235, 0.16);',
      '}',
      '.headless-menubar-overview-plain-state {',
      '  margin: 0;',
      '  color: #64748b;',
      '  font-size: 0.84rem;',
      '}',
      '',
    ].join('\n'),
  );

  protected readonly tailwindCodeTabs = createCodeTabs(
    'headless-menubar-overview-tailwind',
    [
      "import { Component, signal } from '@angular/core';",
      'import {',
      '  TngMenu,',
      '  TngMenuGroupLabel,',
      '  TngMenuItem,',
      '  TngMenuSelectEvent,',
      '  TngMenuSeparator,',
      '  TngMenubar,',
      '  TngMenubarItem,',
      "} from '@tailng-ui/primitives';",
      '',
      '@Component({',
      '  standalone: true,',
      '  imports: [TngMenu, TngMenuGroupLabel, TngMenuItem, TngMenuSeparator, TngMenubar, TngMenubarItem],',
      "  templateUrl: './headless-menubar-overview-tailwind.component.html',",
      "  styleUrl: './headless-menubar-overview-tailwind.component.css',",
      '})',
      'export class HeadlessMenubarOverviewTailwindComponent {',
      "  protected readonly overviewTailwindLastCommand = signal('No command yet');",
      '',
      '  protected onOverviewTailwindCommandSelect(event: TngMenuSelectEvent): void {',
      '    this.overviewTailwindLastCommand.set(String(event.value));',
      '  }',
      '',
      '  protected onOverviewTailwindLeafCommandSelect(value: string): void {',
      '    this.overviewTailwindLastCommand.set(value);',
      '  }',
      '}',
      '',
    ].join('\n'),
    [
      '<section class="mx-auto grid w-full max-w-[24rem] gap-3 rounded-[1.5rem] border border-slate-200/90 bg-[linear-gradient(180deg,#ffffff_0%,#f8fafc_100%)] p-4 text-slate-900 shadow-[0_18px_38px_rgba(15,23,42,0.10)]">',
      '  <span class="text-xs font-semibold uppercase tracking-[0.22em] text-slate-500">Workspace commands</span>',
      '  <p class="m-0 text-sm leading-6 text-slate-600">Keep top-level actions visible while menus own the deeper command tree.</p>',
      '',
      '  <div class="headless-menubar-overview-tailwind-stage">',
      '    <div tngMenubar aria-label="Workspace commands" class="inline-flex min-h-[2.7rem] gap-[0.45rem] rounded-[0.95rem] border border-slate-300 bg-[linear-gradient(180deg,#ffffff_0%,#f8fafc_100%)] p-[0.32rem] shadow-[0_8px_22px_-18px_rgba(15,23,42,0.26),0_10px_32px_-24px_rgba(15,23,42,0.18)]">',
      '      <div class="relative">',
      '        <div tngMenu #overviewTailwindFileMenu="tngMenu" aria-label="File menu" class="absolute left-0 top-[calc(100%+0.45rem)] z-30 hidden min-w-[13.8rem] rounded-[0.82rem] border border-slate-300 bg-white p-[0.45rem] shadow-[0_16px_30px_-22px_rgba(15,23,42,0.35)] data-[state=open]:grid data-[state=open]:gap-[0.24rem]" (tngMenuSelect)="onOverviewTailwindCommandSelect($event)">',
      '          <div tngMenuGroupLabel class="px-[0.45rem] py-[0.25rem] text-[0.72rem] font-bold uppercase tracking-[0.08em] text-slate-500">File</div>',
      '          <button type="button" tngMenuItem tngMenuItemValue="Create document" class="flex min-h-[2rem] justify-between rounded-[0.58rem] px-[0.62rem] py-[0.4rem] text-left text-[0.86rem] font-medium text-slate-900 outline-none transition hover:bg-slate-100 hover:text-slate-950 focus:bg-blue-100 focus:text-blue-700 focus-visible:ring-2 focus-visible:ring-blue-400/40 [&[data-active]]:bg-blue-100 [&[data-active]]:text-blue-700">New</button>',
      '          <button type="button" tngMenuItem tngMenuItemValue="Open document" class="flex min-h-[2rem] justify-between rounded-[0.58rem] px-[0.62rem] py-[0.4rem] text-left text-[0.86rem] font-medium text-slate-900 outline-none transition hover:bg-slate-100 hover:text-slate-950 focus:bg-blue-100 focus:text-blue-700 focus-visible:ring-2 focus-visible:ring-blue-400/40 [&[data-active]]:bg-blue-100 [&[data-active]]:text-blue-700">Open</button>',
      '          <button type="button" tngMenuItem tngMenuItemValue="Save document" class="flex min-h-[2rem] justify-between rounded-[0.58rem] px-[0.62rem] py-[0.4rem] text-left text-[0.86rem] font-medium text-slate-900 outline-none transition hover:bg-slate-100 hover:text-slate-950 focus:bg-blue-100 focus:text-blue-700 focus-visible:ring-2 focus-visible:ring-blue-400/40 [&[data-active]]:bg-blue-100 [&[data-active]]:text-blue-700">Save</button>',
      '        </div>',
      '        <button type="button" tngMenubarItem [tngMenubarMenu]="overviewTailwindFileMenu" class="headless-menubar-overview-tailwind-item min-h-[2.05rem] min-w-[3.3rem] rounded-[0.62rem] px-[0.9rem] py-[0.46rem] text-[0.95rem] font-semibold text-slate-900 outline-none transition hover:bg-blue-50 hover:text-blue-700 focus:bg-blue-100 focus:text-blue-700 focus:shadow-[inset_0_0_0_1px_rgba(37,99,235,0.22)] focus-visible:ring-2 focus-visible:ring-blue-400/40 aria-[expanded=true]:bg-blue-100 aria-[expanded=true]:text-blue-700 aria-[expanded=true]:shadow-[inset_0_0_0_1px_rgba(37,99,235,0.22)]">File</button>',
      '      </div>',
      '',
      '      <div class="relative">',
      '        <div tngMenu #overviewTailwindToolsMenu="tngMenu" aria-label="Tools menu" class="absolute left-0 top-[calc(100%+0.45rem)] z-30 hidden min-w-[13.8rem] rounded-[0.82rem] border border-slate-300 bg-white p-[0.45rem] shadow-[0_16px_30px_-22px_rgba(15,23,42,0.35)] data-[state=open]:grid data-[state=open]:gap-[0.24rem]" (tngMenuSelect)="onOverviewTailwindCommandSelect($event)">',
      '          <div tngMenuGroupLabel class="px-[0.45rem] py-[0.25rem] text-[0.72rem] font-bold uppercase tracking-[0.08em] text-slate-500">Tools</div>',
      '          <button type="button" tngMenuItem tngMenuItemValue="Run lint" class="flex min-h-[2rem] justify-between rounded-[0.58rem] px-[0.62rem] py-[0.4rem] text-left text-[0.86rem] font-medium text-slate-900 outline-none transition hover:bg-slate-100 hover:text-slate-950 focus:bg-blue-100 focus:text-blue-700 focus-visible:ring-2 focus-visible:ring-blue-400/40 [&[data-active]]:bg-blue-100 [&[data-active]]:text-blue-700">Run lint</button>',
      '          <button type="button" tngMenuItem tngMenuItemValue="Run tests" class="flex min-h-[2rem] justify-between rounded-[0.58rem] px-[0.62rem] py-[0.4rem] text-left text-[0.86rem] font-medium text-slate-900 outline-none transition hover:bg-slate-100 hover:text-slate-950 focus:bg-blue-100 focus:text-blue-700 focus-visible:ring-2 focus-visible:ring-blue-400/40 [&[data-active]]:bg-blue-100 [&[data-active]]:text-blue-700">Run tests</button>',
      '        </div>',
      '        <button type="button" tngMenubarItem [tngMenubarMenu]="overviewTailwindToolsMenu" class="headless-menubar-overview-tailwind-item min-h-[2.05rem] min-w-[3.3rem] rounded-[0.62rem] px-[0.9rem] py-[0.46rem] text-[0.95rem] font-semibold text-slate-900 outline-none transition hover:bg-blue-50 hover:text-blue-700 focus:bg-blue-100 focus:text-blue-700 focus:shadow-[inset_0_0_0_1px_rgba(37,99,235,0.22)] focus-visible:ring-2 focus-visible:ring-blue-400/40 aria-[expanded=true]:bg-blue-100 aria-[expanded=true]:text-blue-700 aria-[expanded=true]:shadow-[inset_0_0_0_1px_rgba(37,99,235,0.22)]">Tools</button>',
      '      </div>',
      '',
      '      <button type="button" tngMenubarItem (click)="onOverviewTailwindLeafCommandSelect(\'Help\')" class="headless-menubar-overview-tailwind-item min-h-[2.05rem] min-w-[3.3rem] rounded-[0.62rem] px-[0.9rem] py-[0.46rem] text-[0.95rem] font-semibold text-slate-900 outline-none transition hover:bg-blue-50 hover:text-blue-700 focus:bg-blue-100 focus:text-blue-700 focus:shadow-[inset_0_0_0_1px_rgba(37,99,235,0.22)] focus-visible:ring-2 focus-visible:ring-blue-400/40">Help</button>',
      '    </div>',
      '  </div>',
      '',
      '  <p class="m-0 text-sm text-slate-500">Last command: <strong>{{ overviewTailwindLastCommand() }}</strong></p>',
      '</section>',
      '',
    ].join('\n'),
    [
      '.headless-menubar-overview-tailwind-stage {',
      '  position: relative;',
      '  display: grid;',
      '  justify-items: start;',
      '  align-content: start;',
      '}',
      '',
      ".headless-menubar-overview-tailwind-item[tabindex='0'] {",
      '  background: rgba(37, 99, 235, 0.16);',
      '  box-shadow: inset 0 0 0 1px rgba(37, 99, 235, 0.22);',
      '  color: #1d4ed8;',
      '  outline: none;',
      '}',
      '',
      ".headless-menubar-overview-tailwind-item[aria-expanded='true'] {",
      '  background: rgba(37, 99, 235, 0.16);',
      '  box-shadow: inset 0 0 0 1px rgba(37, 99, 235, 0.22);',
      '  color: #1d4ed8;',
      '}',
      '',
    ].join('\n'),
  );

  public ngOnDestroy(): void {
    this.colorSchemeObserver?.disconnect();
  }

  protected onPlainCommandSelect(event: TngMenuSelectEvent): void {
    this.plainCommand.set(String(event.value));
  }

  protected onPlainLeafCommandSelect(value: string): void {
    this.plainCommand.set(value);
  }

  protected onTailwindCommandSelect(event: TngMenuSelectEvent): void {
    this.tailwindCommand.set(String(event.value));
  }

  protected onTailwindLeafCommandSelect(value: string): void {
    this.tailwindCommand.set(value);
  }
}
