import { DOCUMENT } from '@angular/common';
import { Component, inject, signal, type OnDestroy } from '@angular/core';
import { observeDocsCodeThemeChanges, resolveDocsCodeBlockTheme } from '../../../../../../shared/util';
import {
  TngCardActionsComponent,
  TngCardComponent,
  TngCardContentComponent,
  TngCardDescriptionComponent,
  TngCardDividerComponent,
  TngCardFooterComponent,
  TngCardHeaderComponent,
  TngCardLinkComponent,
  TngCardMediaComponent,
  TngCardTitleComponent,
} from '@tailng-ui/components';
import { type DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';

@Component({
  selector: 'app-card-examples-page',
  imports: [
    TngCardComponent,
    TngCardHeaderComponent,
    TngCardTitleComponent,
    TngCardDescriptionComponent,
    TngCardContentComponent,
    TngCardMediaComponent,
    TngCardFooterComponent,
    TngCardActionsComponent,
    TngCardDividerComponent,
    TngCardLinkComponent,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
  ],
  templateUrl: './card-examples-page.component.html',
  styleUrl: './card-examples-page.component.css',
})
export class CardExamplesPageComponent implements OnDestroy {
  private readonly documentRef = inject(DOCUMENT);

  public readonly codeBlockTheme = signal<'github-dark' | 'github-light'>(
    resolveDocsCodeBlockTheme(this.documentRef),
  );
  private readonly colorSchemeObserver = observeDocsCodeThemeChanges(
    this.documentRef,
    this.codeBlockTheme,
  );

  protected readonly mediaPlainCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'card-examples-media-plain-css.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import {",
        "  TngCardActionsComponent,",
        "  TngCardComponent,",
        "  TngCardContentComponent,",
        "  TngCardDescriptionComponent,",
        "  TngCardFooterComponent,",
        "  TngCardHeaderComponent,",
        "  TngCardMediaComponent,",
        "  TngCardTitleComponent,",
        "} from '@tailng-ui/components';",
        '',
        '@Component({',
        "  selector: 'app-card-examples-media-plain-css',",
        '  standalone: true,',
        '  imports: [',
        '    TngCardComponent,',
        '    TngCardMediaComponent,',
        '    TngCardHeaderComponent,',
        '    TngCardTitleComponent,',
        '    TngCardDescriptionComponent,',
        '    TngCardContentComponent,',
        '    TngCardFooterComponent,',
        '    TngCardActionsComponent,',
        '  ],',
        "  templateUrl: './card-examples-media-plain-css.component.html',",
        "  styleUrl: './card-examples-media-plain-css.component.css',",
        '})',
        'export class CardExamplesMediaPlainCssComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'card-examples-media-plain-css.component.html',
      code: [
        '<div class="card-example-shell card-example-shell--plain">',
        '  <tng-card variant="outline" tone="neutral" interactive>',
        '    <tng-card-media><div class="card-example__media-placeholder" aria-hidden="true">AV</div></tng-card-media>',
        '    <tng-card-header>',
        '      <tng-card-title>Ava Mathews</tng-card-title>',
        '      <tng-card-description>Design systems engineer</tng-card-description>',
        '    </tng-card-header>',
        '    <tng-card-content>',
        '      <p>Building reusable interaction patterns across product teams.</p>',
        '    </tng-card-content>',
        '    <tng-card-footer>',
        '      <tng-card-actions>',
        '        <button type="button">Message</button>',
        '        <button type="button">Follow</button>',
        '      </tng-card-actions>',
        '    </tng-card-footer>',
        '  </tng-card>',
        '</div>',
        '',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'card-examples-media-plain-css.component.css',
      code: [
        '.card-example-shell--plain {',
        '  border: 1px solid var(--tng-semantic-border-subtle);',
        '  border-radius: 0.9rem;',
        '  padding: 1rem;',
        '}',
        '',
      ].join('\n'),
    },
  ]);

  protected readonly mediaTailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'card-examples-media-tailwind.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import {",
        "  TngCardActionsComponent,",
        "  TngCardComponent,",
        "  TngCardContentComponent,",
        "  TngCardDescriptionComponent,",
        "  TngCardFooterComponent,",
        "  TngCardHeaderComponent,",
        "  TngCardMediaComponent,",
        "  TngCardTitleComponent,",
        "} from '@tailng-ui/components';",
        '',
        '@Component({',
        "  selector: 'app-card-examples-media-tailwind',",
        '  standalone: true,',
        '  imports: [',
        '    TngCardComponent,',
        '    TngCardMediaComponent,',
        '    TngCardHeaderComponent,',
        '    TngCardTitleComponent,',
        '    TngCardDescriptionComponent,',
        '    TngCardContentComponent,',
        '    TngCardFooterComponent,',
        '    TngCardActionsComponent,',
        '  ],',
        "  templateUrl: './card-examples-media-tailwind.component.html',",
        "  styleUrl: './card-examples-media-tailwind.component.css',",
        '})',
        'export class CardExamplesMediaTailwindComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'card-examples-media-tailwind.component.html',
      code: [
        '<div class="rounded-xl border border-slate-300 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-900/60">',
        '  <tng-card variant="outline" tone="primary" padding="lg" interactive>',
        '    <tng-card-media><div class="card-example__media-placeholder" aria-hidden="true">AV</div></tng-card-media>',
        '    <tng-card-header>',
        '      <tng-card-title>Ava Mathews</tng-card-title>',
        '      <tng-card-description>Design systems engineer</tng-card-description>',
        '    </tng-card-header>',
        '    <tng-card-content>',
        '      <p class="text-sm text-slate-600 dark:text-slate-300">',
        '        Building reusable interaction patterns across product teams.',
        '      </p>',
        '    </tng-card-content>',
        '    <tng-card-footer>',
        '      <tng-card-actions>',
        '        <button type="button">Message</button>',
        '        <button type="button">Follow</button>',
        '      </tng-card-actions>',
        '    </tng-card-footer>',
        '  </tng-card>',
        '</div>',
        '',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'card-examples-media-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  protected readonly actionPlainCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'card-examples-actions-plain-css.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import {",
        "  TngCardActionsComponent,",
        "  TngCardComponent,",
        "  TngCardContentComponent,",
        "  TngCardDescriptionComponent,",
        "  TngCardDividerComponent,",
        "  TngCardFooterComponent,",
        "  TngCardHeaderComponent,",
        "  TngCardLinkComponent,",
        "  TngCardTitleComponent,",
        "} from '@tailng-ui/components';",
        '',
        '@Component({',
        "  selector: 'app-card-examples-actions-plain-css',",
        '  standalone: true,',
        '  imports: [',
        '    TngCardComponent,',
        '    TngCardHeaderComponent,',
        '    TngCardTitleComponent,',
        '    TngCardDescriptionComponent,',
        '    TngCardContentComponent,',
        '    TngCardDividerComponent,',
        '    TngCardFooterComponent,',
        '    TngCardLinkComponent,',
        '    TngCardActionsComponent,',
        '  ],',
        "  templateUrl: './card-examples-actions-plain-css.component.html',",
        "  styleUrl: './card-examples-actions-plain-css.component.css',",
        '})',
        'export class CardExamplesActionsPlainCssComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'card-examples-actions-plain-css.component.html',
      code: [
        '<div class="card-example-shell card-example-shell--plain">',
        '  <tng-card variant="outline" tone="warning" padding="md">',
        '    <tng-card-header>',
        '      <tng-card-title>Billing reminder</tng-card-title>',
        '      <tng-card-description>Invoice #3912 is due in 2 days.</tng-card-description>',
        '    </tng-card-header>',
        '    <tng-card-content>',
        '      <p>Assign owner and send reminder before due date.</p>',
        '    </tng-card-content>',
        '    <tng-card-divider></tng-card-divider>',
        '    <tng-card-footer>',
        '      <tng-card-link href="#invoice">Open invoice</tng-card-link>',
        '      <tng-card-actions>',
        '        <button type="button">Snooze</button>',
        '        <button type="button">Assign owner</button>',
        '      </tng-card-actions>',
        '    </tng-card-footer>',
        '  </tng-card>',
        '</div>',
        '',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'card-examples-actions-plain-css.component.css',
      code: [
        '.card-example-shell--plain [data-slot="card-link"] {',
        '  color: var(--tng-semantic-accent-brand);',
        '}',
        '',
      ].join('\n'),
    },
  ]);

  protected readonly actionTailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'card-examples-actions-tailwind.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import {",
        "  TngCardActionsComponent,",
        "  TngCardComponent,",
        "  TngCardContentComponent,",
        "  TngCardDescriptionComponent,",
        "  TngCardDividerComponent,",
        "  TngCardFooterComponent,",
        "  TngCardHeaderComponent,",
        "  TngCardLinkComponent,",
        "  TngCardTitleComponent,",
        "} from '@tailng-ui/components';",
        '',
        '@Component({',
        "  selector: 'app-card-examples-actions-tailwind',",
        '  standalone: true,',
        '  imports: [',
        '    TngCardComponent,',
        '    TngCardHeaderComponent,',
        '    TngCardTitleComponent,',
        '    TngCardDescriptionComponent,',
        '    TngCardContentComponent,',
        '    TngCardDividerComponent,',
        '    TngCardFooterComponent,',
        '    TngCardLinkComponent,',
        '    TngCardActionsComponent,',
        '  ],',
        "  templateUrl: './card-examples-actions-tailwind.component.html',",
        "  styleUrl: './card-examples-actions-tailwind.component.css',",
        '})',
        'export class CardExamplesActionsTailwindComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'card-examples-actions-tailwind.component.html',
      code: [
        '<div class="rounded-xl border border-slate-300 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-900/60">',
        '  <tng-card variant="outline" tone="warning" padding="md" interactive>',
        '    <tng-card-header>',
        '      <tng-card-title>Billing reminder</tng-card-title>',
        '      <tng-card-description>Invoice #3912 is due in 2 days.</tng-card-description>',
        '    </tng-card-header>',
        '    <tng-card-content>',
        '      <p class="text-sm text-slate-600 dark:text-slate-300">',
        '        Assign owner and send reminder before due date.',
        '      </p>',
        '    </tng-card-content>',
        '    <tng-card-divider></tng-card-divider>',
        '    <tng-card-footer>',
        '      <tng-card-link href="#invoice">Open invoice</tng-card-link>',
        '      <tng-card-actions>',
        '        <button type="button">Snooze</button>',
        '        <button type="button">Assign owner</button>',
        '      </tng-card-actions>',
        '    </tng-card-footer>',
        '  </tng-card>',
        '</div>',
        '',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'card-examples-actions-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  public ngOnDestroy(): void {
    this.colorSchemeObserver?.disconnect();
  }
}
