import { DOCUMENT } from '@angular/common';
import { Component, inject, signal, type OnDestroy } from '@angular/core';
import { TngTree, TngTreeGroup, TngTreeIndicator, TngTreeItem } from '@tailng-ui/primitives';
import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import {
  observeDocsCodeThemeChanges,
  resolveDocsCodeBlockTheme,
} from '../../../../../../shared/util';

@Component({
  selector: 'app-headless-tree-examples-page',
  imports: [
    TngTree,
    TngTreeItem,
    TngTreeGroup,
    TngTreeIndicator,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
  ],
  templateUrl: './tree-examples-page.component.html',
  styleUrls: ['./tree-examples-page.component.css'],
})
export class HeadlessTreeExamplesPageComponent implements OnDestroy {
  private readonly documentRef = inject(DOCUMENT);

  public readonly codeBlockTheme = signal<'github-dark' | 'github-light'>(
    resolveDocsCodeBlockTheme(this.documentRef),
  );
  private readonly colorSchemeObserver = observeDocsCodeThemeChanges(
    this.documentRef,
    this.codeBlockTheme,
  );

  protected readonly fileBrowserPlainCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'headless-tree-file-browser-plain.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import { TngTree, TngTreeGroup, TngTreeIndicator, TngTreeItem } from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-headless-tree-file-browser-plain',",
        '  standalone: true,',
        '  imports: [TngTree, TngTreeItem, TngTreeGroup, TngTreeIndicator],',
        "  templateUrl: './headless-tree-file-browser-plain.component.html',",
        "  styleUrl: './headless-tree-file-browser-plain.component.css',",
        '})',
        'export class HeadlessTreeFileBrowserPlainComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'headless-tree-file-browser-plain.component.html',
      code: [
        '<div class="headless-tree-example-shell">',
        '  <div tngTree [selectionMode]="\'single\'" [defaultValue]="\'components\'" aria-label="Repository files" class="headless-tree-example-root">',
        '    <div tngTreeItem [value]="\'workspace\'" [defaultExpanded]="true">',
        '      <span class="tree-node-row"><span tngTreeIndicator class="tree-indicator">📂</span>tailng-ui</span>',
        '      <div tngTreeGroup class="tree-node-group">',
        '        <div tngTreeItem [value]="\'libs\'" [defaultExpanded]="true">',
        '          <span class="tree-node-row"><span tngTreeIndicator class="tree-indicator">📂</span>libs</span>',
        '          <div tngTreeGroup class="tree-node-group">',
        '            <div tngTreeItem [value]="\'components\'"><span class="tree-node-row"><span class="tree-icon">📄</span>components</span></div>',
        '            <div tngTreeItem [value]="\'primitives\'"><span class="tree-node-row"><span class="tree-icon">📄</span>primitives</span></div>',
        '            <div tngTreeItem [value]="\'theme\'"><span class="tree-node-row"><span class="tree-icon">📄</span>theme</span></div>',
        '          </div>',
        '        </div>',
        '        <div tngTreeItem [value]="\'apps\'" [defaultExpanded]="true">',
        '          <span class="tree-node-row"><span tngTreeIndicator class="tree-indicator">📂</span>apps</span>',
        '          <div tngTreeGroup class="tree-node-group">',
        '            <div tngTreeItem [value]="\'docs\'"><span class="tree-node-row"><span class="tree-icon">📄</span>docs</span></div>',
        '            <div tngTreeItem [value]="\'playground\'"><span class="tree-node-row"><span class="tree-icon">📄</span>playground-tailwind</span></div>',
        '          </div>',
        '        </div>',
        '      </div>',
        '    </div>',
        '  </div>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'headless-tree-file-browser-plain.component.css',
      code: [
        '.headless-tree-example-shell {',
        '  border: 1px solid var(--tng-semantic-border-subtle);',
        '  border-radius: 0.9rem;',
        '  padding: 0.9rem 1rem;',
        '}',
        '',
        '.headless-tree-example-root {',
        '  cursor: default;',
        '  font-size: 0.875rem;',
        '  line-height: 1.7rem;',
        '}',
        '',
        ".headless-tree-example-root [data-slot='tree-item'][data-expanded='false'] > [data-slot='tree-group'] {",
        '  display: none;',
        '}',
        '',
        '.tree-node-row {',
        '  align-items: center;',
        '  border-radius: 0.4rem;',
        '  display: inline-flex;',
        '  gap: 0.35rem;',
        '  padding: 0 0.35rem;',
        '}',
        '',
        ".headless-tree-example-root [data-slot='tree-item'][data-selected='true'] > .tree-node-row {",
        '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 14%, transparent);',
        '  color: var(--tng-semantic-accent-brand);',
        '}',
        '',
        '.tree-node-group {',
        '  border-left: 1px solid var(--tng-semantic-border-subtle);',
        '  margin-left: 1.15rem;',
        '  padding-left: 0.75rem;',
        '}',
        '',
        '.tree-icon {',
        '  display: inline-block;',
        '  text-align: center;',
        '  width: 1rem;',
        '}',
      ].join('\n'),
    },
  ]);

  protected readonly fileBrowserTailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'headless-tree-file-browser-tailwind.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import { TngTree, TngTreeGroup, TngTreeIndicator, TngTreeItem } from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-headless-tree-file-browser-tailwind',",
        '  standalone: true,',
        '  imports: [TngTree, TngTreeItem, TngTreeGroup, TngTreeIndicator],',
        "  templateUrl: './headless-tree-file-browser-tailwind.component.html',",
        "  styleUrl: './headless-tree-file-browser-tailwind.component.css',",
        '})',
        'export class HeadlessTreeFileBrowserTailwindComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'headless-tree-file-browser-tailwind.component.html',
      code: [
        '<div class="rounded-xl border border-slate-300 bg-slate-50 p-4 text-sm dark:border-slate-700 dark:bg-slate-900/60 [&_[data-slot=tree-item][data-expanded=false]>.tree-node-group]:hidden [&_[data-slot=tree-item][data-selected=true]>.tree-node-row]:bg-sky-100 [&_[data-slot=tree-item][data-selected=true]>.tree-node-row]:text-sky-900 dark:[&_[data-slot=tree-item][data-selected=true]>.tree-node-row]:bg-sky-900/40 dark:[&_[data-slot=tree-item][data-selected=true]>.tree-node-row]:text-sky-100">',
        '  <div tngTree [selectionMode]="\'single\'" [defaultValue]="\'components\'" aria-label="Repository files" class="leading-7">',
        '    <div tngTreeItem [value]="\'workspace\'" [defaultExpanded]="true">',
        '      <span class="tree-node-row inline-flex items-center gap-1.5 rounded-md px-1.5"><span tngTreeIndicator class="inline-block w-4 text-center text-xs">📂</span>tailng-ui</span>',
        '      <div tngTreeGroup class="tree-node-group ml-5 border-l border-slate-300 pl-3 dark:border-slate-700">',
        '        <div tngTreeItem [value]="\'libs\'" [defaultExpanded]="true">',
        '          <span class="tree-node-row inline-flex items-center gap-1.5 rounded-md px-1.5"><span tngTreeIndicator class="inline-block w-4 text-center text-xs">📂</span>libs</span>',
        '          <div tngTreeGroup class="tree-node-group ml-5 border-l border-slate-300 pl-3 dark:border-slate-700">',
        '            <div tngTreeItem [value]="\'components\'"><span class="tree-node-row inline-flex items-center gap-1.5 rounded-md px-1.5"><span class="tree-icon inline-block w-4 text-center text-xs">📄</span>components</span></div>',
        '            <div tngTreeItem [value]="\'primitives\'"><span class="tree-node-row inline-flex items-center gap-1.5 rounded-md px-1.5"><span class="tree-icon inline-block w-4 text-center text-xs">📄</span>primitives</span></div>',
        '            <div tngTreeItem [value]="\'theme\'"><span class="tree-node-row inline-flex items-center gap-1.5 rounded-md px-1.5"><span class="tree-icon inline-block w-4 text-center text-xs">📄</span>theme</span></div>',
        '          </div>',
        '        </div>',
        '        <div tngTreeItem [value]="\'apps\'" [defaultExpanded]="true">',
        '          <span class="tree-node-row inline-flex items-center gap-1.5 rounded-md px-1.5"><span tngTreeIndicator class="inline-block w-4 text-center text-xs">📂</span>apps</span>',
        '          <div tngTreeGroup class="tree-node-group ml-5 border-l border-slate-300 pl-3 dark:border-slate-700">',
        '            <div tngTreeItem [value]="\'docs\'"><span class="tree-node-row inline-flex items-center gap-1.5 rounded-md px-1.5"><span class="tree-icon inline-block w-4 text-center text-xs">📄</span>docs</span></div>',
        '            <div tngTreeItem [value]="\'playground\'"><span class="tree-node-row inline-flex items-center gap-1.5 rounded-md px-1.5"><span class="tree-icon inline-block w-4 text-center text-xs">📄</span>playground-tailwind</span></div>',
        '          </div>',
        '        </div>',
        '      </div>',
        '    </div>',
        '  </div>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'headless-tree-file-browser-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  protected readonly settingsPlainCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'headless-tree-settings-plain.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import { TngTree, TngTreeGroup, TngTreeIndicator, TngTreeItem } from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-headless-tree-settings-plain',",
        '  standalone: true,',
        '  imports: [TngTree, TngTreeItem, TngTreeGroup, TngTreeIndicator],',
        "  templateUrl: './headless-tree-settings-plain.component.html',",
        "  styleUrl: './headless-tree-settings-plain.component.css',",
        '})',
        'export class HeadlessTreeSettingsPlainComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'headless-tree-settings-plain.component.html',
      code: [
        '<div class="headless-tree-example-shell">',
        '  <div tngTree [selectionMode]="\'single\'" [defaultValue]="\'theme-mode\'" aria-label="Settings" class="headless-tree-example-root">',
        '    <div tngTreeItem [value]="\'general\'" [defaultExpanded]="true">',
        '      <span class="tree-node-row"><span tngTreeIndicator class="tree-indicator">⚙️</span>General</span>',
        '      <div tngTreeGroup class="tree-node-group">',
        '        <div tngTreeItem [value]="\'appearance\'" [defaultExpanded]="true">',
        '          <span class="tree-node-row"><span tngTreeIndicator class="tree-indicator">🎨</span>Appearance</span>',
        '          <div tngTreeGroup class="tree-node-group">',
        '            <div tngTreeItem [value]="\'theme-mode\'"><span class="tree-node-row"><span class="tree-icon">📄</span>Theme mode</span></div>',
        '            <div tngTreeItem [value]="\'font-size\'"><span class="tree-node-row"><span class="tree-icon">📄</span>Font size</span></div>',
        '          </div>',
        '        </div>',
        '      </div>',
        '    </div>',
        '    <div tngTreeItem [value]="\'advanced\'" [defaultExpanded]="true">',
        '      <span class="tree-node-row"><span tngTreeIndicator class="tree-indicator">🛠️</span>Advanced</span>',
        '      <div tngTreeGroup class="tree-node-group">',
        '        <div tngTreeItem [value]="\'developer\'"><span class="tree-node-row"><span class="tree-icon">📄</span>Developer tools</span></div>',
        '        <div tngTreeItem [value]="\'experimental\'" [disabled]="true"><span class="tree-node-row"><span class="tree-icon">📄</span>Experimental</span></div>',
        '      </div>',
        '    </div>',
        '  </div>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'headless-tree-settings-plain.component.css',
      code: [
        '.headless-tree-example-shell {',
        '  border: 1px solid var(--tng-semantic-border-subtle);',
        '  border-radius: 0.9rem;',
        '  padding: 0.9rem 1rem;',
        '}',
        '',
        '.headless-tree-example-root {',
        '  cursor: default;',
        '  font-size: 0.875rem;',
        '  line-height: 1.7rem;',
        '}',
        '',
        ".headless-tree-example-root [data-slot='tree-item'][data-expanded='false'] > [data-slot='tree-group'] {",
        '  display: none;',
        '}',
        '',
        '.tree-node-row {',
        '  align-items: center;',
        '  border-radius: 0.4rem;',
        '  display: inline-flex;',
        '  gap: 0.35rem;',
        '  padding: 0 0.35rem;',
        '}',
        '',
        ".headless-tree-example-root [data-slot='tree-item'][data-selected='true'] > .tree-node-row {",
        '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 14%, transparent);',
        '  color: var(--tng-semantic-accent-brand);',
        '}',
        '',
        ".headless-tree-example-root [data-slot='tree-item'][data-disabled='true'] {",
        '  opacity: 0.55;',
        '}',
        '',
        '.tree-icon {',
        '  display: inline-block;',
        '  text-align: center;',
        '  width: 1rem;',
        '}',
      ].join('\n'),
    },
  ]);

  protected readonly settingsTailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'headless-tree-settings-tailwind.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import { TngTree, TngTreeGroup, TngTreeIndicator, TngTreeItem } from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-headless-tree-settings-tailwind',",
        '  standalone: true,',
        '  imports: [TngTree, TngTreeItem, TngTreeGroup, TngTreeIndicator],',
        "  templateUrl: './headless-tree-settings-tailwind.component.html',",
        "  styleUrl: './headless-tree-settings-tailwind.component.css',",
        '})',
        'export class HeadlessTreeSettingsTailwindComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'headless-tree-settings-tailwind.component.html',
      code: [
        '<div class="rounded-xl border border-slate-300 bg-slate-50 p-4 text-sm dark:border-slate-700 dark:bg-slate-900/60 [&_[data-slot=tree-item][data-expanded=false]>.tree-node-group]:hidden [&_[data-slot=tree-item][data-selected=true]>.tree-node-row]:bg-sky-100 [&_[data-slot=tree-item][data-selected=true]>.tree-node-row]:text-sky-900 [&_[data-slot=tree-item][data-disabled=true]]:opacity-60 dark:[&_[data-slot=tree-item][data-selected=true]>.tree-node-row]:bg-sky-900/40 dark:[&_[data-slot=tree-item][data-selected=true]>.tree-node-row]:text-sky-100">',
        '  <div tngTree [selectionMode]="\'single\'" [defaultValue]="\'theme-mode\'" aria-label="Settings" class="leading-7">',
        '    <div tngTreeItem [value]="\'general\'" [defaultExpanded]="true">',
        '      <span class="tree-node-row inline-flex items-center gap-1.5 rounded-md px-1.5"><span tngTreeIndicator class="inline-block w-4 text-center text-xs">⚙️</span>General</span>',
        '      <div tngTreeGroup class="tree-node-group ml-5 border-l border-slate-300 pl-3 dark:border-slate-700">',
        '        <div tngTreeItem [value]="\'appearance\'" [defaultExpanded]="true">',
        '          <span class="tree-node-row inline-flex items-center gap-1.5 rounded-md px-1.5"><span tngTreeIndicator class="inline-block w-4 text-center text-xs">🎨</span>Appearance</span>',
        '          <div tngTreeGroup class="tree-node-group ml-5 border-l border-slate-300 pl-3 dark:border-slate-700">',
        '            <div tngTreeItem [value]="\'theme-mode\'"><span class="tree-node-row inline-flex items-center gap-1.5 rounded-md px-1.5"><span class="tree-icon inline-block w-4 text-center text-xs">📄</span>Theme mode</span></div>',
        '            <div tngTreeItem [value]="\'font-size\'"><span class="tree-node-row inline-flex items-center gap-1.5 rounded-md px-1.5"><span class="tree-icon inline-block w-4 text-center text-xs">📄</span>Font size</span></div>',
        '          </div>',
        '        </div>',
        '      </div>',
        '    </div>',
        '    <div tngTreeItem [value]="\'advanced\'" [defaultExpanded]="true">',
        '      <span class="tree-node-row inline-flex items-center gap-1.5 rounded-md px-1.5"><span tngTreeIndicator class="inline-block w-4 text-center text-xs">🛠️</span>Advanced</span>',
        '      <div tngTreeGroup class="tree-node-group ml-5 border-l border-slate-300 pl-3 dark:border-slate-700">',
        '        <div tngTreeItem [value]="\'developer\'"><span class="tree-node-row inline-flex items-center gap-1.5 rounded-md px-1.5"><span class="tree-icon inline-block w-4 text-center text-xs">📄</span>Developer tools</span></div>',
        '        <div tngTreeItem [value]="\'experimental\'" [disabled]="true"><span class="tree-node-row inline-flex items-center gap-1.5 rounded-md px-1.5"><span class="tree-icon inline-block w-4 text-center text-xs">📄</span>Experimental</span></div>',
        '      </div>',
        '    </div>',
        '  </div>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'headless-tree-settings-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  public ngOnDestroy(): void {
    this.colorSchemeObserver?.disconnect();
  }
}
