import { DOCUMENT } from '@angular/common';
import { Component, inject, signal, type OnDestroy } from '@angular/core';
import { RouterLink } from '@angular/router';
import {
  TngMenu,
  TngMenuGroupLabel,
  TngMenuItem,
  TngMenuSelectEvent,
  TngMenuSeparator,
  TngMenuTrigger,
} from '@tailng-ui/primitives';
import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import {
  observeDocsCodeThemeChanges,
  resolveDocsCodeBlockTheme,
} from '../../../../../../shared/util';
import { stackblitzTailwindUrl, stackblitzVanillaUrl } from '../../menu.util';

function createCodeTabs(
  baseName: string,
  tsCode: string,
  htmlCode: string,
  cssCode: string,
): readonly DocsExampleCodeTab[] {
  return Object.freeze([
    { value: 'ts', label: 'TS', language: 'ts', title: `${baseName}.component.ts`, code: tsCode },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: `${baseName}.component.html`,
      code: htmlCode,
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: `${baseName}.component.css`,
      code: cssCode,
    },
  ]);
}

function createMenuExamplePlainStarter(prefix: string, withSubmenu: boolean): string {
  const p = prefix;
  const lines: string[] = [
    '.' + p + '-shell { position: relative; display: inline-block; }',
    '.' + p + "-shell [data-slot='menu-trigger'] {",
    '  min-height: 2.05rem;',
    '  padding: 0.46rem 0.9rem;',
    '  border: 1px solid var(--tng-semantic-border-strong);',
    '  border-radius: 0.62rem;',
    '  background: color-mix(in srgb, var(--tng-semantic-background-surface) 90%, transparent);',
    '  box-shadow: 0 1px 2px color-mix(in srgb, var(--tng-semantic-foreground-primary) 8%, transparent);',
    '  color: var(--tng-semantic-foreground-primary);',
    '  font: inherit;',
    '  font-size: 0.95rem;',
    '  font-weight: 600;',
    '  line-height: 1.15;',
    '  cursor: pointer;',
    '  transition:',
    '    background-color 130ms ease,',
    '    border-color 130ms ease,',
    '    color 130ms ease,',
    '    box-shadow 130ms ease;',
    '}',
    '.' + p + "-shell [data-slot='menu-trigger']:hover {",
    '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 14%, var(--tng-semantic-background-surface));',
    '  border-color: color-mix(in srgb, var(--tng-semantic-accent-brand) 45%, var(--tng-semantic-border-strong));',
    '}',
    '.' + p + "-shell [data-slot='menu-trigger']:focus-visible {",
    '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 14%, var(--tng-semantic-background-surface));',
    '  border-color: color-mix(in srgb, var(--tng-semantic-accent-brand) 45%, var(--tng-semantic-border-strong));',
    '  outline: 2px solid var(--tng-semantic-focus-ring);',
    '  outline-offset: 2px;',
    '}',
    '.' + p + "-shell [data-slot='menu-trigger'][aria-expanded='true'] {",
    '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 22%, var(--tng-semantic-background-surface));',
    '  border-color: color-mix(in srgb, var(--tng-semantic-accent-brand) 55%, var(--tng-semantic-border-strong));',
    '  color: var(--tng-semantic-accent-brand);',
    '  box-shadow:',
    '    0 1px 2px color-mix(in srgb, var(--tng-semantic-foreground-primary) 8%, transparent),',
    '    inset 0 0 0 1px color-mix(in srgb, var(--tng-semantic-accent-brand) 35%, transparent);',
    '}',
    '.' + p + '-menu[hidden] { display: none !important; }',
    '.' + p + "-menu[data-state='open'] {",
    '  display: grid;',
    '  gap: 0.24rem;',
    '}',
    '.' + p + '-menu {',
    '  position: absolute;',
    '  left: 0;',
    '  top: calc(100% + 0.45rem);',
    '  z-index: 30;',
    '  min-width: 13.8rem;',
    '  padding: 0.45rem;',
    '  border: 1px solid var(--tng-semantic-border-strong);',
    '  border-radius: 0.82rem;',
    '  background: var(--tng-semantic-background-canvas);',
    '  box-shadow: 0 16px 30px -22px color-mix(in srgb, var(--tng-semantic-foreground-primary) 35%, transparent);',
    '}',
    '.' + p + '-group {',
    '  padding: 0.25rem 0.45rem;',
    '  color: var(--tng-semantic-foreground-secondary);',
    '  font-size: 0.72rem;',
    '  font-weight: 700;',
    '  letter-spacing: 0.08em;',
    '  text-transform: uppercase;',
    '}',
    '.' + p + '-separator {',
    '  height: 1px;',
    '  margin: 0.2rem 0.35rem;',
    '  background: var(--tng-semantic-border-subtle);',
    '}',
    '.' + p + '-menu [tngMenuItem] {',
    '  display: flex;',
    '  justify-content: space-between;',
    '  min-height: 2rem;',
    '  padding: 0.4rem 0.62rem;',
    '  border: 0;',
    '  border-radius: 0.58rem;',
    '  background: transparent;',
    '  color: var(--tng-semantic-foreground-primary);',
    '  font: inherit;',
    '  font-size: 0.86rem;',
    '  font-weight: 550;',
    '  text-align: left;',
    '  cursor: pointer;',
    '}',
    '.' + p + '-menu [tngMenuItem]:hover {',
    '  background: color-mix(in srgb, var(--tng-semantic-foreground-primary) 8%, transparent);',
    '}',
    '.' + p + '-menu [tngMenuItem]:focus-visible {',
    '  outline: 2px solid var(--tng-semantic-focus-ring);',
    '  outline-offset: 2px;',
    '}',
    '.' + p + '-menu [tngMenuItem][data-active],',
    '.' + p + "-menu [tngMenuItem][aria-expanded='true'] {",
    '  color: var(--tng-semantic-accent-brand);',
    '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 22%, transparent);',
    '}',
    '',
  ];

  if (withSubmenu) {
    lines.push(
      '.' + p + '-menu--submenu { left: calc(100% + 0.42rem); }',
      '.' + p + '-menu--level-1 { top: 2.7rem; }',
      '.' + p + '-menu--level-2 { top: 5.5rem; }',
      '',
    );
  }

  return lines.join('\n');
}

@Component({
  selector: 'app-headless-menu-examples-page',
  imports: [
    RouterLink,
    TngMenu,
    TngMenuGroupLabel,
    TngMenuItem,
    TngMenuSeparator,
    TngMenuTrigger,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
  ],
  templateUrl: './menu-examples-page.component.html',
  styleUrls: ['./menu-examples-page.component.css'],
})
export class HeadlessMenuExamplesPageComponent implements OnDestroy {
  private readonly documentRef = inject(DOCUMENT);

  public readonly codeBlockTheme = signal<'github-dark' | 'github-light'>(
    resolveDocsCodeBlockTheme(this.documentRef),
  );
  private readonly colorSchemeObserver = observeDocsCodeThemeChanges(
    this.documentRef,
    this.codeBlockTheme,
  );

  protected readonly dropdownPlainCommand = signal('No action yet');
  protected readonly dropdownTailwindCommand = signal('No action yet');
  protected readonly nestedPlainCommand = signal('No command yet');
  protected readonly nestedTailwindCommand = signal('No command yet');

  protected readonly stackblitzVanillaUrl = stackblitzVanillaUrl;
  protected readonly stackblitzTailwindUrl = stackblitzTailwindUrl;

  protected readonly dropdownPlainCodeTabs = createCodeTabs(
    'headless-menu-example-drop-plain',
    [
      "import { Component, signal } from '@angular/core';",
      'import {',
      '  TngMenu,',
      '  TngMenuGroupLabel,',
      '  TngMenuItem,',
      '  TngMenuSelectEvent,',
      '  TngMenuTrigger,',
      "} from '@tailng-ui/primitives';",
      '',
      '@Component({',
      '  standalone: true,',
      '  imports: [TngMenu, TngMenuGroupLabel, TngMenuItem, TngMenuTrigger],',
      "  templateUrl: './headless-menu-example-drop-plain.component.html',",
      "  styleUrl: './headless-menu-example-drop-plain.component.css',",
      '})',
      'export class HeadlessMenuExampleDropPlainComponent {',
      "  protected readonly lastAction = signal('No action yet');",
      '',
      '  protected onAction(event: TngMenuSelectEvent): void {',
      '    this.lastAction.set(String(event.value));',
      '  }',
      '}',
      '',
    ].join('\n'),
    [
      '<div class="headless-menu-example-drop-plain-stage">',
      '  <div class="headless-menu-example-drop-plain-shell">',
      '    <button type="button" [tngMenuTrigger]="actionsMenu">Open actions</button>',
      '    <div',
      '      tngMenu',
      '      #actionsMenu="tngMenu"',
      '      aria-label="Quick actions"',
      '      class="headless-menu-example-drop-plain-menu"',
      '      (tngMenuSelect)="onAction($event)"',
      '    >',
      '      <div tngMenuGroupLabel class="headless-menu-example-drop-plain-group">Recent</div>',
      '      <button type="button" tngMenuItem tngMenuItemValue="copy">Copy</button>',
      '      <button type="button" tngMenuItem tngMenuItemValue="paste">Paste</button>',
      '    </div>',
      '  </div>',
      '</div>',
      '',
    ].join('\n'),
    createMenuExamplePlainStarter('headless-menu-example-drop-plain', false),
  );

  protected readonly dropdownTailwindCodeTabs = createCodeTabs(
    'headless-menu-example-drop-tailwind',
    [
      "import { Component, signal } from '@angular/core';",
      "import { TngMenu, TngMenuGroupLabel, TngMenuItem, TngMenuSelectEvent, TngMenuTrigger } from '@tailng-ui/primitives';",
      '',
      '@Component({',
      '  standalone: true,',
      '  imports: [TngMenu, TngMenuGroupLabel, TngMenuItem, TngMenuTrigger],',
      "  templateUrl: './headless-menu-example-drop-tailwind.component.html',",
      "  styleUrl: './headless-menu-example-drop-tailwind.component.css',",
      '})',
      'export class HeadlessMenuExampleDropTailwindComponent {',
      "  protected readonly lastAction = signal('No action yet');",
      '',
      '  protected onAction(event: TngMenuSelectEvent): void {',
      '    this.lastAction.set(String(event.value));',
      '  }',
      '}',
      '',
    ].join('\n'),
    [
      '<div class="relative grid justify-items-start content-start">',
      '  <div class="relative inline-block">',
      '    <button',
      '      type="button"',
      '      [tngMenuTrigger]="actionsMenu"',
      '      class="headless-menu-example-tailwind-trigger min-h-[2.05rem] rounded-[0.62rem] px-[0.9rem] py-[0.46rem] text-[0.95rem] font-semibold"',
      '    >',
      '      Open actions',
      '    </button>',
      '    <div',
      '      tngMenu',
      '      #actionsMenu="tngMenu"',
      '      aria-label="Quick actions"',
      '      class="headless-menu-example-tw-panel absolute left-0 top-[calc(100%+0.45rem)] z-30 hidden min-w-[13.8rem] p-[0.45rem] data-[state=open]:grid data-[state=open]:gap-[0.24rem]"',
      '      (tngMenuSelect)="onAction($event)"',
      '    >',
      '      <div tngMenuGroupLabel class="headless-menu-example-tw-label px-[0.45rem] py-[0.25rem]">Recent</div>',
      '      <button type="button" tngMenuItem tngMenuItemValue="copy" class="headless-menu-example-tw-item flex min-h-[2rem] justify-between px-[0.62rem] py-[0.4rem] text-left">Copy</button>',
      '      <button type="button" tngMenuItem tngMenuItemValue="paste" class="headless-menu-example-tw-item flex min-h-[2rem] justify-between px-[0.62rem] py-[0.4rem] text-left">Paste</button>',
      '    </div>',
      '  </div>',
      '</div>',
      '',
    ].join('\n'),
    [
      '.headless-menu-example-tailwind-trigger {',
      '  background: color-mix(in srgb, var(--tng-semantic-background-surface) 90%, transparent);',
      '  border: 1px solid var(--tng-semantic-border-strong);',
      '  box-shadow: 0 1px 2px color-mix(in srgb, var(--tng-semantic-foreground-primary) 8%, transparent);',
      '  color: var(--tng-semantic-foreground-primary);',
      '  transition:',
      '    background-color 130ms ease,',
      '    border-color 130ms ease,',
      '    color 130ms ease,',
      '    box-shadow 130ms ease;',
      '}',
      '.headless-menu-example-tailwind-trigger:hover {',
      '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 14%, var(--tng-semantic-background-surface));',
      '  border-color: color-mix(in srgb, var(--tng-semantic-accent-brand) 45%, var(--tng-semantic-border-strong));',
      '}',
      '.headless-menu-example-tailwind-trigger:focus-visible {',
      '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 14%, var(--tng-semantic-background-surface));',
      '  border-color: color-mix(in srgb, var(--tng-semantic-accent-brand) 45%, var(--tng-semantic-border-strong));',
      '  outline: 2px solid var(--tng-semantic-focus-ring);',
      '  outline-offset: 2px;',
      '}',
      '.headless-menu-example-tailwind-trigger[aria-expanded="true"] {',
      '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 22%, var(--tng-semantic-background-surface));',
      '  border-color: color-mix(in srgb, var(--tng-semantic-accent-brand) 55%, var(--tng-semantic-border-strong));',
      '  box-shadow:',
      '    0 1px 2px color-mix(in srgb, var(--tng-semantic-foreground-primary) 8%, transparent),',
      '    inset 0 0 0 1px color-mix(in srgb, var(--tng-semantic-accent-brand) 35%, transparent);',
      '  color: var(--tng-semantic-accent-brand);',
      '}',
      '.headless-menu-example-tw-panel {',
      '  background: var(--tng-semantic-background-canvas);',
      '  border: 1px solid var(--tng-semantic-border-strong);',
      '  border-radius: 0.82rem;',
      '  box-shadow: 0 16px 30px -22px color-mix(in srgb, var(--tng-semantic-foreground-primary) 35%, transparent);',
      '}',
      '.headless-menu-example-tw-label {',
      '  color: var(--tng-semantic-foreground-secondary);',
      '  font-size: 0.72rem;',
      '  font-weight: 700;',
      '  letter-spacing: 0.08em;',
      '  text-transform: uppercase;',
      '}',
      '.headless-menu-example-tw-item {',
      '  background: transparent;',
      '  border-radius: 0.58rem;',
      '  color: var(--tng-semantic-foreground-primary);',
      '  font-size: 0.86rem;',
      '  font-weight: 500;',
      '  outline: none;',
      '  transition:',
      '    background-color 120ms ease,',
      '    color 120ms ease;',
      '}',
      '.headless-menu-example-tw-item:hover {',
      '  background: color-mix(in srgb, var(--tng-semantic-foreground-primary) 8%, transparent);',
      '}',
      '.headless-menu-example-tw-item:focus-visible {',
      '  outline: 2px solid var(--tng-semantic-focus-ring);',
      '  outline-offset: 2px;',
      '}',
      '.headless-menu-example-tw-item[data-active] {',
      '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 22%, transparent);',
      '  color: var(--tng-semantic-accent-brand);',
      '}',
      '',
    ].join('\n'),
  );

  protected readonly nestedPlainCodeTabs = createCodeTabs(
    'headless-menu-example-nested-plain',
    [
      "import { Component, signal } from '@angular/core';",
      "import { TngMenu, TngMenuItem, TngMenuSelectEvent, TngMenuSeparator, TngMenuTrigger } from '@tailng-ui/primitives';",
      '',
      '@Component({',
      '  standalone: true,',
      '  imports: [TngMenu, TngMenuItem, TngMenuSeparator, TngMenuTrigger],',
      "  templateUrl: './headless-menu-example-nested-plain.component.html',",
      "  styleUrl: './headless-menu-example-nested-plain.component.css',",
      '})',
      'export class HeadlessMenuExampleNestedPlainComponent {',
      "  protected readonly lastCommand = signal('No command yet');",
      '',
      '  protected onCommand(event: TngMenuSelectEvent): void {',
      '    this.lastCommand.set(String(event.value));',
      '  }',
      '}',
      '',
    ].join('\n'),
    [
      '<div class="headless-menu-example-nested-plain-stage">',
      '  <div class="headless-menu-example-nested-plain-shell">',
      '    <button type="button" [tngMenuTrigger]="fileMenu">File</button>',
      '    <div',
      '      tngMenu',
      '      #fileMenu="tngMenu"',
      '      aria-label="File menu"',
      '      class="headless-menu-example-nested-plain-menu"',
      '      (tngMenuSelect)="onCommand($event)"',
      '    >',
      '      <button type="button" tngMenuItem tngMenuItemValue="new-notebook">New notebook</button>',
      '      <button type="button" tngMenuItem [tngMenuItemSubmenu]="importMenu" tngMenuItemValue="import">Import…</button>',
      '      <div tngMenuSeparator class="headless-menu-example-nested-plain-separator"></div>',
      '      <button type="button" tngMenuItem tngMenuItemValue="close">Close</button>',
      '',
      '      <div',
      '        tngMenu',
      '        #importMenu="tngMenu"',
      '        aria-label="Import sources"',
      '        class="headless-menu-example-nested-plain-menu headless-menu-example-nested-plain-menu--submenu headless-menu-example-nested-plain-menu--level-1"',
      '        (tngMenuSelect)="onCommand($event)"',
      '      >',
      '        <button type="button" tngMenuItem tngMenuItemValue="csv">CSV file</button>',
      '        <button type="button" tngMenuItem [tngMenuItemSubmenu]="gitMenu" tngMenuItemValue="git">Git repository</button>',
      '      </div>',
      '',
      '      <div',
      '        tngMenu',
      '        #gitMenu="tngMenu"',
      '        aria-label="Git hosts"',
      '        class="headless-menu-example-nested-plain-menu headless-menu-example-nested-plain-menu--submenu headless-menu-example-nested-plain-menu--level-2"',
      '        (tngMenuSelect)="onCommand($event)"',
      '      >',
      '        <button type="button" tngMenuItem tngMenuItemValue="github">GitHub</button>',
      '        <button type="button" tngMenuItem tngMenuItemValue="gitlab">GitLab</button>',
      '      </div>',
      '    </div>',
      '  </div>',
      '</div>',
      '',
    ].join('\n'),
    createMenuExamplePlainStarter('headless-menu-example-nested-plain', true),
  );

  protected readonly nestedTailwindCodeTabs = createCodeTabs(
    'headless-menu-example-nested-tailwind',
    [
      "import { Component, signal } from '@angular/core';",
      "import { TngMenu, TngMenuItem, TngMenuSelectEvent, TngMenuSeparator, TngMenuTrigger } from '@tailng-ui/primitives';",
      '',
      '@Component({',
      '  standalone: true,',
      '  imports: [TngMenu, TngMenuItem, TngMenuSeparator, TngMenuTrigger],',
      "  templateUrl: './headless-menu-example-nested-tailwind.component.html',",
      "  styleUrl: './headless-menu-example-nested-tailwind.component.css',",
      '})',
      'export class HeadlessMenuExampleNestedTailwindComponent {',
      "  protected readonly lastCommand = signal('No command yet');",
      '',
      '  protected onCommand(event: TngMenuSelectEvent): void {',
      '    this.lastCommand.set(String(event.value));',
      '  }',
      '}',
      '',
    ].join('\n'),
    [
      '<div class="relative grid justify-items-start content-start">',
      '  <div class="relative inline-block">',
      '    <button',
      '      type="button"',
      '      [tngMenuTrigger]="fileMenu"',
      '      class="headless-menu-example-tailwind-trigger min-h-[2.05rem] rounded-[0.62rem] px-[0.9rem] py-[0.46rem] text-[0.95rem] font-semibold"',
      '    >',
      '      File',
      '    </button>',
      '    <div',
      '      tngMenu',
      '      #fileMenu="tngMenu"',
      '      aria-label="File menu"',
      '      class="headless-menu-example-tw-panel absolute left-0 top-[calc(100%+0.45rem)] z-30 hidden min-w-[13.8rem] p-[0.45rem] data-[state=open]:grid data-[state=open]:gap-[0.24rem]"',
      '      (tngMenuSelect)="onCommand($event)"',
      '    >',
      '      <button type="button" tngMenuItem tngMenuItemValue="new-notebook" class="headless-menu-example-tw-item flex min-h-[2rem] justify-between px-[0.62rem] py-[0.4rem] text-left">New notebook</button>',
      '      <button type="button" tngMenuItem [tngMenuItemSubmenu]="importMenu" tngMenuItemValue="import" class="headless-menu-example-tw-item flex min-h-[2rem] justify-between px-[0.62rem] py-[0.4rem] text-left">Import…</button>',
      '      <div tngMenuSeparator class="headless-menu-example-tw-sep mx-[0.35rem] my-[0.2rem] h-px"></div>',
      '      <button type="button" tngMenuItem tngMenuItemValue="close" class="headless-menu-example-tw-item flex min-h-[2rem] justify-between px-[0.62rem] py-[0.4rem] text-left">Close</button>',
      '',
      '      <div',
      '        tngMenu',
      '        #importMenu="tngMenu"',
      '        aria-label="Import sources"',
      '        class="headless-menu-example-tw-panel absolute left-[calc(100%+0.42rem)] top-[2.7rem] z-30 hidden min-w-[13.8rem] p-[0.45rem] data-[state=open]:grid data-[state=open]:gap-[0.24rem]"',
      '        (tngMenuSelect)="onCommand($event)"',
      '      >',
      '        <button type="button" tngMenuItem tngMenuItemValue="csv" class="headless-menu-example-tw-item flex min-h-[2rem] justify-between px-[0.62rem] py-[0.4rem] text-left">CSV file</button>',
      '        <button type="button" tngMenuItem [tngMenuItemSubmenu]="gitMenu" tngMenuItemValue="git" class="headless-menu-example-tw-item flex min-h-[2rem] justify-between px-[0.62rem] py-[0.4rem] text-left">Git repository</button>',
      '      </div>',
      '',
      '      <div',
      '        tngMenu',
      '        #gitMenu="tngMenu"',
      '        aria-label="Git hosts"',
      '        class="headless-menu-example-tw-panel absolute left-[calc(100%+0.42rem)] top-[5.5rem] z-30 hidden min-w-[13.8rem] p-[0.45rem] data-[state=open]:grid data-[state=open]:gap-[0.24rem]"',
      '        (tngMenuSelect)="onCommand($event)"',
      '      >',
      '        <button type="button" tngMenuItem tngMenuItemValue="github" class="headless-menu-example-tw-item flex min-h-[2rem] justify-between px-[0.62rem] py-[0.4rem] text-left">GitHub</button>',
      '        <button type="button" tngMenuItem tngMenuItemValue="gitlab" class="headless-menu-example-tw-item flex min-h-[2rem] justify-between px-[0.62rem] py-[0.4rem] text-left">GitLab</button>',
      '      </div>',
      '    </div>',
      '  </div>',
      '</div>',
      '',
    ].join('\n'),
    [
      '.headless-menu-example-tailwind-trigger {',
      '  background: color-mix(in srgb, var(--tng-semantic-background-surface) 90%, transparent);',
      '  border: 1px solid var(--tng-semantic-border-strong);',
      '  box-shadow: 0 1px 2px color-mix(in srgb, var(--tng-semantic-foreground-primary) 8%, transparent);',
      '  color: var(--tng-semantic-foreground-primary);',
      '  transition:',
      '    background-color 130ms ease,',
      '    border-color 130ms ease,',
      '    color 130ms ease,',
      '    box-shadow 130ms ease;',
      '}',
      '.headless-menu-example-tailwind-trigger:hover {',
      '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 14%, var(--tng-semantic-background-surface));',
      '  border-color: color-mix(in srgb, var(--tng-semantic-accent-brand) 45%, var(--tng-semantic-border-strong));',
      '}',
      '.headless-menu-example-tailwind-trigger:focus-visible {',
      '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 14%, var(--tng-semantic-background-surface));',
      '  border-color: color-mix(in srgb, var(--tng-semantic-accent-brand) 45%, var(--tng-semantic-border-strong));',
      '  outline: 2px solid var(--tng-semantic-focus-ring);',
      '  outline-offset: 2px;',
      '}',
      '.headless-menu-example-tailwind-trigger[aria-expanded="true"] {',
      '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 22%, var(--tng-semantic-background-surface));',
      '  border-color: color-mix(in srgb, var(--tng-semantic-accent-brand) 55%, var(--tng-semantic-border-strong));',
      '  box-shadow:',
      '    0 1px 2px color-mix(in srgb, var(--tng-semantic-foreground-primary) 8%, transparent),',
      '    inset 0 0 0 1px color-mix(in srgb, var(--tng-semantic-accent-brand) 35%, transparent);',
      '  color: var(--tng-semantic-accent-brand);',
      '}',
      '.headless-menu-example-tw-panel {',
      '  background: var(--tng-semantic-background-canvas);',
      '  border: 1px solid var(--tng-semantic-border-strong);',
      '  border-radius: 0.82rem;',
      '  box-shadow: 0 16px 30px -22px color-mix(in srgb, var(--tng-semantic-foreground-primary) 35%, transparent);',
      '}',
      '.headless-menu-example-tw-item {',
      '  background: transparent;',
      '  border-radius: 0.58rem;',
      '  color: var(--tng-semantic-foreground-primary);',
      '  font-size: 0.86rem;',
      '  font-weight: 500;',
      '  outline: none;',
      '  transition:',
      '    background-color 120ms ease,',
      '    color 120ms ease;',
      '}',
      '.headless-menu-example-tw-item:hover {',
      '  background: color-mix(in srgb, var(--tng-semantic-foreground-primary) 8%, transparent);',
      '}',
      '.headless-menu-example-tw-item:focus-visible {',
      '  outline: 2px solid var(--tng-semantic-focus-ring);',
      '  outline-offset: 2px;',
      '}',
      '.headless-menu-example-tw-item[data-active] {',
      '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 22%, transparent);',
      '  color: var(--tng-semantic-accent-brand);',
      '}',
      '.headless-menu-example-tw-sep {',
      '  background: var(--tng-semantic-border-subtle);',
      '}',
      '',
    ].join('\n'),
  );

  public ngOnDestroy(): void {
    this.colorSchemeObserver?.disconnect();
  }

  protected onDropdownPlainSelect(event: TngMenuSelectEvent): void {
    this.dropdownPlainCommand.set(String(event.value));
  }

  protected onDropdownTailwindSelect(event: TngMenuSelectEvent): void {
    this.dropdownTailwindCommand.set(String(event.value));
  }

  protected onNestedPlainSelect(event: TngMenuSelectEvent): void {
    this.nestedPlainCommand.set(String(event.value));
  }

  protected onNestedTailwindSelect(event: TngMenuSelectEvent): void {
    this.nestedTailwindCommand.set(String(event.value));
  }
}
