import type { TngChartResolvedTheme } from './chart-theme.types';

export const TNG_CHART_SOURCE_DATUM_KEY = '__tngDatum';

export const TNG_CHART_DEFAULT_THEME: TngChartResolvedTheme = {
  axisLabelColor: '#6b7280',
  axisLineColor: '#d1d5db',
  backgroundColor: '#ffffff',
  borderColor: '#d1d5db',
  dangerColor: '#dc2626',
  foregroundColor: '#111827',
  gridLineColor: '#d1d5db',
  heatmapHighColor: '#2563eb',
  heatmapLowColor: '#dbeafe',
  heatmapMidColor: '#0ea5e9',
  infoColor: '#0ea5e9',
  mutedColor: '#6b7280',
  mutedTextColor: '#6b7280',
  palette: ['#2563eb', '#10b981', '#f59e0b', '#ef4444', '#0ea5e9', '#8b5cf6'],
  primaryColor: '#2563eb',
  successColor: '#10b981',
  surfaceColor: '#ffffff',
  textColor: '#111827',
  tooltipBackgroundColor: '#ffffff',
  tooltipBorderColor: '#d1d5db',
  warningColor: '#f59e0b',
};

export const TNG_CHART_CSS_VARIABLES = {
  axisLabel: [
    '--tng-chart-axis-label',
    '--tng-semantic-foreground-muted',
    '--tng-semantic-foreground-secondary',
    '--color-muted',
  ],
  axisLine: [
    '--tng-chart-axis-line',
    '--tng-chart-border',
    '--tng-semantic-border-subtle',
    '--tng-semantic-border-default',
    '--color-border',
  ],
  background: [
    '--tng-chart-background',
    '--tng-semantic-background-canvas',
    '--tng-semantic-background-base',
    '--color-bg',
  ],
  border: [
    '--tng-chart-border',
    '--tng-semantic-border-subtle',
    '--tng-semantic-border-default',
    '--color-border',
  ],
  danger: ['--tng-chart-danger', '--tng-semantic-accent-danger', '--color-danger'],
  foreground: ['--tng-chart-fg', '--tng-semantic-foreground-primary', '--color-fg'],
  gridLine: [
    '--tng-chart-grid-line',
    '--tng-chart-border',
    '--tng-semantic-border-subtle',
    '--tng-semantic-border-default',
    '--color-border',
  ],
  heatmapHigh: [
    '--tng-chart-heatmap-high',
    '--tng-semantic-accent-brand',
    '--color-primary',
  ],
  heatmapLow: [
    '--tng-chart-heatmap-low',
    '--tng-semantic-background-muted',
    '--tng-semantic-background-surface',
    '--color-surface',
  ],
  heatmapMid: [
    '--tng-chart-heatmap-mid',
    '--tng-chart-info',
    '--color-info',
    '--tng-color-sky500',
    '--tng-color-cyan500',
  ],
  info: ['--tng-chart-info', '--color-info', '--tng-color-sky500', '--tng-color-cyan500'],
  muted: [
    '--tng-chart-muted',
    '--tng-semantic-foreground-muted',
    '--tng-semantic-foreground-secondary',
    '--color-muted',
  ],
  primary: ['--tng-chart-primary', '--tng-semantic-accent-brand', '--color-primary', '--tng-color-primary500'],
  series1: ['--tng-chart-series-1', '--tng-semantic-accent-brand', '--color-primary'],
  series2: ['--tng-chart-series-2', '--tng-semantic-accent-success', '--color-success'],
  series3: ['--tng-chart-series-3', '--tng-semantic-accent-warning', '--color-warning'],
  series4: ['--tng-chart-series-4', '--tng-semantic-accent-danger', '--color-danger'],
  series5: ['--tng-chart-series-5', '--tng-chart-info', '--color-info', '--tng-color-sky500'],
  series6: ['--tng-chart-series-6', '--tng-color-violet500', '--tng-color-purple500'],
  success: ['--tng-chart-success', '--tng-semantic-accent-success', '--color-success'],
  surface: ['--tng-chart-surface', '--tng-semantic-background-surface', '--color-surface'],
  tooltipBackground: [
    '--tng-chart-tooltip-bg',
    '--tng-chart-surface',
    '--tng-semantic-background-surface',
    '--color-surface',
  ],
  tooltipBorder: [
    '--tng-chart-tooltip-border',
    '--tng-chart-border',
    '--tng-semantic-border-subtle',
    '--tng-semantic-border-default',
    '--color-border',
  ],
  warning: ['--tng-chart-warning', '--tng-semantic-accent-warning', '--color-warning'],
} as const;
