import { DOCUMENT } from '@angular/common';
import { Component, inject, signal, type OnDestroy } from '@angular/core';
import { observeDocsCodeThemeChanges, resolveDocsCodeBlockTheme } from '../../../../../../shared/util';
import {
  TngEmptyActionsComponent,
  TngEmptyComponent,
  TngEmptyDescriptionComponent,
  TngEmptyIconComponent,
  TngEmptyTitleComponent,
} from '@tailng-ui/components';
import { type DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';

@Component({
  selector: 'app-empty-examples-page',
  imports: [
    TngEmptyComponent,
    TngEmptyIconComponent,
    TngEmptyTitleComponent,
    TngEmptyDescriptionComponent,
    TngEmptyActionsComponent,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
  ],
  templateUrl: './empty-examples-page.component.html',
  styleUrl: './empty-examples-page.component.css',
})
export class EmptyExamplesPageComponent implements OnDestroy {
  private readonly documentRef = inject(DOCUMENT);
  public readonly codeBlockTheme = signal<'github-dark' | 'github-light'>(
    resolveDocsCodeBlockTheme(this.documentRef),
  );
  private readonly colorSchemeObserver = observeDocsCodeThemeChanges(
    this.documentRef,
    this.codeBlockTheme,
  );

  protected readonly noResultsPlainTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'empty-examples-no-results-plain-css.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        'import {',
        '  TngEmptyActionsComponent,',
        '  TngEmptyComponent,',
        '  TngEmptyDescriptionComponent,',
        '  TngEmptyIconComponent,',
        '  TngEmptyTitleComponent,',
        "} from '@tailng-ui/components';",
        '',
        '@Component({',
        "  selector: 'app-empty-examples-no-results-plain-css',",
        '  standalone: true,',
        '  imports: [',
        '    TngEmptyComponent,',
        '    TngEmptyIconComponent,',
        '    TngEmptyTitleComponent,',
        '    TngEmptyDescriptionComponent,',
        '    TngEmptyActionsComponent,',
        '  ],',
        "  templateUrl: './empty-examples-no-results-plain-css.component.html',",
        "  styleUrl: './empty-examples-no-results-plain-css.component.css',",
        '})',
        'export class EmptyExamplesNoResultsPlainCssComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'empty-examples-no-results-plain-css.component.html',
      code: [
        '<section class="empty-example-shell">',
        '  <tng-empty align="start">',
        '    <tng-empty-icon>🧭</tng-empty-icon>',
        '    <tng-empty-title>No environments selected</tng-empty-title>',
        '    <tng-empty-description>Select one or more environments to continue.</tng-empty-description>',
        '    <tng-empty-actions>',
        '      <button type="button">Select environments</button>',
        '    </tng-empty-actions>',
        '  </tng-empty>',
        '</section>',
        '',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'empty-examples-no-results-plain-css.component.css',
      code: [
        '.empty-example-shell {',
        '  border: 1px solid var(--tng-semantic-border-subtle);',
        '  border-radius: 0.9rem;',
        '  padding: 0.95rem;',
        '}',
      ].join('\n'),
    },
  ]);

  protected readonly noResultsTailwindTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'empty-examples-no-results-tailwind.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        'import {',
        '  TngEmptyActionsComponent,',
        '  TngEmptyComponent,',
        '  TngEmptyDescriptionComponent,',
        '  TngEmptyIconComponent,',
        '  TngEmptyTitleComponent,',
        "} from '@tailng-ui/components';",
        '',
        '@Component({',
        "  selector: 'app-empty-examples-no-results-tailwind',",
        '  standalone: true,',
        '  imports: [',
        '    TngEmptyComponent,',
        '    TngEmptyIconComponent,',
        '    TngEmptyTitleComponent,',
        '    TngEmptyDescriptionComponent,',
        '    TngEmptyActionsComponent,',
        '  ],',
        "  templateUrl: './empty-examples-no-results-tailwind.component.html',",
        "  styleUrl: './empty-examples-no-results-tailwind.component.css',",
        '})',
        'export class EmptyExamplesNoResultsTailwindComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'empty-examples-no-results-tailwind.component.html',
      code: [
        '<section class="rounded-xl border border-[var(--tng-semantic-border-subtle)] bg-[color-mix(in_srgb,var(--tng-semantic-background-surface)_88%,transparent)] p-4">',
        '  <tng-empty>',
        '    <tng-empty-icon>🛰️</tng-empty-icon>',
        '    <tng-empty-title>No telemetry yet</tng-empty-title>',
        '    <tng-empty-description>Connect your first agent to stream runtime metrics.</tng-empty-description>',
        '    <tng-empty-actions>',
        '      <button',
        '        type="button"',
        '        class="rounded-md border border-[var(--tng-semantic-border-default)] px-3 py-1 text-sm font-medium text-[var(--tng-semantic-foreground-primary)]"',
        '      >',
        '        Connect agent',
        '      </button>',
        '    </tng-empty-actions>',
        '  </tng-empty>',
        '</section>',
        '',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'empty-examples-no-results-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  protected readonly onboardingPlainTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'empty-examples-onboarding-plain-css.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        'import {',
        '  TngEmptyActionsComponent,',
        '  TngEmptyComponent,',
        '  TngEmptyDescriptionComponent,',
        '  TngEmptyIconComponent,',
        '  TngEmptyTitleComponent,',
        "} from '@tailng-ui/components';",
        '',
        '@Component({',
        "  selector: 'app-empty-examples-onboarding-plain-css',",
        '  standalone: true,',
        '  imports: [',
        '    TngEmptyComponent,',
        '    TngEmptyIconComponent,',
        '    TngEmptyTitleComponent,',
        '    TngEmptyDescriptionComponent,',
        '    TngEmptyActionsComponent,',
        '  ],',
        "  templateUrl: './empty-examples-onboarding-plain-css.component.html',",
        "  styleUrl: './empty-examples-onboarding-plain-css.component.css',",
        '})',
        'export class EmptyExamplesOnboardingPlainCssComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'empty-examples-onboarding-plain-css.component.html',
      code: [
        '<section class="empty-example-shell">',
        '  <tng-empty>',
        '    <tng-empty-icon>📁</tng-empty-icon>',
        '    <tng-empty-title>No documents uploaded</tng-empty-title>',
        '    <tng-empty-description>Drop files here or choose upload to start indexing.</tng-empty-description>',
        '    <tng-empty-actions>',
        '      <button type="button">Upload files</button>',
        '      <button type="button">Use template</button>',
        '    </tng-empty-actions>',
        '  </tng-empty>',
        '</section>',
        '',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'empty-examples-onboarding-plain-css.component.css',
      code: [
        '.empty-example-shell {',
        '  border: 1px solid var(--tng-semantic-border-subtle);',
        '  border-radius: 0.9rem;',
        '  padding: 0.95rem;',
        '}',
      ].join('\n'),
    },
  ]);

  protected readonly onboardingTailwindTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'empty-examples-onboarding-tailwind.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        'import {',
        '  TngEmptyActionsComponent,',
        '  TngEmptyComponent,',
        '  TngEmptyDescriptionComponent,',
        '  TngEmptyIconComponent,',
        '  TngEmptyTitleComponent,',
        "} from '@tailng-ui/components';",
        '',
        '@Component({',
        "  selector: 'app-empty-examples-onboarding-tailwind',",
        '  standalone: true,',
        '  imports: [',
        '    TngEmptyComponent,',
        '    TngEmptyIconComponent,',
        '    TngEmptyTitleComponent,',
        '    TngEmptyDescriptionComponent,',
        '    TngEmptyActionsComponent,',
        '  ],',
        "  templateUrl: './empty-examples-onboarding-tailwind.component.html',",
        "  styleUrl: './empty-examples-onboarding-tailwind.component.css',",
        '})',
        'export class EmptyExamplesOnboardingTailwindComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'empty-examples-onboarding-tailwind.component.html',
      code: [
        '<section class="rounded-xl border border-[var(--tng-semantic-border-subtle)] bg-[color-mix(in_srgb,var(--tng-semantic-background-surface)_88%,transparent)] p-4">',
        '  <tng-empty align="start">',
        '    <tng-empty-icon>📦</tng-empty-icon>',
        '    <tng-empty-title>No release artifacts</tng-empty-title>',
        '    <tng-empty-description>Build your project to publish the first release bundle.</tng-empty-description>',
        '    <tng-empty-actions>',
        '      <button',
        '        type="button"',
        '        class="rounded-md border border-[var(--tng-semantic-border-default)] px-3 py-1 text-sm font-medium text-[var(--tng-semantic-foreground-primary)]"',
        '      >',
        '        Run build',
        '      </button>',
        '      <button',
        '        type="button"',
        '        class="rounded-md border border-[var(--tng-semantic-border-default)] px-3 py-1 text-sm font-medium text-[var(--tng-semantic-foreground-primary)]"',
        '      >',
        '        Open pipeline',
        '      </button>',
        '    </tng-empty-actions>',
        '  </tng-empty>',
        '</section>',
        '',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'empty-examples-onboarding-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  public ngOnDestroy(): void {
    this.colorSchemeObserver?.disconnect();
  }
}
