export const TNG_LINE_CHART_DEFAULT_AREA_OPACITY = 0.14;
export const TNG_LINE_CHART_DEFAULT_LINE_WIDTH = 3;
export const TNG_LINE_CHART_DEFAULT_SMOOTH = true;
export const TNG_LINE_CHART_DEFAULT_SYMBOL_SIZE = 8;
export const TNG_LINE_CHART_DEFAULT_X_AXIS_LABEL_ROTATION = 24;
