import { DOCUMENT } from '@angular/common';
import { Component, inject, signal, type OnDestroy } from '@angular/core';
import { TngCodeBlockComponent } from '@tailng-ui/components';
import {
  TngDialog,
  TngDialogActions,
  TngDialogBackdrop,
  TngDialogClose,
  TngDialogDescription,
  TngDialogPanel,
  TngDialogTitle,
  TngDialogTrigger,
  type TngDialogCloseReason,
} from '@tailng-ui/primitives';
import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import {
  observeDocsCodeThemeChanges,
  resolveDocsCodeBlockTheme,
} from '../../../../../../shared/util';

@Component({
  selector: 'app-headless-dialog-overview-page',
  imports: [
    TngCodeBlockComponent,
    TngDialog,
    TngDialogActions,
    TngDialogBackdrop,
    TngDialogClose,
    TngDialogDescription,
    TngDialogPanel,
    TngDialogTitle,
    TngDialogTrigger,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
  ],
  templateUrl: './dialog-overview-page.component.html',
  styleUrl: './dialog-overview-page.component.css',
})
export class HeadlessDialogOverviewPageComponent implements OnDestroy {
  private readonly documentRef = inject(DOCUMENT);

  public readonly codeBlockTheme = signal<'github-dark' | 'github-light'>(
    resolveDocsCodeBlockTheme(this.documentRef),
  );
  private readonly colorSchemeObserver = observeDocsCodeThemeChanges(
    this.documentRef,
    this.codeBlockTheme,
  );

  protected readonly plainOpen = signal(false);
  protected readonly tailwindOpen = signal(false);

  protected readonly plainReason = signal<TngDialogCloseReason | 'none'>('none');
  protected readonly tailwindReason = signal<TngDialogCloseReason | 'none'>('none');

  protected readonly importCode = [
    'import {',
    '  TngDialog,',
    '  TngDialogActions,',
    '  TngDialogBackdrop,',
    '  TngDialogClose,',
    '  TngDialogDescription,',
    '  TngDialogPanel,',
    '  TngDialogTitle,',
    '  TngDialogTrigger,',
    "} from '@tailng-ui/primitives';",
    '',
  ].join('\n');

  protected readonly compositionCode = [
    '<button type="button" [tngDialogTrigger]="reviewDialog">Review release</button>',
    '',
    '<section tngDialog #reviewDialog="tngDialog">',
    '  <div tngDialogBackdrop>',
    '    <section tngDialogPanel>',
    '      <h2 tngDialogTitle>Review changes</h2>',
    '      <p tngDialogDescription>Confirm before publishing.</p>',
    '      <div tngDialogActions>',
    '        <button type="button" tngDialogClose>Cancel</button>',
    "        <button type=\"button\" tngDialogClose [tngDialogClose]=\"'programmatic'\">Publish</button>",
    '      </div>',
    '    </section>',
    '  </div>',
    '</section>',
    '',
  ].join('\n');

  protected readonly plainCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'headless-dialog-overview-plain.component.ts',
      code: [
        "import { Component, signal } from '@angular/core';",
        'import {',
        '  TngDialog,',
        '  TngDialogActions,',
        '  TngDialogBackdrop,',
        '  TngDialogClose,',
        '  TngDialogDescription,',
        '  TngDialogPanel,',
        '  TngDialogTitle,',
        '  TngDialogTrigger,',
        "  type TngDialogCloseReason,",
        "} from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-headless-dialog-overview-plain',",
        '  standalone: true,',
        '  imports: [',
        '    TngDialog,',
        '    TngDialogActions,',
        '    TngDialogBackdrop,',
        '    TngDialogClose,',
        '    TngDialogDescription,',
        '    TngDialogPanel,',
        '    TngDialogTitle,',
        '    TngDialogTrigger,',
        '  ],',
        "  templateUrl: './headless-dialog-overview-plain.component.html',",
        "  styleUrl: './headless-dialog-overview-plain.component.css',",
        '})',
        'export class HeadlessDialogOverviewPlainComponent {',
        '  protected readonly open = signal(false);',
        "  protected readonly lastReason = signal<TngDialogCloseReason | 'none'>('none');",
        '',
        '  protected onClosed(reason: TngDialogCloseReason): void {',
        '    this.lastReason.set(reason);',
        '  }',
        '',
        '  protected onOpenChange(next: boolean): void {',
        '    this.open.set(next);',
        '  }',
        '}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'headless-dialog-overview-plain.component.html',
      code: [
        '<div class="headless-dialog-preview-shell">',
        '  <button type="button" class="headless-dialog-trigger" [tngDialogTrigger]="dialog">',
        '    Open release dialog',
        '  </button>',
        '',
        '  <section',
        '    tngDialog',
        '    #dialog="tngDialog"',
        '    [open]="open()"',
        '    (openChange)="onOpenChange($event)"',
        '    (closed)="onClosed($event)"',
        '  >',
        '    <div tngDialogBackdrop class="headless-dialog-backdrop">',
        '      <section tngDialogPanel class="headless-dialog-panel">',
        '        <h3 tngDialogTitle class="headless-dialog-title">Ship this release?</h3>',
        '        <p tngDialogDescription class="headless-dialog-description">Focus remains trapped until the panel closes.</p>',
        '        <div tngDialogActions class="headless-dialog-actions">',
        '          <button type="button" tngDialogClose class="headless-dialog-secondary">Cancel</button>',
        "          <button type=\"button\" tngDialogClose [tngDialogClose]=\"'programmatic'\" class=\"headless-dialog-primary\">Confirm</button>",
        '        </div>',
        '      </section>',
        '    </div>',
        '  </section>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'headless-dialog-overview-plain.component.css',
      code: [
        '.headless-dialog-backdrop {',
        '  align-items: center;',
        '  background: rgb(2 6 23 / 58%);',
        '  display: grid;',
        '  inset: 0;',
        '  padding: 1rem;',
        '  position: fixed;',
        '}',
        '',
        '.headless-dialog-panel {',
        '  background: var(--tng-semantic-background-surface);',
        '  border: 1px solid var(--tng-semantic-border-subtle);',
        '  border-radius: 1rem;',
        '  display: grid;',
        '  gap: 0.75rem;',
        '  inline-size: min(100%, 28rem);',
        '  padding: 1rem;',
        '}',
      ].join('\n'),
    },
  ]);

  protected readonly tailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'headless-dialog-overview-tailwind.component.ts',
      code: [
        "import { Component, signal } from '@angular/core';",
        'import {',
        '  TngDialog,',
        '  TngDialogActions,',
        '  TngDialogBackdrop,',
        '  TngDialogClose,',
        '  TngDialogDescription,',
        '  TngDialogPanel,',
        '  TngDialogTitle,',
        '  TngDialogTrigger,',
        "  type TngDialogCloseReason,",
        "} from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-headless-dialog-overview-tailwind',",
        '  standalone: true,',
        '  imports: [',
        '    TngDialog,',
        '    TngDialogActions,',
        '    TngDialogBackdrop,',
        '    TngDialogClose,',
        '    TngDialogDescription,',
        '    TngDialogPanel,',
        '    TngDialogTitle,',
        '    TngDialogTrigger,',
        '  ],',
        "  templateUrl: './headless-dialog-overview-tailwind.component.html',",
        "  styleUrl: './headless-dialog-overview-tailwind.component.css',",
        '})',
        'export class HeadlessDialogOverviewTailwindComponent {',
        '  protected readonly open = signal(false);',
        "  protected readonly lastReason = signal<TngDialogCloseReason | 'none'>('none');",
        '',
        '  protected onClosed(reason: TngDialogCloseReason): void {',
        '    this.lastReason.set(reason);',
        '  }',
        '',
        '  protected onOpenChange(next: boolean): void {',
        '    this.open.set(next);',
        '  }',
        '}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'headless-dialog-overview-tailwind.component.html',
      code: [
        '<div class="rounded-xl border border-slate-300 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-900/60">',
        '  <button',
        '    type="button"',
        '    class="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-semibold text-slate-800 dark:border-slate-600 dark:bg-slate-800 dark:text-slate-100"',
        '    [tngDialogTrigger]="dialog"',
        '  >',
        '    Open review dialog',
        '  </button>',
        '',
        '  <section',
        '    tngDialog',
        '    #dialog="tngDialog"',
        '    [open]="open()"',
        '    (openChange)="onOpenChange($event)"',
        '    (closed)="onClosed($event)"',
        '  >',
        '    <div tngDialogBackdrop class="fixed inset-0 grid place-items-center bg-slate-950/65 p-4">',
        '      <section tngDialogPanel class="grid w-full max-w-lg gap-3 rounded-3xl border border-slate-200 bg-white p-5 shadow-2xl dark:border-slate-800 dark:bg-slate-950">',
        '        <h3 tngDialogTitle class="m-0 text-lg font-semibold text-slate-950 dark:text-slate-50">Tailwind review</h3>',
        '        <p tngDialogDescription class="m-0 text-sm text-slate-600 dark:text-slate-300">Layer your own shell while the primitive keeps the modal behavior stable.</p>',
        '        <div tngDialogActions class="flex flex-wrap justify-end gap-2">',
        '          <button type="button" tngDialogClose class="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700 dark:border-slate-700 dark:text-slate-200">Cancel</button>',
        "          <button type=\"button\" tngDialogClose [tngDialogClose]=\"'programmatic'\" class=\"rounded-lg border border-sky-600 bg-sky-600 px-3 py-2 text-sm font-semibold text-white\">Approve</button>",
        '        </div>',
        '      </section>',
        '    </div>',
        '  </section>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'headless-dialog-overview-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  public ngOnDestroy(): void {
    this.colorSchemeObserver?.disconnect();
  }
}
