import { Component } from '@angular/core';
import { TngDonutChartComponent, type TngChartOptionOverride } from '@tailng-ui/charts';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import { DocsFormDemoShellComponent } from '../../../../../../../shared/form-demo-shell/docs-form-demo-shell.component';
import { ChartSeriesPilotThemeBase } from '../../../../pilot/shared/chart-series-pilot-theme.base';
import {
  CHART_PILOT_TAILWIND_SHELL_CLASS,
  CHART_PILOT_PLAIN_LAYOUT_CSS,
  CHART_PILOT_TAILWIND_LAYOUT_CSS,
  createChartPilotCodeTabs,
} from '../../../../pilot/shared/chart-series-pilot-examples.util';
import { DONUT_DEMO_DATA } from '../../donut-pilot.data';

@Component({
  selector: 'app-donut-examples-page',
  imports: [
    TngDonutChartComponent,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
    DocsFormDemoShellComponent,
  ],
  templateUrl: './donut-examples-page.component.html',
  styleUrl: './donut-examples-page.component.css',
})
export class DonutExamplesPageComponent extends ChartSeriesPilotThemeBase {
  protected readonly chartHeight = 300;
  protected readonly data = DONUT_DEMO_DATA;
  protected readonly tailwindShellClass = CHART_PILOT_TAILWIND_SHELL_CLASS;

  protected readonly chartOptionOverride: TngChartOptionOverride = (option) => ({
    ...option,
    series: (option['series'] as unknown[] | undefined)?.map((series) => ({
      ...(series as Record<string, unknown>),
      label: { show: true, formatter: '{b}: {d}%' },
    })),
  });

  protected readonly defaultPlainCodeTabs = createChartPilotCodeTabs({
    baseName: 'donut-default-plain',
    tsCode: [
      "import { Component } from '@angular/core';",
      "import { TngDonutChart, type TngChartData } from '@tailng-ui/charts';",
      '',
      'const data: TngChartData = [',
      "  { name: 'Core', value: 44 },",
      "  { name: 'Pro', value: 31 },",
      "  { name: 'Enterprise', value: 18 },",
      "  { name: 'Services', value: 7 },",
      '];',
      '',
      '@Component({',
      "  selector: 'app-donut-default-plain',",
      '  standalone: true,',
      '  imports: [TngDonutChart],',
      "  templateUrl: './donut-default-plain.component.html',",
      "  styleUrl: './donut-default-plain.component.css',",
      '})',
      'export class DonutDefaultPlainComponent {',
      '  protected readonly data = data;',
      '}',
    ].join('\n'),
    htmlCode: [
      '<div class="chart-pilot-example-preview">',
      '  <div class="chart-pilot-example-chart chart-pilot-example-chart--plain">',
      '    <tng-donut-chart',
      '      [data]="data"',
      '      nameField="name"',
      '      valueField="value"',
      '      [height]="320"',
      '    />',
      '  </div>',
      '</div>',
    ].join('\n'),
    cssCode: CHART_PILOT_PLAIN_LAYOUT_CSS,
  });

  protected readonly defaultTailwindCodeTabs = createChartPilotCodeTabs({
    baseName: 'donut-default-tailwind',
    tsCode: [
      "import { Component } from '@angular/core';",
      "import { TngDonutChart, type TngChartData } from '@tailng-ui/charts';",
      '',
      'const data: TngChartData = [',
      "  { name: 'Core', value: 44 },",
      "  { name: 'Pro', value: 31 },",
      "  { name: 'Enterprise', value: 18 },",
      "  { name: 'Services', value: 7 },",
      '];',
      '',
      '@Component({',
      "  selector: 'app-donut-default-tailwind',",
      '  standalone: true,',
      '  imports: [TngDonutChart],',
      "  templateUrl: './donut-default-tailwind.component.html',",
      "  styleUrl: './donut-default-tailwind.component.css',",
      '})',
      'export class DonutDefaultTailwindComponent {',
      '  protected readonly data = data;',
      '}',
    ].join('\n'),
    htmlCode: [
      '<div class="chart-pilot-example-preview">',
      '  <div class="chart-shell">',
      '    <tng-donut-chart',
      '      [data]="data"',
      '      nameField="name"',
      '      valueField="value"',
      '      [height]="320"',
      '    />',
      '  </div>',
      '</div>',
    ].join('\n'),
    cssCode: CHART_PILOT_TAILWIND_LAYOUT_CSS,
  });

  protected readonly themedPlainCodeTabs = createChartPilotCodeTabs({
    baseName: 'donut-themed-plain',
    tsCode: [
      "import { Component } from '@angular/core';",
      "import { TngDonutChart, type TngChartData } from '@tailng-ui/charts';",
      '',
      'const data: TngChartData = [',
      "  { name: 'Core', value: 44 },",
      "  { name: 'Pro', value: 31 },",
      "  { name: 'Enterprise', value: 18 },",
      '];',
      '',
      '@Component({',
      "  selector: 'app-donut-themed-plain',",
      '  standalone: true,',
      '  imports: [TngDonutChart],',
      "  templateUrl: './donut-themed-plain.component.html',",
      "  styleUrl: './donut-themed-plain.component.css',",
      '})',
      'export class DonutThemedPlainComponent {',
      '  protected readonly data = data;',
      '}',
    ].join('\n'),
    htmlCode: [
      '<div class="product-mix-panel">',
      '  <div class="chart-pilot-example-chart chart-pilot-example-chart--themed">',
      '    <tng-donut-chart',
      '      [data]="data"',
      '      nameField="name"',
      '      valueField="value"',
      '      [height]="320"',
      '    />',
      '  </div>',
      '</div>',
    ].join('\n'),
    cssCode: [
      CHART_PILOT_PLAIN_LAYOUT_CSS,
      '',
      '.product-mix-panel tng-donut-chart {',
      '  --tng-chart-series-1: var(--tng-semantic-accent-brand);',
      '  --tng-chart-series-2: var(--tng-semantic-accent-info);',
      '  --tng-chart-muted: var(--tng-semantic-foreground-secondary);',
      '}',
    ].join('\n'),
  });

  protected readonly themedTailwindCodeTabs = createChartPilotCodeTabs({
    baseName: 'donut-themed-tailwind',
    tsCode: [
      "import { Component } from '@angular/core';",
      "import { TngDonutChart, type TngChartData } from '@tailng-ui/charts';",
      '',
      'const data: TngChartData = [',
      "  { name: 'Core', value: 44 },",
      "  { name: 'Pro', value: 31 },",
      "  { name: 'Enterprise', value: 18 },",
      '];',
      '',
      '@Component({',
      "  selector: 'app-donut-themed-tailwind',",
      '  standalone: true,',
      '  imports: [TngDonutChart],',
      "  templateUrl: './donut-themed-tailwind.component.html',",
      "  styleUrl: './donut-themed-tailwind.component.css',",
      '})',
      'export class DonutThemedTailwindComponent {',
      '  protected readonly data = data;',
      '}',
    ].join('\n'),
    htmlCode: [
      '<div class="product-mix-panel rounded-2xl border border-[var(--tng-semantic-border-subtle)] p-4">',
      '  <tng-donut-chart',
      '    [data]="data"',
      '    nameField="name"',
      '    valueField="value"',
      '    [height]="320"',
      '  />',
      '</div>',
    ].join('\n'),
    cssCode: CHART_PILOT_TAILWIND_LAYOUT_CSS,
  });

  protected readonly overridePlainCodeTabs = createChartPilotCodeTabs({
    baseName: 'donut-override-plain',
    tsCode: [
      "import { Component } from '@angular/core';",
      "import { TngDonutChart, type TngChartData, type TngChartOptionOverride } from '@tailng-ui/charts';",
      '',
      'const data: TngChartData = [',
      "  { name: 'Core', value: 44 },",
      "  { name: 'Pro', value: 31 },",
      "  { name: 'Enterprise', value: 18 },",
      '];',
      '',
      '@Component({',
      "  selector: 'app-donut-override-plain',",
      '  standalone: true,',
      '  imports: [TngDonutChart],',
      "  templateUrl: './donut-override-plain.component.html',",
      "  styleUrl: './donut-override-plain.component.css',",
      '})',
      'export class DonutOverridePlainComponent {',
      '  protected readonly data = data;',
      '  protected readonly chartOptionOverride: TngChartOptionOverride = (option) => ({',
      '    ...option,',
      '    series: (option.series as unknown[] | undefined)?.map((series) => ({',
      '      ...(series as Record<string, unknown>),',
      "      label: { show: true, formatter: '{b}: {d}%' },",
      '    })),',
      '  });',
      '}',
    ].join('\n'),
    htmlCode: [
      '<div class="chart-pilot-example-chart chart-pilot-example-chart--plain">',
      '  <tng-donut-chart',
      '    [data]="data"',
      '    nameField="name"',
      '    valueField="value"',
      '    [height]="320"',
      '    [optionOverride]="chartOptionOverride"',
      '  />',
      '</div>',
    ].join('\n'),
    cssCode: CHART_PILOT_PLAIN_LAYOUT_CSS,
  });

  protected readonly overrideTailwindCodeTabs = createChartPilotCodeTabs({
    baseName: 'donut-override-tailwind',
    tsCode: [
      "import { Component } from '@angular/core';",
      "import { TngDonutChart, type TngChartData, type TngChartOptionOverride } from '@tailng-ui/charts';",
      '',
      'const data: TngChartData = [',
      "  { name: 'Core', value: 44 },",
      "  { name: 'Pro', value: 31 },",
      "  { name: 'Enterprise', value: 18 },",
      '];',
      '',
      '@Component({',
      "  selector: 'app-donut-override-tailwind',",
      '  standalone: true,',
      '  imports: [TngDonutChart],',
      "  templateUrl: './donut-override-tailwind.component.html',",
      "  styleUrl: './donut-override-tailwind.component.css',",
      '})',
      'export class DonutOverrideTailwindComponent {',
      '  protected readonly data = data;',
      '  protected readonly chartOptionOverride: TngChartOptionOverride = (option) => ({',
      '    ...option,',
      '    series: (option.series as unknown[] | undefined)?.map((series) => ({',
      '      ...(series as Record<string, unknown>),',
      "      label: { show: true, formatter: '{b}: {d}%' },",
      '    })),',
      '  });',
      '}',
    ].join('\n'),
    htmlCode: [
      '<div class="chart-shell">',
      '  <tng-donut-chart',
      '    [data]="data"',
      '    nameField="name"',
      '    valueField="value"',
      '    [height]="320"',
      '    [optionOverride]="chartOptionOverride"',
      '  />',
      '</div>',
    ].join('\n'),
    cssCode: CHART_PILOT_TAILWIND_LAYOUT_CSS,
  });
}
