import { DOCUMENT } from '@angular/common';
import { Component, inject, signal, type OnDestroy } from '@angular/core';
import {
  TngAccordion,
  TngAccordionItem,
  TngAccordionPanel,
  TngAccordionTrigger,
} from '@tailng-ui/primitives';
import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import {
  observeDocsCodeThemeChanges,
  resolveDocsCodeBlockTheme,
} from '../../../../../../shared/util';

@Component({
  selector: 'app-headless-accordion-examples-page',
  imports: [
    TngAccordion,
    TngAccordionItem,
    TngAccordionTrigger,
    TngAccordionPanel,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
  ],
  templateUrl: './accordion-examples-page.component.html',
  styleUrls: ['./accordion-examples-page.component.css'],
})
export class HeadlessAccordionExamplesPageComponent implements OnDestroy {
  private readonly documentRef = inject(DOCUMENT);

  public readonly codeBlockTheme = signal<'github-dark' | 'github-light'>(
    resolveDocsCodeBlockTheme(this.documentRef),
  );
  private readonly colorSchemeObserver = observeDocsCodeThemeChanges(
    this.documentRef,
    this.codeBlockTheme,
  );

  protected readonly faqPlainCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'headless-accordion-examples-faq-plain.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import {",
        "  TngAccordion,",
        "  TngAccordionItem,",
        "  TngAccordionPanel,",
        "  TngAccordionTrigger,",
        "} from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-headless-accordion-examples-faq-plain',",
        '  standalone: true,',
        '  imports: [TngAccordion, TngAccordionItem, TngAccordionTrigger, TngAccordionPanel],',
        "  templateUrl: './headless-accordion-examples-faq-plain.component.html',",
        "  styleUrl: './headless-accordion-examples-faq-plain.component.css',",
        '})',
        'export class HeadlessAccordionExamplesFaqPlainComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'headless-accordion-examples-faq-plain.component.html',
      code: [
        '<section tngAccordion aria-label="Project FAQ" [defaultValue]="\'license\'" class="headless-accordion-example-shell">',
        '  <article tngAccordionItem value="license" class="headless-accordion-example-item">',
        '    <button tngAccordionTrigger type="button" class="headless-accordion-example-trigger">License</button>',
        '    <div tngAccordionPanel class="headless-accordion-example-panel">MIT with optional enterprise add-ons.</div>',
        '  </article>',
        '  <article tngAccordionItem value="support" class="headless-accordion-example-item">',
        '    <button tngAccordionTrigger type="button" class="headless-accordion-example-trigger">Support window</button>',
        '    <div tngAccordionPanel class="headless-accordion-example-panel">Community and commercial channels.</div>',
        '  </article>',
        '</section>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'headless-accordion-examples-faq-plain.component.css',
      code: [
        '.headless-accordion-example-trigger[data-state="open"] {',
        '  color: var(--tng-semantic-accent-brand);',
        '}',
      ].join('\n'),
    },
  ]);

  protected readonly faqTailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'headless-accordion-examples-faq-tailwind.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import {",
        "  TngAccordion,",
        "  TngAccordionItem,",
        "  TngAccordionPanel,",
        "  TngAccordionTrigger,",
        "} from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-headless-accordion-examples-faq-tailwind',",
        '  standalone: true,',
        '  imports: [TngAccordion, TngAccordionItem, TngAccordionTrigger, TngAccordionPanel],',
        "  templateUrl: './headless-accordion-examples-faq-tailwind.component.html',",
        "  styleUrl: './headless-accordion-examples-faq-tailwind.component.css',",
        '})',
        'export class HeadlessAccordionExamplesFaqTailwindComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'headless-accordion-examples-faq-tailwind.component.html',
      code: [
        '<section',
        '  tngAccordion',
        '  aria-label="Project FAQ"',
        '  [defaultValue]="\'release\'"',
        '  class="overflow-hidden rounded-2xl border border-slate-300 bg-slate-50 dark:border-slate-700 dark:bg-slate-900/60"',
        '>',
        '  <article tngAccordionItem value="release" class="border-b border-slate-200 dark:border-slate-800">',
        '    <button',
        '      tngAccordionTrigger',
        '      type="button"',
        '      class="flex w-full items-center justify-between border-0 bg-transparent px-4 py-3 text-left font-medium text-slate-900 dark:text-slate-100"',
        '    >',
        '      Release model',
        '    </button>',
        '    <div tngAccordionPanel class="px-4 pb-4 text-sm leading-6 text-slate-700 dark:text-slate-300">',
        '      Weekly patch and monthly minor cadence.',
        '    </div>',
        '  </article>',
        '  <article tngAccordionItem value="quality">',
        '    <button',
        '      tngAccordionTrigger',
        '      type="button"',
        '      class="flex w-full items-center justify-between border-0 bg-transparent px-4 py-3 text-left font-medium text-slate-900 dark:text-slate-100"',
        '    >',
        '      Quality gates',
        '    </button>',
        '    <div tngAccordionPanel class="px-4 pb-4 text-sm leading-6 text-slate-700 dark:text-slate-300">',
        '      Tests and lint pass before merge.',
        '    </div>',
        '  </article>',
        '</section>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'headless-accordion-examples-faq-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  protected readonly settingsPlainCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'headless-accordion-examples-settings-plain.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import {",
        "  TngAccordion,",
        "  TngAccordionItem,",
        "  TngAccordionPanel,",
        "  TngAccordionTrigger,",
        "} from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-headless-accordion-examples-settings-plain',",
        '  standalone: true,',
        '  imports: [TngAccordion, TngAccordionItem, TngAccordionTrigger, TngAccordionPanel],',
        "  templateUrl: './headless-accordion-examples-settings-plain.component.html',",
        "  styleUrl: './headless-accordion-examples-settings-plain.component.css',",
        '})',
        'export class HeadlessAccordionExamplesSettingsPlainComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'headless-accordion-examples-settings-plain.component.html',
      code: [
        '<section',
        '  tngAccordion',
        '  type="multiple"',
        '  aria-label="System settings"',
        '  [defaultValue]="[\'alerts\']"',
        '  class="headless-accordion-example-shell"',
        '>',
        '  <article tngAccordionItem value="alerts" class="headless-accordion-example-item">',
        '    <button tngAccordionTrigger type="button" class="headless-accordion-example-trigger">Alerts</button>',
        '    <div tngAccordionPanel class="headless-accordion-example-panel">PagerDuty, email, and Slack routing.</div>',
        '  </article>',
        '  <article tngAccordionItem value="audits" class="headless-accordion-example-item">',
        '    <button tngAccordionTrigger type="button" class="headless-accordion-example-trigger">Audits</button>',
        '    <div tngAccordionPanel class="headless-accordion-example-panel">Retention and export scheduling.</div>',
        '  </article>',
        '  <article tngAccordionItem value="billing" disabled class="headless-accordion-example-item">',
        '    <button tngAccordionTrigger type="button" class="headless-accordion-example-trigger">Billing (disabled)</button>',
        '    <div tngAccordionPanel class="headless-accordion-example-panel">Disabled sections stay locked.</div>',
        '  </article>',
        '</section>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'headless-accordion-examples-settings-plain.component.css',
      code: [
        '.headless-accordion-example-item[data-disabled="true"] {',
        '  opacity: 0.65;',
        '}',
      ].join('\n'),
    },
  ]);

  protected readonly settingsTailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'headless-accordion-examples-settings-tailwind.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import {",
        "  TngAccordion,",
        "  TngAccordionItem,",
        "  TngAccordionPanel,",
        "  TngAccordionTrigger,",
        "} from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-headless-accordion-examples-settings-tailwind',",
        '  standalone: true,',
        '  imports: [TngAccordion, TngAccordionItem, TngAccordionTrigger, TngAccordionPanel],',
        "  templateUrl: './headless-accordion-examples-settings-tailwind.component.html',",
        "  styleUrl: './headless-accordion-examples-settings-tailwind.component.css',",
        '})',
        'export class HeadlessAccordionExamplesSettingsTailwindComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'headless-accordion-examples-settings-tailwind.component.html',
      code: [
        '<section',
        '  tngAccordion',
        '  type="multiple"',
        '  aria-label="System settings"',
        '  [defaultValue]="[\'alerts\']"',
        '  class="overflow-hidden rounded-2xl border border-slate-300 bg-slate-50 dark:border-slate-700 dark:bg-slate-900/60"',
        '>',
        '  <article tngAccordionItem value="alerts" class="border-b border-slate-200 dark:border-slate-800">',
        '    <button',
        '      tngAccordionTrigger',
        '      type="button"',
        '      class="flex w-full items-center justify-between border-0 bg-transparent px-4 py-3 text-left font-medium text-slate-900 dark:text-slate-100"',
        '    >',
        '      Alerts',
        '    </button>',
        '    <div tngAccordionPanel class="px-4 pb-4 text-sm leading-6 text-slate-700 dark:text-slate-300">',
        '      PagerDuty, email, and Slack routing.',
        '    </div>',
        '  </article>',
        '  <article tngAccordionItem value="audits">',
        '    <button',
        '      tngAccordionTrigger',
        '      type="button"',
        '      class="flex w-full items-center justify-between border-0 bg-transparent px-4 py-3 text-left font-medium text-slate-900 dark:text-slate-100"',
        '    >',
        '      Audits',
        '    </button>',
        '    <div tngAccordionPanel class="px-4 pb-4 text-sm leading-6 text-slate-700 dark:text-slate-300">',
        '      Retention and export scheduling.',
        '    </div>',
        '  </article>',
        '</section>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'headless-accordion-examples-settings-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  public ngOnDestroy(): void {
    this.colorSchemeObserver?.disconnect();
  }
}
