import { Component, ViewEncapsulation } from '@angular/core';
import { TngCodeBlockComponent } from '@tailng-ui/components';
import { TngInput, TngInputGroup, TngPrefix, TngSuffix } from '@tailng-ui/primitives';
import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import { InputStylingPageComponent } from '../../../../../components/form/input/sections/styling/input-styling-page.component';

@Component({
  selector: 'app-headless-input-styling-page',
  imports: [
    TngCodeBlockComponent,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
    TngInputGroup,
    TngInput,
    TngPrefix,
    TngSuffix,
  ],
  templateUrl: './headless-input-styling-page.component.html',
  encapsulation: ViewEncapsulation.None,
  styleUrls: [
    '../../../../../components/form/input/sections/styling/input-styling-page.component.css',
    './headless-input-styling-page.component.css',
    '../../../../../../shared/form/input/input-styles.css',
  ],
})
export class HeadlessInputStylingPageComponent extends InputStylingPageComponent {
  protected override readonly headlessScenarioHtmlCode = [
    '<div class="account-profile-example-fields">',
    '  <label class="account-profile-example-field-surface account-profile-example-field-surface--headless">',
    '    <span class="account-profile-example-field-label">Display name</span>',
    '    <div tngInputGroup class="account-profile-example-shell">',
    '      <span tngPrefix aria-hidden="true">@</span>',
    '      <input tngInput type="text" value="Ada Lovelace" aria-label="Display name" />',
    '      <button tngSuffix type="button" aria-label="Clear">X</button>',
    '    </div>',
    '  </label>',
    '</div>',
    '',
  ].join('\n');

  protected override readonly headlessScenarioCssCode = [
    '/* Plain-CSS headless scenario styling (surface + labels + slot internals). */',
    '.account-profile-example-fields {',
    '  display: grid;',
    '  gap: 1rem;',
    '  max-width: 31rem;',
    '  width: min(100%, 31rem);',
    '}',
    '',
    '.account-profile-example-field-surface {',
    '  border: 1px solid rgba(28, 25, 23, 0.14);',
    '  border-radius: 0.85rem;',
    '  color: rgba(28, 25, 23, 0.95);',
    '  color-scheme: light;',
    '  display: grid;',
    '  gap: 0.45rem;',
    '  padding: 0.78rem 0.82rem;',
    '}',
    '',
    '.account-profile-example-field-surface--headless {',
    '  background: #f8fafc;',
    '}',
    '',
    '.account-profile-example-field-surface--tailwind {',
    '  background: rgba(125, 211, 252, 0.12);',
    '}',
    '',
    '.account-profile-example-field-label {',
    '  color: rgba(28, 25, 23, 0.6);',
    '  font-size: 0.82rem;',
    '  font-weight: 600;',
    '  line-height: 1.2;',
    '}',
    '',
    ".account-profile-example-shell[data-slot='input-group'] {",
    '  background: #f8fafc;',
    '  border: 1px solid rgba(28, 25, 23, 0.22);',
    '  border-radius: 0.65rem;',
    '  min-height: 2.4rem;',
    '  padding: 0 0.7rem;',
    '  transition:',
    '    border-color 0.15s ease,',
    '    box-shadow 0.15s ease;',
    '  cursor: text;',
    '}',
    '',
    ".account-profile-example-shell[data-slot='input-group'][data-focused] {",
    '  border-color: rgba(15, 118, 110, 0.65);',
    '  box-shadow: 0 0 0 3px rgba(15, 118, 110, 0.18);',
    '}',
    '',
    ".account-profile-example-shell [data-slot='input-group-leading'],",
    ".account-profile-example-shell [data-slot='input-group-trailing'] {",
    '  align-items: center;',
    '  color: rgba(28, 25, 23, 0.7);',
    '  display: inline-flex;',
    '  font-size: 0.82rem;',
    '  font-weight: 600;',
    '}',
    '',
    ".account-profile-example-shell [data-slot='input-group-leading'] {",
    '  margin-right: 0.45rem;',
    '}',
    '',
    ".account-profile-example-shell [data-slot='input-group-trailing'] {",
    '  margin-left: 0.45rem;',
    '}',
    '',
    ".account-profile-example-shell [data-slot='input-leading'] {",
    '  color: rgba(28, 25, 23, 0.7) !important;',
    '  display: inline-flex;',
    '  align-items: center;',
    '  font-size: 0.82rem;',
    '  font-weight: 600;',
    '  line-height: 1;',
    '}',
    '',
    ".account-profile-example-shell [data-slot='input-trailing'] {",
    '  appearance: none;',
    '  background: transparent !important;',
    '  border: 0 !important;',
    '  box-shadow: none !important;',
    '  color: rgba(28, 25, 23, 0.7) !important;',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  padding: 0 !important;',
    '  margin: 0;',
    '  font: inherit;',
    '  line-height: 1;',
    '  cursor: pointer;',
    '}',
    '',
    ".account-profile-example-shell [data-slot='input-trailing']:hover,",
    ".account-profile-example-shell [data-slot='input-trailing']:active {",
    '  background: transparent !important;',
    '}',
    '',
    ".account-profile-example-shell [data-slot='input-trailing']:focus,",
    ".account-profile-example-shell [data-slot='input-trailing']:focus-visible {",
    '  outline: none !important;',
    '  box-shadow: none !important;',
    '}',
    '',
    ".account-profile-example-shell [data-slot='input'] {",
    '  background: transparent;',
    '  border: 0;',
    '  box-shadow: none;',
    '  color: rgba(28, 25, 23, 0.95);',
    '  font-size: 0.98rem;',
    '  font-weight: 500;',
    '  line-height: 1.35;',
    '  outline: none;',
    '  padding: 0;',
    '}',
    '',
    ".account-profile-example-shell [data-slot='input']::placeholder {",
    '  color: rgba(28, 25, 23, 0.55);',
    '}',
    '',
    ".account-profile-example-shell [data-slot='input']:focus,",
    ".account-profile-example-shell [data-slot='input']:focus-visible {",
    '  outline: none;',
    '}',
    '',
  ].join('\n');

  protected readonly tailwindHeadlessScenarioHtmlCode = [
    '<div class="account-profile-example-fields">',
    '  <label class="account-profile-example-field-surface account-profile-example-field-surface--tailwind">',
    '    <span class="account-profile-example-field-label">Display name</span>',
    '    <div',
    '      tngInputGroup',
    '      class="account-profile-example-shell min-h-10 rounded-lg border border-slate-300 bg-slate-50 px-3 shadow-sm transition [&[data-focused]]:border-cyan-500 [&[data-focused]]:ring-2 [&[data-focused]]:ring-cyan-200/70"',
    '    >',
    '      <span tngPrefix aria-hidden="true">@</span>',
    '      <input',
    '        tngInput',
    '        type="text"',
    '        value="Ada Lovelace"',
    '        aria-label="Display name"',
    '        class="w-full border-0 bg-transparent p-0 text-[0.98rem] font-medium leading-5 outline-none"',
    '      />',
    '      <button tngSuffix type="button" aria-label="Clear">X</button>',
    '    </div>',
    '  </label>',
    '</div>',
    '',
  ].join('\n');

  protected readonly tailwindHeadlessScenarioCssCode = this.headlessScenarioCssCode;

  protected readonly plainCssHeadlessScenarioTsCode = [
    "import { Component } from '@angular/core';",
    "import { TngInput, TngInputGroup, TngPrefix, TngSuffix } from '@tailng-ui/primitives';",
    '',
    '@Component({',
    "  selector: 'app-plain-css-headless-account-form',",
    '  imports: [TngInput, TngInputGroup, TngPrefix, TngSuffix],',
    "  templateUrl: './plain-css-headless-account-form.component.html',",
    "  styleUrl: './plain-css-headless-account-form.component.css',",
    '})',
    'export class PlainCssHeadlessAccountFormComponent {}',
    '',
  ].join('\n');

  protected readonly tailwindHeadlessScenarioTsCode = [
    "import { Component } from '@angular/core';",
    "import { TngInput, TngInputGroup, TngPrefix, TngSuffix } from '@tailng-ui/primitives';",
    '',
    '@Component({',
    "  selector: 'app-tailwind-headless-account-form',",
    '  imports: [TngInput, TngInputGroup, TngPrefix, TngSuffix],',
    "  templateUrl: './tailwind-headless-account-form.component.html',",
    "  styleUrl: './tailwind-headless-account-form.component.css',",
    '})',
    'export class TailwindHeadlessAccountFormComponent {}',
    '',
  ].join('\n');

  protected readonly plainCssHeadlessScenarioCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'plain-css-headless-account-form.component.ts',
      code: this.plainCssHeadlessScenarioTsCode,
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'plain-css-headless-account-form.component.html',
      code: this.headlessScenarioHtmlCode,
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'plain-css-headless-account-form.component.css',
      code: this.headlessScenarioCssCode,
    },
  ]);

  protected readonly tailwindHeadlessScenarioCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'tailwind-headless-account-form.component.ts',
      code: this.tailwindHeadlessScenarioTsCode,
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'tailwind-headless-account-form.component.html',
      code: this.tailwindHeadlessScenarioHtmlCode,
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'tailwind-headless-account-form.component.css',
      code: this.tailwindHeadlessScenarioCssCode,
    },
  ]);
}
