import { Component, ViewEncapsulation } from '@angular/core';
import { TngCodeBlockComponent } from '@tailng-ui/components';
import { TngInput, TngInputGroup, TngPrefix, TngSuffix } from '@tailng-ui/primitives';
import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import { InputStylingPageComponent } from '../../../../../components/form/input/sections/styling/input-styling-page.component';
import { stackblitzVanillaUrl, stackblitzTailwindUrl } from '../../input.util';

@Component({
  selector: 'app-headless-input-styling-page',
  imports: [
    TngCodeBlockComponent,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
    TngInputGroup,
    TngInput,
    TngPrefix,
    TngSuffix,
  ],
  templateUrl: './headless-input-styling-page.component.html',
  encapsulation: ViewEncapsulation.None,
  styleUrls: [
    '../../../../../components/form/input/sections/styling/input-styling-page.component.css',
    './headless-input-styling-page.component.css',
    '../../../../../../shared/form/input/input-styles.css',
  ],
})
export class HeadlessInputStylingPageComponent extends InputStylingPageComponent {

  protected readonly stackblitzVanillaUrl = stackblitzVanillaUrl;
  protected readonly stackblitzTailwindUrl = stackblitzTailwindUrl;

  protected override readonly headlessScenarioHtmlCode = [
    '<div class="account-profile-example-fields">',
    '  <label',
    '    class="account-profile-example-field-surface account-profile-example-field-surface--headless"',
    '>',
    '  <span class="account-profile-example-field-label">Display name</span>',
    '    <div tngInputGroup class="account-profile-example-shell">',
    '      <span tngPrefix aria-hidden="true">@</span>',
    '      <input',
    '        tngInput',
    '        type="text"',
    '        value="Ada Lovelace"',
    '        aria-label="Display name"',
    '      />',
    '      <button tngSuffix type="button" aria-label="Clear">X</button>',
    '    </div>',
    '</label>',
    '</div>',
    '',
  ].join('\n');

  protected override readonly headlessScenarioCssCode = [
    '/* Plain-CSS headless scenario styling (surface + labels + slot internals). */',
    ".account-profile-example-fields {",
    "  display: grid;",
    "  gap: 1rem;",
    "  width: min(100%, 32rem);",
    "  max-width: 32rem;",
    "}",
    "",
    ".account-profile-example-field-surface {",
    "  display: grid;",
    "  gap: 0.55rem;",
    "  padding: 1rem;",
    "  border: 1px solid #d9dde3;",
    "  border-radius: 1rem;",
    "  background: #f3f4f6;",
    "  color: #1f2937;",
    "}",
    "",
    ".account-profile-example-field-label {",
    "  font-size: 0.84rem;",
    "  font-weight: 600;",
    "  line-height: 1.25;",
    "  color: #374151;",
    "}",
    "",
    ".account-profile-example-shell[data-slot='input-group'] {",
    "  min-height: 2.75rem;",
    "  padding: 0 0.85rem;",
    "  border: 1px solid #cfd6df;",
    "  border-radius: 0.8rem;",
    "  background: #ffffff;",
    "  color: #111827;",
    "  cursor: text;",
    "  transition:",
    "    border-color 0.18s ease,",
    "    box-shadow 0.18s ease,",
    "    background-color 0.18s ease;",
    "}",
    "",
    ".account-profile-example-shell[data-slot='input-group'][data-focused] {",
    "  border-color: #3b82f6;",
    "  box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.16);",
    "}",
    "",
    ".account-profile-example-shell [data-slot='input-leading'] {",
    "  display: inline-flex;",
    "  align-items: center;",
    "  color: #6b7280;",
    "  font-size: 0.95rem;",
    "  font-weight: 600;",
    "  line-height: 1;",
    "}",
    "",
    ".account-profile-example-shell [data-slot='input-trailing'] {",
    "  appearance: none;",
    "  display: inline-flex;",
    "  align-items: center;",
    "  justify-content: center;",
    "  min-width: 1.5rem;",
    "  min-height: 1.5rem;",
    "  padding: 0;",
    "  margin: 0;",
    "  border: 0;",
    "  background: transparent;",
    "  color: #6b7280;",
    "  font: inherit;",
    "  line-height: 1;",
    "  cursor: pointer;",
    "  border-radius: 999px;",
    "  transition:",
    "    background-color 0.18s ease,",
    "    color 0.18s ease;",
    "}",
    "",
    ".account-profile-example-shell [data-slot='input-trailing']:hover {",
    "  background: #f3f4f6;",
    "  color: #374151;",
    "}",
    "",
    ".account-profile-example-shell [data-slot='input-trailing']:focus,",
    ".account-profile-example-shell [data-slot='input-trailing']:focus-visible {",
    "  outline: none;",
    "  box-shadow: none;",
    "}",
    "",
    ".account-profile-example-shell [data-slot='input'] {",
    "  background: transparent;",
    "  border: 0;",
    "  box-shadow: none;",
    "  color: #111827;",
    "  font-size: 0.98rem;",
    "  font-weight: 500;",
    "  line-height: 1.35;",
    "  outline: none;",
    "  padding: 0;",
    "}",
    "",
    ".account-profile-example-shell [data-slot='input']::placeholder {",
    "  color: #9ca3af;",
    "}",
    "",
    ".account-profile-example-shell [data-slot='input']:focus,",
    ".account-profile-example-shell [data-slot='input']:focus-visible {",
    "  outline: none;",
    "}",
    '',
  ].join('\n');

  protected readonly tailwindHeadlessScenarioHtmlCode = [
    '<div class="grid w-full max-w-[32rem] gap-4">',
    '  <label class="grid gap-2 rounded-2xl border border-[#d9dde3] bg-[#f3f4f6] p-4 text-[#1f2937]">',
    '    <span class="text-[0.84rem] font-semibold leading-[1.25] text-[#374151]">',
    '      Display name',
    '    </span>',
    '',
    '    <div',
    '      tngInputGroup',
    '      class="min-h-11 cursor-text rounded-[0.8rem] border border-[#cfd6df] bg-white px-[0.85rem] text-[#111827] shadow-sm transition-[border-color,box-shadow,background-color] duration-200 [&[data-focused]]:border-[#3b82f6] [&[data-focused]]:shadow-[0_0_0_3px_rgba(59,130,246,0.16)]">',
    '      <span',
    '        tngPrefix',
    '        aria-hidden="true"',
    '        class="inline-flex items-center text-[0.95rem] font-semibold leading-none text-[#6b7280]">',
    '        @',
    '      </span>',
    '',
    '      <input',
    '        tngInput',
    '        type="text"',
    '        value="Ada Lovelaze"',
    '        aria-label="Display name"',
    '        class="w-full border-0 bg-transparent p-0 text-[0.98rem] font-medium leading-5 text-[#111827] outline-none placeholder:text-[#9ca3af]"/>',
    '',
    '      <button',
    '        tngSuffix',
    '        type="button"',
    '        aria-label="Clear"',
    '        class="inline-flex min-h-6 min-w-6 items-center justify-center rounded-full border-0 bg-transparent p-0 leading-none text-[#6b7280] transition-[background-color,color] duration-200 hover:bg-[#f3f4f6] hover:text-[#374151] focus:outline-none">',
    '        X',
    '      </button>',
    '    </div>',
    '  </label>',
    '</div>',
    '',
  ].join('\n');

  protected readonly tailwindHeadlessScenarioCssCode = '/* No custom CSS required. Styles are applied with Tailwind utility classes in the template. */';

  protected readonly plainCssHeadlessScenarioTsCode = [
    "import { Component } from '@angular/core';",
    "import { TngInput, TngInputGroup, TngPrefix, TngSuffix } from '@tailng-ui/primitives';",
    '',
    '@Component({',
    "  selector: 'app-plain-css-headless-account-form',",
    '  imports: [TngInput, TngInputGroup, TngPrefix, TngSuffix],',
    "  templateUrl: './plain-css-headless-account-form.component.html',",
    "  styleUrl: './plain-css-headless-account-form.component.css',",
    '})',
    'export class PlainCssHeadlessAccountFormComponent {}',
    '',
  ].join('\n');

  protected readonly tailwindHeadlessScenarioTsCode = [
    "import { Component } from '@angular/core';",
    "import { TngInput, TngInputGroup, TngPrefix, TngSuffix } from '@tailng-ui/primitives';",
    '',
    '@Component({',
    "  selector: 'app-tailwind-headless-account-form',",
    '  imports: [TngInput, TngInputGroup, TngPrefix, TngSuffix],',
    "  templateUrl: './tailwind-headless-account-form.component.html',",
    "  styleUrl: './tailwind-headless-account-form.component.css',",
    '})',
    'export class TailwindHeadlessAccountFormComponent {}',
    '',
  ].join('\n');

  protected readonly plainCssHeadlessScenarioCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'plain-css-headless-account-form.component.ts',
      code: this.plainCssHeadlessScenarioTsCode,
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'plain-css-headless-account-form.component.html',
      code: this.headlessScenarioHtmlCode,
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'plain-css-headless-account-form.component.css',
      code: this.headlessScenarioCssCode,
    },
  ]);

  protected readonly tailwindHeadlessScenarioCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'tailwind-headless-account-form.component.ts',
      code: this.tailwindHeadlessScenarioTsCode,
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'tailwind-headless-account-form.component.html',
      code: this.tailwindHeadlessScenarioHtmlCode,
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'tailwind-headless-account-form.component.css',
      code: this.tailwindHeadlessScenarioCssCode,
    },
  ]);
}
