import { DOCUMENT } from '@angular/common';
import { Component, inject, signal, type OnDestroy } from '@angular/core';
import { TngSwitch } from '@tailng-ui/primitives';
import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import {
  observeDocsCodeThemeChanges,
  resolveDocsCodeBlockTheme,
} from '../../../../../../shared/util';
import { stackblitzTailwindUrl, stackblitzVanillaUrl } from '../../switch.util';

function createCodeTabs(
  baseName: string,
  tsCode: string,
  htmlCode: string,
  cssCode: string,
): readonly DocsExampleCodeTab[] {
  return Object.freeze([
    { value: 'ts', label: 'TS', language: 'ts', title: `${baseName}.component.ts`, code: tsCode },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: `${baseName}.component.html`,
      code: htmlCode,
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: `${baseName}.component.css`,
      code: cssCode,
    },
  ]);
}

@Component({
  selector: 'app-headless-switch-examples-page',
  imports: [DocsExampleTabsSectionComponent, DocsExampleVariantDirective, TngSwitch],
  templateUrl: './headless-switch-examples-page.component.html',
  styleUrl: './headless-switch-examples-page.component.css',
})
export class HeadlessSwitchExamplesPageComponent implements OnDestroy {
  private readonly documentRef = inject(DOCUMENT);

  public readonly codeBlockTheme = signal<'github-dark' | 'github-light'>(
    resolveDocsCodeBlockTheme(this.documentRef),
  );
  private readonly colorSchemeObserver = observeDocsCodeThemeChanges(
    this.documentRef,
    this.codeBlockTheme,
  );

  protected readonly stackblitzVanillaUrl = stackblitzVanillaUrl;
  protected readonly stackblitzTailwindUrl = stackblitzTailwindUrl;

  protected readonly plainCssReleaseEmails = signal(true);
  protected readonly plainCssDeployWindow = signal(false);
  protected readonly plainCssPrivacy = signal(true);
  protected readonly tailwindReleaseEmails = signal(true);
  protected readonly tailwindDeployWindow = signal(false);
  protected readonly tailwindPrivacy = signal(true);

  protected readonly releasePreferencesPlainCodeTabs = createCodeTabs(
    'headless-switch-release-preferences-plain',
    [
      "import { Component, signal } from '@angular/core';",
      "import { TngSwitch } from '@tailng-ui/primitives';",
      '',
      '@Component({',
      "  selector: 'app-headless-switch-release-preferences-plain',",
      '  standalone: true,',
      '  imports: [TngSwitch],',
      "  templateUrl: './headless-switch-release-preferences-plain.component.html',",
      "  styleUrl: './headless-switch-release-preferences-plain.component.css',",
      '})',
      'export class HeadlessSwitchReleasePreferencesPlainComponent {',
      '  readonly releaseEmailsEnabled = signal(true);',
      '  readonly freezeDeployWindow = signal(false);',
      '',
      '  onReleaseEmailsToggle(): void {',
      '    this.releaseEmailsEnabled.update((value) => !value);',
      '  }',
      '',
      '  onFreezeDeployWindowToggle(): void {',
      '    this.freezeDeployWindow.update((value) => !value);',
      '  }',
      '}',
      '',
    ].join('\n'),
    [
      '<section class="headless-switch-release-example">',
      '  <div class="headless-switch-release-example__row">',
      '    <div class="headless-switch-release-example__copy">',
      '      <span class="headless-switch-release-example__title">Release summary email</span>',
      '      <span class="headless-switch-release-example__meta">Send the launch digest to stakeholders.</span>',
      '    </div>',
      '    <button',
      '      tngSwitch',
      '      class="headless-switch-release-example__control"',
      '      [checked]="releaseEmailsEnabled()"',
      '      ariaLabel="Release summary email"',
      '      (click)="onReleaseEmailsToggle()"',
      '    >',
      '      <span class="headless-switch-release-example__thumb" aria-hidden="true"></span>',
      '    </button>',
      '  </div>',
      '  <div class="headless-switch-release-example__row">',
      '    <div class="headless-switch-release-example__copy">',
      '      <span class="headless-switch-release-example__title">Freeze deploy window</span>',
      '      <span class="headless-switch-release-example__meta">Pause publishing until the handoff call ends.</span>',
      '    </div>',
      '    <button',
      '      tngSwitch',
      '      class="headless-switch-release-example__control"',
      '      [checked]="freezeDeployWindow()"',
      '      ariaLabel="Freeze deploy window"',
      '      (click)="onFreezeDeployWindowToggle()"',
      '    >',
      '      <span class="headless-switch-release-example__thumb" aria-hidden="true"></span>',
      '    </button>',
      '  </div>',
      '</section>',
      '',
    ].join('\n'),
    [
      '.headless-switch-release-example {',
      '  display: grid;',
      '  gap: 0.75rem;',
      '  inline-size: min(100%, 32rem);',
      '  margin-inline: auto;',
      '  padding: 1rem;',
      '  border: 1px solid #cbd5e1;',
      '  border-radius: 1rem;',
      '  background: #ffffff;',
      '  color: #0f172a;',
      '  color-scheme: light;',
      '}',
      '',
      '.headless-switch-release-example__row {',
      '  display: inline-flex;',
      '  align-items: center;',
      '  justify-content: space-between;',
      '  gap: 1rem;',
      '}',
      '',
      '.headless-switch-release-example__copy {',
      '  display: grid;',
      '  gap: 0.2rem;',
      '}',
      '',
      '.headless-switch-release-example__title {',
      '  font-size: 0.95rem;',
      '  font-weight: 700;',
      '  color: #0f172a;',
      '}',
      '',
      '.headless-switch-release-example__meta {',
      '  font-size: 0.82rem;',
      '  color: #64748b;',
      '}',
      '',
      '.headless-switch-release-example__control {',
      '  align-items: center;',
      '  display: inline-flex;',
      '  justify-content: flex-start;',
      '  inline-size: 2.75rem;',
      '  block-size: 1.55rem;',
      '  padding: 0.125rem;',
      '  border: 0;',
      '  border-radius: 999px;',
      '  background: #cbd5e1;',
      '  cursor: pointer;',
      '  transition: background-color 150ms ease;',
      '}',
      '',
      '.headless-switch-release-example__control[data-state="checked"] {',
      '  background: #2563eb;',
      '}',
      '',
      '.headless-switch-release-example__control:focus-visible {',
      '  outline: 2px solid rgba(37, 99, 235, 0.32);',
      '  outline-offset: 2px;',
      '}',
      '',
      '.headless-switch-release-example__thumb {',
      '  display: block;',
      '  inline-size: 1.25rem;',
      '  block-size: 1.25rem;',
      '  border-radius: 999px;',
      '  background: #ffffff;',
      '  box-shadow: 0 1px 2px rgba(15, 23, 42, 0.16);',
      '  transform: translateX(0);',
      '  transition: transform 150ms ease;',
      '}',
      '',
      '.headless-switch-release-example__control[data-state="checked"] .headless-switch-release-example__thumb {',
      '  transform: translateX(1.18rem);',
      '}',
      '',
    ].join('\n'),
  );

  protected readonly releasePreferencesTailwindCodeTabs = createCodeTabs(
    'headless-switch-release-preferences-tailwind',
    [
      "import { Component, signal } from '@angular/core';",
      "import { TngSwitch } from '@tailng-ui/primitives';",
      '',
      '@Component({',
      "  selector: 'app-headless-switch-release-preferences-tailwind',",
      '  standalone: true,',
      '  imports: [TngSwitch],',
      "  templateUrl: './headless-switch-release-preferences-tailwind.component.html',",
      '})',
      'export class HeadlessSwitchReleasePreferencesTailwindComponent {',
      '  readonly releaseEmailsEnabled = signal(true);',
      '  readonly freezeDeployWindow = signal(false);',
      '',
      '  onReleaseEmailsToggle(): void {',
      '    this.releaseEmailsEnabled.update((value) => !value);',
      '  }',
      '',
      '  onFreezeDeployWindowToggle(): void {',
      '    this.freezeDeployWindow.update((value) => !value);',
      '  }',
      '}',
      '',
    ].join('\n'),
    [
      '<section class="grid w-full max-w-[32rem] gap-3 rounded-2xl border border-slate-300 bg-white p-4 text-slate-900 shadow-sm [color-scheme:light]">',
      '  <div class="inline-flex items-center justify-between gap-4">',
      '    <div class="grid gap-0.5">',
      '      <span class="text-sm font-semibold text-slate-900">Release summary email</span>',
      '      <span class="text-xs text-slate-500">Send the launch digest to stakeholders.</span>',
      '    </div>',
      '    <button',
      '      tngSwitch',
      '      class="inline-flex h-6 w-11 items-center rounded-full border-0 bg-slate-300 p-0.5 transition data-[state=checked]:bg-blue-600 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-blue-100"',
      '      [checked]="releaseEmailsEnabled()"',
      '      ariaLabel="Release summary email"',
      '      (click)="onReleaseEmailsToggle()"',
      '    >',
      '      <span aria-hidden="true" class="block h-5 w-5 rounded-full bg-white shadow-sm transition-transform" [class.translate-x-5]="releaseEmailsEnabled()"></span>',
      '    </button>',
      '  </div>',
      '  <div class="inline-flex items-center justify-between gap-4">',
      '    <div class="grid gap-0.5">',
      '      <span class="text-sm font-semibold text-slate-900">Freeze deploy window</span>',
      '      <span class="text-xs text-slate-500">Pause publishing until the handoff call ends.</span>',
      '    </div>',
      '    <button',
      '      tngSwitch',
      '      class="inline-flex h-6 w-11 items-center rounded-full border-0 bg-slate-300 p-0.5 transition data-[state=checked]:bg-blue-600 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-blue-100"',
      '      [checked]="freezeDeployWindow()"',
      '      ariaLabel="Freeze deploy window"',
      '      (click)="onFreezeDeployWindowToggle()"',
      '    >',
      '      <span aria-hidden="true" class="block h-5 w-5 rounded-full bg-white shadow-sm transition-transform" [class.translate-x-5]="freezeDeployWindow()"></span>',
      '    </button>',
      '  </div>',
      '</section>',
      '',
    ].join('\n'),
    '/* Tailwind utilities are applied directly in the template. */',
  );

  protected readonly privacyPlainCodeTabs = createCodeTabs(
    'headless-switch-privacy-plain',
    [
      "import { Component, signal } from '@angular/core';",
      "import { TngSwitch } from '@tailng-ui/primitives';",
      '',
      '@Component({',
      "  selector: 'app-headless-switch-privacy-plain',",
      '  standalone: true,',
      '  imports: [TngSwitch],',
      "  templateUrl: './headless-switch-privacy-plain.component.html',",
      "  styleUrl: './headless-switch-privacy-plain.component.css',",
      '})',
      'export class HeadlessSwitchPrivacyPlainComponent {',
      '  readonly shareDiagnosticLogs = signal(true);',
      '',
      '  onShareDiagnosticLogsToggle(): void {',
      '    this.shareDiagnosticLogs.update((value) => !value);',
      '  }',
      '}',
      '',
    ].join('\n'),
    [
      '<section class="headless-switch-privacy-card">',
      '  <div class="headless-switch-privacy-card__row">',
      '    <div class="headless-switch-privacy-card__copy">',
      '      <span class="headless-switch-privacy-card__title">Share diagnostic logs</span>',
      '      <span class="headless-switch-privacy-card__meta">Include anonymized traces in support bundles.</span>',
      '    </div>',
      '    <button',
      '      tngSwitch',
      '      class="headless-switch-privacy-card__control"',
      '      [checked]="shareDiagnosticLogs()"',
      '      ariaLabel="Share diagnostic logs"',
      '      (click)="onShareDiagnosticLogsToggle()"',
      '    >',
      '      <span class="headless-switch-privacy-card__thumb" aria-hidden="true"></span>',
      '    </button>',
      '  </div>',
      '  <p class="headless-switch-privacy-card__helper">Your workspace owner can revoke this at any time.</p>',
      '</section>',
      '',
    ].join('\n'),
    [
      '.headless-switch-privacy-card {',
      '  display: grid;',
      '  gap: 0.85rem;',
      '  inline-size: min(100%, 32rem);',
      '  margin-inline: auto;',
      '  padding: 1rem;',
      '  border: 1px solid #cbd5e1;',
      '  border-radius: 1rem;',
      '  background: #ffffff;',
      '  color: #0f172a;',
      '  color-scheme: light;',
      '}',
      '',
      '.headless-switch-privacy-card__row {',
      '  display: inline-flex;',
      '  align-items: center;',
      '  justify-content: space-between;',
      '  gap: 1rem;',
      '}',
      '',
      '.headless-switch-privacy-card__copy { display: grid; gap: 0.2rem; }',
      '.headless-switch-privacy-card__title { font-size: 0.95rem; font-weight: 700; color: #0f172a; }',
      '.headless-switch-privacy-card__meta,',
      '.headless-switch-privacy-card__helper { font-size: 0.82rem; color: #64748b; margin: 0; }',
      '.headless-switch-privacy-card__control {',
      '  align-items: center; display: inline-flex; justify-content: flex-start;',
      '  inline-size: 2.75rem; block-size: 1.55rem; padding: 0.125rem;',
      '  border: 0; border-radius: 999px; background: #cbd5e1; cursor: pointer;',
      '  transition: background-color 150ms ease;',
      '}',
      '.headless-switch-privacy-card__control[data-state="checked"] { background: #2563eb; }',
      '.headless-switch-privacy-card__control:focus-visible { outline: 2px solid rgba(37, 99, 235, 0.32); outline-offset: 2px; }',
      '.headless-switch-privacy-card__thumb {',
      '  display: block; inline-size: 1.25rem; block-size: 1.25rem; border-radius: 999px;',
      '  background: #ffffff; box-shadow: 0 1px 2px rgba(15, 23, 42, 0.16);',
      '  transform: translateX(0); transition: transform 150ms ease;',
      '}',
      '.headless-switch-privacy-card__control[data-state="checked"] .headless-switch-privacy-card__thumb { transform: translateX(1.18rem); }',
      '',
    ].join('\n'),
  );

  protected readonly privacyTailwindCodeTabs = createCodeTabs(
    'headless-switch-privacy-tailwind',
    [
      "import { Component, signal } from '@angular/core';",
      "import { TngSwitch } from '@tailng-ui/primitives';",
      '',
      '@Component({',
      "  selector: 'app-headless-switch-privacy-tailwind',",
      '  standalone: true,',
      '  imports: [TngSwitch],',
      "  templateUrl: './headless-switch-privacy-tailwind.component.html',",
      '})',
      'export class HeadlessSwitchPrivacyTailwindComponent {',
      '  readonly shareDiagnosticLogs = signal(true);',
      '',
      '  onShareDiagnosticLogsToggle(): void {',
      '    this.shareDiagnosticLogs.update((value) => !value);',
      '  }',
      '}',
      '',
    ].join('\n'),
    [
      '<section class="grid w-full max-w-[32rem] gap-3 rounded-2xl border border-slate-300 bg-white p-4 text-slate-900 shadow-sm [color-scheme:light]">',
      '  <div class="inline-flex items-center justify-between gap-4">',
      '    <div class="grid gap-0.5">',
      '      <span class="text-sm font-semibold text-slate-900">Share diagnostic logs</span>',
      '      <span class="text-xs text-slate-500">Include anonymized traces in support bundles.</span>',
      '    </div>',
      '    <button',
      '      tngSwitch',
      '      class="inline-flex h-6 w-11 items-center rounded-full border-0 bg-slate-300 p-0.5 transition data-[state=checked]:bg-blue-600 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-blue-100"',
      '      [checked]="shareDiagnosticLogs()"',
      '      ariaLabel="Share diagnostic logs"',
      '      (click)="onShareDiagnosticLogsToggle()"',
      '    >',
      '      <span aria-hidden="true" class="block h-5 w-5 rounded-full bg-white shadow-sm transition-transform" [class.translate-x-5]="shareDiagnosticLogs()"></span>',
      '    </button>',
      '  </div>',
      '  <p class="m-0 text-xs text-slate-500">Your workspace owner can revoke this at any time.</p>',
      '</section>',
      '',
    ].join('\n'),
    '/* Tailwind utilities are applied directly in the template. */',
  );

  protected readonly disabledPlainCodeTabs = createCodeTabs(
    'headless-switch-disabled-plain',
    [
      "import { Component } from '@angular/core';",
      "import { TngSwitch } from '@tailng-ui/primitives';",
      '',
      '@Component({',
      "  selector: 'app-headless-switch-disabled-plain',",
      '  standalone: true,',
      '  imports: [TngSwitch],',
      "  templateUrl: './headless-switch-disabled-plain.component.html',",
      "  styleUrl: './headless-switch-disabled-plain.component.css',",
      '})',
      'export class HeadlessSwitchDisabledPlainComponent {}',
      '',
    ].join('\n'),
    [
      '<section class="headless-switch-state-card">',
      '  <div class="headless-switch-state-card__row">',
      '    <span class="headless-switch-state-card__title">Emergency cutoff</span>',
      '    <button',
      '      tngSwitch',
      '      class="headless-switch-state-card__control"',
      '      [checked]="true"',
      '      [required]="true"',
      '      ariaLabel="Emergency cutoff"',
      '    >',
      '      <span class="headless-switch-state-card__thumb" aria-hidden="true"></span>',
      '    </button>',
      '  </div>',
      '  <div class="headless-switch-state-card__row headless-switch-state-card__row--disabled">',
      '    <span class="headless-switch-state-card__title">Production bypass</span>',
      '    <button',
      '      tngSwitch',
      '      class="headless-switch-state-card__control"',
      '      [checked]="false"',
      '      [disabled]="true"',
      '      ariaLabel="Production bypass"',
      '    >',
      '      <span class="headless-switch-state-card__thumb" aria-hidden="true"></span>',
      '    </button>',
      '  </div>',
      '</section>',
      '',
    ].join('\n'),
    [
      '.headless-switch-state-card {',
      '  display: grid;',
      '  gap: 0.75rem;',
      '  inline-size: min(100%, 32rem);',
      '  margin-inline: auto;',
      '  padding: 1rem;',
      '  border: 1px solid #cbd5e1;',
      '  border-radius: 1rem;',
      '  background: #ffffff;',
      '  color: #0f172a;',
      '  color-scheme: light;',
      '}',
      '.headless-switch-state-card__row {',
      '  display: inline-flex; align-items: center; justify-content: space-between; gap: 1rem;',
      '}',
      '.headless-switch-state-card__row--disabled { color: #64748b; }',
      '.headless-switch-state-card__title { font-size: 0.92rem; font-weight: 600; }',
      '.headless-switch-state-card__control {',
      '  align-items: center; display: inline-flex; justify-content: flex-start;',
      '  inline-size: 2.75rem; block-size: 1.55rem; padding: 0.125rem;',
      '  border: 0; border-radius: 999px; background: #cbd5e1; cursor: pointer; transition: background-color 150ms ease;',
      '}',
      '.headless-switch-state-card__control[data-state="checked"] { background: #2563eb; }',
      '.headless-switch-state-card__control[data-disabled] { cursor: not-allowed; opacity: 0.55; }',
      '.headless-switch-state-card__thumb {',
      '  display: block; inline-size: 1.25rem; block-size: 1.25rem; border-radius: 999px;',
      '  background: #ffffff; box-shadow: 0 1px 2px rgba(15, 23, 42, 0.16); transform: translateX(0); transition: transform 150ms ease;',
      '}',
      '.headless-switch-state-card__control[data-state="checked"] .headless-switch-state-card__thumb { transform: translateX(1.18rem); }',
      '',
    ].join('\n'),
  );

  protected readonly disabledTailwindCodeTabs = createCodeTabs(
    'headless-switch-disabled-tailwind',
    [
      "import { Component } from '@angular/core';",
      "import { TngSwitch } from '@tailng-ui/primitives';",
      '',
      '@Component({',
      "  selector: 'app-headless-switch-disabled-tailwind',",
      '  standalone: true,',
      '  imports: [TngSwitch],',
      "  templateUrl: './headless-switch-disabled-tailwind.component.html',",
      '})',
      'export class HeadlessSwitchDisabledTailwindComponent {}',
      '',
    ].join('\n'),
    [
      '<section class="grid w-full max-w-[32rem] gap-3 rounded-2xl border border-slate-300 bg-white p-4 text-slate-900 shadow-sm [color-scheme:light]">',
      '  <div class="inline-flex items-center justify-between gap-4">',
      '    <span class="text-sm font-semibold text-slate-900">Emergency cutoff</span>',
      '    <button',
      '      tngSwitch',
      '      class="inline-flex h-6 w-11 items-center rounded-full border-0 bg-slate-300 p-0.5 transition data-[state=checked]:bg-blue-600 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-blue-100"',
      '      [checked]="true"',
      '      [required]="true"',
      '      ariaLabel="Emergency cutoff"',
      '    >',
      '      <span aria-hidden="true" class="block h-5 w-5 rounded-full bg-white shadow-sm transition-transform translate-x-5"></span>',
      '    </button>',
      '  </div>',
      '  <div class="inline-flex items-center justify-between gap-4 text-slate-500">',
      '    <span class="text-sm font-semibold">Production bypass</span>',
      '    <button',
      '      tngSwitch',
      '      class="inline-flex h-6 w-11 items-center rounded-full border-0 bg-slate-300 p-0.5 opacity-55 transition data-[state=checked]:bg-blue-600"',
      '      [checked]="false"',
      '      [disabled]="true"',
      '      ariaLabel="Production bypass"',
      '    >',
      '      <span aria-hidden="true" class="block h-5 w-5 rounded-full bg-white shadow-sm"></span>',
      '    </button>',
      '  </div>',
      '</section>',
      '',
    ].join('\n'),
    '/* Tailwind utilities are applied directly in the template. */',
  );

  public onPlainCssReleaseEmailsToggle(): void {
    this.plainCssReleaseEmails.update((value) => !value);
  }

  public onPlainCssDeployWindowToggle(): void {
    this.plainCssDeployWindow.update((value) => !value);
  }

  public onPlainCssPrivacyToggle(): void {
    this.plainCssPrivacy.update((value) => !value);
  }

  public onTailwindReleaseEmailsToggle(): void {
    this.tailwindReleaseEmails.update((value) => !value);
  }

  public onTailwindDeployWindowToggle(): void {
    this.tailwindDeployWindow.update((value) => !value);
  }

  public onTailwindPrivacyToggle(): void {
    this.tailwindPrivacy.update((value) => !value);
  }

  public ngOnDestroy(): void {
    this.colorSchemeObserver?.disconnect();
  }
}
