export * from './autocomplete/tng-autocomplete.component';
export { TngAutocompleteComponent as TngAutocomplete } from './autocomplete/tng-autocomplete.component';
export * from './button-toggle/tng-button-toggle.component';
export { TngButtonToggleComponent as TngButtonToggle } from './button-toggle/tng-button-toggle.component';
export * from './button-toggle/tng-button-toggle-group.component';
export { TngButtonToggleGroupComponent as TngButtonToggleGroup } from './button-toggle/tng-button-toggle-group.component';
export * from './checkbox/tng-checkbox.component';
export { TngCheckboxComponent as TngCheckbox } from './checkbox/tng-checkbox.component';
export * from './chips/tng-chips.component';
export { TngChipsComponent as TngChips } from './chips/tng-chips.component';
export * from './combobox/tng-combobox.component';
export { TngComboboxComponent as TngCombobox } from './combobox/tng-combobox.component';
export * from './input/tng-input.component';
export { TngInputComponent as TngInput } from './input/tng-input.component';
export * from './input-otp/tng-input-otp.component';
export { TngInputOtpComponent as TngInputOtp } from './input-otp/tng-input-otp.component';
export * from './label/tng-label.component';
export { TngLabelComponent as TngLabel } from './label/tng-label.component';
export * from './multiselect/tng-multiselect.component';
export { TngMultiselectComponent as TngMultiselect } from './multiselect/tng-multiselect.component';
export * from './radio/tng-radio.component';
export { TngRadioComponent as TngRadio } from './radio/tng-radio.component';
export * from './select/tng-select.component';
export { TngSelectComponent as TngSelect } from './select/tng-select.component';
export * from './slider/tng-slider.component';
export { TngSliderComponent as TngSlider } from './slider/tng-slider.component';
export * from './switch/tng-switch.component';
export { TngSwitchComponent as TngSwitch } from './switch/tng-switch.component';
export * from './textarea/tng-textarea.component';
export { TngTextareaComponent as TngTextarea } from './textarea/tng-textarea.component';
export * from './toggle/tng-toggle.component';
export { TngToggleComponent as TngToggle } from './toggle/tng-toggle.component';
export * from './toggle-group/tng-toggle-group.component';
export { TngToggleGroupComponent as TngToggleGroup } from './toggle-group/tng-toggle-group.component';
