export * from './autocomplete/tng-autocomplete.component';
export { TngAutocompleteComponent } from './autocomplete/tng-autocomplete.component';
export * from './button-toggle/tng-button-toggle.component';
export { TngButtonToggleComponent } from './button-toggle/tng-button-toggle.component';
export * from './button-toggle/tng-button-toggle-group.component';
export { TngButtonToggleGroupComponent} from './button-toggle/tng-button-toggle-group.component';
export * from './checkbox/tng-checkbox.component';
export { TngCheckboxComponent} from './checkbox/tng-checkbox.component';
export * from './chips/tng-chips.component';
export { TngChipsComponent} from './chips/tng-chips.component';
export * from './combobox/tng-combobox.component';
export { TngComboboxComponent} from './combobox/tng-combobox.component';
export * from './input/tng-input.component';
export { TngInputComponent} from './input/tng-input.component';
export * from './input-otp';
export { TngInputOtpComponent } from './input-otp';
export * from './label/tng-label.component';
export { TngLabelComponent} from './label/tng-label.component';
export * from './multi-autocomplete/tng-multi-autocomplete.component';
export { TngMultiAutocompleteComponent } from './multi-autocomplete/tng-multi-autocomplete.component';
export * from './multiselect/tng-multiselect.component';
export { TngMultiSelectComponent } from './multiselect/tng-multiselect.component';
export * from './radio/tng-radio.component';
export { TngRadioComponent} from './radio/tng-radio.component';
export * from './select/tng-select.component';
export { TngSelectComponent} from './select/tng-select.component';
export * from './slider/tng-slider.component';
export { TngSliderComponent} from './slider/tng-slider.component';
export * from './switch/tng-switch.component';
export { TngSwitchComponent} from './switch/tng-switch.component';
export * from './textarea/tng-textarea.component';
export { TngTextareaComponent} from './textarea/tng-textarea.component';
export * from './toggle/tng-toggle.component';
export { TngToggleComponent} from './toggle/tng-toggle.component';
export * from './toggle-group/tng-toggle-group.component';
export { TngToggleGroupComponent} from './toggle-group/tng-toggle-group.component';
