import { DOCUMENT } from '@angular/common';
import { Component, inject, signal, type OnDestroy } from '@angular/core';
import { TngCodeBlockComponent } from '@tailng-ui/components';
import { TngTree, TngTreeGroup, TngTreeIndicator, TngTreeItem } from '@tailng-ui/primitives';
import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import {
  observeDocsCodeThemeChanges,
  resolveDocsCodeBlockTheme,
} from '../../../../../../shared/util';

@Component({
  selector: 'app-headless-tree-overview-page',
  imports: [
    TngCodeBlockComponent,
    TngTree,
    TngTreeItem,
    TngTreeGroup,
    TngTreeIndicator,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
  ],
  templateUrl: './tree-overview-page.component.html',
  styleUrls: ['./tree-overview-page.component.css'],
})
export class HeadlessTreeOverviewPageComponent implements OnDestroy {
  private readonly documentRef = inject(DOCUMENT);

  public readonly codeBlockTheme = signal<'github-dark' | 'github-light'>(
    resolveDocsCodeBlockTheme(this.documentRef),
  );
  private readonly colorSchemeObserver = observeDocsCodeThemeChanges(
    this.documentRef,
    this.codeBlockTheme,
  );

  protected readonly importCode = [
    'import {',
    '  TngTree,',
    '  TngTreeItem,',
    '  TngTreeGroup,',
    '  TngTreeIndicator,',
    "} from '@tailng-ui/primitives';",
  ].join('\n');

  protected readonly usageCode = [
    '<div',
    "  tngTree",
    "  [selectionMode]=\"'single'\"",
    "  [defaultValue]=\"'button'\"",
    '  aria-label="Project files"',
    '>',
    "  <div tngTreeItem [value]=\"'src'\" [defaultExpanded]=\"true\">",
    '    <span class="tree-node-row">',
    '      <span tngTreeIndicator class="tree-indicator">📂</span>',
    '      src',
    '    </span>',
    '    <div tngTreeGroup class="tree-node-group">',
    "      <div tngTreeItem [value]=\"'components'\" [defaultExpanded]=\"true\">",
    '        <span class="tree-node-row">',
    '          <span tngTreeIndicator class="tree-indicator">📂</span>',
    '          components',
    '        </span>',
    '        <div tngTreeGroup class="tree-node-group">',
    "          <div tngTreeItem [value]=\"'button'\">",
    '            <span class="tree-node-row">',
    '              <span class="tree-icon">📄</span>',
    '              button.ts',
    '            </span>',
    '          </div>',
    '        </div>',
    '      </div>',
    '    </div>',
    '  </div>',
    '</div>',
  ].join('\n');

  protected readonly plainCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'headless-tree-overview-plain.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import { TngTree, TngTreeGroup, TngTreeIndicator, TngTreeItem } from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-headless-tree-overview-plain',",
        '  standalone: true,',
        '  imports: [TngTree, TngTreeItem, TngTreeGroup, TngTreeIndicator],',
        "  templateUrl: './headless-tree-overview-plain.component.html',",
        "  styleUrl: './headless-tree-overview-plain.component.css',",
        '})',
        'export class HeadlessTreeOverviewPlainComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'headless-tree-overview-plain.component.html',
      code: [
        '<div class="headless-tree-shell">',
        '  <div tngTree [selectionMode]="\'single\'" [defaultValue]="\'button\'" aria-label="Project files" class="headless-tree-root">',
        '    <div tngTreeItem [value]="\'src\'" [defaultExpanded]="true">',
        '      <span class="tree-node-row"><span tngTreeIndicator class="tree-indicator">📂</span>src</span>',
        '      <div tngTreeGroup class="tree-node-group">',
        '        <div tngTreeItem [value]="\'components\'" [defaultExpanded]="true">',
        '          <span class="tree-node-row"><span tngTreeIndicator class="tree-indicator">📂</span>components</span>',
        '          <div tngTreeGroup class="tree-node-group">',
        '            <div tngTreeItem [value]="\'button\'">',
        '              <span class="tree-node-row"><span class="tree-icon">📄</span>button.ts</span>',
        '            </div>',
        '            <div tngTreeItem [value]="\'input\'">',
        '              <span class="tree-node-row"><span class="tree-icon">📄</span>input.ts</span>',
        '            </div>',
        '          </div>',
        '        </div>',
        '        <div tngTreeItem [value]="\'utils\'">',
        '          <span class="tree-node-row"><span class="tree-icon">📄</span>utils.ts</span>',
        '        </div>',
        '      </div>',
        '    </div>',
        '  </div>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'headless-tree-overview-plain.component.css',
      code: [
        '.headless-tree-shell {',
        '  border: 1px solid var(--tng-semantic-border-subtle);',
        '  border-radius: 0.9rem;',
        '  padding: 0.9rem 1rem;',
        '}',
        '',
        '.headless-tree-root {',
        '  cursor: default;',
        '  font-size: 0.875rem;',
        '  line-height: 1.7rem;',
        '}',
        '',
        ".headless-tree-root [data-slot='tree-item'][data-expanded='false'] > [data-slot='tree-group'] {",
        '  display: none;',
        '}',
        '',
        '.tree-node-row {',
        '  align-items: center;',
        '  border-radius: 0.4rem;',
        '  display: inline-flex;',
        '  gap: 0.35rem;',
        '  padding: 0 0.35rem;',
        '}',
        '',
        ".headless-tree-root [data-slot='tree-item'][data-selected='true'] > .tree-node-row {",
        '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 14%, transparent);',
        '  color: var(--tng-semantic-accent-brand);',
        '}',
        '',
        ".headless-tree-root [data-slot='tree-item']:focus-visible > .tree-node-row {",
        '  box-shadow: 0 0 0 2px var(--tng-semantic-focus-ring);',
        '}',
        '',
        '.tree-node-group {',
        '  border-left: 1px solid var(--tng-semantic-border-subtle);',
        '  margin-left: 1.15rem;',
        '  padding-left: 0.75rem;',
        '}',
        '',
        '.tree-indicator {',
        '  display: inline-block;',
        '  text-align: center;',
        '  width: 1rem;',
        '}',
      ].join('\n'),
    },
  ]);

  protected readonly tailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'headless-tree-overview-tailwind.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import { TngTree, TngTreeGroup, TngTreeIndicator, TngTreeItem } from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-headless-tree-overview-tailwind',",
        '  standalone: true,',
        '  imports: [TngTree, TngTreeItem, TngTreeGroup, TngTreeIndicator],',
        "  templateUrl: './headless-tree-overview-tailwind.component.html',",
        "  styleUrl: './headless-tree-overview-tailwind.component.css',",
        '})',
        'export class HeadlessTreeOverviewTailwindComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'headless-tree-overview-tailwind.component.html',
      code: [
        '<div class="rounded-xl border border-slate-300 bg-slate-50 p-4 text-sm dark:border-slate-700 dark:bg-slate-900/60 [&_[data-slot=tree-item][data-expanded=false]>.tree-node-group]:hidden [&_[data-slot=tree-item][data-selected=true]>.tree-node-row]:bg-sky-100 [&_[data-slot=tree-item][data-selected=true]>.tree-node-row]:text-sky-900 dark:[&_[data-slot=tree-item][data-selected=true]>.tree-node-row]:bg-sky-900/40 dark:[&_[data-slot=tree-item][data-selected=true]>.tree-node-row]:text-sky-100">',
        '  <div tngTree [selectionMode]="\'single\'" [defaultValue]="\'button\'" aria-label="Project files" class="leading-7">',
        '    <div tngTreeItem [value]="\'src\'" [defaultExpanded]="true">',
        '      <span class="tree-node-row inline-flex items-center gap-1.5 rounded-md px-1.5"><span tngTreeIndicator class="tree-indicator inline-block w-4 text-center text-xs">📂</span>src</span>',
        '      <div tngTreeGroup class="tree-node-group ml-5 border-l border-slate-300 pl-3 dark:border-slate-700">',
        '        <div tngTreeItem [value]="\'components\'" [defaultExpanded]="true">',
        '          <span class="tree-node-row inline-flex items-center gap-1.5 rounded-md px-1.5"><span tngTreeIndicator class="tree-indicator inline-block w-4 text-center text-xs">📂</span>components</span>',
        '          <div tngTreeGroup class="tree-node-group ml-5 border-l border-slate-300 pl-3 dark:border-slate-700">',
        '            <div tngTreeItem [value]="\'button\'">',
        '              <span class="tree-node-row inline-flex items-center gap-1.5 rounded-md px-1.5"><span class="tree-icon inline-block w-4 text-center text-xs">📄</span>button.ts</span>',
        '            </div>',
        '            <div tngTreeItem [value]="\'input\'">',
        '              <span class="tree-node-row inline-flex items-center gap-1.5 rounded-md px-1.5"><span class="tree-icon inline-block w-4 text-center text-xs">📄</span>input.ts</span>',
        '            </div>',
        '          </div>',
        '        </div>',
        '        <div tngTreeItem [value]="\'utils\'">',
        '          <span class="tree-node-row inline-flex items-center gap-1.5 rounded-md px-1.5"><span class="tree-icon inline-block w-4 text-center text-xs">📄</span>utils.ts</span>',
        '        </div>',
        '      </div>',
        '    </div>',
        '  </div>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'headless-tree-overview-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  public ngOnDestroy(): void {
    this.colorSchemeObserver?.disconnect();
  }
}
