import { Component } from '@angular/core';
import { TngCodeBlockComponent } from '@tailng-ui/components';

@Component({
  selector: 'app-dialog-styling-page',
  imports: [TngCodeBlockComponent],
  templateUrl: './dialog-styling-page.component.html',
  styleUrl: './dialog-styling-page.component.css',
})
export class DialogStylingPageComponent {
  protected readonly stylingContractCode = [
    '[tngDialog][data-open="true"] {',
    '  --dialog-backdrop: rgb(2 6 23 / 56%);',
    '  --tng-dialog-width: 64rem;',
    '  --tng-dialog-height: 28rem;',
    '}',
    '',
    '[data-slot="dialog-backdrop"] {',
    '  align-items: center;',
    '  background: var(--dialog-backdrop);',
    '  display: grid;',
    '  inset: 0;',
    '  position: fixed;',
    '}',
    '',
    '[data-slot="dialog-panel"] {',
    '  background: var(--tng-semantic-background-surface);',
    '  border: 1px solid var(--tng-semantic-border-subtle);',
    '  border-radius: 0.9rem;',
    '  display: grid;',
    '  gap: 0.75rem;',
    '  height: var(--tng-dialog-height, auto);',
    '  max-width: var(--tng-dialog-width, 34rem);',
    '  padding: 1rem;',
    '}',
    '',
    '[data-slot="dialog-content"] {',
    '  display: grid;',
    '  gap: 0.75rem;',
    '  max-block-size: min(52vh, 24rem);',
    '  overflow: auto;',
    '  padding-inline: 1rem;',
    '}',
    '',
    '[data-slot="dialog-close"] {',
    '  border-radius: 0.6rem;',
    '  min-height: 2rem;',
    '}',
  ].join('\n');
}
