import { DOCUMENT } from '@angular/common';
import { Component, inject, signal, type OnDestroy } from '@angular/core';
import { TngCodeBlockComponent } from '@tailng-ui/components';
import {
  TngDialog,
  TngDialogActions,
  TngDialogBackdrop,
  TngDialogClose,
  TngDialogDescription,
  TngDialogPanel,
  TngDialogTitle,
  TngDialogTrigger,
  type TngDialogCloseReason,
} from '@tailng-ui/primitives';
import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import {
  observeDocsCodeThemeChanges,
  resolveDocsCodeBlockTheme,
} from '../../../../../../shared/util';

@Component({
  selector: 'app-headless-dialog-examples-page',
  imports: [
    TngCodeBlockComponent,
    TngDialog,
    TngDialogActions,
    TngDialogBackdrop,
    TngDialogClose,
    TngDialogDescription,
    TngDialogPanel,
    TngDialogTitle,
    TngDialogTrigger,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
  ],
  templateUrl: './dialog-examples-page.component.html',
  styleUrl: './dialog-examples-page.component.css',
})
export class HeadlessDialogExamplesPageComponent implements OnDestroy {
  private readonly documentRef = inject(DOCUMENT);

  public readonly codeBlockTheme = signal<'github-dark' | 'github-light'>(
    resolveDocsCodeBlockTheme(this.documentRef),
  );
  private readonly colorSchemeObserver = observeDocsCodeThemeChanges(
    this.documentRef,
    this.codeBlockTheme,
  );

  protected readonly destructiveOpen = signal(false);
  protected readonly destructiveResult = signal('No decision yet');

  protected readonly destructivePlainCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'headless-dialog-destructive-plain.component.ts',
      code: [
        "import { Component, signal } from '@angular/core';",
        'import {',
        '  TngDialog,',
        '  TngDialogActions,',
        '  TngDialogBackdrop,',
        '  TngDialogClose,',
        '  TngDialogDescription,',
        '  TngDialogPanel,',
        '  TngDialogTitle,',
        '  TngDialogTrigger,',
        "  type TngDialogCloseReason,",
        "} from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-headless-dialog-destructive-plain',",
        '  standalone: true,',
        '  imports: [',
        '    TngDialog,',
        '    TngDialogActions,',
        '    TngDialogBackdrop,',
        '    TngDialogClose,',
        '    TngDialogDescription,',
        '    TngDialogPanel,',
        '    TngDialogTitle,',
        '    TngDialogTrigger,',
        '  ],',
        "  templateUrl: './headless-dialog-destructive-plain.component.html',",
        "  styleUrl: './headless-dialog-destructive-plain.component.css',",
        '})',
        'export class HeadlessDialogDestructivePlainComponent {',
        '  protected readonly open = signal(false);',
        "  protected readonly result = signal('No decision yet');",
        '',
        '  protected onClosed(reason: TngDialogCloseReason): void {',
        "    this.result.set(reason === 'programmatic' ? 'Deleted release branch' : `Closed (${reason})`);",
        '  }',
        '',
        '  protected onOpenChange(next: boolean): void {',
        '    this.open.set(next);',
        '  }',
        '}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'headless-dialog-destructive-plain.component.html',
      code: [
        '<button type="button" class="headless-dialog-example-trigger" [tngDialogTrigger]="dialog">',
        '  Delete release branch',
        '</button>',
        '',
        '<section',
        '  tngDialog',
        '  #dialog="tngDialog"',
        '  [open]="open()"',
        '  (openChange)="onOpenChange($event)"',
        '  (closed)="onClosed($event)"',
        '>',
        '  <div tngDialogBackdrop class="headless-dialog-example-backdrop">',
        '    <section tngDialogPanel class="headless-dialog-example-panel">',
        '      <h3 tngDialogTitle class="headless-dialog-example-title">Delete release branch?</h3>',
        '      <p tngDialogDescription class="headless-dialog-example-copy">This action removes branch automation and cannot be undone.</p>',
        '      <div tngDialogActions class="headless-dialog-action-row">',
        '        <button type="button" tngDialogClose class="headless-dialog-example-secondary">Cancel</button>',
        "        <button type=\"button\" tngDialogClose [tngDialogClose]=\"'programmatic'\" class=\"headless-dialog-example-danger\">Delete</button>",
        '      </div>',
        '    </section>',
        '  </div>',
        '</section>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'headless-dialog-destructive-plain.component.css',
      code: [
        '.headless-dialog-example-backdrop {',
        '  align-items: center;',
        '  background: rgb(2 6 23 / 60%);',
        '  display: grid;',
        '  inset: 0;',
        '  padding: 1rem;',
        '  position: fixed;',
        '}',
        '',
        '.headless-dialog-example-panel {',
        '  background: var(--tng-semantic-background-surface);',
        '  border: 1px solid var(--tng-semantic-border-subtle);',
        '  border-radius: 1rem;',
        '  display: grid;',
        '  gap: 0.75rem;',
        '  inline-size: min(100%, 30rem);',
        '  padding: 1rem;',
        '}',
      ].join('\n'),
    },
  ]);

  protected readonly destructiveTailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'headless-dialog-destructive-tailwind.component.ts',
      code: [
        "import { Component, signal } from '@angular/core';",
        'import {',
        '  TngDialog,',
        '  TngDialogActions,',
        '  TngDialogBackdrop,',
        '  TngDialogClose,',
        '  TngDialogDescription,',
        '  TngDialogPanel,',
        '  TngDialogTitle,',
        '  TngDialogTrigger,',
        "  type TngDialogCloseReason,",
        "} from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-headless-dialog-destructive-tailwind',",
        '  standalone: true,',
        '  imports: [',
        '    TngDialog,',
        '    TngDialogActions,',
        '    TngDialogBackdrop,',
        '    TngDialogClose,',
        '    TngDialogDescription,',
        '    TngDialogPanel,',
        '    TngDialogTitle,',
        '    TngDialogTrigger,',
        '  ],',
        "  templateUrl: './headless-dialog-destructive-tailwind.component.html',",
        "  styleUrl: './headless-dialog-destructive-tailwind.component.css',",
        '})',
        'export class HeadlessDialogDestructiveTailwindComponent {',
        '  protected readonly open = signal(false);',
        "  protected readonly result = signal('No decision yet');",
        '',
        '  protected onClosed(reason: TngDialogCloseReason): void {',
        "    this.result.set(reason === 'programmatic' ? 'Deleted release branch' : `Closed (${reason})`);",
        '  }',
        '',
        '  protected onOpenChange(next: boolean): void {',
        '    this.open.set(next);',
        '  }',
        '}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'headless-dialog-destructive-tailwind.component.html',
      code: [
        '<div class="rounded-xl border border-slate-300 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-900/60">',
        '  <button',
        '    type="button"',
        '    class="rounded-lg border border-rose-300 bg-white px-3 py-2 text-sm font-semibold text-rose-700 dark:border-rose-800 dark:bg-slate-900 dark:text-rose-200"',
        '    [tngDialogTrigger]="dialog"',
        '  >',
        '    Delete release branch',
        '  </button>',
        '',
        '  <section',
        '    tngDialog',
        '    #dialog="tngDialog"',
        '    [open]="open()"',
        '    (openChange)="onOpenChange($event)"',
        '    (closed)="onClosed($event)"',
        '  >',
        '    <div tngDialogBackdrop class="fixed inset-0 grid place-items-center bg-slate-950/70 p-4">',
        '      <section tngDialogPanel class="grid w-full max-w-lg gap-3 rounded-3xl border border-slate-200 bg-white p-5 shadow-2xl dark:border-slate-800 dark:bg-slate-950">',
        '        <h3 tngDialogTitle class="m-0 text-lg font-semibold text-slate-950 dark:text-slate-50">Delete release branch?</h3>',
        '        <p tngDialogDescription class="m-0 text-sm text-slate-600 dark:text-slate-300">This action removes branch automation and cannot be undone.</p>',
        '        <div tngDialogActions class="flex flex-wrap justify-end gap-2">',
        '          <button type="button" tngDialogClose class="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700 dark:border-slate-700 dark:text-slate-200">Cancel</button>',
        "          <button type=\"button\" tngDialogClose [tngDialogClose]=\"'programmatic'\" class=\"rounded-lg border border-rose-600 bg-rose-600 px-3 py-2 text-sm font-semibold text-white\">Delete</button>",
        '        </div>',
        '      </section>',
        '    </div>',
        '  </section>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'headless-dialog-destructive-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  protected readonly controlledReviewTsCode = [
    "import { Component, signal } from '@angular/core';",
    'import {',
    '  TngDialog,',
    '  TngDialogActions,',
    '  TngDialogBackdrop,',
    '  TngDialogClose,',
    '  TngDialogDescription,',
    '  TngDialogPanel,',
    '  TngDialogTitle,',
    "} from '@tailng-ui/primitives';",
    '',
    '@Component({',
    "  selector: 'app-headless-dialog-controlled-review',",
    '  standalone: true,',
    '  imports: [',
    '    TngDialog,',
    '    TngDialogActions,',
    '    TngDialogBackdrop,',
    '    TngDialogClose,',
    '    TngDialogDescription,',
    '    TngDialogPanel,',
    '    TngDialogTitle,',
    '  ],',
    "  templateUrl: './headless-dialog-controlled-review.component.html',",
    "  styleUrl: './headless-dialog-controlled-review.component.css',",
    '})',
    'export class HeadlessDialogControlledReviewComponent {',
    '  protected readonly open = signal(false);',
    '}',
  ].join('\n');

  protected readonly controlledReviewHtmlCode = [
    '<button type="button" (click)="open.set(true)">Open security review</button>',
    '',
    '<section',
    '  tngDialog',
    '  [open]="open()"',
    '  [dismissible]="false"',
    '  [closeOnBackdropClick]="false"',
    '  [closeOnEscape]="false"',
    '  (openChange)="open.set($event)"',
    '>',
    '  <div tngDialogBackdrop class="review-backdrop">',
    '    <section tngDialogPanel class="review-panel">',
    '      <h2 tngDialogTitle>Security review required</h2>',
    '      <p tngDialogDescription>Complete the checklist before continuing.</p>',
    '      <div tngDialogActions class="review-actions">',
    '        <button type="button" tngDialogClose>Cancel</button>',
    "        <button type=\"button\" tngDialogClose [tngDialogClose]=\"'programmatic'\">Continue</button>",
    '      </div>',
    '    </section>',
    '  </div>',
    '</section>',
    '',
  ].join('\n');

  protected readonly controlledReviewCssCode = [
    '.review-backdrop {',
    '  align-items: center;',
    '  background: rgb(15 23 42 / 0.72);',
    '  display: grid;',
    '  inset: 0;',
    '  padding: 1rem;',
    '  position: fixed;',
    '}',
    '',
    '.review-panel {',
    '  inline-size: min(100%, 34rem);',
    '}',
    '',
  ].join('\n');

  public ngOnDestroy(): void {
    this.colorSchemeObserver?.disconnect();
  }

  protected onDestructiveClosed(reason: TngDialogCloseReason): void {
    this.destructiveResult.set(
      reason === 'programmatic' ? 'Deleted release branch' : `Closed (${reason})`,
    );
  }
}
