import { DOCUMENT } from '@angular/common';
import { Component, inject, signal, type OnDestroy } from '@angular/core';
import { TngCodeBlockComponent } from '@tailng-ui/components';
import {
  TngCodeBlock,
  TngCodeBlockBody,
  TngCodeBlockCode,
  TngCodeBlockGutter,
  TngCodeBlockHeader,
} from '@tailng-ui/primitives';
import { type DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import { observeDocsCodeThemeChanges, resolveDocsCodeBlockTheme } from '../../../../../../shared/util';

@Component({
  selector: 'app-headless-codeblock-overview-page',
  imports: [
    TngCodeBlockComponent,
    TngCodeBlock,
    TngCodeBlockHeader,
    TngCodeBlockBody,
    TngCodeBlockGutter,
    TngCodeBlockCode,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
  ],
  templateUrl: './codeblock-overview-page.component.html',
  styleUrl: './codeblock-overview-page.component.css',
})
export class HeadlessCodeblockOverviewPageComponent implements OnDestroy {
  private readonly documentRef = inject(DOCUMENT);
  public readonly codeBlockTheme = signal<'github-dark' | 'github-light'>(
    resolveDocsCodeBlockTheme(this.documentRef),
  );
  private readonly colorSchemeObserver = observeDocsCodeThemeChanges(
    this.documentRef,
    this.codeBlockTheme,
  );

  protected readonly primitiveImportCode = [
    'import {',
    '  TngCodeBlock,',
    '  TngCodeBlockHeader,',
    '  TngCodeBlockBody,',
    '  TngCodeBlockGutter,',
    '  TngCodeBlockCode,',
    "} from '@tailng-ui/primitives';",
    '',
  ].join('\n');

  protected readonly compositionCode = [
    '<section tngCodeBlock class="docs-codeblock">',
    '  <header tngCodeBlockHeader class="docs-codeblock__header">',
    '    <h3 class="docs-codeblock__title">app.config.ts</h3>',
    '  </header>',
    '',
    '  <div tngCodeBlockBody class="docs-codeblock__body">',
    '    <ol tngCodeBlockGutter class="docs-codeblock__gutter" aria-hidden="true">',
    '      <li>1</li>',
    '      <li>2</li>',
    '      <li>3</li>',
    '    </ol>',
    '',
    '    <pre class="docs-codeblock__pre"><code tngCodeBlockCode class="docs-codeblock__code">',
    '      <span class="docs-codeblock__line">const appConfig = {};</span>',
    '      <span class="docs-codeblock__line">export default appConfig;</span>',
    '    </code></pre>',
    '  </div>',
    '</section>',
    '',
  ].join('\n');

  protected readonly plainCssCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'headless-codeblock-overview-plain-css.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        'import {',
        '  TngCodeBlock,',
        '  TngCodeBlockHeader,',
        '  TngCodeBlockBody,',
        '  TngCodeBlockGutter,',
        '  TngCodeBlockCode,',
        "} from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-headless-codeblock-overview-plain-css',",
        '  standalone: true,',
        '  imports: [',
        '    TngCodeBlock,',
        '    TngCodeBlockHeader,',
        '    TngCodeBlockBody,',
        '    TngCodeBlockGutter,',
        '    TngCodeBlockCode,',
        '  ],',
        "  templateUrl: './headless-codeblock-overview-plain-css.component.html',",
        "  styleUrl: './headless-codeblock-overview-plain-css.component.css',",
        '})',
        'export class HeadlessCodeblockOverviewPlainCssComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'headless-codeblock-overview-plain-css.component.html',
      code: [
        '<section class="codeblock-preview-shell codeblock-preview-shell--plain">',
        '  <section tngCodeBlock class="headless-codeblock">',
        '    <header tngCodeBlockHeader class="headless-codeblock__header">',
        '      <h3 class="headless-codeblock__title">app.config.ts</h3>',
        '      <div class="headless-codeblock__actions">',
        '        <span class="headless-codeblock__language">ts</span>',
        '        <button type="button" class="headless-codeblock__copy">Copy</button>',
        '      </div>',
        '    </header>',
        '    <div tngCodeBlockBody class="headless-codeblock__body">',
        '      <ol tngCodeBlockGutter class="headless-codeblock__gutter" aria-hidden="true">',
        '        <li>1</li>',
        '        <li>2</li>',
        '        <li>3</li>',
        '        <li>4</li>',
        '      </ol>',
        '      <pre class="headless-codeblock__pre"><code tngCodeBlockCode class="headless-codeblock__code">',
        '        <span class="headless-codeblock__line"><span class="headless-codeblock__token headless-codeblock__token--keyword">const</span> <span class="headless-codeblock__token headless-codeblock__token--variable">config</span> = <span class="headless-codeblock__token headless-codeblock__token--plain">{ mode: </span><span class="headless-codeblock__token headless-codeblock__token--string">\'preview\'</span><span class="headless-codeblock__token headless-codeblock__token--plain"> };</span></span>',
        '        <span class="headless-codeblock__line"></span>',
        '        <span class="headless-codeblock__line"><span class="headless-codeblock__token headless-codeblock__token--keyword">export function</span> <span class="headless-codeblock__token headless-codeblock__token--variable">buildLabel</span>(name: string): string {</span>',
        '        <span class="headless-codeblock__line">  <span class="headless-codeblock__token headless-codeblock__token--keyword">return</span> <span class="headless-codeblock__token headless-codeblock__token--string">`${name}:${config.mode}`</span>;</span>',
        '      </code></pre>',
        '    </div>',
        '  </section>',
        '</section>',
        '',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'headless-codeblock-overview-plain-css.component.css',
      code: [
        '.headless-codeblock[data-slot="code-block"] {',
        '  background: var(--tng-semantic-background-base);',
        '  border: 1px solid var(--tng-semantic-border-subtle);',
        '  border-radius: 0.85rem;',
        '  overflow: hidden;',
        '}',
        '',
        '.headless-codeblock [data-slot="code-block-header"] {',
        '  align-items: center;',
        '  background: color-mix(in srgb, var(--tng-semantic-background-surface) 88%, transparent);',
        '  border-bottom: 1px solid var(--tng-semantic-border-subtle);',
        '  display: flex;',
        '  justify-content: space-between;',
        '  padding: 0.45rem 0.7rem;',
        '}',
        '',
        '.headless-codeblock__line {',
        '  display: block;',
        '  line-height: 1.6;',
        '  white-space: pre;',
        '}',
        '',
      ].join('\n'),
    },
  ]);

  protected readonly tailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'headless-codeblock-overview-tailwind.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        'import {',
        '  TngCodeBlock,',
        '  TngCodeBlockHeader,',
        '  TngCodeBlockBody,',
        '  TngCodeBlockGutter,',
        '  TngCodeBlockCode,',
        "} from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-headless-codeblock-overview-tailwind',",
        '  standalone: true,',
        '  imports: [',
        '    TngCodeBlock,',
        '    TngCodeBlockHeader,',
        '    TngCodeBlockBody,',
        '    TngCodeBlockGutter,',
        '    TngCodeBlockCode,',
        '  ],',
        "  templateUrl: './headless-codeblock-overview-tailwind.component.html',",
        "  styleUrl: './headless-codeblock-overview-tailwind.component.css',",
        '})',
        'export class HeadlessCodeblockOverviewTailwindComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'headless-codeblock-overview-tailwind.component.html',
      code: [
        '<section class="rounded-2xl border border-[var(--tng-semantic-border-subtle)] bg-[color-mix(in_srgb,var(--tng-semantic-background-surface)_88%,transparent)] p-4">',
        '  <section',
        '    tngCodeBlock',
        '    class="overflow-hidden rounded-xl border border-[var(--tng-semantic-border-subtle)] bg-[var(--tng-semantic-background-base)] text-[var(--tng-semantic-foreground-primary)] shadow-sm"',
        '  >',
        '    <header tngCodeBlockHeader class="flex items-center justify-between border-b border-[var(--tng-semantic-border-subtle)] bg-[color-mix(in_srgb,var(--tng-semantic-background-surface)_90%,transparent)] px-4 py-2">',
        '      <h3 class="text-sm font-semibold text-[var(--tng-semantic-foreground-primary)]">review.ts</h3>',
        '      <div class="inline-flex items-center gap-2 text-xs text-[var(--tng-semantic-foreground-secondary)]">',
        '        <span class="rounded-full bg-[color-mix(in_srgb,var(--tng-semantic-accent-brand)_16%,transparent)] px-2 py-1 font-semibold uppercase tracking-[0.18em] text-[var(--tng-semantic-accent-brand)]">ts</span>',
        '        <button type="button" class="rounded-md border border-[var(--tng-semantic-border-default)] px-2 py-1 text-[var(--tng-semantic-foreground-secondary)]">Copy</button>',
        '      </div>',
        '    </header>',
        '    <div tngCodeBlockBody class="grid grid-cols-[auto_minmax(0,1fr)]">',
        '      <ol tngCodeBlockGutter class="m-0 list-none border-r border-[var(--tng-semantic-border-subtle)] bg-[color-mix(in_srgb,var(--tng-semantic-background-surface)_78%,transparent)] px-3 py-3 text-right text-xs text-[var(--tng-semantic-foreground-muted)]" aria-hidden="true">',
        '        <li>12</li>',
        '        <li>13</li>',
        '        <li>14</li>',
        '        <li>15</li>',
        '      </ol>',
        '      <pre class="m-0 overflow-x-auto px-4 py-3"><code tngCodeBlockCode class="block font-mono text-[0.84rem] leading-6 text-[var(--tng-semantic-foreground-primary)]"><span class="block whitespace-pre"><span class="text-fuchsia-300">const</span> <span class="text-sky-300">result</span> = <span class="text-amber-200">await</span> loadProfile();</span><span class="block whitespace-pre"></span><span class="block whitespace-pre rounded bg-[color-mix(in_srgb,var(--tng-semantic-accent-brand)_12%,transparent)] px-1"><span class="text-fuchsia-300">if</span> (result.status !== <span class="text-emerald-300">\'ready\'</span>) &#123;</span><span class="block whitespace-pre">  <span class="text-fuchsia-300">return</span> <span class="text-emerald-300">\'retry\'</span>;</span></code></pre>',
        '    </div>',
        '  </section>',
        '</section>',
        '',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'headless-codeblock-overview-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  public ngOnDestroy(): void {
    this.colorSchemeObserver?.disconnect();
  }
}
