import { DOCUMENT } from '@angular/common';
import { Component, inject, signal, type OnDestroy } from '@angular/core';
import {
  TngEmpty,
  TngEmptyActions,
  TngEmptyDescription,
  TngEmptyIcon,
  TngEmptyTitle,
} from '@tailng-ui/primitives';
import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import {
  observeDocsCodeThemeChanges,
  resolveDocsCodeBlockTheme,
} from '../../../../../../shared/util';

@Component({
  selector: 'app-headless-empty-examples-page',
  imports: [
    TngEmpty,
    TngEmptyIcon,
    TngEmptyTitle,
    TngEmptyDescription,
    TngEmptyActions,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
  ],
  templateUrl: './empty-examples-page.component.html',
  styleUrl: './empty-examples-page.component.css',
})
export class HeadlessEmptyExamplesPageComponent implements OnDestroy {
  private readonly documentRef = inject(DOCUMENT);
  public readonly codeBlockTheme = signal<'github-dark' | 'github-light'>(
    resolveDocsCodeBlockTheme(this.documentRef),
  );
  private readonly colorSchemeObserver = observeDocsCodeThemeChanges(
    this.documentRef,
    this.codeBlockTheme,
  );

  protected readonly noResultsPlainTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'headless-empty-no-results-plain.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        'import {',
        '  TngEmpty,',
        '  TngEmptyActions,',
        '  TngEmptyDescription,',
        '  TngEmptyIcon,',
        '  TngEmptyTitle,',
        "} from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-headless-empty-no-results-plain',",
        '  standalone: true,',
        '  imports: [TngEmpty, TngEmptyIcon, TngEmptyTitle, TngEmptyDescription, TngEmptyActions],',
        "  templateUrl: './headless-empty-no-results-plain.component.html',",
        "  styleUrl: './headless-empty-no-results-plain.component.css',",
        '})',
        'export class HeadlessEmptyNoResultsPlainComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'headless-empty-no-results-plain.component.html',
      code: [
        '<section tngEmpty class="empty-example empty-example--plain">',
        '  <div tngEmptyIcon>🔎</div>',
        '  <h3 tngEmptyTitle>No search results</h3>',
        '  <p tngEmptyDescription>Try broader keywords or remove a few filters.</p>',
        '  <div tngEmptyActions class="empty-example-actions">',
        '    <button type="button" class="empty-example-button">Reset search</button>',
        '  </div>',
        '</section>',
        '',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'headless-empty-no-results-plain.component.css',
      code: [
        '.empty-example--plain {',
        '  border: 1px dashed var(--tng-semantic-border-strong);',
        '  border-radius: 1rem;',
        '  justify-items: center;',
        '  padding: 1.1rem;',
        '  text-align: center;',
        '}',
      ].join('\n'),
    },
  ]);

  protected readonly noResultsTailwindTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'headless-empty-no-results-tailwind.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        'import {',
        '  TngEmpty,',
        '  TngEmptyActions,',
        '  TngEmptyDescription,',
        '  TngEmptyIcon,',
        '  TngEmptyTitle,',
        "} from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-headless-empty-no-results-tailwind',",
        '  standalone: true,',
        '  imports: [TngEmpty, TngEmptyIcon, TngEmptyTitle, TngEmptyDescription, TngEmptyActions],',
        "  templateUrl: './headless-empty-no-results-tailwind.component.html',",
        "  styleUrl: './headless-empty-no-results-tailwind.component.css',",
        '})',
        'export class HeadlessEmptyNoResultsTailwindComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'headless-empty-no-results-tailwind.component.html',
      code: [
        '<div class="rounded-xl border border-[var(--tng-semantic-border-subtle)] bg-[color-mix(in_srgb,var(--tng-semantic-background-surface)_88%,transparent)] p-4">',
        '  <section tngEmpty class="grid gap-3 text-center">',
        '    <div tngEmptyIcon class="text-4xl leading-none text-[var(--tng-semantic-foreground-muted)]">🛰️</div>',
        '    <h3 tngEmptyTitle class="m-0 text-lg font-semibold text-[var(--tng-semantic-foreground-primary)]">No telemetry yet</h3>',
        '    <p tngEmptyDescription class="m-0 max-w-md text-sm leading-6 text-[var(--tng-semantic-foreground-secondary)]">',
        '      Connect your first agent to stream runtime metrics.',
        '    </p>',
        '    <div tngEmptyActions class="flex flex-wrap justify-center gap-2">',
        '      <button',
        '        type="button"',
        '        class="rounded-md border border-[var(--tng-semantic-border-default)] px-3 py-1 text-sm font-medium text-[var(--tng-semantic-foreground-primary)]"',
        '      >',
        '        Connect agent',
        '      </button>',
        '    </div>',
        '  </section>',
        '</div>',
        '',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'headless-empty-no-results-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  protected readonly onboardingPlainTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'headless-empty-onboarding-plain.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        'import {',
        '  TngEmpty,',
        '  TngEmptyActions,',
        '  TngEmptyDescription,',
        '  TngEmptyIcon,',
        '  TngEmptyTitle,',
        "} from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-headless-empty-onboarding-plain',",
        '  standalone: true,',
        '  imports: [TngEmpty, TngEmptyIcon, TngEmptyTitle, TngEmptyDescription, TngEmptyActions],',
        "  templateUrl: './headless-empty-onboarding-plain.component.html',",
        "  styleUrl: './headless-empty-onboarding-plain.component.css',",
        '})',
        'export class HeadlessEmptyOnboardingPlainComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'headless-empty-onboarding-plain.component.html',
      code: [
        '<section tngEmpty class="empty-example empty-example--plain" [attr.data-align]="\'start\'">',
        '  <div tngEmptyIcon>✨</div>',
        '  <h3 tngEmptyTitle>Welcome to workspace setup</h3>',
        '  <p tngEmptyDescription>Create your first pipeline to activate deployments.</p>',
        '  <div tngEmptyActions class="empty-example-actions">',
        '    <button type="button" class="empty-example-button">Start onboarding</button>',
        '    <button type="button" class="empty-example-button empty-example-button--subtle">View docs</button>',
        '  </div>',
        '</section>',
        '',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'headless-empty-onboarding-plain.component.css',
      code: [
        '.empty-example-actions {',
        '  display: flex;',
        '  flex-wrap: wrap;',
        '  gap: 0.5rem;',
        '}',
        '',
        '.empty-example-button--subtle {',
        '  background: transparent;',
        '  border: 1px solid var(--tng-semantic-border-strong);',
        '  color: var(--tng-semantic-foreground-secondary);',
        '}',
      ].join('\n'),
    },
  ]);

  protected readonly onboardingTailwindTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'headless-empty-onboarding-tailwind.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        'import {',
        '  TngEmpty,',
        '  TngEmptyActions,',
        '  TngEmptyDescription,',
        '  TngEmptyIcon,',
        '  TngEmptyTitle,',
        "} from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-headless-empty-onboarding-tailwind',",
        '  standalone: true,',
        '  imports: [TngEmpty, TngEmptyIcon, TngEmptyTitle, TngEmptyDescription, TngEmptyActions],',
        "  templateUrl: './headless-empty-onboarding-tailwind.component.html',",
        "  styleUrl: './headless-empty-onboarding-tailwind.component.css',",
        '})',
        'export class HeadlessEmptyOnboardingTailwindComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'headless-empty-onboarding-tailwind.component.html',
      code: [
        '<div class="rounded-xl border border-[var(--tng-semantic-border-subtle)] bg-[color-mix(in_srgb,var(--tng-semantic-background-surface)_88%,transparent)] p-4">',
        '  <section tngEmpty class="grid gap-3 text-left" [attr.data-align]="\'start\'">',
        '    <div tngEmptyIcon class="text-4xl leading-none text-[var(--tng-semantic-foreground-muted)]">📦</div>',
        '    <h3 tngEmptyTitle class="m-0 text-lg font-semibold text-[var(--tng-semantic-foreground-primary)]">',
        '      No release artifacts',
        '    </h3>',
        '    <p tngEmptyDescription class="m-0 max-w-md text-sm leading-6 text-[var(--tng-semantic-foreground-secondary)]">',
        '      Build your project to publish the first release bundle.',
        '    </p>',
        '    <div tngEmptyActions class="flex flex-wrap gap-2">',
        '      <button',
        '        type="button"',
        '        class="rounded-md border border-[var(--tng-semantic-border-default)] px-3 py-1 text-sm font-medium text-[var(--tng-semantic-foreground-primary)]"',
        '      >',
        '        Run build',
        '      </button>',
        '      <button',
        '        type="button"',
        '        class="rounded-md border border-[var(--tng-semantic-border-default)] px-3 py-1 text-sm font-medium text-[var(--tng-semantic-foreground-primary)]"',
        '      >',
        '        Open pipeline',
        '      </button>',
        '    </div>',
        '  </section>',
        '</div>',
        '',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'headless-empty-onboarding-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  public ngOnDestroy(): void {
    this.colorSchemeObserver?.disconnect();
  }
}
