import { DOCUMENT } from '@angular/common';
import { Component, inject, signal, type OnDestroy } from '@angular/core';
import { TngMenuComponent, TngMenubarComponent } from '@tailng-ui/components';
import type {
  TngMenuSelectEvent
} from '@tailng-ui/primitives';
import {
  TngMenu,
  TngMenuGroupLabel,
  TngMenuItem,
  TngMenuSeparator,
  TngMenubar,
  TngMenubarGroup,
  TngMenubarItem
} from '@tailng-ui/primitives';
import { type DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import { observeDocsCodeThemeChanges, resolveDocsCodeBlockTheme } from '../../../../../../shared/util';

@Component({
  selector: 'app-menubar-examples-page',
  imports: [
    TngMenu,
    TngMenuComponent,
    TngMenuGroupLabel,
    TngMenuItem,
    TngMenuSeparator,
    TngMenubar,
    TngMenubarGroup,
    TngMenubarComponent,
    TngMenubarItem,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
  ],
  templateUrl: './menubar-examples-page.component.html',
  styleUrls: ['./menubar-examples-page.component.css'],
})
export class MenubarExamplesPageComponent implements OnDestroy {
  private readonly documentRef = inject(DOCUMENT);
  public readonly codeBlockTheme = signal<'github-dark' | 'github-light'>(
    resolveDocsCodeBlockTheme(this.documentRef),
  );
  private readonly colorSchemeObserver = observeDocsCodeThemeChanges(this.documentRef, this.codeBlockTheme);

  protected readonly plainCommand = signal('No command yet');
  protected readonly tailwindCommand = signal('No command yet');
  protected readonly cascadeCommand = signal('No command yet');

  protected readonly plainCssCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'menubar-examples-workspace-plain.component.ts',
      code: [
        "import { Component, signal } from '@angular/core';",
        "import { TngMenuComponent, TngMenubarComponent } from '@tailng-ui/components';",
        "import { TngMenuGroupLabel, TngMenuItem, TngMenubarGroup, TngMenubarItem, type TngMenuSelectEvent } from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-menubar-examples-workspace-plain',",
        '  standalone: true,',
        '  imports: [',
        '    TngMenuComponent,',
        '    TngMenubarComponent,',
        '    TngMenuGroupLabel,',
        '    TngMenuItem,',
        '    TngMenubarGroup,',
        '    TngMenubarItem,',
        '  ],',
        "  templateUrl: './menubar-examples-workspace-plain.component.html',",
        "  styleUrl: './menubar-examples-workspace-plain.component.css',",
        '})',
        'export class MenubarExamplesWorkspacePlainComponent {',
        "  readonly menubarExamplesWorkspacePlainLastCommand = signal('No command yet');",
        '',
        '  onMenubarExamplesWorkspacePlainMenuSelect(event: TngMenuSelectEvent): void {',
        '    this.menubarExamplesWorkspacePlainLastCommand.set(String(event.value));',
        '  }',
        '}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'menubar-examples-workspace-plain.component.html',
      code: [
        '<div class="menubar-examples-workspace-plain-stage menubar-examples-workspace-plain-stage--short">',
        '  <tng-menubar ariaLabel="Wrapper workspace commands" class="menubar-examples-workspace-plain-menubar">',
        '    <div tngMenubarGroup class="menubar-examples-workspace-plain-group">',
        '      <tng-menu',
        '        #workspacePlainFileMenu="tngMenu"',
        '        ariaLabel="File menu"',
        '        class="menubar-examples-workspace-plain-menu"',
        '        (tngMenuSelect)="onMenubarExamplesWorkspacePlainMenuSelect($event)"',
        '      >',
        '        <div tngMenuGroupLabel class="menubar-examples-workspace-plain-group-label">File</div>',
        '        <button type="button" tngMenuItem tngMenuItemValue="Create release">New release</button>',
        '        <button type="button" tngMenuItem tngMenuItemValue="Publish release">Publish</button>',
        '      </tng-menu>',
        '      <button type="button" tngMenubarItem [tngMenubarMenu]="workspacePlainFileMenu">File</button>',
        '    </div>',
        '    <div tngMenubarGroup class="menubar-examples-workspace-plain-group">',
        '      <tng-menu',
        '        #workspacePlainViewMenu="tngMenu"',
        '        ariaLabel="View menu"',
        '        class="menubar-examples-workspace-plain-menu"',
        '        (tngMenuSelect)="onMenubarExamplesWorkspacePlainMenuSelect($event)"',
        '      >',
        '        <button type="button" tngMenuItem tngMenuItemValue="Toggle sidebar">Toggle sidebar</button>',
        '        <button type="button" tngMenuItem tngMenuItemValue="Open command palette">Command palette</button>',
        '      </tng-menu>',
        '      <button type="button" tngMenubarItem [tngMenubarMenu]="workspacePlainViewMenu">View</button>',
        '    </div>',
        '    <button type="button" tngMenubarItem>Help</button>',
        '  </tng-menubar>',
        '</div>',
        '<p class="menubar-examples-workspace-plain-state">last command: {{ menubarExamplesWorkspacePlainLastCommand() }}</p>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'menubar-examples-workspace-plain.component.css',
      code: [
        '.menubar-examples-workspace-plain-stage {',
        '  align-content: start;',
        '  display: grid;',
        '  justify-items: start;',
        '  position: relative;',
        '}',
        '',
        '.menubar-examples-workspace-plain-menubar {',
        '  align-items: center;',
        '  background: color-mix(in srgb, var(--tng-semantic-background-surface) 88%, transparent);',
        '  border: 1px solid var(--tng-semantic-border-subtle);',
        '  border-radius: 0.95rem;',
        '  display: inline-flex;',
        '  gap: 0.45rem;',
        '  min-height: 2.7rem;',
        '  padding: 0.32rem;',
        '}',
        '',
        '.menubar-examples-workspace-plain-menubar [tngMenubarItem] {',
        '  background: transparent;',
        '  border: 0;',
        '  border-radius: 0.62rem;',
        '  color: var(--tng-semantic-foreground-primary);',
        '  cursor: pointer;',
        '  font-size: 0.95rem;',
        '  font-weight: 600;',
        '  line-height: 1.15;',
        '  min-height: 2.05rem;',
        '  min-width: 3.3rem;',
        '  padding: 0.46rem 0.9rem;',
        '  transition:',
        '    background-color 130ms ease,',
        '    color 130ms ease,',
        '    box-shadow 130ms ease;',
        '}',
        '',
        '.menubar-examples-workspace-plain-menubar [tngMenubarItem]:is(:hover, :focus-visible) {',
        '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 9%, transparent);',
        '  outline: none;',
        '}',
        '',
        '.menubar-examples-workspace-plain-menubar [tngMenubarItem][tabindex=\'0\'] {',
        '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 13%, transparent);',
        '  box-shadow: inset 0 0 0 1px color-mix(in srgb, var(--tng-semantic-accent-brand) 42%, transparent);',
        '  color: color-mix(',
        '    in srgb,',
        '    var(--tng-semantic-accent-brand) 72%,',
        '    var(--tng-semantic-foreground-primary)',
        '  );',
        '}',
        '',
        '.menubar-examples-workspace-plain-menubar [tngMenubarItem][aria-expanded=\'true\'] {',
        '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 16%, transparent);',
        '  color: color-mix(',
        '    in srgb,',
        '    var(--tng-semantic-accent-brand) 72%,',
        '    var(--tng-semantic-foreground-primary)',
        '  );',
        '}',
        '',
        '.menubar-examples-workspace-plain-menu {',
        '  background: var(--tng-semantic-background-canvas);',
        '  border: 1px solid var(--tng-semantic-border-subtle);',
        '  border-radius: 0.76rem;',
        '  gap: 0.2rem;',
        '  left: 0;',
        '  min-width: 13.8rem;',
        '  padding: 0.45rem;',
        '  position: absolute;',
        '  top: calc(100% + 0.45rem);',
        '  z-index: 30;',
        '}',
        '',
        '.menubar-examples-workspace-plain-menu[data-state=\'open\'] {',
        '  display: grid;',
        '}',
        '',
        '.menubar-examples-workspace-plain-menu[hidden] {',
        '  display: none !important;',
        '}',
        '',
        '.menubar-examples-workspace-plain-group-label {',
        '  color: var(--tng-semantic-foreground-secondary);',
        '  font-size: 0.72rem;',
        '  font-weight: 700;',
        '  letter-spacing: 0.08em;',
        '  padding: 0.25rem 0.45rem;',
        '  text-transform: uppercase;',
        '}',
        '',
        '.menubar-examples-workspace-plain-menu [tngMenuItem] {',
        '  background: transparent;',
        '  border: 0;',
        '  border-radius: 0.58rem;',
        '  color: var(--tng-semantic-foreground-primary);',
        '  cursor: pointer;',
        '  display: flex;',
        '  font-size: 0.86rem;',
        '  font-weight: 550;',
        '  justify-content: space-between;',
        '  min-height: 2rem;',
        '  padding: 0.4rem 0.62rem;',
        '  text-align: left;',
        '  transition: background-color 120ms ease;',
        '}',
        '',
        '.menubar-examples-workspace-plain-menu [tngMenuItem]:hover {',
        '  background: color-mix(in srgb, var(--tng-semantic-foreground-primary) 8%, transparent);',
        '}',
        '',
        '.menubar-examples-workspace-plain-menu [tngMenuItem][data-active],',
        '.menubar-examples-workspace-plain-menu [tngMenuItem][aria-expanded=\'true\'] {',
        '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 16%, transparent);',
        '  color: color-mix(',
        '    in srgb,',
        '    var(--tng-semantic-accent-brand) 72%,',
        '    var(--tng-semantic-foreground-primary)',
        '  );',
        '}',
        '',
        '.menubar-examples-workspace-plain-state {',
        '  color: var(--tng-semantic-foreground-secondary);',
        '  font-size: 0.84rem;',
        '  margin: 0;',
        '}',
      ].join('\n'),
    },
  ]);

  protected readonly tailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'menubar-examples-workspace-tailwind.component.ts',
      code: [
        "import { Component, signal } from '@angular/core';",
        "import { TngMenuComponent, TngMenubarComponent } from '@tailng-ui/components';",
        "import { TngMenuGroupLabel, TngMenuItem, TngMenubarGroup, TngMenubarItem, type TngMenuSelectEvent } from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-menubar-examples-workspace-tailwind',",
        '  standalone: true,',
        '  imports: [',
        '    TngMenuComponent,',
        '    TngMenubarComponent,',
        '    TngMenuGroupLabel,',
        '    TngMenuItem,',
        '    TngMenubarGroup,',
        '    TngMenubarItem,',
        '  ],',
        "  templateUrl: './menubar-examples-workspace-tailwind.component.html',",
        "  styleUrl: './menubar-examples-workspace-tailwind.component.css',",
        '})',
        'export class MenubarExamplesWorkspaceTailwindComponent {',
        "  readonly menubarExamplesWorkspaceTwLastCommand = signal('No command yet');",
        '',
        '  onMenubarExamplesWorkspaceTwMenuSelect(event: TngMenuSelectEvent): void {',
        '    this.menubarExamplesWorkspaceTwLastCommand.set(String(event.value));',
        '  }',
        '}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'menubar-examples-workspace-tailwind.component.html',
      code: [
        '<div',
        '  class="menubar-examples-workspace-tw-panel rounded-xl border border-slate-300 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-900/60"',
        '>',
        '  <div class="menubar-examples-workspace-tw-stage menubar-examples-workspace-tw-stage--short">',
        '    <tng-menubar',
        '      ariaLabel="Tailwind workspace commands"',
        '      class="menubar-examples-workspace-tw-menubar inline-flex items-center gap-1 rounded-xl border border-slate-200 bg-white p-1 shadow-sm dark:border-slate-600 dark:bg-slate-950 dark:shadow-black/20"',
        '    >',
        '      <div tngMenubarGroup class="menubar-examples-workspace-tw-group">',
        '        <tng-menu',
        '          #workspaceTwFileMenu="tngMenu"',
        '          ariaLabel="File menu"',
        '          class="menubar-examples-workspace-tw-menu min-w-48 gap-1 rounded-xl border border-slate-200 bg-white p-1 shadow-xl data-[state=open]:grid dark:border-slate-600 dark:bg-slate-950 dark:shadow-black/40"',
        '          (tngMenuSelect)="onMenubarExamplesWorkspaceTwMenuSelect($event)"',
        '        >',
        '          <div tngMenuGroupLabel class="px-3 pt-2 text-[0.68rem] font-semibold uppercase tracking-[0.18em] text-slate-400 dark:text-slate-500">',
        '            File',
        '          </div>',
        '          <button',
        '            type="button"',
        '            tngMenuItem',
        '            tngMenuItemValue="Create file"',
        '            class="flex min-h-9 w-full items-center rounded-lg px-3 text-left text-sm font-medium text-slate-700 outline-none transition hover:bg-sky-50 hover:text-slate-950 focus-visible:bg-sky-50 focus-visible:text-slate-950 focus-visible:ring-2 focus-visible:ring-sky-400/50 [&[data-active]]:bg-sky-50 [&[data-active]]:text-slate-950 dark:text-slate-200 dark:hover:bg-slate-800/80 dark:hover:text-white dark:focus-visible:bg-slate-800 dark:focus-visible:text-white dark:focus-visible:ring-sky-500/40 dark:[&[data-active]]:bg-slate-800 dark:[&[data-active]]:text-white"',
        '          >',
        '            New',
        '          </button>',
        '          <button',
        '            type="button"',
        '            tngMenuItem',
        '            tngMenuItemValue="Open file"',
        '            class="flex min-h-9 w-full items-center rounded-lg px-3 text-left text-sm font-medium text-slate-700 outline-none transition hover:bg-sky-50 hover:text-slate-950 focus-visible:bg-sky-50 focus-visible:text-slate-950 focus-visible:ring-2 focus-visible:ring-sky-400/50 [&[data-active]]:bg-sky-50 [&[data-active]]:text-slate-950 dark:text-slate-200 dark:hover:bg-slate-800/80 dark:hover:text-white dark:focus-visible:bg-slate-800 dark:focus-visible:text-white dark:focus-visible:ring-sky-500/40 dark:[&[data-active]]:bg-slate-800 dark:[&[data-active]]:text-white"',
        '          >',
        '            Open',
        '          </button>',
        '        </tng-menu>',
        '        <button',
        '          type="button"',
        '          tngMenubarItem',
        '          [tngMenubarMenu]="workspaceTwFileMenu"',
        '          class="inline-flex min-h-9 items-center rounded-lg px-3 text-sm font-medium text-slate-700 outline-none transition hover:bg-slate-100 hover:text-slate-950 focus-visible:bg-white focus-visible:text-slate-950 focus-visible:ring-2 focus-visible:ring-sky-400/60 [&[tabindex=\'0\']]:bg-white [&[tabindex=\'0\']]:text-slate-950 [&[tabindex=\'0\']]:shadow-sm [&[aria-expanded=\'true\']]:bg-white [&[aria-expanded=\'true\']]:text-slate-950 [&[aria-expanded=\'true\']]:shadow-sm dark:text-slate-200 dark:hover:bg-slate-800 dark:hover:text-white dark:focus-visible:bg-slate-900 dark:focus-visible:text-white dark:focus-visible:ring-sky-500/50 dark:[&[tabindex=\'0\']]:bg-slate-900 dark:[&[tabindex=\'0\']]:text-white dark:[&[tabindex=\'0\']]:shadow-black/20 dark:[&[aria-expanded=\'true\']]:bg-slate-900 dark:[&[aria-expanded=\'true\']]:text-white"',
        '        >',
        '          File',
        '        </button>',
        '      </div>',
        '      <div tngMenubarGroup class="menubar-examples-workspace-tw-group">',
        '        <tng-menu',
        '          #workspaceTwToolsMenu="tngMenu"',
        '          ariaLabel="Tools menu"',
        '          class="menubar-examples-workspace-tw-menu min-w-48 gap-1 rounded-xl border border-slate-200 bg-white p-1 shadow-xl data-[state=open]:grid dark:border-slate-600 dark:bg-slate-950 dark:shadow-black/40"',
        '          (tngMenuSelect)="onMenubarExamplesWorkspaceTwMenuSelect($event)"',
        '        >',
        '          <button',
        '            type="button"',
        '            tngMenuItem',
        '            tngMenuItemValue="Run lint"',
        '            class="flex min-h-9 w-full items-center rounded-lg px-3 text-left text-sm font-medium text-slate-700 outline-none transition hover:bg-sky-50 hover:text-slate-950 focus-visible:bg-sky-50 focus-visible:text-slate-950 focus-visible:ring-2 focus-visible:ring-sky-400/50 [&[data-active]]:bg-sky-50 [&[data-active]]:text-slate-950 dark:text-slate-200 dark:hover:bg-slate-800/80 dark:hover:text-white dark:focus-visible:bg-slate-800 dark:focus-visible:text-white dark:focus-visible:ring-sky-500/40 dark:[&[data-active]]:bg-slate-800 dark:[&[data-active]]:text-white"',
        '          >',
        '            Run lint',
        '          </button>',
        '          <button',
        '            type="button"',
        '            tngMenuItem',
        '            tngMenuItemValue="Run tests"',
        '            class="flex min-h-9 w-full items-center rounded-lg px-3 text-left text-sm font-medium text-slate-700 outline-none transition hover:bg-sky-50 hover:text-slate-950 focus-visible:bg-sky-50 focus-visible:text-slate-950 focus-visible:ring-2 focus-visible:ring-sky-400/50 [&[data-active]]:bg-sky-50 [&[data-active]]:text-slate-950 dark:text-slate-200 dark:hover:bg-slate-800/80 dark:hover:text-white dark:focus-visible:bg-slate-800 dark:focus-visible:text-white dark:focus-visible:ring-sky-500/40 dark:[&[data-active]]:bg-slate-800 dark:[&[data-active]]:text-white"',
        '          >',
        '            Run tests',
        '          </button>',
        '        </tng-menu>',
        '        <button',
        '          type="button"',
        '          tngMenubarItem',
        '          [tngMenubarMenu]="workspaceTwToolsMenu"',
        '          class="inline-flex min-h-9 items-center rounded-lg px-3 text-sm font-medium text-slate-700 outline-none transition hover:bg-slate-100 hover:text-slate-950 focus-visible:bg-white focus-visible:text-slate-950 focus-visible:ring-2 focus-visible:ring-sky-400/60 [&[tabindex=\'0\']]:bg-white [&[tabindex=\'0\']]:text-slate-950 [&[tabindex=\'0\']]:shadow-sm [&[aria-expanded=\'true\']]:bg-white [&[aria-expanded=\'true\']]:text-slate-950 [&[aria-expanded=\'true\']]:shadow-sm dark:text-slate-200 dark:hover:bg-slate-800 dark:hover:text-white dark:focus-visible:bg-slate-900 dark:focus-visible:text-white dark:focus-visible:ring-sky-500/50 dark:[&[tabindex=\'0\']]:bg-slate-900 dark:[&[tabindex=\'0\']]:text-white dark:[&[tabindex=\'0\']]:shadow-black/20 dark:[&[aria-expanded=\'true\']]:bg-slate-900 dark:[&[aria-expanded=\'true\']]:text-white"',
        '        >',
        '          Tools',
        '        </button>',
        '      </div>',
        '    </tng-menubar>',
        '  </div>',
        '  <p class="menubar-examples-workspace-tw-state">last command: {{ menubarExamplesWorkspaceTwLastCommand() }}</p>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'menubar-examples-workspace-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  protected readonly cascadePlainCssCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'menubar-examples-cascade-plain.component.ts',
      code: [
        "import { Component, signal } from '@angular/core';",
        "import { TngMenuComponent, TngMenubarComponent } from '@tailng-ui/components';",
        "import { TngMenuGroupLabel, TngMenuItem, TngMenubarGroup, TngMenubarItem, type TngMenuSelectEvent } from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-menubar-examples-cascade-plain',",
        '  standalone: true,',
        '  imports: [',
        '    TngMenuComponent,',
        '    TngMenubarComponent,',
        '    TngMenuGroupLabel,',
        '    TngMenuItem,',
        '    TngMenubarGroup,',
        '    TngMenubarItem,',
        '  ],',
        "  templateUrl: './menubar-examples-cascade-plain.component.html',",
        "  styleUrl: './menubar-examples-cascade-plain.component.css',",
        '})',
        'export class MenubarExamplesCascadePlainComponent {',
        "  readonly menubarExamplesCascadePlainLastCommand = signal('No command yet');",
        '',
        '  onMenubarExamplesCascadePlainMenuSelect(event: TngMenuSelectEvent): void {',
        '    this.menubarExamplesCascadePlainLastCommand.set(String(event.value));',
        '  }',
        '}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'menubar-examples-cascade-plain.component.html',
      code: [
        '<div class="menubar-examples-cascade-plain-stage menubar-examples-cascade-plain-stage--cascade">',
        '  <tng-menubar ariaLabel="Cascaded command bar" class="menubar-examples-cascade-plain-menubar">',
        '    <div tngMenubarGroup class="menubar-examples-cascade-plain-group">',
        '      <tng-menu',
        '        #cascadePlainFileMenu="tngMenu"',
        '        ariaLabel="File menu"',
        '        class="menubar-examples-cascade-plain-menu"',
        '        (tngMenuSelect)="onMenubarExamplesCascadePlainMenuSelect($event)"',
        '      >',
        '        <div tngMenuGroupLabel class="menubar-examples-cascade-plain-group-label">File</div>',
        '        <button type="button" tngMenuItem tngMenuItemValue="Create project">Create project</button>',
        '        <button',
        '          type="button"',
        '          tngMenuItem',
        '          [tngMenuItemSubmenu]="cascadePlainImportMenu"',
        '          tngMenuItemValue="Import from source"',
        '        >',
        '          Import from...',
        '        </button>',
        '        <div tngMenuSeparator class="menubar-examples-cascade-plain-separator"></div>',
        '        <button type="button" tngMenuItem tngMenuItemValue="Archive project">Archive project</button>',
        '        <tng-menu',
        '          #cascadePlainImportMenu="tngMenu"',
        '          ariaLabel="Import submenu"',
        '          class="menubar-examples-cascade-plain-menu menubar-examples-cascade-plain-menu--submenu menubar-examples-cascade-plain-menu--level-1"',
        '          (tngMenuSelect)="onMenubarExamplesCascadePlainMenuSelect($event)"',
        '        >',
        '          <button type="button" tngMenuItem tngMenuItemValue="Import from CSV">CSV file</button>',
        '          <button',
        '            type="button"',
        '            tngMenuItem',
        '            [tngMenuItemSubmenu]="cascadePlainGitMenu"',
        '            tngMenuItemValue="Import from git"',
        '          >',
        '            Git repository',
        '          </button>',
        '        </tng-menu>',
        '        <tng-menu',
        '          #cascadePlainGitMenu="tngMenu"',
        '          ariaLabel="Git provider submenu"',
        '          class="menubar-examples-cascade-plain-menu menubar-examples-cascade-plain-menu--submenu menubar-examples-cascade-plain-menu--level-2"',
        '          (tngMenuSelect)="onMenubarExamplesCascadePlainMenuSelect($event)"',
        '        >',
        '          <button type="button" tngMenuItem tngMenuItemValue="Import from GitHub">GitHub</button>',
        '          <button type="button" tngMenuItem tngMenuItemValue="Import from GitLab">GitLab</button>',
        '        </tng-menu>',
        '      </tng-menu>',
        '      <button type="button" tngMenubarItem [tngMenubarMenu]="cascadePlainFileMenu">File</button>',
        '    </div>',
        '    <div tngMenubarGroup class="menubar-examples-cascade-plain-group">',
        '      <tng-menu',
        '        #cascadePlainToolsMenu="tngMenu"',
        '        ariaLabel="Tools menu"',
        '        class="menubar-examples-cascade-plain-menu"',
        '        (tngMenuSelect)="onMenubarExamplesCascadePlainMenuSelect($event)"',
        '      >',
        '        <button type="button" tngMenuItem tngMenuItemValue="Run lint">Run lint</button>',
        '        <button type="button" tngMenuItem tngMenuItemValue="Run tests">Run tests</button>',
        '      </tng-menu>',
        '      <button type="button" tngMenubarItem [tngMenubarMenu]="cascadePlainToolsMenu">Tools</button>',
        '    </div>',
        '  </tng-menubar>',
        '</div>',
        '<p class="menubar-examples-cascade-plain-state">last cascaded command: {{ menubarExamplesCascadePlainLastCommand() }}</p>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'menubar-examples-cascade-plain.component.css',
      code: [
        '.menubar-examples-cascade-plain-stage {',
        '  align-content: start;',
        '  display: grid;',
        '  justify-items: start;',
        '  position: relative;',
        '}',
        '',
        '.menubar-examples-cascade-plain-menubar {',
        '  align-items: center;',
        '  background: color-mix(in srgb, var(--tng-semantic-background-surface) 88%, transparent);',
        '  border: 1px solid var(--tng-semantic-border-subtle);',
        '  border-radius: 0.95rem;',
        '  display: inline-flex;',
        '  gap: 0.45rem;',
        '  min-height: 2.7rem;',
        '  padding: 0.32rem;',
        '}',
        '',
        '.menubar-examples-cascade-plain-menubar [tngMenubarItem] {',
        '  background: transparent;',
        '  border: 0;',
        '  border-radius: 0.62rem;',
        '  color: var(--tng-semantic-foreground-primary);',
        '  cursor: pointer;',
        '  font-size: 0.95rem;',
        '  font-weight: 600;',
        '  line-height: 1.15;',
        '  min-height: 2.05rem;',
        '  min-width: 3.3rem;',
        '  padding: 0.46rem 0.9rem;',
        '  transition:',
        '    background-color 130ms ease,',
        '    color 130ms ease,',
        '    box-shadow 130ms ease;',
        '}',
        '',
        '.menubar-examples-cascade-plain-menubar [tngMenubarItem]:is(:hover, :focus-visible) {',
        '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 9%, transparent);',
        '  outline: none;',
        '}',
        '',
        '.menubar-examples-cascade-plain-menubar [tngMenubarItem][tabindex=\'0\'] {',
        '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 13%, transparent);',
        '  box-shadow: inset 0 0 0 1px color-mix(in srgb, var(--tng-semantic-accent-brand) 42%, transparent);',
        '  color: color-mix(',
        '    in srgb,',
        '    var(--tng-semantic-accent-brand) 72%,',
        '    var(--tng-semantic-foreground-primary)',
        '  );',
        '}',
        '',
        '.menubar-examples-cascade-plain-menubar [tngMenubarItem][aria-expanded=\'true\'] {',
        '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 16%, transparent);',
        '  color: color-mix(',
        '    in srgb,',
        '    var(--tng-semantic-accent-brand) 72%,',
        '    var(--tng-semantic-foreground-primary)',
        '  );',
        '}',
        '',
        '.menubar-examples-cascade-plain-menu {',
        '  background: var(--tng-semantic-background-canvas);',
        '  border: 1px solid var(--tng-semantic-border-subtle);',
        '  border-radius: 0.76rem;',
        '  gap: 0.2rem;',
        '  left: 0;',
        '  min-width: 13.8rem;',
        '  padding: 0.45rem;',
        '  position: absolute;',
        '  top: calc(100% + 0.45rem);',
        '  z-index: 30;',
        '}',
        '',
        '.menubar-examples-cascade-plain-menu[data-state=\'open\'] {',
        '  display: grid;',
        '}',
        '',
        '.menubar-examples-cascade-plain-menu[hidden] {',
        '  display: none !important;',
        '}',
        '',
        '.menubar-examples-cascade-plain-menu--submenu {',
        '  left: calc(100% + 0.42rem);',
        '}',
        '',
        '.menubar-examples-cascade-plain-menu--level-1 {',
        '  top: 2.7rem;',
        '}',
        '',
        '.menubar-examples-cascade-plain-menu--level-2 {',
        '  top: 5.5rem;',
        '}',
        '',
        '.menubar-examples-cascade-plain-group-label {',
        '  color: var(--tng-semantic-foreground-secondary);',
        '  font-size: 0.72rem;',
        '  font-weight: 700;',
        '  letter-spacing: 0.08em;',
        '  padding: 0.25rem 0.45rem;',
        '  text-transform: uppercase;',
        '}',
        '',
        '.menubar-examples-cascade-plain-separator {',
        '  background: color-mix(in srgb, var(--tng-semantic-border-subtle) 84%, transparent);',
        '  height: 1px;',
        '  margin: 0.2rem 0.35rem;',
        '}',
        '',
        '.menubar-examples-cascade-plain-menu [tngMenuItem] {',
        '  background: transparent;',
        '  border: 0;',
        '  border-radius: 0.58rem;',
        '  color: var(--tng-semantic-foreground-primary);',
        '  cursor: pointer;',
        '  display: flex;',
        '  font-size: 0.86rem;',
        '  font-weight: 550;',
        '  justify-content: space-between;',
        '  min-height: 2rem;',
        '  padding: 0.4rem 0.62rem;',
        '  text-align: left;',
        '  transition: background-color 120ms ease;',
        '}',
        '',
        '.menubar-examples-cascade-plain-menu [tngMenuItem]:hover {',
        '  background: color-mix(in srgb, var(--tng-semantic-foreground-primary) 8%, transparent);',
        '}',
        '',
        '.menubar-examples-cascade-plain-menu [tngMenuItem][data-active],',
        '.menubar-examples-cascade-plain-menu [tngMenuItem][aria-expanded=\'true\'] {',
        '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 16%, transparent);',
        '  color: color-mix(',
        '    in srgb,',
        '    var(--tng-semantic-accent-brand) 72%,',
        '    var(--tng-semantic-foreground-primary)',
        '  );',
        '}',
        '',
        '.menubar-examples-cascade-plain-state {',
        '  color: var(--tng-semantic-foreground-secondary);',
        '  font-size: 0.84rem;',
        '  margin: 0;',
        '}',
      ].join('\n'),
    },
  ]);

  protected readonly cascadeTailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'menubar-examples-cascade-tailwind.component.ts',
      code: [
        "import { Component, signal } from '@angular/core';",
        "import { TngMenuComponent, TngMenubarComponent } from '@tailng-ui/components';",
        "import { TngMenuGroupLabel, TngMenuItem, TngMenubarGroup, TngMenubarItem, type TngMenuSelectEvent } from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-menubar-examples-cascade-tailwind',",
        '  standalone: true,',
        '  imports: [',
        '    TngMenuComponent,',
        '    TngMenubarComponent,',
        '    TngMenuGroupLabel,',
        '    TngMenuItem,',
        '    TngMenubarGroup,',
        '    TngMenubarItem,',
        '  ],',
        "  templateUrl: './menubar-examples-cascade-tailwind.component.html',",
        "  styleUrl: './menubar-examples-cascade-tailwind.component.css',",
        '})',
        'export class MenubarExamplesCascadeTailwindComponent {',
        "  readonly menubarExamplesCascadeTwLastCommand = signal('No command yet');",
        '',
        '  onMenubarExamplesCascadeTwMenuSelect(event: TngMenuSelectEvent): void {',
        '    this.menubarExamplesCascadeTwLastCommand.set(String(event.value));',
        '  }',
        '}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'menubar-examples-cascade-tailwind.component.html',
      code: [
        '<div',
        '  class="menubar-examples-cascade-tw-panel rounded-xl border border-slate-300 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-900/60"',
        '>',
        '  <div class="menubar-examples-cascade-tw-stage menubar-examples-cascade-tw-stage--cascade">',
        '    <tng-menubar',
        '      ariaLabel="Cascaded command bar"',
        '      class="menubar-examples-cascade-tw-menubar inline-flex items-center gap-1 rounded-xl border border-slate-200 bg-white p-1 shadow-sm dark:border-slate-600 dark:bg-slate-950 dark:shadow-black/20"',
        '    >',
        '      <div tngMenubarGroup class="menubar-examples-cascade-tw-group">',
        '        <tng-menu',
        '          #cascadeTwFileMenu="tngMenu"',
        '          ariaLabel="File menu"',
        '          class="menubar-examples-cascade-tw-menu min-w-48 gap-1 rounded-xl border border-slate-200 bg-white p-1 shadow-xl data-[state=open]:grid dark:border-slate-600 dark:bg-slate-950 dark:shadow-black/40"',
        '          (tngMenuSelect)="onMenubarExamplesCascadeTwMenuSelect($event)"',
        '        >',
        '          <div tngMenuGroupLabel class="menubar-examples-cascade-tw-group-label px-3 pt-2 text-[0.68rem] font-semibold uppercase tracking-[0.18em] text-slate-400 dark:text-slate-500">File</div>',
        '          <button type="button" tngMenuItem tngMenuItemValue="Create project" class="flex min-h-9 w-full items-center rounded-lg px-3 text-left text-sm font-medium text-slate-700 outline-none transition hover:bg-sky-50 hover:text-slate-950 focus-visible:bg-sky-50 focus-visible:text-slate-950 focus-visible:ring-2 focus-visible:ring-sky-400/50 [&[data-active]]:bg-sky-50 [&[data-active]]:text-slate-950 dark:text-slate-200 dark:hover:bg-slate-800/80 dark:hover:text-white dark:focus-visible:bg-slate-800 dark:focus-visible:text-white dark:focus-visible:ring-sky-500/40 dark:[&[data-active]]:bg-slate-800 dark:[&[data-active]]:text-white">Create project</button>',
        '          <button',
        '            type="button"',
        '            tngMenuItem',
        '            [tngMenuItemSubmenu]="cascadeTwImportMenu"',
        '            tngMenuItemValue="Import from source"',
        '            class="flex min-h-9 w-full items-center rounded-lg px-3 text-left text-sm font-medium text-slate-700 outline-none transition hover:bg-sky-50 hover:text-slate-950 focus-visible:bg-sky-50 focus-visible:text-slate-950 focus-visible:ring-2 focus-visible:ring-sky-400/50 [&[data-active]]:bg-sky-50 [&[data-active]]:text-slate-950 dark:text-slate-200 dark:hover:bg-slate-800/80 dark:hover:text-white dark:focus-visible:bg-slate-800 dark:focus-visible:text-white dark:focus-visible:ring-sky-500/40 dark:[&[data-active]]:bg-slate-800 dark:[&[data-active]]:text-white"',
        '          >',
        '            Import from...',
        '          </button>',
        '          <div tngMenuSeparator class="menubar-examples-cascade-tw-separator mx-1 my-1 h-px bg-slate-200 dark:bg-slate-600"></div>',
        '          <button type="button" tngMenuItem tngMenuItemValue="Archive project" class="flex min-h-9 w-full items-center rounded-lg px-3 text-left text-sm font-medium text-slate-700 outline-none transition hover:bg-sky-50 hover:text-slate-950 focus-visible:bg-sky-50 focus-visible:text-slate-950 focus-visible:ring-2 focus-visible:ring-sky-400/50 [&[data-active]]:bg-sky-50 [&[data-active]]:text-slate-950 dark:text-slate-200 dark:hover:bg-slate-800/80 dark:hover:text-white dark:focus-visible:bg-slate-800 dark:focus-visible:text-white dark:focus-visible:ring-sky-500/40 dark:[&[data-active]]:bg-slate-800 dark:[&[data-active]]:text-white">Archive project</button>',
        '          <tng-menu',
        '            #cascadeTwImportMenu="tngMenu"',
        '            ariaLabel="Import submenu"',
        '            class="menubar-examples-cascade-tw-menu menubar-examples-cascade-tw-menu--submenu menubar-examples-cascade-tw-menu--level-1 min-w-48 gap-1 rounded-xl border border-slate-200 bg-white p-1 shadow-xl data-[state=open]:grid dark:border-slate-600 dark:bg-slate-950 dark:shadow-black/40"',
        '            (tngMenuSelect)="onMenubarExamplesCascadeTwMenuSelect($event)"',
        '          >',
        '            <button type="button" tngMenuItem tngMenuItemValue="Import from CSV" class="flex min-h-9 w-full items-center rounded-lg px-3 text-left text-sm font-medium text-slate-700 outline-none transition hover:bg-sky-50 hover:text-slate-950 focus-visible:bg-sky-50 focus-visible:text-slate-950 focus-visible:ring-2 focus-visible:ring-sky-400/50 [&[data-active]]:bg-sky-50 [&[data-active]]:text-slate-950 dark:text-slate-200 dark:hover:bg-slate-800/80 dark:hover:text-white dark:focus-visible:bg-slate-800 dark:focus-visible:text-white dark:focus-visible:ring-sky-500/40 dark:[&[data-active]]:bg-slate-800 dark:[&[data-active]]:text-white">CSV file</button>',
        '            <button',
        '              type="button"',
        '              tngMenuItem',
        '              [tngMenuItemSubmenu]="cascadeTwGitMenu"',
        '              tngMenuItemValue="Import from git"',
        '              class="flex min-h-9 w-full items-center rounded-lg px-3 text-left text-sm font-medium text-slate-700 outline-none transition hover:bg-sky-50 hover:text-slate-950 focus-visible:bg-sky-50 focus-visible:text-slate-950 focus-visible:ring-2 focus-visible:ring-sky-400/50 [&[data-active]]:bg-sky-50 [&[data-active]]:text-slate-950 dark:text-slate-200 dark:hover:bg-slate-800/80 dark:hover:text-white dark:focus-visible:bg-slate-800 dark:focus-visible:text-white dark:focus-visible:ring-sky-500/40 dark:[&[data-active]]:bg-slate-800 dark:[&[data-active]]:text-white"',
        '            >',
        '              Git repository',
        '            </button>',
        '          </tng-menu>',
        '          <tng-menu',
        '            #cascadeTwGitMenu="tngMenu"',
        '            ariaLabel="Git provider submenu"',
        '            class="menubar-examples-cascade-tw-menu menubar-examples-cascade-tw-menu--submenu menubar-examples-cascade-tw-menu--level-2 min-w-48 gap-1 rounded-xl border border-slate-200 bg-white p-1 shadow-xl data-[state=open]:grid dark:border-slate-600 dark:bg-slate-950 dark:shadow-black/40"',
        '            (tngMenuSelect)="onMenubarExamplesCascadeTwMenuSelect($event)"',
        '          >',
        '            <button type="button" tngMenuItem tngMenuItemValue="Import from GitHub" class="flex min-h-9 w-full items-center rounded-lg px-3 text-left text-sm font-medium text-slate-700 outline-none transition hover:bg-sky-50 hover:text-slate-950 focus-visible:bg-sky-50 focus-visible:text-slate-950 focus-visible:ring-2 focus-visible:ring-sky-400/50 [&[data-active]]:bg-sky-50 [&[data-active]]:text-slate-950 dark:text-slate-200 dark:hover:bg-slate-800/80 dark:hover:text-white dark:focus-visible:bg-slate-800 dark:focus-visible:text-white dark:focus-visible:ring-sky-500/40 dark:[&[data-active]]:bg-slate-800 dark:[&[data-active]]:text-white">GitHub</button>',
        '            <button type="button" tngMenuItem tngMenuItemValue="Import from GitLab" class="flex min-h-9 w-full items-center rounded-lg px-3 text-left text-sm font-medium text-slate-700 outline-none transition hover:bg-sky-50 hover:text-slate-950 focus-visible:bg-sky-50 focus-visible:text-slate-950 focus-visible:ring-2 focus-visible:ring-sky-400/50 [&[data-active]]:bg-sky-50 [&[data-active]]:text-slate-950 dark:text-slate-200 dark:hover:bg-slate-800/80 dark:hover:text-white dark:focus-visible:bg-slate-800 dark:focus-visible:text-white dark:focus-visible:ring-sky-500/40 dark:[&[data-active]]:bg-slate-800 dark:[&[data-active]]:text-white">GitLab</button>',
        '          </tng-menu>',
        '        </tng-menu>',
        '        <button type="button" tngMenubarItem [tngMenubarMenu]="cascadeTwFileMenu" class="inline-flex min-h-9 items-center rounded-lg px-3 text-sm font-medium text-slate-700 outline-none transition hover:bg-slate-100 hover:text-slate-950 focus-visible:bg-white focus-visible:text-slate-950 focus-visible:ring-2 focus-visible:ring-sky-400/60 [&[tabindex=\'0\']]:bg-white [&[tabindex=\'0\']]:text-slate-950 [&[tabindex=\'0\']]:shadow-sm [&[aria-expanded=\'true\']]:bg-white [&[aria-expanded=\'true\']]:text-slate-950 [&[aria-expanded=\'true\']]:shadow-sm dark:text-slate-200 dark:hover:bg-slate-800 dark:hover:text-white dark:focus-visible:bg-slate-900 dark:focus-visible:text-white dark:focus-visible:ring-sky-500/50 dark:[&[tabindex=\'0\']]:bg-slate-900 dark:[&[tabindex=\'0\']]:text-white dark:[&[tabindex=\'0\']]:shadow-black/20 dark:[&[aria-expanded=\'true\']]:bg-slate-900 dark:[&[aria-expanded=\'true\']]:text-white">File</button>',
        '      </div>',
        '      <div tngMenubarGroup class="menubar-examples-cascade-tw-group">',
        '        <tng-menu',
        '          #cascadeTwToolsMenu="tngMenu"',
        '          ariaLabel="Tools menu"',
        '          class="menubar-examples-cascade-tw-menu min-w-48 gap-1 rounded-xl border border-slate-200 bg-white p-1 shadow-xl data-[state=open]:grid dark:border-slate-600 dark:bg-slate-950 dark:shadow-black/40"',
        '          (tngMenuSelect)="onMenubarExamplesCascadeTwMenuSelect($event)"',
        '        >',
        '          <button type="button" tngMenuItem tngMenuItemValue="Run lint" class="flex min-h-9 w-full items-center rounded-lg px-3 text-left text-sm font-medium text-slate-700 outline-none transition hover:bg-sky-50 hover:text-slate-950 focus-visible:bg-sky-50 focus-visible:text-slate-950 focus-visible:ring-2 focus-visible:ring-sky-400/50 [&[data-active]]:bg-sky-50 [&[data-active]]:text-slate-950 dark:text-slate-200 dark:hover:bg-slate-800/80 dark:hover:text-white dark:focus-visible:bg-slate-800 dark:focus-visible:text-white dark:focus-visible:ring-sky-500/40 dark:[&[data-active]]:bg-slate-800 dark:[&[data-active]]:text-white">Run lint</button>',
        '          <button type="button" tngMenuItem tngMenuItemValue="Run tests" class="flex min-h-9 w-full items-center rounded-lg px-3 text-left text-sm font-medium text-slate-700 outline-none transition hover:bg-sky-50 hover:text-slate-950 focus-visible:bg-sky-50 focus-visible:text-slate-950 focus-visible:ring-2 focus-visible:ring-sky-400/50 [&[data-active]]:bg-sky-50 [&[data-active]]:text-slate-950 dark:text-slate-200 dark:hover:bg-slate-800/80 dark:hover:text-white dark:focus-visible:bg-slate-800 dark:focus-visible:text-white dark:focus-visible:ring-sky-500/40 dark:[&[data-active]]:bg-slate-800 dark:[&[data-active]]:text-white">Run tests</button>',
        '        </tng-menu>',
        '        <button type="button" tngMenubarItem [tngMenubarMenu]="cascadeTwToolsMenu" class="inline-flex min-h-9 items-center rounded-lg px-3 text-sm font-medium text-slate-700 outline-none transition hover:bg-slate-100 hover:text-slate-950 focus-visible:bg-white focus-visible:text-slate-950 focus-visible:ring-2 focus-visible:ring-sky-400/60 [&[tabindex=\'0\']]:bg-white [&[tabindex=\'0\']]:text-slate-950 [&[tabindex=\'0\']]:shadow-sm [&[aria-expanded=\'true\']]:bg-white [&[aria-expanded=\'true\']]:text-slate-950 [&[aria-expanded=\'true\']]:shadow-sm dark:text-slate-200 dark:hover:bg-slate-800 dark:hover:text-white dark:focus-visible:bg-slate-900 dark:focus-visible:text-white dark:focus-visible:ring-sky-500/50 dark:[&[tabindex=\'0\']]:bg-slate-900 dark:[&[tabindex=\'0\']]:text-white dark:[&[tabindex=\'0\']]:shadow-black/20 dark:[&[aria-expanded=\'true\']]:bg-slate-900 dark:[&[aria-expanded=\'true\']]:text-white">Tools</button>',
        '      </div>',
        '    </tng-menubar>',
        '  </div>',
        '  <p class="menubar-examples-cascade-tw-state">last cascaded command: {{ menubarExamplesCascadeTwLastCommand() }}</p>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'menubar-examples-cascade-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  public ngOnDestroy(): void {
    this.colorSchemeObserver?.disconnect();
  }

  protected onPlainCommandSelect(event: TngMenuSelectEvent): void {
    this.plainCommand.set(String(event.value));
  }

  protected onTailwindCommandSelect(event: TngMenuSelectEvent): void {
    this.tailwindCommand.set(String(event.value));
  }

  protected onCascadeCommandSelect(event: TngMenuSelectEvent): void {
    this.cascadeCommand.set(String(event.value));
  }

}
