import { DOCUMENT } from '@angular/common';
import { Component, inject, signal, type OnDestroy } from '@angular/core';
import { TngMenuComponent, TngMenubarComponent } from '@tailng-ui/components';
import type {
  TngMenuSelectEvent
} from '@tailng-ui/primitives';
import {
  TngMenu,
  TngMenuGroupLabel,
  TngMenuItem,
  TngMenuSeparator,
  TngMenubar,
  TngMenubarGroup,
  TngMenubarItem
} from '@tailng-ui/primitives';
import { type DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import { observeDocsCodeThemeChanges, resolveDocsCodeBlockTheme } from '../../../../../../shared/util';

@Component({
  selector: 'app-menubar-examples-page',
  imports: [
    TngMenu,
    TngMenuComponent,
    TngMenuGroupLabel,
    TngMenuItem,
    TngMenuSeparator,
    TngMenubar,
    TngMenubarGroup,
    TngMenubarComponent,
    TngMenubarItem,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
  ],
  templateUrl: './menubar-examples-page.component.html',
})
export class MenubarExamplesPageComponent implements OnDestroy {
  private readonly documentRef = inject(DOCUMENT);
  public readonly codeBlockTheme = signal<'github-dark' | 'github-light'>(
    resolveDocsCodeBlockTheme(this.documentRef),
  );
  private readonly colorSchemeObserver = observeDocsCodeThemeChanges(this.documentRef, this.codeBlockTheme);

  protected readonly plainCommand = signal('No command yet');
  protected readonly tailwindCommand = signal('No command yet');
  protected readonly cascadeCommand = signal('No command yet');

  protected readonly plainCssCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'menubar-examples-workspace-plain.component.ts',
      code: [
        "import { Component, signal } from '@angular/core';",
        "import { TngMenuComponent, TngMenubarComponent } from '@tailng-ui/components';",
        "import { TngMenuGroupLabel, TngMenuItem, TngMenubarGroup, TngMenubarItem, type TngMenuSelectEvent } from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-menubar-examples-workspace-plain',",
        '  standalone: true,',
        '  imports: [',
        '    TngMenuComponent,',
        '    TngMenubarComponent,',
        '    TngMenuGroupLabel,',
        '    TngMenuItem,',
        '    TngMenubarGroup,',
        '    TngMenubarItem,',
        '  ],',
        "  templateUrl: './menubar-examples-workspace-plain.component.html',",
        "  styleUrl: './menubar-examples-workspace-plain.component.css',",
        '})',
        'export class MenubarExamplesWorkspacePlainComponent {',
        "  readonly menubarExamplesWorkspacePlainLastCommand = signal('No command yet');",
        '',
        '  onMenubarExamplesWorkspacePlainMenuSelect(event: TngMenuSelectEvent): void {',
        '    this.menubarExamplesWorkspacePlainLastCommand.set(String(event.value));',
        '  }',
        '}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'menubar-examples-workspace-plain.component.html',
      code: [
        '  <tng-menubar ariaLabel="Wrapper workspace commands">',
        '    <div tngMenubarGroup>',
        '      <tng-menu',
        '        #workspacePlainFileMenu="tngMenu"',
        '        ariaLabel="File menu"',
        '        (tngMenuSelect)="onMenubarExamplesWorkspacePlainMenuSelect($event)"',
        '      >',
        '        <div tngMenuGroupLabel>File</div>',
        '        <button type="button" tngMenuItem tngMenuItemValue="Create release">New release</button>',
        '        <button type="button" tngMenuItem tngMenuItemValue="Publish release">Publish</button>',
        '      </tng-menu>',
        '      <button type="button" tngMenubarItem [tngMenubarMenu]="workspacePlainFileMenu">File</button>',
        '    </div>',
        '    <div tngMenubarGroup>',
        '      <tng-menu',
        '        #workspacePlainViewMenu="tngMenu"',
        '        ariaLabel="View menu"',
        '        (tngMenuSelect)="onMenubarExamplesWorkspacePlainMenuSelect($event)"',
        '      >',
        '        <button type="button" tngMenuItem tngMenuItemValue="Toggle sidebar">Toggle sidebar</button>',
        '        <button type="button" tngMenuItem tngMenuItemValue="Open command palette">Command palette</button>',
        '      </tng-menu>',
        '      <button type="button" tngMenubarItem [tngMenubarMenu]="workspacePlainViewMenu">View</button>',
        '    </div>',
        '    <button type="button" tngMenubarItem>Help</button>',
        '  </tng-menubar>',
        '<p>last command: {{ menubarExamplesWorkspacePlainLastCommand() }}</p>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'menubar-examples-workspace-plain.component.css',
      code: [
        '/*',
        ' * Menubar and menu internals are styled by TailNG component contracts.',
        ' * Keep local CSS for layout wrappers only.',
        ' */',
      ].join('\n'),
    },
  ]);

  protected readonly tailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'menubar-examples-workspace-tailwind.component.ts',
      code: [
        "import { Component, signal } from '@angular/core';",
        "import { TngMenuComponent, TngMenubarComponent } from '@tailng-ui/components';",
        "import { TngMenuGroupLabel, TngMenuItem, TngMenubarGroup, TngMenubarItem, type TngMenuSelectEvent } from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-menubar-examples-workspace-tailwind',",
        '  standalone: true,',
        '  imports: [',
        '    TngMenuComponent,',
        '    TngMenubarComponent,',
        '    TngMenuGroupLabel,',
        '    TngMenuItem,',
        '    TngMenubarGroup,',
        '    TngMenubarItem,',
        '  ],',
        "  templateUrl: './menubar-examples-workspace-tailwind.component.html',",
        "  styleUrl: './menubar-examples-workspace-tailwind.component.css',",
        '})',
        'export class MenubarExamplesWorkspaceTailwindComponent {',
        "  readonly menubarExamplesWorkspaceTwLastCommand = signal('No command yet');",
        '',
        '  onMenubarExamplesWorkspaceTwMenuSelect(event: TngMenuSelectEvent): void {',
        '    this.menubarExamplesWorkspaceTwLastCommand.set(String(event.value));',
        '  }',
        '}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'menubar-examples-workspace-tailwind.component.html',
      code: [
        '    <tng-menubar ariaLabel="Tailwind workspace commands">',
        '      <div tngMenubarGroup>',
        '        <tng-menu',
        '          #workspaceTwFileMenu="tngMenu"',
        '          ariaLabel="File menu"',
        '          (tngMenuSelect)="onMenubarExamplesWorkspaceTwMenuSelect($event)"',
        '        >',
        '          <div tngMenuGroupLabel>File</div>',
        '          <button type="button" tngMenuItem tngMenuItemValue="Create file">New</button>',
        '          <button type="button" tngMenuItem tngMenuItemValue="Open file">Open</button>',
        '        </tng-menu>',
        '        <button type="button" tngMenubarItem [tngMenubarMenu]="workspaceTwFileMenu">File</button>',
        '      </div>',
        '      <div tngMenubarGroup>',
        '        <tng-menu',
        '          #workspaceTwToolsMenu="tngMenu"',
        '          ariaLabel="Tools menu"',
        '          (tngMenuSelect)="onMenubarExamplesWorkspaceTwMenuSelect($event)"',
        '        >',
        '          <button type="button" tngMenuItem tngMenuItemValue="Run lint">Run lint</button>',
        '          <button type="button" tngMenuItem tngMenuItemValue="Run tests">Run tests</button>',
        '        </tng-menu>',
        '        <button type="button" tngMenubarItem [tngMenubarMenu]="workspaceTwToolsMenu">Tools</button>',
        '      </div>',
        '    </tng-menubar>',
        '  <p>last command: {{ menubarExamplesWorkspaceTwLastCommand() }}</p>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'menubar-examples-workspace-tailwind.component.css',
      code: '/* Menubar and menu primitives use component styles; optional panel chrome can use utilities on wrappers. */',
    },
  ]);

  protected readonly cascadePlainCssCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'menubar-examples-cascade-plain.component.ts',
      code: [
        "import { Component, signal } from '@angular/core';",
        "import { TngMenuComponent, TngMenubarComponent } from '@tailng-ui/components';",
        "import { TngMenuGroupLabel, TngMenuItem, TngMenubarGroup, TngMenubarItem, type TngMenuSelectEvent } from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-menubar-examples-cascade-plain',",
        '  standalone: true,',
        '  imports: [',
        '    TngMenuComponent,',
        '    TngMenubarComponent,',
        '    TngMenuGroupLabel,',
        '    TngMenuItem,',
        '    TngMenubarGroup,',
        '    TngMenubarItem,',
        '  ],',
        "  templateUrl: './menubar-examples-cascade-plain.component.html',",
        "  styleUrl: './menubar-examples-cascade-plain.component.css',",
        '})',
        'export class MenubarExamplesCascadePlainComponent {',
        "  readonly menubarExamplesCascadePlainLastCommand = signal('No command yet');",
        '',
        '  onMenubarExamplesCascadePlainMenuSelect(event: TngMenuSelectEvent): void {',
        '    this.menubarExamplesCascadePlainLastCommand.set(String(event.value));',
        '  }',
        '}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'menubar-examples-cascade-plain.component.html',
      code: [
        '  <tng-menubar ariaLabel="Cascaded command bar">',
        '    <div tngMenubarGroup>',
        '      <tng-menu',
        '        #cascadePlainFileMenu="tngMenu"',
        '        ariaLabel="File menu"',
        '        (tngMenuSelect)="onMenubarExamplesCascadePlainMenuSelect($event)"',
        '      >',
        '        <div tngMenuGroupLabel>File</div>',
        '        <button type="button" tngMenuItem tngMenuItemValue="Create project">Create project</button>',
        '        <button',
        '          type="button"',
        '          tngMenuItem',
        '          [tngMenuItemSubmenu]="cascadePlainImportMenu"',
        '          tngMenuItemValue="Import from source"',
        '        >',
        '          Import from...',
        '        </button>',
        '        <div tngMenuSeparator></div>',
        '        <button type="button" tngMenuItem tngMenuItemValue="Archive project">Archive project</button>',
        '        <tng-menu',
        '          #cascadePlainImportMenu="tngMenu"',
        '          ariaLabel="Import submenu"',
        '          (tngMenuSelect)="onMenubarExamplesCascadePlainMenuSelect($event)"',
        '        >',
        '          <button type="button" tngMenuItem tngMenuItemValue="Import from CSV">CSV file</button>',
        '          <button',
        '            type="button"',
        '            tngMenuItem',
        '            [tngMenuItemSubmenu]="cascadePlainGitMenu"',
        '            tngMenuItemValue="Import from git"',
        '          >',
        '            Git repository',
        '          </button>',
        '        </tng-menu>',
        '        <tng-menu',
        '          #cascadePlainGitMenu="tngMenu"',
        '          ariaLabel="Git provider submenu"',
        '          (tngMenuSelect)="onMenubarExamplesCascadePlainMenuSelect($event)"',
        '        >',
        '          <button type="button" tngMenuItem tngMenuItemValue="Import from GitHub">GitHub</button>',
        '          <button type="button" tngMenuItem tngMenuItemValue="Import from GitLab">GitLab</button>',
        '        </tng-menu>',
        '      </tng-menu>',
        '      <button type="button" tngMenubarItem [tngMenubarMenu]="cascadePlainFileMenu">File</button>',
        '    </div>',
        '    <div tngMenubarGroup>',
        '      <tng-menu',
        '        #cascadePlainToolsMenu="tngMenu"',
        '        ariaLabel="Tools menu"',
        '        (tngMenuSelect)="onMenubarExamplesCascadePlainMenuSelect($event)"',
        '      >',
        '        <button type="button" tngMenuItem tngMenuItemValue="Run lint">Run lint</button>',
        '        <button type="button" tngMenuItem tngMenuItemValue="Run tests">Run tests</button>',
        '      </tng-menu>',
        '      <button type="button" tngMenubarItem [tngMenubarMenu]="cascadePlainToolsMenu">Tools</button>',
        '    </div>',
        '  </tng-menubar>',
        '<p>last cascaded command: {{ menubarExamplesCascadePlainLastCommand() }}</p>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'menubar-examples-cascade-plain.component.css',
      code: [
        '/*',
        ' * Menubar and menu internals are styled by TailNG component contracts.',
        ' * Keep local CSS for layout wrappers only.',
        ' */',
      ].join('\n'),
    },
  ]);

  protected readonly cascadeTailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'menubar-examples-cascade-tailwind.component.ts',
      code: [
        "import { Component, signal } from '@angular/core';",
        "import { TngMenuComponent, TngMenubarComponent } from '@tailng-ui/components';",
        "import { TngMenuGroupLabel, TngMenuItem, TngMenubarGroup, TngMenubarItem, type TngMenuSelectEvent } from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-menubar-examples-cascade-tailwind',",
        '  standalone: true,',
        '  imports: [',
        '    TngMenuComponent,',
        '    TngMenubarComponent,',
        '    TngMenuGroupLabel,',
        '    TngMenuItem,',
        '    TngMenubarGroup,',
        '    TngMenubarItem,',
        '  ],',
        "  templateUrl: './menubar-examples-cascade-tailwind.component.html',",
        "  styleUrl: './menubar-examples-cascade-tailwind.component.css',",
        '})',
        'export class MenubarExamplesCascadeTailwindComponent {',
        "  readonly menubarExamplesCascadeTwLastCommand = signal('No command yet');",
        '',
        '  onMenubarExamplesCascadeTwMenuSelect(event: TngMenuSelectEvent): void {',
        '    this.menubarExamplesCascadeTwLastCommand.set(String(event.value));',
        '  }',
        '}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'menubar-examples-cascade-tailwind.component.html',
      code: [
        '    <tng-menubar ariaLabel="Cascaded command bar">',
        '      <div tngMenubarGroup>',
        '        <tng-menu',
        '          #cascadeTwFileMenu="tngMenu"',
        '          ariaLabel="File menu"',
        '          (tngMenuSelect)="onMenubarExamplesCascadeTwMenuSelect($event)"',
        '        >',
        '          <div tngMenuGroupLabel>File</div>',
        '          <button type="button" tngMenuItem tngMenuItemValue="Create project">Create project</button>',
        '          <button',
        '            type="button"',
        '            tngMenuItem',
        '            [tngMenuItemSubmenu]="cascadeTwImportMenu"',
        '            tngMenuItemValue="Import from source"',
        '          >',
        '            Import from...',
        '          </button>',
        '          <div tngMenuSeparator></div>',
        '          <button type="button" tngMenuItem tngMenuItemValue="Archive project">Archive project</button>',
        '          <tng-menu',
        '            #cascadeTwImportMenu="tngMenu"',
        '            ariaLabel="Import submenu"',
        '            (tngMenuSelect)="onMenubarExamplesCascadeTwMenuSelect($event)"',
        '          >',
        '            <button type="button" tngMenuItem tngMenuItemValue="Import from CSV">CSV file</button>',
        '            <button',
        '              type="button"',
        '              tngMenuItem',
        '              [tngMenuItemSubmenu]="cascadeTwGitMenu"',
        '              tngMenuItemValue="Import from git"',
        '            >',
        '              Git repository',
        '            </button>',
        '          </tng-menu>',
        '          <tng-menu',
        '            #cascadeTwGitMenu="tngMenu"',
        '            ariaLabel="Git provider submenu"',
        '            (tngMenuSelect)="onMenubarExamplesCascadeTwMenuSelect($event)"',
        '          >',
        '            <button type="button" tngMenuItem tngMenuItemValue="Import from GitHub">GitHub</button>',
        '            <button type="button" tngMenuItem tngMenuItemValue="Import from GitLab">GitLab</button>',
        '          </tng-menu>',
        '        </tng-menu>',
        '        <button type="button" tngMenubarItem [tngMenubarMenu]="cascadeTwFileMenu">File</button>',
        '      </div>',
        '      <div tngMenubarGroup>',
        '        <tng-menu',
        '          #cascadeTwToolsMenu="tngMenu"',
        '          ariaLabel="Tools menu"',
        '          (tngMenuSelect)="onMenubarExamplesCascadeTwMenuSelect($event)"',
        '        >',
        '          <button type="button" tngMenuItem tngMenuItemValue="Run lint">Run lint</button>',
        '          <button type="button" tngMenuItem tngMenuItemValue="Run tests">Run tests</button>',
        '        </tng-menu>',
        '        <button type="button" tngMenubarItem [tngMenubarMenu]="cascadeTwToolsMenu">Tools</button>',
        '      </div>',
        '    </tng-menubar>',
        '  <p>last cascaded command: {{ menubarExamplesCascadeTwLastCommand() }}</p>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'menubar-examples-cascade-tailwind.component.css',
      code: '/* Menubar and menu primitives use component styles; optional panel chrome can use utilities on wrappers. */',
    },
  ]);

  public ngOnDestroy(): void {
    this.colorSchemeObserver?.disconnect();
  }

  protected onPlainCommandSelect(event: TngMenuSelectEvent): void {
    this.plainCommand.set(String(event.value));
  }

  protected onTailwindCommandSelect(event: TngMenuSelectEvent): void {
    this.tailwindCommand.set(String(event.value));
  }

  protected onCascadeCommandSelect(event: TngMenuSelectEvent): void {
    this.cascadeCommand.set(String(event.value));
  }

}
