import { DOCUMENT } from '@angular/common';
import { Component, inject, signal, type OnDestroy } from '@angular/core';
import {
  TngAccordionComponent,
  TngAccordionItemComponent,
  TngAccordionPanelComponent,
  TngAccordionTriggerComponent,
} from '@tailng-ui/components';
import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import {
  observeDocsCodeThemeChanges,
  resolveDocsCodeBlockTheme,
} from '../../../../../../shared/util';

@Component({
  selector: 'app-accordion-examples-page',
  imports: [
    TngAccordionComponent,
    TngAccordionItemComponent,
    TngAccordionTriggerComponent,
    TngAccordionPanelComponent,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
  ],
  templateUrl: './accordion-examples-page.component.html',
  styleUrl: './accordion-examples-page.component.css',
})
export class AccordionExamplesPageComponent implements OnDestroy {
  private readonly documentRef = inject(DOCUMENT);

  public readonly codeBlockTheme = signal<'github-dark' | 'github-light'>(
    resolveDocsCodeBlockTheme(this.documentRef),
  );
  private readonly colorSchemeObserver = observeDocsCodeThemeChanges(this.documentRef, this.codeBlockTheme);

  protected readonly faqPlainCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'accordion-examples-faq-plain-css.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import {",
        "  TngAccordionComponent,",
        "  TngAccordionItemComponent,",
        "  TngAccordionPanelComponent,",
        "  TngAccordionTriggerComponent,",
        "} from '@tailng-ui/components';",
        '',
        '@Component({',
        "  selector: 'app-accordion-examples-faq-plain-css',",
        '  standalone: true,',
        '  imports: [',
        '    TngAccordionComponent,',
        '    TngAccordionItemComponent,',
        '    TngAccordionTriggerComponent,',
        '    TngAccordionPanelComponent,',
        '  ],',
        "  templateUrl: './accordion-examples-faq-plain-css.component.html',",
        "  styleUrl: './accordion-examples-faq-plain-css.component.css',",
        '})',
        'export class AccordionExamplesFaqPlainCssComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'accordion-examples-faq-plain-css.component.html',
      code: [
        '<div class="accordion-example-shell accordion-example-shell--plain">',
        '  <tng-accordion ariaLabel="Project FAQ" [defaultValue]="\'timeline\'">',
        '    <tng-accordion-item value="timeline">',
        '      <tng-accordion-trigger class="accordion-example-trigger">Timeline</tng-accordion-trigger>',
        '      <tng-accordion-panel class="accordion-example-panel">Roadmap and release cadence.</tng-accordion-panel>',
        '    </tng-accordion-item>',
        '    <tng-accordion-item value="governance">',
        '      <tng-accordion-trigger class="accordion-example-trigger">Governance</tng-accordion-trigger>',
        '      <tng-accordion-panel class="accordion-example-panel">Contribution and review policy.</tng-accordion-panel>',
        '    </tng-accordion-item>',
        '  </tng-accordion>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'accordion-examples-faq-plain-css.component.css',
      code: [
        '.accordion-example-panel {',
        '  color: var(--tng-semantic-foreground-secondary);',
        '}',
      ].join('\n'),
    },
  ]);

  protected readonly faqTailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'accordion-examples-faq-tailwind.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import {",
        "  TngAccordionComponent,",
        "  TngAccordionItemComponent,",
        "  TngAccordionPanelComponent,",
        "  TngAccordionTriggerComponent,",
        "} from '@tailng-ui/components';",
        '',
        '@Component({',
        "  selector: 'app-accordion-examples-faq-tailwind',",
        '  standalone: true,',
        '  imports: [',
        '    TngAccordionComponent,',
        '    TngAccordionItemComponent,',
        '    TngAccordionTriggerComponent,',
        '    TngAccordionPanelComponent,',
        '  ],',
        "  templateUrl: './accordion-examples-faq-tailwind.component.html',",
        "  styleUrl: './accordion-examples-faq-tailwind.component.css',",
        '})',
        'export class AccordionExamplesFaqTailwindComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'accordion-examples-faq-tailwind.component.html',
      code: [
        '<div class="rounded-xl border border-slate-300 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-900/60">',
        '  <tng-accordion ariaLabel="Project FAQ" [defaultValue]="\'release\'">',
        '    <tng-accordion-item value="release">',
        '      <tng-accordion-trigger class="accordion-example-trigger font-medium text-slate-900 dark:text-slate-100">',
        '        Release model',
        '      </tng-accordion-trigger>',
        '      <tng-accordion-panel class="accordion-example-panel text-slate-700 dark:text-slate-300">',
        '        Weekly patch and monthly minor cadence.',
        '      </tng-accordion-panel>',
        '    </tng-accordion-item>',
        '    <tng-accordion-item value="quality">',
        '      <tng-accordion-trigger class="accordion-example-trigger font-medium text-slate-900 dark:text-slate-100">',
        '        Quality gates',
        '      </tng-accordion-trigger>',
        '      <tng-accordion-panel class="accordion-example-panel text-slate-700 dark:text-slate-300">',
        '        Tests and lint pass before merge.',
        '      </tng-accordion-panel>',
        '    </tng-accordion-item>',
        '  </tng-accordion>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'accordion-examples-faq-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  protected readonly settingsPlainCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'accordion-examples-settings-plain-css.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import {",
        "  TngAccordionComponent,",
        "  TngAccordionItemComponent,",
        "  TngAccordionPanelComponent,",
        "  TngAccordionTriggerComponent,",
        "} from '@tailng-ui/components';",
        '',
        '@Component({',
        "  selector: 'app-accordion-examples-settings-plain-css',",
        '  standalone: true,',
        '  imports: [',
        '    TngAccordionComponent,',
        '    TngAccordionItemComponent,',
        '    TngAccordionTriggerComponent,',
        '    TngAccordionPanelComponent,',
        '  ],',
        "  templateUrl: './accordion-examples-settings-plain-css.component.html',",
        "  styleUrl: './accordion-examples-settings-plain-css.component.css',",
        '})',
        'export class AccordionExamplesSettingsPlainCssComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'accordion-examples-settings-plain-css.component.html',
      code: [
        '<div class="accordion-example-shell accordion-example-shell--plain">',
        '  <tng-accordion type="multiple" [defaultValue]="[\'alerts\']" ariaLabel="System settings">',
        '    <tng-accordion-item value="alerts">',
        '      <tng-accordion-trigger class="accordion-example-trigger">Alerts</tng-accordion-trigger>',
        '      <tng-accordion-panel class="accordion-example-panel">PagerDuty, email, and Slack routing.</tng-accordion-panel>',
        '    </tng-accordion-item>',
        '    <tng-accordion-item value="audits">',
        '      <tng-accordion-trigger class="accordion-example-trigger">Audits</tng-accordion-trigger>',
        '      <tng-accordion-panel class="accordion-example-panel">Retention and export scheduling.</tng-accordion-panel>',
        '    </tng-accordion-item>',
        '    <tng-accordion-item value="billing" disabled>',
        '      <tng-accordion-trigger class="accordion-example-trigger">Billing (disabled)</tng-accordion-trigger>',
        '      <tng-accordion-panel class="accordion-example-panel">Disabled sections stay locked.</tng-accordion-panel>',
        '    </tng-accordion-item>',
        '  </tng-accordion>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'accordion-examples-settings-plain-css.component.css',
      code: [
        'tng-accordion-item[disabled] {',
        '  opacity: 0.65;',
        '}',
      ].join('\n'),
    },
  ]);

  protected readonly settingsTailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'accordion-examples-settings-tailwind.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import {",
        "  TngAccordionComponent,",
        "  TngAccordionItemComponent,",
        "  TngAccordionPanelComponent,",
        "  TngAccordionTriggerComponent,",
        "} from '@tailng-ui/components';",
        '',
        '@Component({',
        "  selector: 'app-accordion-examples-settings-tailwind',",
        '  standalone: true,',
        '  imports: [',
        '    TngAccordionComponent,',
        '    TngAccordionItemComponent,',
        '    TngAccordionTriggerComponent,',
        '    TngAccordionPanelComponent,',
        '  ],',
        "  templateUrl: './accordion-examples-settings-tailwind.component.html',",
        "  styleUrl: './accordion-examples-settings-tailwind.component.css',",
        '})',
        'export class AccordionExamplesSettingsTailwindComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'accordion-examples-settings-tailwind.component.html',
      code: [
        '<div class="rounded-xl border border-slate-300 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-900/60">',
        '  <tng-accordion type="multiple" [defaultValue]="[\'alerts\']" ariaLabel="System settings">',
        '    <tng-accordion-item value="alerts">',
        '      <tng-accordion-trigger class="accordion-example-trigger font-medium text-slate-900 dark:text-slate-100">',
        '        Alerts',
        '      </tng-accordion-trigger>',
        '      <tng-accordion-panel class="accordion-example-panel text-slate-700 dark:text-slate-300">',
        '        PagerDuty, email, and Slack routing.',
        '      </tng-accordion-panel>',
        '    </tng-accordion-item>',
        '    <tng-accordion-item value="audits">',
        '      <tng-accordion-trigger class="accordion-example-trigger font-medium text-slate-900 dark:text-slate-100">',
        '        Audits',
        '      </tng-accordion-trigger>',
        '      <tng-accordion-panel class="accordion-example-panel text-slate-700 dark:text-slate-300">',
        '        Retention and export scheduling.',
        '      </tng-accordion-panel>',
        '    </tng-accordion-item>',
        '  </tng-accordion>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'accordion-examples-settings-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  public ngOnDestroy(): void {
    this.colorSchemeObserver?.disconnect();
  }
}
