import { Component } from '@angular/core';
import { TngStackedBarChartComponent, type TngChartOptionOverride } from '@tailng-ui/charts';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import { DocsFormDemoShellComponent } from '../../../../../../shared/form-demo-shell/docs-form-demo-shell.component';
import {
  CHART_PILOT_PLAIN_LAYOUT_CSS,
  CHART_PILOT_TAILWIND_LAYOUT_CSS,
  CHART_PILOT_TAILWIND_SHELL_CLASS,
  createChartPilotCodeTabs,
} from '../../../../series/pilot/shared/chart-series-pilot-examples.util';
import { ChartSeriesPilotThemeBase } from '../../../../series/pilot/shared/chart-series-pilot-theme.base';
import { STACKED_BAR_DEMO_DATA, STACKED_BAR_DEMO_SERIES } from '../../stacked-bar-pilot.data';

@Component({
  selector: 'app-stacked-bar-examples-page',
  imports: [
    TngStackedBarChartComponent,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
    DocsFormDemoShellComponent,
  ],
  templateUrl: './stacked-bar-examples-page.component.html',
  styleUrl: './stacked-bar-examples-page.component.css',
})
export class StackedBarExamplesPageComponent extends ChartSeriesPilotThemeBase {
  protected readonly chartHeight = 300;
  protected readonly data = STACKED_BAR_DEMO_DATA;
  protected readonly series = STACKED_BAR_DEMO_SERIES;
  protected readonly tailwindShellClass = CHART_PILOT_TAILWIND_SHELL_CLASS;

  protected readonly chartOptionOverride: TngChartOptionOverride = (option) => ({
    ...option,
    series: (option['series'] as unknown[] | undefined)?.map((series) => ({
      ...(series as Record<string, unknown>),
      itemStyle: { borderRadius: [6, 6, 0, 0] },
    })),
  });

  protected readonly defaultPlainCodeTabs = createChartPilotCodeTabs({
    baseName: 'stacked-bar-default-plain',
    tsCode: [
      "import { Component } from '@angular/core';",
      "import { TngStackedBarChart, type TngChartData, type TngChartSeries } from '@tailng-ui/charts';",
      '',
      'const data: TngChartData = [',
      "  { label: 'North', subscriptions: 26, services: 14, support: 8 },",
      "  { label: 'West', subscriptions: 34, services: 18, support: 12 },",
      "  { label: 'South', subscriptions: 30, services: 16, support: 10 },",
      "  { label: 'East', subscriptions: 22, services: 12, support: 7 },",
      "  { label: 'Central', subscriptions: 28, services: 15, support: 9 },",
      '];',
      '',
      'const series: readonly TngChartSeries[] = [',
      "  { key: 'subscriptions', label: 'Subscriptions', yField: 'subscriptions' },",
      "  { key: 'services', label: 'Services', yField: 'services' },",
      "  { key: 'support', label: 'Support', yField: 'support' },",
      '];',
      '',
      '@Component({',
      "  selector: 'app-stacked-bar-default-plain',",
      '  standalone: true,',
      '  imports: [TngStackedBarChart],',
      "  templateUrl: './stacked-bar-default-plain.component.html',",
      "  styleUrl: './stacked-bar-default-plain.component.css',",
      '})',
      'export class StackedBarDefaultPlainComponent {',
      '  protected readonly data = data;',
      '  protected readonly series = series;',
      '}',
    ].join('\n'),
    htmlCode: [
      '<div class="chart-pilot-example-preview">',
      '  <div class="chart-pilot-example-chart chart-pilot-example-chart--plain">',
      '    <tng-stacked-bar-chart',
      '      [data]="data"',
      '      xField="label"',
      '      [series]="series"',
      '      [height]="320"',
      '    />',
      '  </div>',
      '</div>',
    ].join('\n'),
    cssCode: CHART_PILOT_PLAIN_LAYOUT_CSS,
  });

  protected readonly defaultTailwindCodeTabs = createChartPilotCodeTabs({
    baseName: 'stacked-bar-default-tailwind',
    tsCode: [
      "import { Component } from '@angular/core';",
      "import { TngStackedBarChart, type TngChartData, type TngChartSeries } from '@tailng-ui/charts';",
      '',
      'const data: TngChartData = [',
      "  { label: 'North', subscriptions: 26, services: 14, support: 8 },",
      "  { label: 'West', subscriptions: 34, services: 18, support: 12 },",
      "  { label: 'South', subscriptions: 30, services: 16, support: 10 },",
      "  { label: 'East', subscriptions: 22, services: 12, support: 7 },",
      "  { label: 'Central', subscriptions: 28, services: 15, support: 9 },",
      '];',
      '',
      'const series: readonly TngChartSeries[] = [',
      "  { key: 'subscriptions', label: 'Subscriptions', yField: 'subscriptions' },",
      "  { key: 'services', label: 'Services', yField: 'services' },",
      "  { key: 'support', label: 'Support', yField: 'support' },",
      '];',
      '',
      '@Component({',
      "  selector: 'app-stacked-bar-default-tailwind',",
      '  standalone: true,',
      '  imports: [TngStackedBarChart],',
      "  templateUrl: './stacked-bar-default-tailwind.component.html',",
      "  styleUrl: './stacked-bar-default-tailwind.component.css',",
      '})',
      'export class StackedBarDefaultTailwindComponent {',
      '  protected readonly data = data;',
      '  protected readonly series = series;',
      '}',
    ].join('\n'),
    htmlCode: [
      '<div class="chart-pilot-example-preview">',
      '  <div class="chart-shell">',
      '    <tng-stacked-bar-chart',
      '      [data]="data"',
      '      xField="label"',
      '      [series]="series"',
      '      [height]="320"',
      '    />',
      '  </div>',
      '</div>',
    ].join('\n'),
    cssCode: CHART_PILOT_TAILWIND_LAYOUT_CSS,
  });

  protected readonly themedPlainCodeTabs = createChartPilotCodeTabs({
    baseName: 'stacked-bar-themed-plain',
    tsCode: [
      "import { Component } from '@angular/core';",
      "import { TngStackedBarChart, type TngChartData, type TngChartSeries } from '@tailng-ui/charts';",
      '',
      'const data: TngChartData = [',
      "  { label: 'North', subscriptions: 26, services: 14, support: 8 },",
      "  { label: 'West', subscriptions: 34, services: 18, support: 12 },",
      "  { label: 'South', subscriptions: 30, services: 16, support: 10 },",
      '];',
      '',
      'const series: readonly TngChartSeries[] = [',
      "  { key: 'subscriptions', label: 'Subscriptions', yField: 'subscriptions' },",
      "  { key: 'services', label: 'Services', yField: 'services' },",
      "  { key: 'support', label: 'Support', yField: 'support' },",
      '];',
      '',
      '@Component({',
      "  selector: 'app-stacked-bar-themed-plain',",
      '  standalone: true,',
      '  imports: [TngStackedBarChart],',
      "  templateUrl: './stacked-bar-themed-plain.component.html',",
      "  styleUrl: './stacked-bar-themed-plain.component.css',",
      '})',
      'export class StackedBarThemedPlainComponent {',
      '  protected readonly data = data;',
      '  protected readonly series = series;',
      '}',
    ].join('\n'),
    htmlCode: [
      '<div class="analytics-panel">',
      '  <div class="chart-pilot-example-chart chart-pilot-example-chart--themed">',
      '    <tng-stacked-bar-chart',
      '      [data]="data"',
      '      xField="label"',
      '      [series]="series"',
      '      [height]="320"',
      '    />',
      '  </div>',
      '</div>',
    ].join('\n'),
    cssCode: [
      CHART_PILOT_PLAIN_LAYOUT_CSS,
      '',
      '.analytics-panel tng-stacked-bar-chart {',
      '  --tng-chart-series-1: var(--tng-semantic-accent-brand);',
      '  --tng-chart-axis-label: var(--tng-semantic-foreground-secondary);',
      '  --tng-chart-grid-line: color-mix(in srgb, var(--tng-semantic-border-subtle) 72%, transparent);',
      '}',
    ].join('\n'),
  });

  protected readonly themedTailwindCodeTabs = createChartPilotCodeTabs({
    baseName: 'stacked-bar-themed-tailwind',
    tsCode: [
      "import { Component } from '@angular/core';",
      "import { TngStackedBarChart, type TngChartData, type TngChartSeries } from '@tailng-ui/charts';",
      '',
      'const data: TngChartData = [',
      "  { label: 'North', subscriptions: 26, services: 14, support: 8 },",
      "  { label: 'West', subscriptions: 34, services: 18, support: 12 },",
      "  { label: 'South', subscriptions: 30, services: 16, support: 10 },",
      '];',
      '',
      'const series: readonly TngChartSeries[] = [',
      "  { key: 'subscriptions', label: 'Subscriptions', yField: 'subscriptions' },",
      "  { key: 'services', label: 'Services', yField: 'services' },",
      "  { key: 'support', label: 'Support', yField: 'support' },",
      '];',
      '',
      '@Component({',
      "  selector: 'app-stacked-bar-themed-tailwind',",
      '  standalone: true,',
      '  imports: [TngStackedBarChart],',
      "  templateUrl: './stacked-bar-themed-tailwind.component.html',",
      "  styleUrl: './stacked-bar-themed-tailwind.component.css',",
      '})',
      'export class StackedBarThemedTailwindComponent {',
      '  protected readonly data = data;',
      '  protected readonly series = series;',
      '}',
    ].join('\n'),
    htmlCode: [
      '<div class="analytics-panel rounded-2xl border border-[var(--tng-semantic-border-subtle)] p-4">',
      '  <tng-stacked-bar-chart',
      '    [data]="data"',
      '    xField="label"',
      '    [series]="series"',
      '    [height]="320"',
      '  />',
      '</div>',
    ].join('\n'),
    cssCode: CHART_PILOT_TAILWIND_LAYOUT_CSS,
  });

  protected readonly overridePlainCodeTabs = createChartPilotCodeTabs({
    baseName: 'stacked-bar-override-plain',
    tsCode: [
      "import { Component } from '@angular/core';",
      "import { TngStackedBarChart, type TngChartData, type TngChartOptionOverride, type TngChartSeries } from '@tailng-ui/charts';",
      '',
      'const data: TngChartData = [',
      "  { label: 'North', subscriptions: 26, services: 14, support: 8 },",
      "  { label: 'West', subscriptions: 34, services: 18, support: 12 },",
      "  { label: 'South', subscriptions: 30, services: 16, support: 10 },",
      '];',
      '',
      'const series: readonly TngChartSeries[] = [',
      "  { key: 'subscriptions', label: 'Subscriptions', yField: 'subscriptions' },",
      "  { key: 'services', label: 'Services', yField: 'services' },",
      "  { key: 'support', label: 'Support', yField: 'support' },",
      '];',
      '',
      '@Component({',
      "  selector: 'app-stacked-bar-override-plain',",
      '  standalone: true,',
      '  imports: [TngStackedBarChart],',
      "  templateUrl: './stacked-bar-override-plain.component.html',",
      "  styleUrl: './stacked-bar-override-plain.component.css',",
      '})',
      'export class StackedBarOverridePlainComponent {',
      '  protected readonly data = data;',
      '  protected readonly series = series;',
      '  protected readonly chartOptionOverride: TngChartOptionOverride = (option) => ({',
      '    ...option,',
      '    series: (option.series as unknown[] | undefined)?.map((series) => ({',
      '      ...(series as Record<string, unknown>),',
      '      itemStyle: { borderRadius: [6, 6, 0, 0] },',
      '    })),',
      '  });',
      '}',
    ].join('\n'),
    htmlCode: [
      '<div class="chart-pilot-example-chart chart-pilot-example-chart--plain">',
      '  <tng-stacked-bar-chart',
      '    [data]="data"',
      '    xField="label"',
      '    [series]="series"',
      '    [height]="320"',
      '    [optionOverride]="chartOptionOverride"',
      '  />',
      '</div>',
    ].join('\n'),
    cssCode: CHART_PILOT_PLAIN_LAYOUT_CSS,
  });

  protected readonly overrideTailwindCodeTabs = createChartPilotCodeTabs({
    baseName: 'stacked-bar-override-tailwind',
    tsCode: [
      "import { Component } from '@angular/core';",
      "import { TngStackedBarChart, type TngChartData, type TngChartOptionOverride, type TngChartSeries } from '@tailng-ui/charts';",
      '',
      'const data: TngChartData = [',
      "  { label: 'North', subscriptions: 26, services: 14, support: 8 },",
      "  { label: 'West', subscriptions: 34, services: 18, support: 12 },",
      "  { label: 'South', subscriptions: 30, services: 16, support: 10 },",
      '];',
      '',
      'const series: readonly TngChartSeries[] = [',
      "  { key: 'subscriptions', label: 'Subscriptions', yField: 'subscriptions' },",
      "  { key: 'services', label: 'Services', yField: 'services' },",
      "  { key: 'support', label: 'Support', yField: 'support' },",
      '];',
      '',
      '@Component({',
      "  selector: 'app-stacked-bar-override-tailwind',",
      '  standalone: true,',
      '  imports: [TngStackedBarChart],',
      "  templateUrl: './stacked-bar-override-tailwind.component.html',",
      "  styleUrl: './stacked-bar-override-tailwind.component.css',",
      '})',
      'export class StackedBarOverrideTailwindComponent {',
      '  protected readonly data = data;',
      '  protected readonly series = series;',
      '  protected readonly chartOptionOverride: TngChartOptionOverride = (option) => ({',
      '    ...option,',
      '    series: (option.series as unknown[] | undefined)?.map((series) => ({',
      '      ...(series as Record<string, unknown>),',
      '      itemStyle: { borderRadius: [6, 6, 0, 0] },',
      '    })),',
      '  });',
      '}',
    ].join('\n'),
    htmlCode: [
      '<div class="chart-shell">',
      '  <tng-stacked-bar-chart',
      '    [data]="data"',
      '    xField="label"',
      '    [series]="series"',
      '    [height]="320"',
      '    [optionOverride]="chartOptionOverride"',
      '  />',
      '</div>',
    ].join('\n'),
    cssCode: CHART_PILOT_TAILWIND_LAYOUT_CSS,
  });
}
