import { DOCUMENT } from '@angular/common';
import { Component, inject, signal, type OnDestroy } from '@angular/core';
import { TngCodeBlockComponent } from '@tailng-ui/components';
import type {
  TngMenuSelectEvent} from '@tailng-ui/primitives';
import {
  TngMenu,
  TngMenuGroupLabel,
  TngMenuItem,
  TngMenuSeparator,
  TngMenuTrigger,
} from '@tailng-ui/primitives';
import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import {
  observeDocsCodeThemeChanges,
  resolveDocsCodeBlockTheme,
} from '../../../../../../shared/util';
import { stackblitzTailwindUrl, stackblitzVanillaUrl } from '../../menu.util';

function createCodeTabs(
  baseName: string,
  tsCode: string,
  htmlCode: string,
  cssCode: string,
): readonly DocsExampleCodeTab[] {
  return Object.freeze([
    { value: 'ts', label: 'TS', language: 'ts', title: `${baseName}.component.ts`, code: tsCode },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: `${baseName}.component.html`,
      code: htmlCode,
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: `${baseName}.component.css`,
      code: cssCode,
    },
  ]);
}

@Component({
  selector: 'app-headless-menu-overview-page',
  imports: [
    TngCodeBlockComponent,
    TngMenu,
    TngMenuGroupLabel,
    TngMenuItem,
    TngMenuSeparator,
    TngMenuTrigger,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
  ],
  templateUrl: './menu-overview-page.component.html',
  styleUrls: ['./menu-overview-page.component.css'],
})
export class HeadlessMenuOverviewPageComponent implements OnDestroy {
  private readonly documentRef = inject(DOCUMENT);

  public readonly codeBlockTheme = signal<'github-dark' | 'github-light'>(
    resolveDocsCodeBlockTheme(this.documentRef),
  );
  private readonly colorSchemeObserver = observeDocsCodeThemeChanges(
    this.documentRef,
    this.codeBlockTheme,
  );

  protected readonly stackblitzVanillaUrl = stackblitzVanillaUrl;
  protected readonly stackblitzTailwindUrl = stackblitzTailwindUrl;

  protected readonly plainCommand = signal('No command yet');
  protected readonly tailwindCommand = signal('No command yet');

  protected readonly importCode = [
    'import {',
    '  TngMenu,',
    '  TngMenuTrigger,',
    '  TngMenuItem,',
    '  TngMenuGroupLabel,',
    '  TngMenuSeparator,',
    "} from '@tailng-ui/primitives';",
    '',
  ].join('\n');

  protected readonly usageCode = [
    '<div class="menu-shell">',
    '  <button type="button" [tngMenuTrigger]="overviewUsageActionsMenu">Open</button>',
    '  <div tngMenu #overviewUsageActionsMenu="tngMenu" aria-label="Actions">',
    '    <button type="button" tngMenuItem tngMenuItemValue="save">Save</button>',
    '  </div>',
    '</div>',
    '',
  ].join('\n');

  protected readonly plainCodeTabs = createCodeTabs(
    'headless-menu-overview-plain',
    [
      "import { Component, signal } from '@angular/core';",
      'import {',
      '  TngMenu,',
      '  TngMenuGroupLabel,',
      '  TngMenuItem,',
      '  TngMenuSelectEvent,',
      '  TngMenuSeparator,',
      '  TngMenuTrigger,',
      "} from '@tailng-ui/primitives';",
      '',
      '@Component({',
      '  standalone: true,',
      '  imports: [TngMenu, TngMenuGroupLabel, TngMenuItem, TngMenuSeparator, TngMenuTrigger],',
      "  templateUrl: './headless-menu-overview-plain.component.html',",
      "  styleUrl: './headless-menu-overview-plain.component.css',",
      '})',
      'export class HeadlessMenuOverviewPlainComponent {',
      "  protected readonly overviewPlainLastCommand = signal('No command yet');",
      '',
      '  protected onOverviewPlainCommandSelect(event: TngMenuSelectEvent): void {',
      '    this.overviewPlainLastCommand.set(String(event.value));',
      '  }',
      '}',
      '',
    ].join('\n'),
    [
      '<section class="headless-menu-overview-plain-card">',
      '  <span class="headless-menu-overview-plain-kicker">Actions menu</span>',
      '  <p class="headless-menu-overview-plain-copy">A single trigger opens a panel; you control placement and elevation with CSS.</p>',
      '',
      '  <div class="headless-menu-overview-plain-stage">',
      '    <div class="headless-menu-overview-plain-trigger-shell">',
      '      <button type="button" [tngMenuTrigger]="overviewPlainMenu">Open menu</button>',
      '      <div',
      '        tngMenu',
      '        #overviewPlainMenu="tngMenu"',
      '        aria-label="Actions"',
      '        class="headless-menu-overview-plain-menu"',
      '        (tngMenuSelect)="onOverviewPlainCommandSelect($event)"',
      '      >',
      '        <div tngMenuGroupLabel class="headless-menu-overview-plain-group">Actions</div>',
      '        <button type="button" tngMenuItem tngMenuItemValue="duplicate">Duplicate</button>',
      '        <button type="button" tngMenuItem tngMenuItemValue="rename">Rename</button>',
      '        <div tngMenuSeparator class="headless-menu-overview-plain-separator"></div>',
      '        <button type="button" tngMenuItem tngMenuItemValue="delete">Delete</button>',
      '      </div>',
      '    </div>',
      '  </div>',
      '',
      '  <p class="headless-menu-overview-plain-state">Last command: <strong>{{ overviewPlainLastCommand() }}</strong></p>',
      '</section>',
      '',
    ].join('\n'),
    [
      '.headless-menu-overview-plain-card {',
      '  --headless-menu-plain-bg: var(--tng-semantic-background-canvas, #ffffff);',
      '  --headless-menu-plain-surface: var(--tng-semantic-background-surface, #f8fafc);',
      '  --headless-menu-plain-fg: var(--tng-semantic-foreground-primary, #0f172a);',
      '  --headless-menu-plain-muted: var(--tng-semantic-foreground-secondary, #64748b);',
      '  --headless-menu-plain-border: var(--tng-semantic-border-subtle, #cbd5e1);',
      '  --headless-menu-plain-border-strong: var(--tng-semantic-border-strong, #94a3b8);',
      '  --headless-menu-plain-brand: var(--tng-semantic-accent-brand, #2563eb);',
      '  --headless-menu-plain-focus: var(--tng-semantic-focus-ring, #93c5fd);',
      '  display: grid;',
      '  gap: 0.85rem;',
      '  width: min(100%, 24rem);',
      '  margin-inline: auto;',
      '  padding: 1rem;',
      '  border: 1px solid var(--headless-menu-plain-border);',
      '  border-radius: 1.2rem;',
      '  background: var(--headless-menu-plain-bg);',
      '  color: var(--headless-menu-plain-fg);',
      '  box-shadow: 0 16px 34px color-mix(in srgb, var(--headless-menu-plain-fg) 10%, transparent);',
      '}',
      '.headless-menu-overview-plain-kicker {',
      '  color: var(--headless-menu-plain-muted);',
      '  font-size: 0.78rem;',
      '  font-weight: 700;',
      '  letter-spacing: 0.08em;',
      '  text-transform: uppercase;',
      '}',
      '.headless-menu-overview-plain-copy {',
      '  margin: 0;',
      '  color: var(--headless-menu-plain-muted);',
      '  line-height: 1.6;',
      '}',
      '.headless-menu-overview-plain-stage {',
      '  position: relative;',
      '  display: grid;',
      '  justify-items: start;',
      '  align-content: start;',
      '}',
      '.headless-menu-overview-plain-trigger-shell { position: relative; display: inline-block; }',
      '.headless-menu-overview-plain-trigger-shell [data-slot="menu-trigger"] {',
      '  min-height: 2.05rem;',
      '  padding: 0.46rem 0.9rem;',
      '  border: 1px solid var(--headless-menu-plain-border-strong);',
      '  border-radius: 0.62rem;',
      '  background: color-mix(in srgb, var(--headless-menu-plain-surface) 90%, transparent);',
      '  box-shadow: 0 1px 2px color-mix(in srgb, var(--headless-menu-plain-fg) 8%, transparent);',
      '  color: var(--headless-menu-plain-fg);',
      '  cursor: pointer;',
      '  font: inherit;',
      '  font-size: 0.95rem;',
      '  font-weight: 600;',
      '  line-height: 1.15;',
      '  transition:',
      '    background-color 130ms ease,',
      '    border-color 130ms ease,',
      '    color 130ms ease,',
      '    box-shadow 130ms ease;',
      '}',
      '.headless-menu-overview-plain-trigger-shell [data-slot="menu-trigger"]:hover {',
      '  background: color-mix(in srgb, var(--headless-menu-plain-brand) 14%, var(--headless-menu-plain-surface));',
      '  border-color: color-mix(in srgb, var(--headless-menu-plain-brand) 45%, var(--headless-menu-plain-border-strong));',
      '}',
      '.headless-menu-overview-plain-trigger-shell [data-slot="menu-trigger"]:focus-visible {',
      '  background: color-mix(in srgb, var(--headless-menu-plain-brand) 14%, var(--headless-menu-plain-surface));',
      '  border-color: color-mix(in srgb, var(--headless-menu-plain-brand) 45%, var(--headless-menu-plain-border-strong));',
      '  outline: 2px solid var(--headless-menu-plain-focus);',
      '  outline-offset: 2px;',
      '}',
      '.headless-menu-overview-plain-trigger-shell [data-slot="menu-trigger"][aria-expanded="true"] {',
      '  background: color-mix(in srgb, var(--headless-menu-plain-brand) 22%, var(--headless-menu-plain-surface));',
      '  border-color: color-mix(in srgb, var(--headless-menu-plain-brand) 55%, var(--headless-menu-plain-border-strong));',
      '  color: var(--headless-menu-plain-brand);',
      '  box-shadow:',
      '    0 1px 2px color-mix(in srgb, var(--headless-menu-plain-fg) 8%, transparent),',
      '    inset 0 0 0 1px color-mix(in srgb, var(--headless-menu-plain-brand) 35%, transparent);',
      '}',
      '.headless-menu-overview-plain-menu {',
      '  position: absolute;',
      '  top: calc(100% + 0.45rem);',
      '  left: 0;',
      '  z-index: 30;',
      '  min-width: 13.8rem;',
      '  padding: 0.45rem;',
      '  border: 1px solid var(--headless-menu-plain-border-strong);',
      '  border-radius: 0.82rem;',
      '  background: var(--headless-menu-plain-bg);',
      '  box-shadow: 0 16px 30px -22px color-mix(in srgb, var(--headless-menu-plain-fg) 35%, transparent);',
      '}',
      '.headless-menu-overview-plain-menu[hidden] { display: none !important; }',
      '.headless-menu-overview-plain-menu[data-state="open"] { display: grid; gap: 0.24rem; }',
      '.headless-menu-overview-plain-group {',
      '  padding: 0.25rem 0.45rem;',
      '  color: var(--headless-menu-plain-muted);',
      '  font-size: 0.72rem;',
      '  font-weight: 700;',
      '  letter-spacing: 0.08em;',
      '  text-transform: uppercase;',
      '}',
      '.headless-menu-overview-plain-separator {',
      '  height: 1px;',
      '  margin: 0.2rem 0.35rem;',
      '  background: var(--headless-menu-plain-border);',
      '}',
      '.headless-menu-overview-plain-menu [tngMenuItem] {',
      '  display: flex;',
      '  justify-content: space-between;',
      '  min-height: 2rem;',
      '  padding: 0.4rem 0.62rem;',
      '  border: 0;',
      '  border-radius: 0.58rem;',
      '  background: transparent;',
      '  color: var(--headless-menu-plain-fg);',
      '  font: inherit;',
      '  font-size: 0.86rem;',
      '  font-weight: 550;',
      '  text-align: left;',
      '  cursor: pointer;',
      '}',
      '.headless-menu-overview-plain-menu [tngMenuItem]:hover {',
      '  background: color-mix(in srgb, var(--headless-menu-plain-fg) 8%, transparent);',
      '}',
      '.headless-menu-overview-plain-menu [tngMenuItem]:focus-visible {',
      '  outline: 2px solid var(--headless-menu-plain-focus);',
      '  outline-offset: 2px;',
      '}',
      '.headless-menu-overview-plain-menu [tngMenuItem][data-active] {',
      '  color: var(--headless-menu-plain-brand);',
      '  background: color-mix(in srgb, var(--headless-menu-plain-brand) 22%, transparent);',
      '}',
      '.headless-menu-overview-plain-state {',
      '  margin: 0;',
      '  color: var(--headless-menu-plain-muted);',
      '  font-size: 0.84rem;',
      '}',
      '.headless-menu-overview-plain-state strong {',
      '  color: var(--headless-menu-plain-fg);',
      '  font-weight: 600;',
      '}',
      '',
    ].join('\n'),
  );

  protected readonly tailwindCodeTabs = createCodeTabs(
    'headless-menu-overview-tailwind',
    [
      "import { Component, signal } from '@angular/core';",
      'import {',
      '  TngMenu,',
      '  TngMenuGroupLabel,',
      '  TngMenuItem,',
      '  TngMenuSelectEvent,',
      '  TngMenuSeparator,',
      '  TngMenuTrigger,',
      "} from '@tailng-ui/primitives';",
      '',
      '@Component({',
      '  standalone: true,',
      '  imports: [TngMenu, TngMenuGroupLabel, TngMenuItem, TngMenuSeparator, TngMenuTrigger],',
      "  templateUrl: './headless-menu-overview-tailwind.component.html',",
      '})',
      'export class HeadlessMenuOverviewTailwindComponent {',
      "  protected readonly overviewTailwindLastCommand = signal('No command yet');",
      '',
      '  protected onOverviewTailwindCommandSelect(event: TngMenuSelectEvent): void {',
      '    this.overviewTailwindLastCommand.set(String(event.value));',
      '  }',
      '}',
      '',
    ].join('\n'),
    [
      '<section class="mx-auto grid w-full max-w-[24rem] gap-3 rounded-[1.5rem] border border-slate-200 bg-white p-4 text-slate-900 shadow-[0_18px_38px_rgba(15,23,42,0.12)]">',
      '  <span class="text-[0.75rem] font-semibold uppercase tracking-[0.22em] text-slate-500">Actions menu</span>',
      '  <p class="m-0 text-[0.875rem] leading-6 text-slate-500">',
      '    A single trigger opens a panel; utilities style the trigger and absolutely positioned panel.',
      '  </p>',
      '',
      '  <div class="relative grid justify-items-start content-start">',
      '    <div class="relative inline-block">',
      '      <button',
      '        type="button"',
      '        [tngMenuTrigger]="overviewTailwindMenu"',
      '        class="min-h-[2.05rem] rounded-[0.62rem] border border-slate-400 bg-slate-50 px-[0.9rem] py-[0.46rem] text-[0.95rem] font-semibold text-slate-900 shadow-[0_1px_2px_rgba(15,23,42,0.08)] transition hover:border-blue-400 hover:bg-blue-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-300 aria-expanded:border-blue-500 aria-expanded:bg-blue-100 aria-expanded:text-blue-700 aria-expanded:shadow-[inset_0_0_0_1px_rgba(37,99,235,0.25),0_1px_2px_rgba(15,23,42,0.08)]"',
      '      >',
      '        Open menu',
      '      </button>',
      '      <div',
      '        tngMenu',
      '        #overviewTailwindMenu="tngMenu"',
      '        aria-label="Actions"',
      '        class="absolute left-0 top-[calc(100%+0.45rem)] z-30 hidden min-w-[13.8rem] rounded-[0.82rem] border border-slate-400 bg-white p-[0.45rem] shadow-[0_16px_30px_-22px_rgba(15,23,42,0.35)] data-[state=open]:grid data-[state=open]:gap-[0.24rem]"',
      '        (tngMenuSelect)="onOverviewTailwindCommandSelect($event)"',
      '      >',
      '        <div tngMenuGroupLabel class="px-[0.45rem] py-[0.25rem] text-[0.72rem] font-bold uppercase tracking-[0.08em] text-slate-500">Actions</div>',
      '        <button type="button" tngMenuItem tngMenuItemValue="duplicate" class="flex min-h-[2rem] justify-between rounded-[0.58rem] px-[0.62rem] py-[0.4rem] text-left text-[0.86rem] font-medium text-slate-900 outline-none transition hover:bg-slate-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-300 [&[data-active]]:bg-blue-100 [&[data-active]]:text-blue-700">Duplicate</button>',
      '        <button type="button" tngMenuItem tngMenuItemValue="rename" class="flex min-h-[2rem] justify-between rounded-[0.58rem] px-[0.62rem] py-[0.4rem] text-left text-[0.86rem] font-medium text-slate-900 outline-none transition hover:bg-slate-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-300 [&[data-active]]:bg-blue-100 [&[data-active]]:text-blue-700">Rename</button>',
      '        <div tngMenuSeparator class="mx-[0.35rem] my-[0.2rem] h-px bg-slate-200"></div>',
      '        <button type="button" tngMenuItem tngMenuItemValue="delete" class="flex min-h-[2rem] justify-between rounded-[0.58rem] px-[0.62rem] py-[0.4rem] text-left text-[0.86rem] font-medium text-slate-900 outline-none transition hover:bg-slate-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-300 [&[data-active]]:bg-blue-100 [&[data-active]]:text-blue-700">Delete</button>',
      '      </div>',
      '    </div>',
      '  </div>',
      '',
      '  <p class="m-0 text-[0.875rem] text-slate-500">Last command: <strong class="font-semibold text-slate-900">{{ overviewTailwindLastCommand() }}</strong></p>',
      '</section>',
      '',
    ].join('\n'),
    '/* No custom CSS required. Tailwind utilities own the trigger, panel, and item styling. */\n',
  );

  public ngOnDestroy(): void {
    this.colorSchemeObserver?.disconnect();
  }

  protected onPlainCommandSelect(event: TngMenuSelectEvent): void {
    this.plainCommand.set(String(event.value));
  }

  protected onTailwindCommandSelect(event: TngMenuSelectEvent): void {
    this.tailwindCommand.set(String(event.value));
  }
}
