import { DOCUMENT } from '@angular/common';
import { Component, inject, signal, type OnDestroy } from '@angular/core';
import { TngCodeBlockComponent } from '@tailng-ui/components';
import {
  TngMenu,
  TngMenuGroupLabel,
  TngMenuItem,
  TngMenuSelectEvent,
  TngMenuSeparator,
  TngMenuTrigger,
} from '@tailng-ui/primitives';
import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import {
  observeDocsCodeThemeChanges,
  resolveDocsCodeBlockTheme,
} from '../../../../../../shared/util';
import { stackblitzTailwindUrl, stackblitzVanillaUrl } from '../../menu.util';

function createCodeTabs(
  baseName: string,
  tsCode: string,
  htmlCode: string,
  cssCode: string,
): readonly DocsExampleCodeTab[] {
  return Object.freeze([
    { value: 'ts', label: 'TS', language: 'ts', title: `${baseName}.component.ts`, code: tsCode },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: `${baseName}.component.html`,
      code: htmlCode,
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: `${baseName}.component.css`,
      code: cssCode,
    },
  ]);
}

@Component({
  selector: 'app-headless-menu-overview-page',
  imports: [
    TngCodeBlockComponent,
    TngMenu,
    TngMenuGroupLabel,
    TngMenuItem,
    TngMenuSeparator,
    TngMenuTrigger,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
  ],
  templateUrl: './menu-overview-page.component.html',
  styleUrls: ['./menu-overview-page.component.css'],
})
export class HeadlessMenuOverviewPageComponent implements OnDestroy {
  private readonly documentRef = inject(DOCUMENT);

  public readonly codeBlockTheme = signal<'github-dark' | 'github-light'>(
    resolveDocsCodeBlockTheme(this.documentRef),
  );
  private readonly colorSchemeObserver = observeDocsCodeThemeChanges(
    this.documentRef,
    this.codeBlockTheme,
  );

  protected readonly stackblitzVanillaUrl = stackblitzVanillaUrl;
  protected readonly stackblitzTailwindUrl = stackblitzTailwindUrl;

  protected readonly plainCommand = signal('No command yet');
  protected readonly tailwindCommand = signal('No command yet');

  protected readonly importCode = [
    'import {',
    '  TngMenu,',
    '  TngMenuTrigger,',
    '  TngMenuItem,',
    '  TngMenuGroupLabel,',
    '  TngMenuSeparator,',
    "} from '@tailng-ui/primitives';",
    '',
  ].join('\n');

  protected readonly usageCode = [
    '<div class="menu-shell">',
    '  <button type="button" [tngMenuTrigger]="actionsMenu">Open</button>',
    '  <div tngMenu #actionsMenu="tngMenu" aria-label="Actions">',
    '    <button type="button" tngMenuItem tngMenuItemValue="save">Save</button>',
    '  </div>',
    '</div>',
    '',
  ].join('\n');

  protected readonly plainCodeTabs = createCodeTabs(
    'headless-menu-overview-plain',
    [
      "import { Component, signal } from '@angular/core';",
      'import {',
      '  TngMenu,',
      '  TngMenuGroupLabel,',
      '  TngMenuItem,',
      '  TngMenuSelectEvent,',
      '  TngMenuSeparator,',
      '  TngMenuTrigger,',
      "} from '@tailng-ui/primitives';",
      '',
      '@Component({',
      '  standalone: true,',
      '  imports: [TngMenu, TngMenuGroupLabel, TngMenuItem, TngMenuSeparator, TngMenuTrigger],',
      "  templateUrl: './headless-menu-overview-plain.component.html',",
      "  styleUrl: './headless-menu-overview-plain.component.css',",
      '})',
      'export class HeadlessMenuOverviewPlainComponent {',
      "  protected readonly overviewPlainLastCommand = signal('No command yet');",
      '',
      '  protected onOverviewPlainCommandSelect(event: TngMenuSelectEvent): void {',
      '    this.overviewPlainLastCommand.set(String(event.value));',
      '  }',
      '}',
      '',
    ].join('\n'),
    [
      '<section class="headless-menu-overview-plain-card">',
      '  <span class="headless-menu-overview-plain-kicker">Actions menu</span>',
      '  <p class="headless-menu-overview-plain-copy">A single trigger opens a panel; you control placement and elevation with CSS.</p>',
      '',
      '  <div class="headless-menu-overview-plain-stage">',
      '    <div class="docs-headless-menu-trigger-shell">',
      '      <button type="button" [tngMenuTrigger]="overviewPlainMenu">Open menu</button>',
      '      <div',
      '        tngMenu',
      '        #overviewPlainMenu="tngMenu"',
      '        aria-label="Actions"',
      '        class="docs-headless-menu-overview-menu"',
      '        (tngMenuSelect)="onOverviewPlainCommandSelect($event)"',
      '      >',
      '        <div tngMenuGroupLabel class="docs-headless-menu-overview-group">Actions</div>',
      '        <button type="button" tngMenuItem tngMenuItemValue="duplicate">Duplicate</button>',
      '        <button type="button" tngMenuItem tngMenuItemValue="rename">Rename</button>',
      '        <div tngMenuSeparator class="docs-headless-menu-overview-separator"></div>',
      '        <button type="button" tngMenuItem tngMenuItemValue="delete">Delete</button>',
      '      </div>',
      '    </div>',
      '  </div>',
      '',
      '  <p class="headless-menu-overview-plain-state">Last command: <strong>{{ overviewPlainLastCommand() }}</strong></p>',
      '</section>',
      '',
    ].join('\n'),
    [
      '.headless-menu-overview-plain-card {',
      '  display: grid;',
      '  gap: 0.85rem;',
      '  width: min(100%, 24rem);',
      '  margin-inline: auto;',
      '  padding: 1rem;',
      '  border: 1px solid var(--tng-semantic-border-subtle);',
      '  border-radius: 1.2rem;',
      '  background: var(--tng-semantic-background-canvas);',
      '  color: var(--tng-semantic-foreground-primary);',
      '  box-shadow: 0 16px 34px color-mix(in srgb, var(--tng-semantic-foreground-primary) 10%, transparent);',
      '}',
      '.headless-menu-overview-plain-kicker {',
      '  color: var(--tng-semantic-foreground-secondary);',
      '  font-size: 0.78rem;',
      '  font-weight: 700;',
      '  letter-spacing: 0.08em;',
      '  text-transform: uppercase;',
      '}',
      '.headless-menu-overview-plain-copy {',
      '  margin: 0;',
      '  color: var(--tng-semantic-foreground-secondary);',
      '  line-height: 1.6;',
      '}',
      '.headless-menu-overview-plain-stage {',
      '  position: relative;',
      '  display: grid;',
      '  justify-items: start;',
      '  align-content: start;',
      '}',
      '.docs-headless-menu-trigger-shell { position: relative; display: inline-block; }',
      '.docs-headless-menu-trigger-shell [data-slot="menu-trigger"] {',
      '  min-height: 2.05rem;',
      '  padding: 0.46rem 0.9rem;',
      '  border: 0;',
      '  border-radius: 0.62rem;',
      '  background: transparent;',
      '  color: var(--tng-semantic-foreground-primary);',
      '  cursor: pointer;',
      '  font: inherit;',
      '  font-size: 0.95rem;',
      '  font-weight: 600;',
      '  line-height: 1.15;',
      '  transition:',
      '    background-color 130ms ease,',
      '    color 130ms ease,',
      '    box-shadow 130ms ease;',
      '}',
      '.docs-headless-menu-trigger-shell [data-slot="menu-trigger"]:hover {',
      '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 14%, transparent);',
      '}',
      '.docs-headless-menu-trigger-shell [data-slot="menu-trigger"]:focus-visible {',
      '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 14%, transparent);',
      '  outline: 2px solid var(--tng-semantic-focus-ring);',
      '  outline-offset: 2px;',
      '}',
      '.docs-headless-menu-trigger-shell [data-slot="menu-trigger"][aria-expanded="true"] {',
      '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 22%, transparent);',
      '  color: var(--tng-semantic-accent-brand);',
      '  box-shadow: inset 0 0 0 1px color-mix(in srgb, var(--tng-semantic-accent-brand) 35%, transparent);',
      '}',
      '.docs-headless-menu-overview-menu {',
      '  position: absolute;',
      '  top: calc(100% + 0.45rem);',
      '  left: 0;',
      '  z-index: 30;',
      '  min-width: 13.8rem;',
      '  padding: 0.45rem;',
      '  border: 1px solid var(--tng-semantic-border-strong);',
      '  border-radius: 0.82rem;',
      '  background: var(--tng-semantic-background-canvas);',
      '  box-shadow: 0 16px 30px -22px color-mix(in srgb, var(--tng-semantic-foreground-primary) 35%, transparent);',
      '}',
      '.docs-headless-menu-overview-menu[hidden] { display: none !important; }',
      '.docs-headless-menu-overview-menu[data-state="open"] { display: grid; gap: 0.24rem; }',
      '.docs-headless-menu-overview-group {',
      '  padding: 0.25rem 0.45rem;',
      '  color: var(--tng-semantic-foreground-secondary);',
      '  font-size: 0.72rem;',
      '  font-weight: 700;',
      '  letter-spacing: 0.08em;',
      '  text-transform: uppercase;',
      '}',
      '.docs-headless-menu-overview-separator {',
      '  height: 1px;',
      '  margin: 0.2rem 0.35rem;',
      '  background: var(--tng-semantic-border-subtle);',
      '}',
      '.docs-headless-menu-overview-menu [tngMenuItem] {',
      '  display: flex;',
      '  justify-content: space-between;',
      '  min-height: 2rem;',
      '  padding: 0.4rem 0.62rem;',
      '  border: 0;',
      '  border-radius: 0.58rem;',
      '  background: transparent;',
      '  color: var(--tng-semantic-foreground-primary);',
      '  font: inherit;',
      '  font-size: 0.86rem;',
      '  font-weight: 550;',
      '  text-align: left;',
      '  cursor: pointer;',
      '}',
      '.docs-headless-menu-overview-menu [tngMenuItem]:hover {',
      '  background: color-mix(in srgb, var(--tng-semantic-foreground-primary) 8%, transparent);',
      '}',
      '.docs-headless-menu-overview-menu [tngMenuItem]:focus-visible {',
      '  outline: 2px solid var(--tng-semantic-focus-ring);',
      '  outline-offset: 2px;',
      '}',
      '.docs-headless-menu-overview-menu [tngMenuItem][data-active] {',
      '  color: var(--tng-semantic-accent-brand);',
      '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 22%, transparent);',
      '}',
      '.headless-menu-overview-plain-state {',
      '  margin: 0;',
      '  color: var(--tng-semantic-foreground-secondary);',
      '  font-size: 0.84rem;',
      '}',
      '',
    ].join('\n'),
  );

  protected readonly tailwindCodeTabs = createCodeTabs(
    'headless-menu-overview-tailwind',
    [
      "import { Component, signal } from '@angular/core';",
      'import {',
      '  TngMenu,',
      '  TngMenuGroupLabel,',
      '  TngMenuItem,',
      '  TngMenuSelectEvent,',
      '  TngMenuSeparator,',
      '  TngMenuTrigger,',
      "} from '@tailng-ui/primitives';",
      '',
      '@Component({',
      '  standalone: true,',
      '  imports: [TngMenu, TngMenuGroupLabel, TngMenuItem, TngMenuSeparator, TngMenuTrigger],',
      "  templateUrl: './headless-menu-overview-tailwind.component.html',",
      "  styleUrl: './headless-menu-overview-tailwind.component.css',",
      '})',
      'export class HeadlessMenuOverviewTailwindComponent {',
      "  protected readonly overviewTailwindLastCommand = signal('No command yet');",
      '',
      '  protected onOverviewTailwindCommandSelect(event: TngMenuSelectEvent): void {',
      '    this.overviewTailwindLastCommand.set(String(event.value));',
      '  }',
      '}',
      '',
    ].join('\n'),
    [
      '<section class="docs-headless-menu-overview-tw mx-auto grid w-full max-w-[24rem] gap-3 p-4">',
      '  <span class="docs-headless-menu-overview-tw-kicker">Actions menu</span>',
      '  <p class="docs-headless-menu-overview-tw-lead m-0">',
      '    A single trigger opens a panel; utilities style the trigger and absolutely positioned panel.',
      '  </p>',
      '',
      '  <div class="relative grid justify-items-start content-start">',
      '    <div class="relative inline-block">',
      '      <button',
      '        type="button"',
      '        [tngMenuTrigger]="overviewTailwindMenu"',
      '        class="docs-headless-menu-overview-tailwind-trigger min-h-[2.05rem] rounded-[0.62rem] px-[0.9rem] py-[0.46rem] text-[0.95rem] font-semibold"',
      '      >',
      '        Open menu',
      '      </button>',
      '      <div',
      '        tngMenu',
      '        #overviewTailwindMenu="tngMenu"',
      '        aria-label="Actions"',
      '        class="docs-headless-menu-overview-tw-panel absolute left-0 top-[calc(100%+0.45rem)] z-30 hidden min-w-[13.8rem] p-[0.45rem] data-[state=open]:grid data-[state=open]:gap-[0.24rem]"',
      '        (tngMenuSelect)="onOverviewTailwindCommandSelect($event)"',
      '      >',
      '        <div tngMenuGroupLabel class="docs-headless-menu-overview-tw-label px-[0.45rem] py-[0.25rem]">Actions</div>',
      '        <button type="button" tngMenuItem tngMenuItemValue="duplicate" class="docs-headless-menu-overview-tw-item flex min-h-[2rem] justify-between px-[0.62rem] py-[0.4rem] text-left">Duplicate</button>',
      '        <button type="button" tngMenuItem tngMenuItemValue="rename" class="docs-headless-menu-overview-tw-item flex min-h-[2rem] justify-between px-[0.62rem] py-[0.4rem] text-left">Rename</button>',
      '        <div tngMenuSeparator class="docs-headless-menu-overview-tw-sep mx-[0.35rem] my-[0.2rem] h-px"></div>',
      '        <button type="button" tngMenuItem tngMenuItemValue="delete" class="docs-headless-menu-overview-tw-item flex min-h-[2rem] justify-between px-[0.62rem] py-[0.4rem] text-left">Delete</button>',
      '      </div>',
      '    </div>',
      '  </div>',
      '',
      '  <p class="docs-headless-menu-overview-tw-foot m-0">Last command: <strong>{{ overviewTailwindLastCommand() }}</strong></p>',
      '</section>',
      '',
    ].join('\n'),
    [
      '.docs-headless-menu-overview-tw {',
      '  background: linear-gradient(',
      '    180deg,',
      '    var(--tng-semantic-background-canvas) 0%,',
      '    var(--tng-semantic-background-surface) 100%',
      '  );',
      '  border: 1px solid var(--tng-semantic-border-subtle);',
      '  border-radius: 1.5rem;',
      '  box-shadow: 0 18px 38px color-mix(in srgb, var(--tng-semantic-foreground-primary) 12%, transparent);',
      '  color: var(--tng-semantic-foreground-primary);',
      '}',
      '.docs-headless-menu-overview-tw-kicker {',
      '  color: var(--tng-semantic-foreground-secondary);',
      '  font-size: 0.75rem;',
      '  font-weight: 600;',
      '  letter-spacing: 0.22em;',
      '  text-transform: uppercase;',
      '}',
      '.docs-headless-menu-overview-tw-lead {',
      '  color: var(--tng-semantic-foreground-secondary);',
      '  font-size: 0.875rem;',
      '  line-height: 1.5rem;',
      '}',
      '.docs-headless-menu-overview-tailwind-trigger {',
      '  color: var(--tng-semantic-foreground-primary);',
      '  transition:',
      '    background-color 130ms ease,',
      '    color 130ms ease,',
      '    box-shadow 130ms ease;',
      '}',
      '.docs-headless-menu-overview-tailwind-trigger:hover {',
      '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 12%, transparent);',
      '}',
      '.docs-headless-menu-overview-tailwind-trigger:focus-visible {',
      '  outline: 2px solid var(--tng-semantic-focus-ring);',
      '  outline-offset: 2px;',
      '}',
      '.docs-headless-menu-overview-tailwind-trigger[aria-expanded="true"] {',
      '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 22%, transparent);',
      '  box-shadow: inset 0 0 0 1px color-mix(in srgb, var(--tng-semantic-accent-brand) 35%, transparent);',
      '  color: var(--tng-semantic-accent-brand);',
      '}',
      '.docs-headless-menu-overview-tw-panel {',
      '  background: var(--tng-semantic-background-canvas);',
      '  border: 1px solid var(--tng-semantic-border-strong);',
      '  border-radius: 0.82rem;',
      '  box-shadow: 0 16px 30px -22px color-mix(in srgb, var(--tng-semantic-foreground-primary) 35%, transparent);',
      '}',
      '.docs-headless-menu-overview-tw-label {',
      '  color: var(--tng-semantic-foreground-secondary);',
      '  font-size: 0.72rem;',
      '  font-weight: 700;',
      '  letter-spacing: 0.08em;',
      '  text-transform: uppercase;',
      '}',
      '.docs-headless-menu-overview-tw-item {',
      '  background: transparent;',
      '  border-radius: 0.58rem;',
      '  color: var(--tng-semantic-foreground-primary);',
      '  font-size: 0.86rem;',
      '  font-weight: 500;',
      '  outline: none;',
      '  transition:',
      '    background-color 120ms ease,',
      '    color 120ms ease;',
      '}',
      '.docs-headless-menu-overview-tw-item:hover {',
      '  background: color-mix(in srgb, var(--tng-semantic-foreground-primary) 8%, transparent);',
      '}',
      '.docs-headless-menu-overview-tw-item:focus-visible {',
      '  outline: 2px solid var(--tng-semantic-focus-ring);',
      '  outline-offset: 2px;',
      '}',
      '.docs-headless-menu-overview-tw-item[data-active] {',
      '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 22%, transparent);',
      '  color: var(--tng-semantic-accent-brand);',
      '}',
      '.docs-headless-menu-overview-tw-sep {',
      '  background: var(--tng-semantic-border-subtle);',
      '}',
      '.docs-headless-menu-overview-tw-foot {',
      '  color: var(--tng-semantic-foreground-secondary);',
      '  font-size: 0.875rem;',
      '}',
      '.docs-headless-menu-overview-tw-foot strong {',
      '  color: var(--tng-semantic-foreground-primary);',
      '  font-weight: 600;',
      '}',
      '',
    ].join('\n'),
  );

  public ngOnDestroy(): void {
    this.colorSchemeObserver?.disconnect();
  }

  protected onPlainCommandSelect(event: TngMenuSelectEvent): void {
    this.plainCommand.set(String(event.value));
  }

  protected onTailwindCommandSelect(event: TngMenuSelectEvent): void {
    this.tailwindCommand.set(String(event.value));
  }
}
