import { Component } from '@angular/core';
import { TngBasicLineChartComponent, type TngChartOptionOverride } from '@tailng-ui/charts';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import { DocsFormDemoShellComponent } from '../../../../../../../shared/form-demo-shell/docs-form-demo-shell.component';
import { ChartSeriesPilotThemeBase } from '../../../../pilot/shared/chart-series-pilot-theme.base';
import {
  CHART_PILOT_TAILWIND_SHELL_CLASS,
  CHART_PILOT_PLAIN_LAYOUT_CSS,
  CHART_PILOT_TAILWIND_LAYOUT_CSS,
  createChartPilotCodeTabs,
} from '../../../../pilot/shared/chart-series-pilot-examples.util';
import { BASIC_LINE_DEMO_DATA } from '../../basic-line-pilot.data';

@Component({
  selector: 'app-basic-line-examples-page',
  imports: [
    TngBasicLineChartComponent,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
    DocsFormDemoShellComponent,
  ],
  templateUrl: './basic-line-examples-page.component.html',
  styleUrl: './basic-line-examples-page.component.css',
})
export class BasicLineExamplesPageComponent extends ChartSeriesPilotThemeBase {
  protected readonly chartHeight = 300;
  protected readonly data = BASIC_LINE_DEMO_DATA;
  protected readonly tailwindShellClass = CHART_PILOT_TAILWIND_SHELL_CLASS;

  protected readonly chartOptionOverride: TngChartOptionOverride = (option) => ({
    ...option,
    series: (option['series'] as unknown[] | undefined)?.map((series) => ({
      ...(series as Record<string, unknown>),
      lineStyle: { width: 3 },
      symbolSize: 8,
    })),
  });

  protected readonly defaultPlainCodeTabs = createChartPilotCodeTabs({
    baseName: 'basic-line-default-plain',
    tsCode: [
      "import { Component } from '@angular/core';",
      "import { TngBasicLineChart, type TngChartData } from '@tailng-ui/charts';",
      '',
      'const data: TngChartData = [',
      "  { label: 'Jan', value: 42 },",
      "  { label: 'Feb', value: 58 },",
      "  { label: 'Mar', value: 64 },",
      "  { label: 'Apr', value: 86 },",
      '];',
      '',
      '@Component({',
      "  selector: 'app-basic-line-default-plain',",
      '  standalone: true,',
      '  imports: [TngBasicLineChart],',
      "  templateUrl: './basic-line-default-plain.component.html',",
      "  styleUrl: './basic-line-default-plain.component.css',",
      '})',
      'export class BasicLineDefaultPlainComponent {',
      '  protected readonly data = data;',
      '}',
    ].join('\n'),
    htmlCode: [
      '<div class="chart-pilot-example-preview">',
      '  <div class="chart-pilot-example-chart chart-pilot-example-chart--plain">',
      '    <tng-basic-line-chart',
      '      [data]="data"',
      '      xField="label"',
      '      yField="value"',
      '      [height]="320"',
      '    />',
      '  </div>',
      '</div>',
    ].join('\n'),
    cssCode: CHART_PILOT_PLAIN_LAYOUT_CSS,
  });

  protected readonly defaultTailwindCodeTabs = createChartPilotCodeTabs({
    baseName: 'basic-line-default-tailwind',
    tsCode: [
      "import { Component } from '@angular/core';",
      "import { TngBasicLineChart, type TngChartData } from '@tailng-ui/charts';",
      '',
      'const data: TngChartData = [',
      "  { label: 'Jan', value: 42 },",
      "  { label: 'Feb', value: 58 },",
      "  { label: 'Mar', value: 64 },",
      "  { label: 'Apr', value: 86 },",
      '];',
      '',
      '@Component({',
      "  selector: 'app-basic-line-default-tailwind',",
      '  standalone: true,',
      '  imports: [TngBasicLineChart],',
      "  templateUrl: './basic-line-default-tailwind.component.html',",
      "  styleUrl: './basic-line-default-tailwind.component.css',",
      '})',
      'export class BasicLineDefaultTailwindComponent {',
      '  protected readonly data = data;',
      '}',
    ].join('\n'),
    htmlCode: [
      '<div class="chart-pilot-example-preview">',
      '  <div class="chart-shell">',
      '    <tng-basic-line-chart',
      '      [data]="data"',
      '      xField="label"',
      '      yField="value"',
      '      [height]="320"',
      '    />',
      '  </div>',
      '</div>',
    ].join('\n'),
    cssCode: CHART_PILOT_TAILWIND_LAYOUT_CSS,
  });

  protected readonly themedPlainCodeTabs = createChartPilotCodeTabs({
    baseName: 'basic-line-themed-plain',
    tsCode: [
      "import { Component } from '@angular/core';",
      "import { TngBasicLineChart, type TngChartData } from '@tailng-ui/charts';",
      '',
      'const data: TngChartData = [',
      "  { label: 'Jan', value: 42 },",
      "  { label: 'Feb', value: 58 },",
      "  { label: 'Mar', value: 64 },",
      '];',
      '',
      '@Component({',
      "  selector: 'app-basic-line-themed-plain',",
      '  standalone: true,',
      '  imports: [TngBasicLineChart],',
      "  templateUrl: './basic-line-themed-plain.component.html',",
      "  styleUrl: './basic-line-themed-plain.component.css',",
      '})',
      'export class BasicLineThemedPlainComponent {',
      '  protected readonly data = data;',
      '}',
    ].join('\n'),
    htmlCode: [
      '<div class="analytics-panel">',
      '  <div class="chart-pilot-example-chart chart-pilot-example-chart--themed">',
      '    <tng-basic-line-chart',
      '      [data]="data"',
      '      xField="label"',
      '      yField="value"',
      '      [height]="320"',
      '    />',
      '  </div>',
      '</div>',
    ].join('\n'),
    cssCode: [
      CHART_PILOT_PLAIN_LAYOUT_CSS,
      '',
      '.analytics-panel tng-basic-line-chart {',
      '  --tng-chart-series-1: var(--tng-semantic-accent-brand);',
      '  --tng-chart-axis-label: var(--tng-semantic-foreground-secondary);',
      '  --tng-chart-grid-line: color-mix(in srgb, var(--tng-semantic-border-subtle) 72%, transparent);',
      '}',
    ].join('\n'),
  });

  protected readonly themedTailwindCodeTabs = createChartPilotCodeTabs({
    baseName: 'basic-line-themed-tailwind',
    tsCode: [
      "import { Component } from '@angular/core';",
      "import { TngBasicLineChart, type TngChartData } from '@tailng-ui/charts';",
      '',
      'const data: TngChartData = [',
      "  { label: 'Jan', value: 42 },",
      "  { label: 'Feb', value: 58 },",
      "  { label: 'Mar', value: 64 },",
      '];',
      '',
      '@Component({',
      "  selector: 'app-basic-line-themed-tailwind',",
      '  standalone: true,',
      '  imports: [TngBasicLineChart],',
      "  templateUrl: './basic-line-themed-tailwind.component.html',",
      "  styleUrl: './basic-line-themed-tailwind.component.css',",
      '})',
      'export class BasicLineThemedTailwindComponent {',
      '  protected readonly data = data;',
      '}',
    ].join('\n'),
    htmlCode: [
      '<div class="analytics-panel rounded-2xl border border-[var(--tng-semantic-border-subtle)] p-4">',
      '  <tng-basic-line-chart',
      '    [data]="data"',
      '    xField="label"',
      '    yField="value"',
      '    [height]="320"',
      '  />',
      '</div>',
    ].join('\n'),
    cssCode: CHART_PILOT_TAILWIND_LAYOUT_CSS,
  });

  protected readonly overridePlainCodeTabs = createChartPilotCodeTabs({
    baseName: 'basic-line-override-plain',
    tsCode: [
      "import { Component } from '@angular/core';",
      "import { TngBasicLineChart, type TngChartData, type TngChartOptionOverride } from '@tailng-ui/charts';",
      '',
      'const data: TngChartData = [',
      "  { label: 'Jan', value: 42 },",
      "  { label: 'Feb', value: 58 },",
      "  { label: 'Mar', value: 64 },",
      '];',
      '',
      '@Component({',
      "  selector: 'app-basic-line-override-plain',",
      '  standalone: true,',
      '  imports: [TngBasicLineChart],',
      "  templateUrl: './basic-line-override-plain.component.html',",
      "  styleUrl: './basic-line-override-plain.component.css',",
      '})',
      'export class BasicLineOverridePlainComponent {',
      '  protected readonly data = data;',
      '  protected readonly chartOptionOverride: TngChartOptionOverride = (option) => ({',
      '    ...option,',
      '    series: (option.series as unknown[] | undefined)?.map((series) => ({',
      '      ...(series as Record<string, unknown>),',
      '      lineStyle: { width: 3 },',
      '      symbolSize: 8,',
      '    })),',
      '  });',
      '}',
    ].join('\n'),
    htmlCode: [
      '<div class="chart-pilot-example-chart chart-pilot-example-chart--plain">',
      '  <tng-basic-line-chart',
      '    [data]="data"',
      '    xField="label"',
      '    yField="value"',
      '    [height]="320"',
      '    [optionOverride]="chartOptionOverride"',
      '  />',
      '</div>',
    ].join('\n'),
    cssCode: CHART_PILOT_PLAIN_LAYOUT_CSS,
  });

  protected readonly overrideTailwindCodeTabs = createChartPilotCodeTabs({
    baseName: 'basic-line-override-tailwind',
    tsCode: [
      "import { Component } from '@angular/core';",
      "import { TngBasicLineChart, type TngChartData, type TngChartOptionOverride } from '@tailng-ui/charts';",
      '',
      'const data: TngChartData = [',
      "  { label: 'Jan', value: 42 },",
      "  { label: 'Feb', value: 58 },",
      "  { label: 'Mar', value: 64 },",
      '];',
      '',
      '@Component({',
      "  selector: 'app-basic-line-override-tailwind',",
      '  standalone: true,',
      '  imports: [TngBasicLineChart],',
      "  templateUrl: './basic-line-override-tailwind.component.html',",
      "  styleUrl: './basic-line-override-tailwind.component.css',",
      '})',
      'export class BasicLineOverrideTailwindComponent {',
      '  protected readonly data = data;',
      '  protected readonly chartOptionOverride: TngChartOptionOverride = (option) => ({',
      '    ...option,',
      '    series: (option.series as unknown[] | undefined)?.map((series) => ({',
      '      ...(series as Record<string, unknown>),',
      '      lineStyle: { width: 3 },',
      '    })),',
      '  });',
      '}',
    ].join('\n'),
    htmlCode: [
      '<div class="chart-shell">',
      '  <tng-basic-line-chart',
      '    [data]="data"',
      '    xField="label"',
      '    yField="value"',
      '    [height]="320"',
      '    [optionOverride]="chartOptionOverride"',
      '  />',
      '</div>',
    ].join('\n'),
    cssCode: CHART_PILOT_TAILWIND_LAYOUT_CSS,
  });
}
