export type TngPlaygroundCategory =
  | 'navigation'
  | 'form'
  | 'layout'
  | 'overlay'
  | 'feedback'
  | 'utility'
  | 'other';

export type TngPlaygroundItem = Readonly<{
  path: string;
  title: string;
  description: string;
  category: TngPlaygroundCategory;
  headless: boolean;
  headlessTest: boolean;
  component: boolean;
  componentTest: boolean;
  registry: boolean;
  registryTest: boolean;
  plain: boolean;
  tailwind: boolean;
  stackblitz: boolean;
}>;

export type TngCategoryGroup = Readonly<{
  category: TngPlaygroundCategory;
  label: string;
  items: readonly TngPlaygroundItem[];
}>;

export const ALL_PLAYGROUND_ITEMS: readonly TngPlaygroundItem[] = Object.freeze([
  { path: '/theme', title: 'Theme', description: 'Switch presets/modes and inspect semantic tokens.', category: 'other',
    headless: false,
    headlessTest: false,
    component: false,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
   },
  { path: '/button', title: 'Button', description: 'Test primitive behavior and owned component styles.', category: 'utility',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
   },
  { path: '/copy', title: 'Copy', description: 'Copy payloads from direct text or DOM sources.', category: 'utility',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/code-block', title: 'Code Block', description: 'Adapter-ready syntax highlighting.', category: 'utility',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
   },
  { path: '/accordion', title: 'Accordion', description: 'Expand/collapse panels.', category: 'layout',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: true,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/collapsible', title: 'Collapsible', description: 'Single disclosure panel.', category: 'layout',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/menu', title: 'Menu', description: 'Keyboard navigation for menuitem actions.', category: 'navigation',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/dropdown-menu', title: 'Dropdown Menu', description: 'Triggered menu panel.', category: 'navigation',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/avatar', title: 'Avatar', description: 'User identity display.', category: 'utility',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/card', title: 'Card', description: 'Validate card primitives.', category: 'layout',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: true,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/tag', title: 'Tag', description: 'Compact status/count labels.', category: 'utility',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/badge', title: 'Badge', description: 'Notification indicator.', category: 'utility',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: true,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/separator', title: 'Separator', description: 'Horizontal and vertical dividers.', category: 'layout',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/empty', title: 'Empty', description: 'Empty-state layout.', category: 'feedback',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/progress-bar', title: 'Progress Bar', description: 'Linear progress indicators.', category: 'feedback',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/progress-spinner', title: 'Progress Spinner', description: 'Circular loader.', category: 'feedback',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/skeleton', title: 'Skeleton', description: 'Loading placeholder blocks.', category: 'feedback',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/input', title: 'Input', description: 'Input primitive and wrapper.', category: 'form',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: true,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/label', title: 'Label', description: 'Accessible form labels.', category: 'form',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/input-otp', title: 'Input OTP', description: 'Segmented OTP entry.', category: 'form',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/radio', title: 'Radio', description: 'Grouped single-select behavior.', category: 'form',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/checkbox', title: 'Checkbox', description: 'Checked/unchecked/mixed tri-state.', category: 'form',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: true,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/textarea', title: 'Textarea', description: 'Multiline text input.', category: 'form',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/icons', title: 'Icon', description: 'Icon library with Lucide integration.', category: 'utility',
    headless: false,
    headlessTest: false,
    component: false,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/charts-country-metrics', title: 'Charts', description: 'Country metrics with bar/line chart.', category: 'other',
    headless: false,
    headlessTest: false,
    component: false,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/listbox', title: 'ListBox', description: 'CDK keyboard and multi-select.', category: 'form',
    headless: true,
    headlessTest: true,
    component: false,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/dialog', title: 'Dialog', description: 'Backdrop, focus-trap.', category: 'overlay',
    headless: false,
    headlessTest: false,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/popover', title: 'Popover', description: 'Trigger semantics and dismissal.', category: 'overlay',
    headless: false,
    headlessTest: false,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/tooltip', title: 'Tooltip', description: 'Hover/focus helper text.', category: 'overlay',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/toast', title: 'Toast', description: 'Notification system.', category: 'feedback',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/context-menu', title: 'Context Menu', description: 'Context-triggered actions.', category: 'navigation',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/menubar', title: 'Menubar', description: 'Horizontal menu surface.', category: 'navigation',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/navigation-menu', title: 'Navigation Menu', description: 'Structured navigation list.', category: 'navigation',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/breadcrumb', title: 'Breadcrumb', description: 'Hierarchical navigation trail.', category: 'navigation',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: true,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/toolbar', title: 'Toolbar', description: 'Action controls grouping.', category: 'navigation',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/tabs', title: 'Tabs', description: 'Tabbed container surface.', category: 'navigation',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/stepper', title: 'Stepper', description: 'Multi-step flow surface.', category: 'layout',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: true,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/toggle-group', title: 'Toggle Group', description: 'Grouped toggle controls.', category: 'form',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: true,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/button-toggle', title: 'Button Toggle', description: 'Toggleable button options.', category: 'form',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/switch', title: 'Switch', description: 'Two-state on/off control.', category: 'form',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: true,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/toggle', title: 'Toggle', description: 'Icon-style pressed button.', category: 'form',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: true,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/slider', title: 'Slider', description: 'Range-based input.', category: 'form',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/chips', title: 'Chips', description: 'Compact item set.', category: 'form',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: true,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/combobox', title: 'Combobox', description: 'Text input with options popup.', category: 'form',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/select', title: 'Select', description: 'Single-choice dropdown.', category: 'form',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/autocomplete', title: 'Autocomplete', description: 'Dynamic suggestion list.', category: 'form',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  {
    path: '/multi-autocomplete',
    title: 'Multi Autocomplete',
    description: 'Chips input with multi-select suggestions.',
    category: 'form',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/multiselect', title: 'Multiselect', description: 'Multiple-choice listbox.', category: 'form',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/grid', title: 'Grid', description: 'Keyboard-navigable grid.', category: 'layout',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/tree', title: 'Tree', description: 'Hierarchical expandable list.', category: 'layout',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/drawer', title: 'Drawer', description: 'Slide-in overlay panel.', category: 'layout',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
  { path: '/bottom-sheet', title: 'Bottom Sheet', description: 'Partial-height overlay sheet.', category: 'layout',
    headless: true,
    headlessTest: true,
    component: true,
    componentTest: false,
    plain: false,
    tailwind: false,
    registry: false,
    registryTest: false,
    stackblitz: false,
  },
]);

export const CATEGORY_LABELS: Readonly<Record<TngPlaygroundCategory, string>> = {
  navigation: 'Navigation',
  form: 'Form',
  layout: 'Layout',
  overlay: 'Overlay',
  feedback: 'Feedback',
  utility: 'Utility',
  other: 'Other',
};

export const CATEGORY_ORDER: readonly TngPlaygroundCategory[] = [
  'navigation',
  'form',
  'layout',
  'overlay',
  'feedback',
  'utility',
  'other',
];
