import { DOCUMENT } from '@angular/common';
import { Component, inject, signal, type OnDestroy } from '@angular/core';
import { TngToggle, TngToggleGroup } from '@tailng-ui/primitives';
import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import {
  observeDocsCodeThemeChanges,
  resolveDocsCodeBlockTheme,
} from '../../../../../../shared/util';
import { stackblitzTailwindUrl, stackblitzVanillaUrl } from '../../toggle.util';

type ToolbarOption = 'bold' | 'code';
type ViewMode = 'grid' | 'list' | 'split';

function createCodeTabs(
  baseName: string,
  tsCode: string,
  htmlCode: string,
  cssCode: string,
): readonly DocsExampleCodeTab[] {
  return Object.freeze([
    { value: 'ts', label: 'TS', language: 'ts', title: `${baseName}.component.ts`, code: tsCode },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: `${baseName}.component.html`,
      code: htmlCode,
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: `${baseName}.component.css`,
      code: cssCode,
    },
  ]);
}

function isToolbarOption(value: string): value is ToolbarOption {
  return value === 'bold' || value === 'code';
}

@Component({
  selector: 'app-headless-toggle-examples-page',
  imports: [DocsExampleTabsSectionComponent, DocsExampleVariantDirective, TngToggle, TngToggleGroup],
  templateUrl: './headless-toggle-examples-page.component.html',
  styleUrl: './headless-toggle-examples-page.component.css',
})
export class HeadlessToggleExamplesPageComponent implements OnDestroy {
  private readonly documentRef = inject(DOCUMENT);

  public readonly codeBlockTheme = signal<'github-dark' | 'github-light'>(
    resolveDocsCodeBlockTheme(this.documentRef),
  );
  private readonly colorSchemeObserver = observeDocsCodeThemeChanges(
    this.documentRef,
    this.codeBlockTheme,
  );

  protected readonly stackblitzVanillaUrl = stackblitzVanillaUrl;
  protected readonly stackblitzTailwindUrl = stackblitzTailwindUrl;

  protected readonly plainToolbarSelections = signal<readonly ToolbarOption[]>(['bold']);
  protected readonly tailwindToolbarSelections = signal<readonly ToolbarOption[]>(['bold']);
  protected readonly plainViewMode = signal<ViewMode>('list');
  protected readonly tailwindViewMode = signal<ViewMode>('grid');
  protected readonly plainAlertsEnabled = signal(true);
  protected readonly tailwindAlertsEnabled = signal(true);

  protected readonly toolbarPlainCodeTabs = createCodeTabs(
    'headless-toggle-toolbar-example',
    [
      "import { Component, signal } from '@angular/core';",
      "import { TngToggle, TngToggleGroup } from '@tailng-ui/primitives';",
      '',
      "type ToolbarOption = 'bold' | 'code';",
      '',
      '@Component({',
      "  selector: 'app-headless-toggle-toolbar-example',",
      '  standalone: true,',
      '  imports: [TngToggle, TngToggleGroup],',
      "  templateUrl: './headless-toggle-toolbar-example.component.html',",
      "  styleUrl: './headless-toggle-toolbar-example.component.css',",
      '})',
      'export class HeadlessToggleToolbarExampleComponent {',
      "  readonly toolbarSelections = signal<readonly ToolbarOption[]>(['bold']);",
      '',
      '  onToolbarSelectionsChange(values: readonly string[]): void {',
      "    this.toolbarSelections.set(values.filter((value): value is ToolbarOption => value === 'bold' || value === 'code'));",
      '  }',
      '}',
      '',
    ].join('\n'),
    [
      '<section class="headless-toggle-toolbar-example">',
      '  <div',
      '    tngToggleGroup',
      '    class="headless-toggle-toolbar-example__group"',
      '    ariaLabel="Editor tools"',
      '    [values]="toolbarSelections()"',
      '    (valuesChange)="onToolbarSelectionsChange($event)"',
      '  >',
      '    <button tngToggle tngToggleValue="bold" class="headless-toggle-toolbar-example__item">Bold</button>',
      '    <button tngToggle tngToggleValue="code" class="headless-toggle-toolbar-example__item">Code</button>',
      '  </div>',
      '  <p class="headless-toggle-toolbar-example__summary">Active: {{ toolbarSelections().join(", ") }}</p>',
      '</section>',
      '',
    ].join('\n'),
    [
      '.headless-toggle-toolbar-example {',
      '  display: grid;',
      '  gap: 0.75rem;',
      '  inline-size: min(100%, 26rem);',
      '  margin-inline: auto;',
      '  padding: 1rem;',
      '  border: 1px solid #cbd5e1;',
      '  border-radius: 1rem;',
      '  background: #ffffff;',
      '  color: #0f172a;',
      '  color-scheme: light;',
      '}',
      '',
      '.headless-toggle-toolbar-example__group {',
      '  display: inline-flex;',
      '  gap: 0.55rem;',
      '  padding: 0.55rem;',
      '  border: 1px solid #dbe4ee;',
      '  border-radius: 1rem;',
      '  background: #f8fafc;',
      '}',
      '',
      '.headless-toggle-toolbar-example__item {',
      '  align-items: center;',
      '  appearance: none;',
      '  background: #ffffff;',
      '  border: 1px solid #c6d4e1;',
      '  border-radius: 0.85rem;',
      '  color: #1e293b;',
      '  cursor: pointer;',
      '  display: inline-flex;',
      '  font: inherit;',
      '  font-size: 0.9rem;',
      '  font-weight: 600;',
      '  justify-content: center;',
      '  line-height: 1.1;',
      '  min-height: 2.3rem;',
      '  min-width: 5.4rem;',
      '  padding: 0.45rem 0.95rem;',
      '  transition: background-color 140ms ease, border-color 140ms ease, color 140ms ease, box-shadow 140ms ease;',
      '}',
      '',
      '.headless-toggle-toolbar-example__item[data-state="on"] {',
      '  background: #2563eb;',
      '  border-color: #2563eb;',
      '  color: #ffffff;',
      '}',
      '',
      '.headless-toggle-toolbar-example__summary {',
      '  margin: 0;',
      '  font-size: 0.82rem;',
      '  color: #475569;',
      '}',
      '',
    ].join('\n'),
  );

  protected readonly toolbarTailwindCodeTabs = createCodeTabs(
    'headless-toggle-toolbar-tailwind-example',
    [
      "import { Component, signal } from '@angular/core';",
      "import { TngToggle, TngToggleGroup } from '@tailng-ui/primitives';",
      '',
      "type ToolbarOption = 'bold' | 'code';",
      '',
      '@Component({',
      "  selector: 'app-headless-toggle-toolbar-tailwind-example',",
      '  standalone: true,',
      '  imports: [TngToggle, TngToggleGroup],',
      "  templateUrl: './headless-toggle-toolbar-tailwind-example.component.html',",
      '})',
      'export class HeadlessToggleToolbarTailwindExampleComponent {',
      "  readonly toolbarSelections = signal<readonly ToolbarOption[]>(['bold']);",
      '',
      '  onToolbarSelectionsChange(values: readonly string[]): void {',
      "    this.toolbarSelections.set(values.filter((value): value is ToolbarOption => value === 'bold' || value === 'code'));",
      '  }',
      '}',
      '',
    ].join('\n'),
    [
      '<section class="grid w-full max-w-[28rem] gap-3 rounded-2xl border border-slate-300 bg-white p-4 text-slate-900 shadow-sm [color-scheme:light]">',
      '  <div class="grid gap-1">',
      '    <span class="text-base font-semibold text-slate-900">Editor tools</span>',
      '    <p class="m-0 text-sm leading-6 text-slate-600">Multiple-selection formatting actions where each button keeps its own pressed state.</p>',
      '  </div>',
      '  <div',
      '    tngToggleGroup',
      '    class="inline-flex flex-wrap gap-2 rounded-2xl border border-slate-200 bg-slate-100 p-2.5"',
      '    ariaLabel="Editor tools"',
      '    [values]="toolbarSelections()"',
      '    (valuesChange)="onToolbarSelectionsChange($event)"',
      '  >',
      '    <button tngToggle tngToggleValue="bold" class="inline-flex min-h-9 min-w-[5.4rem] items-center justify-center rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-800 transition data-[state=on]:border-blue-600 data-[state=on]:bg-blue-600 data-[state=on]:text-white focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-blue-100">Bold</button>',
      '    <button tngToggle tngToggleValue="code" class="inline-flex min-h-9 min-w-[5.4rem] items-center justify-center rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-800 transition data-[state=on]:border-blue-600 data-[state=on]:bg-blue-600 data-[state=on]:text-white focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-blue-100">Code</button>',
      '  </div>',
      '  <p class="m-0 text-xs text-slate-600">Active: {{ toolbarSelections().join(", ") }}</p>',
      '</section>',
      '',
    ].join('\n'),
    '/* Tailwind utilities are applied directly in the template. */',
  );

  protected readonly viewModePlainCodeTabs = createCodeTabs(
    'headless-toggle-view-mode-example',
    [
      "import { Component, signal } from '@angular/core';",
      "import { TngToggle, TngToggleGroup } from '@tailng-ui/primitives';",
      '',
      "type ViewMode = 'grid' | 'list' | 'split';",
      '',
      '@Component({',
      "  selector: 'app-headless-toggle-view-mode-example',",
      '  standalone: true,',
      '  imports: [TngToggle, TngToggleGroup],',
      "  templateUrl: './headless-toggle-view-mode-example.component.html',",
      "  styleUrl: './headless-toggle-view-mode-example.component.css',",
      '})',
      'export class HeadlessToggleViewModeExampleComponent {',
      "  readonly viewMode = signal<ViewMode>('list');",
      '',
      '  onViewModeChange(value: string | null): void {',
      "    if (value === 'grid' || value === 'list' || value === 'split') {",
      '      this.viewMode.set(value);',
      '    }',
      '  }',
      '}',
      '',
    ].join('\n'),
    [
      '<section class="headless-toggle-view-mode-example">',
      '  <div class="headless-toggle-view-mode-example__header">',
      '    <span class="headless-toggle-view-mode-example__eyebrow">View mode</span>',
      '    <p class="headless-toggle-view-mode-example__body">Single-select groups are a good fit for layout pickers.</p>',
      '  </div>',
      '  <div',
      '    tngToggleGroup',
      '    class="headless-toggle-view-mode-example__group"',
      '    selectionMode="single"',
      '    ariaLabel="View mode"',
      '    [value]="viewMode()"',
      '    (valueChange)="onViewModeChange($event)"',
      '  >',
      '    <button tngToggle tngToggleValue="grid" class="headless-toggle-view-mode-example__item">Grid</button>',
      '    <button tngToggle tngToggleValue="list" class="headless-toggle-view-mode-example__item">List</button>',
      '    <button tngToggle tngToggleValue="split" class="headless-toggle-view-mode-example__item">Split</button>',
      '  </div>',
      '  <p class="headless-toggle-view-mode-example__summary">Selected: {{ viewMode() }}</p>',
      '</section>',
      '',
    ].join('\n'),
    [
      '.headless-toggle-view-mode-example {',
      '  display: grid;',
      '  gap: 0.85rem;',
      '  inline-size: min(100%, 30rem);',
      '  margin-inline: auto;',
      '  padding: 1rem;',
      '  border: 1px solid #cbd5e1;',
      '  border-radius: 1rem;',
      '  background: #ffffff;',
      '  color: #0f172a;',
      '  color-scheme: light;',
      '}',
      '',
      '.headless-toggle-view-mode-example__header {',
      '  display: grid;',
      '  gap: 0.35rem;',
      '}',
      '',
      '.headless-toggle-view-mode-example__eyebrow {',
      '  color: #0f172a;',
      '  font-size: 1rem;',
      '  font-weight: 700;',
      '}',
      '',
      '.headless-toggle-view-mode-example__body {',
      '  margin: 0;',
      '  color: #475569;',
      '  font-size: 0.92rem;',
      '  line-height: 1.6;',
      '}',
      '',
      '.headless-toggle-view-mode-example__group {',
      '  display: inline-flex;',
      '  flex-wrap: wrap;',
      '  gap: 0.55rem;',
      '  padding: 0.55rem;',
      '  border: 1px solid #dbe4ee;',
      '  border-radius: 1rem;',
      '  background: #f8fafc;',
      '}',
      '',
      '.headless-toggle-view-mode-example__item {',
      '  align-items: center;',
      '  appearance: none;',
      '  background: #ffffff;',
      '  border: 1px solid #c6d4e1;',
      '  border-radius: 0.85rem;',
      '  color: #1e293b;',
      '  cursor: pointer;',
      '  display: inline-flex;',
      '  font: inherit;',
      '  font-size: 0.9rem;',
      '  font-weight: 600;',
      '  justify-content: center;',
      '  line-height: 1.1;',
      '  min-height: 2.3rem;',
      '  min-width: 5.4rem;',
      '  padding: 0.45rem 0.95rem;',
      '  transition: background-color 140ms ease, border-color 140ms ease, color 140ms ease, box-shadow 140ms ease;',
      '}',
      '',
      '.headless-toggle-view-mode-example__item[data-state="on"] {',
      '  background: #2563eb;',
      '  border-color: #2563eb;',
      '  color: #ffffff;',
      '}',
      '',
      '.headless-toggle-view-mode-example__summary {',
      '  margin: 0;',
      '  font-size: 0.82rem;',
      '  color: #475569;',
      '}',
      '',
    ].join('\n'),
  );

  protected readonly viewModeTailwindCodeTabs = createCodeTabs(
    'headless-toggle-view-mode-tailwind-example',
    [
      "import { Component, signal } from '@angular/core';",
      "import { TngToggle, TngToggleGroup } from '@tailng-ui/primitives';",
      '',
      "type ViewMode = 'grid' | 'list' | 'split';",
      '',
      '@Component({',
      "  selector: 'app-headless-toggle-view-mode-tailwind-example',",
      '  standalone: true,',
      '  imports: [TngToggle, TngToggleGroup],',
      "  templateUrl: './headless-toggle-view-mode-tailwind-example.component.html',",
      '})',
      'export class HeadlessToggleViewModeTailwindExampleComponent {',
      "  readonly viewMode = signal<ViewMode>('grid');",
      '',
      '  onViewModeChange(value: string | null): void {',
      "    if (value === 'grid' || value === 'list' || value === 'split') {",
      '      this.viewMode.set(value);',
      '    }',
      '  }',
      '}',
      '',
    ].join('\n'),
    [
      '<section class="grid w-full max-w-[30rem] gap-3 rounded-2xl border border-slate-300 bg-white p-4 text-slate-900 shadow-sm [color-scheme:light]">',
      '  <div class="grid gap-1">',
      '    <span class="text-base font-semibold text-slate-900">View mode</span>',
      '    <p class="m-0 text-sm leading-6 text-slate-600">Single-select groups are a good fit for layout pickers.</p>',
      '  </div>',
      '  <div',
      '    tngToggleGroup',
      '    class="inline-flex flex-wrap gap-2 rounded-2xl border border-slate-200 bg-slate-100 p-2.5"',
      '    selectionMode="single"',
      '    ariaLabel="View mode"',
      '    [value]="viewMode()"',
      '    (valueChange)="onViewModeChange($event)"',
      '  >',
      '    <button tngToggle tngToggleValue="grid" class="inline-flex min-h-9 min-w-[5.4rem] items-center justify-center rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-800 transition data-[state=on]:border-blue-600 data-[state=on]:bg-blue-600 data-[state=on]:text-white focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-blue-100">Grid</button>',
      '    <button tngToggle tngToggleValue="list" class="inline-flex min-h-9 min-w-[5.4rem] items-center justify-center rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-800 transition data-[state=on]:border-blue-600 data-[state=on]:bg-blue-600 data-[state=on]:text-white focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-blue-100">List</button>',
      '    <button tngToggle tngToggleValue="split" class="inline-flex min-h-9 min-w-[5.4rem] items-center justify-center rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-800 transition data-[state=on]:border-blue-600 data-[state=on]:bg-blue-600 data-[state=on]:text-white focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-blue-100">Split</button>',
      '  </div>',
      '  <p class="m-0 text-xs text-slate-600">Selected: {{ viewMode() }}</p>',
      '</section>',
      '',
    ].join('\n'),
    '/* Tailwind utilities are applied directly in the template. */',
  );

  protected readonly disabledPlainCodeTabs = createCodeTabs(
    'headless-toggle-disabled-example',
    [
      "import { Component, signal } from '@angular/core';",
      "import { TngToggle } from '@tailng-ui/primitives';",
      '',
      '@Component({',
      "  selector: 'app-headless-toggle-disabled-example',",
      '  standalone: true,',
      '  imports: [TngToggle],',
      "  templateUrl: './headless-toggle-disabled-example.component.html',",
      "  styleUrl: './headless-toggle-disabled-example.component.css',",
      '})',
      'export class HeadlessToggleDisabledExampleComponent {',
      '  readonly alertsEnabled = signal(true);',
      '}',
      '',
    ].join('\n'),
    [
      '<section class="headless-toggle-disabled-example">',
      '  <button tngToggle class="headless-toggle-disabled-example__item" [pressed]="alertsEnabled()" (pressedChange)="alertsEnabled.set($event)">Alerts</button>',
      '  <button tngToggle class="headless-toggle-disabled-example__item" [disabled]="true">Scheduled reports</button>',
      '</section>',
      '',
    ].join('\n'),
    [
      '.headless-toggle-disabled-example {',
      '  display: inline-flex;',
      '  gap: 0.55rem;',
      '  flex-wrap: wrap;',
      '  inline-size: min(100%, 28rem);',
      '  margin-inline: auto;',
      '  padding: 1rem;',
      '  border: 1px solid #cbd5e1;',
      '  border-radius: 1rem;',
      '  background: #ffffff;',
      '  color: #0f172a;',
      '  color-scheme: light;',
      '}',
      '',
      '.headless-toggle-disabled-example__item {',
      '  align-items: center;',
      '  appearance: none;',
      '  background: #ffffff;',
      '  border: 1px solid #c6d4e1;',
      '  border-radius: 0.85rem;',
      '  color: #1e293b;',
      '  cursor: pointer;',
      '  display: inline-flex;',
      '  font: inherit;',
      '  font-size: 0.9rem;',
      '  font-weight: 600;',
      '  justify-content: center;',
      '  line-height: 1.1;',
      '  min-height: 2.3rem;',
      '  min-width: 7.25rem;',
      '  padding: 0.45rem 0.95rem;',
      '  transition: background-color 140ms ease, border-color 140ms ease, color 140ms ease, box-shadow 140ms ease;',
      '}',
      '',
      '.headless-toggle-disabled-example__item[data-state="on"] {',
      '  background: #2563eb;',
      '  border-color: #2563eb;',
      '  color: #ffffff;',
      '}',
      '',
      '.headless-toggle-disabled-example__item:focus-visible {',
      '  outline: 3px solid rgba(37, 99, 235, 0.18);',
      '  outline-offset: 2px;',
      '}',
      '',
      '.headless-toggle-disabled-example__item[data-disabled] {',
      '  background: #f8fafc;',
      '  border-color: #dbe4ee;',
      '  color: #94a3b8;',
      '  cursor: not-allowed;',
      '  opacity: 1;',
      '  box-shadow: none;',
      '}',
      '',
    ].join('\n'),
  );

  protected readonly disabledTailwindCodeTabs = createCodeTabs(
    'headless-toggle-disabled-tailwind-example',
    [
      "import { Component, signal } from '@angular/core';",
      "import { TngToggle } from '@tailng-ui/primitives';",
      '',
      '@Component({',
      "  selector: 'app-headless-toggle-disabled-tailwind-example',",
      '  standalone: true,',
      '  imports: [TngToggle],',
      "  templateUrl: './headless-toggle-disabled-tailwind-example.component.html',",
      '})',
      'export class HeadlessToggleDisabledTailwindExampleComponent {',
      '  readonly alertsEnabled = signal(true);',
      '}',
      '',
    ].join('\n'),
    [
      '<section class="grid w-full max-w-[28rem] gap-3 rounded-2xl border border-slate-300 bg-white p-4 text-slate-900 shadow-sm [color-scheme:light]">',
      '  <div class="grid gap-1">',
      '    <span class="text-base font-semibold text-slate-900">Fallback actions</span>',
      '    <p class="m-0 text-sm leading-6 text-slate-600">Keep the primary action available while clearly muting the unavailable fallback.</p>',
      '  </div>',
      '  <div class="inline-flex flex-wrap gap-2">',
      '    <button tngToggle class="inline-flex min-h-9 min-w-[7.25rem] items-center justify-center rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-800 transition data-[state=on]:border-blue-600 data-[state=on]:bg-blue-600 data-[state=on]:text-white focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-blue-100" [pressed]="alertsEnabled()" (pressedChange)="alertsEnabled.set($event)">Alerts</button>',
      '    <button tngToggle class="inline-flex min-h-9 min-w-[9.5rem] items-center justify-center rounded-xl border border-slate-200 bg-slate-50 px-4 py-2 text-sm font-semibold text-slate-400 shadow-none opacity-100 transition disabled:cursor-not-allowed disabled:border-slate-200 disabled:bg-slate-50 disabled:text-slate-400 disabled:shadow-none disabled:opacity-100" [disabled]="true">Scheduled reports</button>',
      '  </div>',
      '</section>',
      '',
    ].join('\n'),
    '/* Tailwind utilities are applied directly in the template. */',
  );

  protected onPlainToolbarSelectionsChange(values: readonly string[]): void {
    this.plainToolbarSelections.set(values.filter(isToolbarOption));
  }

  protected onTailwindToolbarSelectionsChange(values: readonly string[]): void {
    this.tailwindToolbarSelections.set(values.filter(isToolbarOption));
  }

  protected onPlainViewModeChange(value: string | null): void {
    if (value === 'grid' || value === 'list' || value === 'split') {
      this.plainViewMode.set(value);
    }
  }

  protected onTailwindViewModeChange(value: string | null): void {
    if (value === 'grid' || value === 'list' || value === 'split') {
      this.tailwindViewMode.set(value);
    }
  }

  public ngOnDestroy(): void {
    this.colorSchemeObserver?.disconnect();
  }
}
