import { DOCUMENT } from '@angular/common';
import { Component, inject, signal, type OnDestroy } from '@angular/core';
import {
  TngBreadcrumb,
  TngBreadcrumbItem,
  TngBreadcrumbLink,
  TngBreadcrumbList,
  TngBreadcrumbSeparator,
} from '@tailng-ui/primitives';
import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import {
  observeDocsCodeThemeChanges,
  resolveDocsCodeBlockTheme,
} from '../../../../../../shared/util';

@Component({
  selector: 'app-headless-breadcrumb-examples-page',
  imports: [
    TngBreadcrumb,
    TngBreadcrumbList,
    TngBreadcrumbItem,
    TngBreadcrumbLink,
    TngBreadcrumbSeparator,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
  ],
  templateUrl: './breadcrumb-examples-page.component.html',
  styleUrls: ['./breadcrumb-examples-page.component.css'],
})
export class HeadlessBreadcrumbExamplesPageComponent implements OnDestroy {
  private readonly documentRef = inject(DOCUMENT);

  public readonly codeBlockTheme = signal<'github-dark' | 'github-light'>(
    resolveDocsCodeBlockTheme(this.documentRef),
  );
  private readonly colorSchemeObserver = observeDocsCodeThemeChanges(
    this.documentRef,
    this.codeBlockTheme,
  );

  protected readonly collapsedPlainCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'headless-breadcrumb-examples-collapsed-plain.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import {",
        "  TngBreadcrumb,",
        "  TngBreadcrumbItem,",
        "  TngBreadcrumbLink,",
        "  TngBreadcrumbList,",
        "  TngBreadcrumbSeparator,",
        "} from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-headless-breadcrumb-examples-collapsed-plain',",
        '  standalone: true,',
        '  imports: [',
        '    TngBreadcrumb,',
        '    TngBreadcrumbList,',
        '    TngBreadcrumbItem,',
        '    TngBreadcrumbLink,',
        '    TngBreadcrumbSeparator,',
        '  ],',
        "  templateUrl: './headless-breadcrumb-examples-collapsed-plain.component.html',",
        "  styleUrl: './headless-breadcrumb-examples-collapsed-plain.component.css',",
        '})',
        'export class HeadlessBreadcrumbExamplesCollapsedPlainComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'headless-breadcrumb-examples-collapsed-plain.component.html',
      code: [
        '<div class="headless-breadcrumb-example-shell">',
        '  <nav tngBreadcrumb aria-label="Catalog path">',
        '    <ol tngBreadcrumbList class="headless-breadcrumb-example-list">',
        '      <li tngBreadcrumbItem><a tngBreadcrumbLink href="#">Home</a></li>',
        '      <li tngBreadcrumbSeparator>/</li>',
        '      <li tngBreadcrumbItem><span aria-hidden="true">…</span></li>',
        '      <li tngBreadcrumbSeparator>/</li>',
        '      <li tngBreadcrumbItem><a tngBreadcrumbLink href="#">Shoes</a></li>',
        '      <li tngBreadcrumbSeparator>/</li>',
        '      <li tngBreadcrumbItem><span aria-current="page">Running</span></li>',
        '    </ol>',
        '  </nav>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'headless-breadcrumb-examples-collapsed-plain.component.css',
      code: [
        '.headless-breadcrumb-example-shell {',
        '  border: 1px solid var(--tng-semantic-border-subtle);',
        '  border-radius: 0.9rem;',
        '  padding: 0.9rem 1rem;',
        '}',
        '',
        '.headless-breadcrumb-example-list {',
        '  display: flex;',
        '  flex-wrap: wrap;',
        '  align-items: center;',
        '  gap: 0.45rem;',
        '  margin: 0;',
        '  padding: 0;',
        '  list-style: none;',
        '}',
      ].join('\n'),
    },
  ]);

  protected readonly collapsedTailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'headless-breadcrumb-examples-collapsed-tailwind.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import {",
        "  TngBreadcrumb,",
        "  TngBreadcrumbItem,",
        "  TngBreadcrumbLink,",
        "  TngBreadcrumbList,",
        "  TngBreadcrumbSeparator,",
        "} from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-headless-breadcrumb-examples-collapsed-tailwind',",
        '  standalone: true,',
        '  imports: [',
        '    TngBreadcrumb,',
        '    TngBreadcrumbList,',
        '    TngBreadcrumbItem,',
        '    TngBreadcrumbLink,',
        '    TngBreadcrumbSeparator,',
        '  ],',
        "  templateUrl: './headless-breadcrumb-examples-collapsed-tailwind.component.html',",
        "  styleUrl: './headless-breadcrumb-examples-collapsed-tailwind.component.css',",
        '})',
        'export class HeadlessBreadcrumbExamplesCollapsedTailwindComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'headless-breadcrumb-examples-collapsed-tailwind.component.html',
      code: [
        '<div class="rounded-xl border border-slate-300 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-900/60">',
        '  <nav tngBreadcrumb aria-label="Catalog path">',
        '    <ol tngBreadcrumbList class="m-0 flex list-none flex-wrap items-center gap-[0.45rem] p-0">',
        '      <li tngBreadcrumbItem><a tngBreadcrumbLink class="text-sky-700 no-underline hover:underline dark:text-sky-300" href="#">Home</a></li>',
        '      <li tngBreadcrumbSeparator class="text-slate-400">›</li>',
        '      <li tngBreadcrumbItem><span class="text-slate-500">…</span></li>',
        '      <li tngBreadcrumbSeparator class="text-slate-400">›</li>',
        '      <li tngBreadcrumbItem><a tngBreadcrumbLink class="text-sky-700 no-underline hover:underline dark:text-sky-300" href="#">Shoes</a></li>',
        '      <li tngBreadcrumbSeparator class="text-slate-400">›</li>',
        '      <li tngBreadcrumbItem><span class="font-semibold text-slate-900 dark:text-slate-100" aria-current="page">Running</span></li>',
        '    </ol>',
        '  </nav>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'headless-breadcrumb-examples-collapsed-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  protected readonly currentPlainCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'headless-breadcrumb-examples-current-plain.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import {",
        "  TngBreadcrumb,",
        "  TngBreadcrumbItem,",
        "  TngBreadcrumbLink,",
        "  TngBreadcrumbList,",
        "  TngBreadcrumbSeparator,",
        "} from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-headless-breadcrumb-examples-current-plain',",
        '  standalone: true,',
        '  imports: [',
        '    TngBreadcrumb,',
        '    TngBreadcrumbList,',
        '    TngBreadcrumbItem,',
        '    TngBreadcrumbLink,',
        '    TngBreadcrumbSeparator,',
        '  ],',
        "  templateUrl: './headless-breadcrumb-examples-current-plain.component.html',",
        "  styleUrl: './headless-breadcrumb-examples-current-plain.component.css',",
        '})',
        'export class HeadlessBreadcrumbExamplesCurrentPlainComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'headless-breadcrumb-examples-current-plain.component.html',
      code: [
        '<div class="headless-breadcrumb-example-shell">',
        '  <nav tngBreadcrumb aria-label="Current-link path">',
        '    <ol tngBreadcrumbList class="headless-breadcrumb-example-list">',
        '      <li tngBreadcrumbItem><a tngBreadcrumbLink href="#">Home</a></li>',
        '      <li tngBreadcrumbSeparator>/</li>',
        '      <li tngBreadcrumbItem><span aria-disabled="true">Restricted</span></li>',
        '      <li tngBreadcrumbSeparator>/</li>',
        '      <li tngBreadcrumbItem><a tngBreadcrumbLink aria-current="page" href="#">Docs</a></li>',
        '    </ol>',
        '  </nav>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'headless-breadcrumb-examples-current-plain.component.css',
      code: [
        ".headless-breadcrumb-example-list [aria-disabled='true'] {",
        '  color: var(--tng-semantic-foreground-secondary);',
        '  cursor: default;',
        '}',
        '',
        ".headless-breadcrumb-example-list [aria-current='page'] {",
        '  color: var(--tng-semantic-foreground-primary);',
        '  font-weight: 600;',
        '}',
      ].join('\n'),
    },
  ]);

  protected readonly currentTailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'headless-breadcrumb-examples-current-tailwind.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import {",
        "  TngBreadcrumb,",
        "  TngBreadcrumbItem,",
        "  TngBreadcrumbLink,",
        "  TngBreadcrumbList,",
        "  TngBreadcrumbSeparator,",
        "} from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-headless-breadcrumb-examples-current-tailwind',",
        '  standalone: true,',
        '  imports: [',
        '    TngBreadcrumb,',
        '    TngBreadcrumbList,',
        '    TngBreadcrumbItem,',
        '    TngBreadcrumbLink,',
        '    TngBreadcrumbSeparator,',
        '  ],',
        "  templateUrl: './headless-breadcrumb-examples-current-tailwind.component.html',",
        "  styleUrl: './headless-breadcrumb-examples-current-tailwind.component.css',",
        '})',
        'export class HeadlessBreadcrumbExamplesCurrentTailwindComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'headless-breadcrumb-examples-current-tailwind.component.html',
      code: [
        '<div class="rounded-xl border border-slate-300 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-900/60">',
        '  <nav tngBreadcrumb aria-label="Billing path">',
        '    <ol tngBreadcrumbList class="m-0 flex list-none flex-wrap items-center gap-[0.45rem] p-0">',
        '      <li tngBreadcrumbItem><a tngBreadcrumbLink class="text-sky-700 no-underline hover:underline dark:text-sky-300" href="#">Workspace</a></li>',
        '      <li tngBreadcrumbSeparator class="text-slate-400">›</li>',
        '      <li tngBreadcrumbItem><span class="text-slate-500 dark:text-slate-400" aria-disabled="true">Restricted</span></li>',
        '      <li tngBreadcrumbSeparator class="text-slate-400">›</li>',
        '      <li tngBreadcrumbItem><span class="font-semibold text-slate-900 dark:text-slate-100" aria-current="page">Billing</span></li>',
        '    </ol>',
        '  </nav>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'headless-breadcrumb-examples-current-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  public ngOnDestroy(): void {
    this.colorSchemeObserver?.disconnect();
  }
}
