import { DOCUMENT } from '@angular/common';
import { Component, computed, inject, signal, type OnDestroy } from '@angular/core';
import { observeDocsCodeThemeChanges, resolveDocsCodeBlockTheme } from '../../../../../../shared/util';
import { TngListboxDirective, TngOptionDirective } from '@tailng-ui/primitives';
import { type DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import { stackblitzTailwindUrl, stackblitzVanillaUrl } from '../../listbox.util';

interface ListboxOption {
  readonly description: string;
  readonly disabled?: boolean;
  readonly id: string;
  readonly label: string;
}

type ListboxModel = string | readonly string[] | null;

const PRIORITY_OPTIONS: readonly ListboxOption[] = Object.freeze([
  {
    description: 'Regression blockers and ship-stopping accessibility bugs.',
    id: 'critical',
    label: 'Critical',
  },
  {
    description: 'Features required to close the sprint plan.',
    id: 'high',
    label: 'High',
  },
  {
    description: 'Backlog items ready for parallel delivery.',
    id: 'medium',
    label: 'Medium',
  },
  {
    description: 'Long-tail improvements and non-blocking polish.',
    id: 'low',
    label: 'Low',
  },
  {
    description: 'Deferred item for later planning.',
    disabled: true,
    id: 'deferred',
    label: 'Deferred (disabled)',
  },
]);

const CHANNEL_OPTIONS: readonly ListboxOption[] = Object.freeze([
  {
    description: 'Release notes and external announcements.',
    id: 'changelog',
    label: 'Changelog',
  },
  {
    description: 'Public docs synchronization and snippets.',
    id: 'docs',
    label: 'Docs',
  },
  {
    description: 'Internal team status updates.',
    id: 'team',
    label: 'Team updates',
  },
  {
    description: 'Customer success and support queues.',
    id: 'support',
    label: 'Support',
  },
]);

@Component({
  selector: 'app-headless-listbox-examples-page',
  imports: [
    TngListboxDirective,
    TngOptionDirective,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
  ],
  templateUrl: './listbox-examples-page.component.html',
  styleUrl: './listbox-examples-page.component.css',
})
export class HeadlessListboxExamplesPageComponent implements OnDestroy {
  private readonly documentRef = inject(DOCUMENT);
  private readonly optionLabelById = new Map(
    [...PRIORITY_OPTIONS, ...CHANNEL_OPTIONS].map((option) => [option.id, option.label]),
  );
  public readonly codeBlockTheme = signal<'github-dark' | 'github-light'>(
    resolveDocsCodeBlockTheme(this.documentRef),
  );
  private readonly colorSchemeObserver = observeDocsCodeThemeChanges(this.documentRef, this.codeBlockTheme);
  protected readonly stackblitzVanillaUrl = stackblitzVanillaUrl;
  protected readonly stackblitzTailwindUrl = stackblitzTailwindUrl;

  protected readonly priorityOptions = PRIORITY_OPTIONS;
  protected readonly channelOptions = CHANNEL_OPTIONS;

  protected readonly plainValue = signal<readonly string[]>(['medium']);
  protected readonly tailwindValue = signal<readonly string[]>(['low']);

  protected readonly dualPlainChannelValueA = signal<readonly string[]>(['docs']);
  protected readonly dualPlainChannelValueB = signal<readonly string[]>(['team']);
  protected readonly dualTailwindChannelValueA = signal<readonly string[]>(['docs']);
  protected readonly dualTailwindChannelValueB = signal<readonly string[]>(['support']);

  protected readonly plainSummary = computed(() => this.formatSelection(this.plainValue()));
  protected readonly tailwindSummary = computed(() => this.formatSelection(this.tailwindValue()));
  protected readonly dualPlainChannelSummaryA = computed(() =>
    this.formatSelection(this.dualPlainChannelValueA()),
  );
  protected readonly dualPlainChannelSummaryB = computed(() =>
    this.formatSelection(this.dualPlainChannelValueB()),
  );
  protected readonly dualTailwindChannelSummaryA = computed(() =>
    this.formatSelection(this.dualTailwindChannelValueA()),
  );
  protected readonly dualTailwindChannelSummaryB = computed(() =>
    this.formatSelection(this.dualTailwindChannelValueB()),
  );

  protected readonly dualListPlainCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'listbox-examples-dual-handoff-plain-css.component.ts',
      code: [
        "import { Component, computed, signal } from '@angular/core';",
        "import { TngListboxDirective, TngOptionDirective } from '@tailng-ui/primitives';",
        '',
        "type ChannelId = 'changelog' | 'docs' | 'support' | 'team';",
        '',
        'interface ChannelOption {',
        '  readonly description: string;',
        '  readonly id: ChannelId;',
        '  readonly label: string;',
        '}',
        '',
        'const CHANNEL_OPTIONS: readonly ChannelOption[] = Object.freeze([',
        "  { id: 'changelog', label: 'Changelog', description: 'Release notes and external announcements.' },",
        "  { id: 'docs', label: 'Docs', description: 'Public docs synchronization and snippets.' },",
        "  { id: 'team', label: 'Team updates', description: 'Internal team status updates.' },",
        "  { id: 'support', label: 'Support', description: 'Customer success and support queues.' },",
        ']);',
        '',
        'function isChannelId(value: string): value is ChannelId {',
        "  return value === 'changelog' || value === 'docs' || value === 'team' || value === 'support';",
        '}',
        '',
        '@Component({',
        "  selector: 'app-headless-listbox-dual-handoff-plain-css-example',",
        '  standalone: true,',
        '  imports: [TngListboxDirective, TngOptionDirective],',
        "  templateUrl: './listbox-examples-dual-handoff-plain-css.component.html',",
        "  styleUrl: './listbox-examples-dual-handoff-plain-css.component.css',",
        '})',
        'export class HeadlessListboxDualHandoffPlainCssExampleComponent {',
        '  readonly channelOptions = CHANNEL_OPTIONS;',
        "  readonly selectedChannelsA = signal<readonly ChannelId[]>(['docs']);",
        "  readonly selectedChannelsB = signal<readonly ChannelId[]>(['team']);",
        '  readonly selectedSummaryA = computed(() => this.formatSelection(this.selectedChannelsA()));',
        '  readonly selectedSummaryB = computed(() => this.formatSelection(this.selectedChannelsB()));',
        '',
        '  onSelectedChannelsAChange(value: string | readonly string[] | null): void {',
        '    this.selectedChannelsA.set(this.toArray(value));',
        '  }',
        '',
        '  onSelectedChannelsBChange(value: string | readonly string[] | null): void {',
        '    this.selectedChannelsB.set(this.toArray(value));',
        '  }',
        '',
        '  private formatSelection(values: readonly ChannelId[]): string {',
        '    const labels = values',
        '      .map((value) => this.channelOptions.find((option) => option.id === value)?.label)',
        "      .filter((label): label is string => label !== undefined);",
        '',
        "    return labels.length > 0 ? labels.join(', ') : 'none';",
        '  }',
        '',
        '  private toArray(value: string | readonly string[] | null): readonly ChannelId[] {',
        '    if (value === null) {',
        '      return [];',
        '    }',
        '',
        "    const values = typeof value === 'string' ? [value] : value;",
        '    return values.filter(isChannelId);',
        '  }',
        '}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'listbox-examples-dual-handoff-plain-css.component.html',
      code: [
        '<section class="headless-listbox-dual-handoff-example">',
        '  <div class="headless-listbox-dual-handoff-example__grid">',
        '    <section class="headless-listbox-dual-handoff-example__card">',
        '      <h3 class="headless-listbox-dual-handoff-example__title">Publish channels A</h3>',
        '      <div',
        '        tngListbox',
        '        tabindex="0"',
        '        class="headless-listbox-dual-handoff-example__listbox"',
        '        [multiple]="true"',
        '        [value]="selectedChannelsA()"',
        '        (valueChange)="onSelectedChannelsAChange($event)"',
        '      >',
        '        @for (option of channelOptions; track option.id) {',
        '          <div',
        '            tngOption',
        '            class="headless-listbox-dual-handoff-example__option"',
        '            [tngValue]="option.id"',
        '          >',
        '            <p class="headless-listbox-dual-handoff-example__option-title">{{ option.label }}</p>',
        '            <p class="headless-listbox-dual-handoff-example__option-description">{{ option.description }}</p>',
        '          </div>',
        '        }',
        '      </div>',
        '      <p class="headless-listbox-dual-handoff-example__summary">',
        '        Selected: {{ selectedSummaryA() }}',
        '      </p>',
        '    </section>',
        '',
        '    <section class="headless-listbox-dual-handoff-example__card">',
        '      <h3 class="headless-listbox-dual-handoff-example__title">Publish channels B</h3>',
        '      <div',
        '        tngListbox',
        '        tabindex="0"',
        '        class="headless-listbox-dual-handoff-example__listbox"',
        '        [multiple]="true"',
        '        [value]="selectedChannelsB()"',
        '        (valueChange)="onSelectedChannelsBChange($event)"',
        '      >',
        '        @for (option of channelOptions; track option.id) {',
        '          <div',
        '            tngOption',
        '            class="headless-listbox-dual-handoff-example__option"',
        '            [tngValue]="option.id"',
        '          >',
        '            <p class="headless-listbox-dual-handoff-example__option-title">{{ option.label }}</p>',
        '            <p class="headless-listbox-dual-handoff-example__option-description">{{ option.description }}</p>',
        '          </div>',
        '        }',
        '      </div>',
        '      <p class="headless-listbox-dual-handoff-example__summary">',
        '        Selected: {{ selectedSummaryB() }}',
        '      </p>',
        '    </section>',
        '  </div>',
        '</section>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'listbox-examples-dual-handoff-plain-css.component.css',
      code: [
        '.headless-listbox-dual-handoff-example {',
        '  display: grid;',
        '  gap: 1rem;',
        '  color: var(--tng-semantic-foreground-primary, #0f172a);',
        '  color-scheme: light;',
        '}',
        '',
        '.headless-listbox-dual-handoff-example__grid {',
        '  display: grid;',
        '  gap: 1rem;',
        '}',
        '',
        '.headless-listbox-dual-handoff-example__card {',
        '  display: grid;',
        '  gap: 0.75rem;',
        '  min-width: 0;',
        '  padding: 1rem;',
        '  border: 1px solid var(--tng-semantic-border-subtle, #cbd5e1);',
        '  border-radius: 1rem;',
        '  background: var(--tng-semantic-background-surface, #ffffff);',
        '}',
        '',
        '.headless-listbox-dual-handoff-example__title {',
        '  margin: 0;',
        '  font-size: 1rem;',
        '  font-weight: 700;',
        '  color: var(--tng-semantic-foreground-primary, #0f172a);',
        '}',
        '',
        '.headless-listbox-dual-handoff-example__listbox {',
        '  display: grid;',
        '  gap: 0.5rem;',
        '  padding: 0.75rem;',
        '  border: 1px solid var(--tng-semantic-border-subtle, #cbd5e1);',
        '  border-radius: 0.9rem;',
        '  background: var(--tng-semantic-background-canvas, #f8fafc);',
        '  outline: none;',
        '}',
        '',
        '.headless-listbox-dual-handoff-example__listbox:focus {',
        '  border-color: var(--tng-semantic-accent-brand, #2563eb);',
        '  box-shadow: 0 0 0 2px color-mix(in srgb, var(--tng-semantic-accent-brand, #2563eb) 28%, transparent);',
        '}',
        '',
        '.headless-listbox-dual-handoff-example__option {',
        '  display: grid;',
        '  gap: 0.25rem;',
        '  padding: 0.75rem 0.85rem;',
        '  border: 1px solid var(--tng-semantic-border-subtle, #cbd5e1);',
        '  border-radius: 0.8rem;',
        '  background: var(--tng-semantic-background-surface, #ffffff);',
        '  cursor: pointer;',
        '  transition: border-color 120ms ease, background-color 120ms ease;',
        '}',
        '',
        '.headless-listbox-dual-handoff-example__option[data-active] {',
        '  border-color: var(--tng-semantic-accent-brand, #2563eb);',
        '}',
        '',
        '.headless-listbox-dual-handoff-example__option[data-selected] {',
        '  background: color-mix(in srgb, var(--tng-semantic-accent-brand, #2563eb) 15%, white);',
        '}',
        '',
        '.headless-listbox-dual-handoff-example__option-title {',
        '  margin: 0;',
        '  font-size: 0.92rem;',
        '  font-weight: 600;',
        '  color: var(--tng-semantic-foreground-primary, #0f172a);',
        '}',
        '',
        '.headless-listbox-dual-handoff-example__option-description {',
        '  margin: 0;',
        '  font-size: 0.82rem;',
        '  color: var(--tng-semantic-foreground-secondary, #475569);',
        '}',
        '',
        '.headless-listbox-dual-handoff-example__summary {',
        '  margin: 0;',
        '  font-size: 0.82rem;',
        '  color: var(--tng-semantic-foreground-secondary, #475569);',
        '}',
        '',
        '@media (min-width: 64rem) {',
        '  .headless-listbox-dual-handoff-example__grid {',
        '    grid-template-columns: repeat(2, minmax(0, 1fr));',
        '  }',
        '}',
      ].join('\n'),
    },
  ]);

  protected readonly dualListTailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'listbox-examples-dual-handoff-tailwind.component.ts',
      code: [
        "import { Component, computed, signal } from '@angular/core';",
        "import { TngListboxDirective, TngOptionDirective } from '@tailng-ui/primitives';",
        '',
        "type ChannelId = 'changelog' | 'docs' | 'support' | 'team';",
        '',
        'interface ChannelOption {',
        '  readonly description: string;',
        '  readonly id: ChannelId;',
        '  readonly label: string;',
        '}',
        '',
        'const CHANNEL_OPTIONS: readonly ChannelOption[] = Object.freeze([',
        "  { id: 'changelog', label: 'Changelog', description: 'Release notes and external announcements.' },",
        "  { id: 'docs', label: 'Docs', description: 'Public docs synchronization and snippets.' },",
        "  { id: 'team', label: 'Team updates', description: 'Internal team status updates.' },",
        "  { id: 'support', label: 'Support', description: 'Customer success and support queues.' },",
        ']);',
        '',
        'function isChannelId(value: string): value is ChannelId {',
        "  return value === 'changelog' || value === 'docs' || value === 'team' || value === 'support';",
        '}',
        '',
        '@Component({',
        "  selector: 'app-headless-listbox-dual-handoff-tailwind-example',",
        '  standalone: true,',
        '  imports: [TngListboxDirective, TngOptionDirective],',
        "  templateUrl: './listbox-examples-dual-handoff-tailwind.component.html',",
        '})',
        'export class HeadlessListboxDualHandoffTailwindExampleComponent {',
        '  readonly channelOptions = CHANNEL_OPTIONS;',
        "  readonly selectedChannelsA = signal<readonly ChannelId[]>(['docs']);",
        "  readonly selectedChannelsB = signal<readonly ChannelId[]>(['support']);",
        '  readonly selectedSummaryA = computed(() => this.formatSelection(this.selectedChannelsA()));',
        '  readonly selectedSummaryB = computed(() => this.formatSelection(this.selectedChannelsB()));',
        '',
        '  onSelectedChannelsAChange(value: string | readonly string[] | null): void {',
        '    this.selectedChannelsA.set(this.toArray(value));',
        '  }',
        '',
        '  onSelectedChannelsBChange(value: string | readonly string[] | null): void {',
        '    this.selectedChannelsB.set(this.toArray(value));',
        '  }',
        '',
        '  private formatSelection(values: readonly ChannelId[]): string {',
        '    const labels = values',
        '      .map((value) => this.channelOptions.find((option) => option.id === value)?.label)',
        "      .filter((label): label is string => label !== undefined);",
        '',
        "    return labels.length > 0 ? labels.join(', ') : 'none';",
        '  }',
        '',
        '  private toArray(value: string | readonly string[] | null): readonly ChannelId[] {',
        '    if (value === null) {',
        '      return [];',
        '    }',
        '',
        "    const values = typeof value === 'string' ? [value] : value;",
        '    return values.filter(isChannelId);',
        '  }',
        '}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'listbox-examples-dual-handoff-tailwind.component.html',
      code: [
        '<section class="grid gap-4 [color-scheme:light]">',
        '  <div class="grid gap-4 xl:grid-cols-2">',
        '    <section class="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 text-slate-900 shadow-sm">',
        '      <h3 class="m-0 text-base font-semibold text-slate-900">Publish channels A</h3>',
        '      <div',
        '        tngListbox',
        '        tabindex="0"',
        '        class="grid gap-2 rounded-2xl border border-slate-200 bg-slate-50 p-3 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-200"',
        '        [multiple]="true"',
        '        [value]="selectedChannelsA()"',
        '        (valueChange)="onSelectedChannelsAChange($event)"',
        '      >',
        '        @for (option of channelOptions; track option.id) {',
        '          <div',
        '            tngOption',
        '            class="grid gap-1 rounded-xl border border-slate-200 bg-white px-4 py-3 transition data-[active]:border-blue-500 data-[selected]:border-blue-200 data-[selected]:bg-blue-50"',
        '            [tngValue]="option.id"',
        '          >',
        '            <p class="m-0 text-sm font-semibold text-slate-900">{{ option.label }}</p>',
        '            <p class="m-0 text-sm leading-6 text-slate-600">{{ option.description }}</p>',
        '          </div>',
        '        }',
        '      </div>',
        '      <p class="m-0 text-xs text-slate-600">Selected: {{ selectedSummaryA() }}</p>',
        '    </section>',
        '',
        '    <section class="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 text-slate-900 shadow-sm">',
        '      <h3 class="m-0 text-base font-semibold text-slate-900">Publish channels B</h3>',
        '      <div',
        '        tngListbox',
        '        tabindex="0"',
        '        class="grid gap-2 rounded-2xl border border-slate-200 bg-slate-50 p-3 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-200"',
        '        [multiple]="true"',
        '        [value]="selectedChannelsB()"',
        '        (valueChange)="onSelectedChannelsBChange($event)"',
        '      >',
        '        @for (option of channelOptions; track option.id) {',
        '          <div',
        '            tngOption',
        '            class="grid gap-1 rounded-xl border border-slate-200 bg-white px-4 py-3 transition data-[active]:border-blue-500 data-[selected]:border-blue-200 data-[selected]:bg-blue-50"',
        '            [tngValue]="option.id"',
        '          >',
        '            <p class="m-0 text-sm font-semibold text-slate-900">{{ option.label }}</p>',
        '            <p class="m-0 text-sm leading-6 text-slate-600">{{ option.description }}</p>',
        '          </div>',
        '        }',
        '      </div>',
        '      <p class="m-0 text-xs text-slate-600">Selected: {{ selectedSummaryB() }}</p>',
        '    </section>',
        '  </div>',
        '</section>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'listbox-examples-dual-handoff-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  protected readonly plainCssCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'listbox-examples-plain-css.component.ts',
      code: [
        "import { Component, computed, signal } from '@angular/core';",
        "import { TngListboxDirective, TngOptionDirective } from '@tailng-ui/primitives';",
        '',
        "type PriorityId = 'critical' | 'high' | 'medium' | 'low' | 'deferred';",
        '',
        'interface PriorityOption {',
        '  readonly description: string;',
        '  readonly disabled?: boolean;',
        '  readonly id: PriorityId;',
        '  readonly label: string;',
        '}',
        '',
        'const PRIORITY_OPTIONS: readonly PriorityOption[] = Object.freeze([',
        "  { id: 'critical', label: 'Critical', description: 'Regression blockers and ship-stopping accessibility bugs.' },",
        "  { id: 'high', label: 'High', description: 'Features required to close the sprint plan.' },",
        "  { id: 'medium', label: 'Medium', description: 'Backlog items ready for parallel delivery.' },",
        "  { id: 'low', label: 'Low', description: 'Long-tail improvements and non-blocking polish.' },",
        "  { id: 'deferred', label: 'Deferred (disabled)', description: 'Deferred item for later planning.', disabled: true },",
        ']);',
        '',
        'function isPriorityId(value: string): value is PriorityId {',
        "  return value === 'critical' || value === 'high' || value === 'medium' || value === 'low' || value === 'deferred';",
        '}',
        '',
        '@Component({',
        "  selector: 'app-headless-listbox-priority-plain-css-example',",
        '  standalone: true,',
        '  imports: [TngListboxDirective, TngOptionDirective],',
        "  templateUrl: './listbox-examples-plain-css.component.html',",
        "  styleUrl: './listbox-examples-plain-css.component.css',",
        '})',
        'export class HeadlessListboxPriorityPlainCssExampleComponent {',
        '  readonly priorityOptions = PRIORITY_OPTIONS;',
        "  readonly selectedPriorities = signal<readonly PriorityId[]>(['medium']);",
        '  readonly selectedSummary = computed(() => {',
        '    const labels = this.selectedPriorities()',
        '      .map((value) => this.priorityOptions.find((option) => option.id === value)?.label)',
        "      .filter((label): label is string => label !== undefined);",
        '',
        "    return labels.length > 0 ? labels.join(', ') : 'none';",
        '  });',
        '',
        '  onSelectedPrioritiesChange(value: string | readonly string[] | null): void {',
        '    this.selectedPriorities.set(this.toArray(value));',
        '  }',
        '',
        '  private toArray(value: string | readonly string[] | null): readonly PriorityId[] {',
        '    if (value === null) {',
        '      return [];',
        '    }',
        '',
        "    const values = typeof value === 'string' ? [value] : value;",
        '    return values.filter(isPriorityId);',
        '  }',
        '}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'listbox-examples-plain-css.component.html',
      code: [
        '<section class="headless-listbox-priority-example">',
        '  <div',
        '    tngListbox',
        '    tabindex="0"',
        '    class="headless-listbox-priority-example__listbox"',
        '    [multiple]="true"',
        '    [value]="selectedPriorities()"',
        '    (valueChange)="onSelectedPrioritiesChange($event)"',
        '  >',
        '    @for (option of priorityOptions; track option.id) {',
        '      <div',
        '        tngOption',
        '        class="headless-listbox-priority-example__option"',
        '        [tngValue]="option.id"',
        '        [disabled]="option.disabled === true"',
        '      >',
        '        <p class="headless-listbox-priority-example__title">{{ option.label }}</p>',
        '        <p class="headless-listbox-priority-example__description">{{ option.description }}</p>',
        '      </div>',
        '    }',
        '  </div>',
        '  <p class="headless-listbox-priority-example__summary">',
        '    Selected: {{ selectedSummary() }}',
        '  </p>',
        '</section>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'listbox-examples-plain-css.component.css',
      code: [
        '.headless-listbox-priority-example {',
        '  display: grid;',
        '  gap: 0.75rem;',
        '  inline-size: min(100%, 30rem);',
        '  margin-inline: auto;',
        '  padding: 1rem;',
        '  border: 1px solid var(--tng-semantic-border-subtle, #cbd5e1);',
        '  border-radius: 1rem;',
        '  background: var(--tng-semantic-background-surface, #ffffff);',
        '  color: var(--tng-semantic-foreground-primary, #0f172a);',
        '  color-scheme: light;',
        '}',
        '',
        '.headless-listbox-priority-example__listbox {',
        '  display: grid;',
        '  gap: 0.5rem;',
        '  padding: 0.75rem;',
        '  border: 1px solid var(--tng-semantic-border-subtle, #cbd5e1);',
        '  border-radius: 0.85rem;',
        '  background: var(--tng-semantic-background-canvas, #f8fafc);',
        '  outline: none;',
        '}',
        '',
        '.headless-listbox-priority-example__listbox:focus {',
        '  border-color: var(--tng-semantic-accent-brand, #2563eb);',
        '  box-shadow: 0 0 0 2px color-mix(in srgb, var(--tng-semantic-accent-brand, #2563eb) 28%, transparent);',
        '}',
        '',
        '.headless-listbox-priority-example__option {',
        '  display: grid;',
        '  gap: 0.25rem;',
        '  padding: 0.7rem 0.8rem;',
        '  border: 1px solid var(--tng-semantic-border-subtle, #cbd5e1);',
        '  border-radius: 0.75rem;',
        '  background: var(--tng-semantic-background-surface, #ffffff);',
        '  cursor: pointer;',
        '  transition:',
        '    border-color 120ms ease,',
        '    background-color 120ms ease,',
        '    opacity 120ms ease;',
        '}',
        '',
        '.headless-listbox-priority-example__option[data-active] {',
        '  border-color: var(--tng-semantic-accent-brand, #2563eb);',
        '}',
        '',
        '.headless-listbox-priority-example__option[data-selected] {',
        '  background: color-mix(in srgb, var(--tng-semantic-accent-brand, #2563eb) 15%, white);',
        '}',
        '',
        '.headless-listbox-priority-example__option[data-disabled] {',
        '  cursor: not-allowed;',
        '  opacity: 0.56;',
        '}',
        '',
        '.headless-listbox-priority-example__title {',
        '  margin: 0;',
        '  font-size: 0.92rem;',
        '  font-weight: 600;',
        '  color: var(--tng-semantic-foreground-primary, #0f172a);',
        '}',
        '',
        '.headless-listbox-priority-example__description {',
        '  margin: 0;',
        '  font-size: 0.82rem;',
        '  color: var(--tng-semantic-foreground-secondary, #475569);',
        '}',
        '',
        '.headless-listbox-priority-example__summary {',
        '  margin: 0;',
        '  font-size: 0.82rem;',
        '  color: var(--tng-semantic-foreground-secondary, #475569);',
        '}',
      ].join('\n'),
    },
  ]);

  protected readonly tailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'listbox-examples-tailwind.component.ts',
      code: [
        "import { Component, computed, signal } from '@angular/core';",
        "import { TngListboxDirective, TngOptionDirective } from '@tailng-ui/primitives';",
        '',
        "type PriorityId = 'critical' | 'high' | 'medium' | 'low' | 'deferred';",
        '',
        'interface PriorityOption {',
        '  readonly description: string;',
        '  readonly disabled?: boolean;',
        '  readonly id: PriorityId;',
        '  readonly label: string;',
        '}',
        '',
        'const PRIORITY_OPTIONS: readonly PriorityOption[] = Object.freeze([',
        "  { id: 'critical', label: 'Critical', description: 'Regression blockers and ship-stopping accessibility bugs.' },",
        "  { id: 'high', label: 'High', description: 'Features required to close the sprint plan.' },",
        "  { id: 'medium', label: 'Medium', description: 'Backlog items ready for parallel delivery.' },",
        "  { id: 'low', label: 'Low', description: 'Long-tail improvements and non-blocking polish.' },",
        "  { id: 'deferred', label: 'Deferred (disabled)', description: 'Deferred item for later planning.', disabled: true },",
        ']);',
        '',
        'function isPriorityId(value: string): value is PriorityId {',
        "  return value === 'critical' || value === 'high' || value === 'medium' || value === 'low' || value === 'deferred';",
        '}',
        '',
        '@Component({',
        "  selector: 'app-headless-listbox-priority-tailwind-example',",
        '  standalone: true,',
        '  imports: [TngListboxDirective, TngOptionDirective],',
        "  templateUrl: './listbox-examples-tailwind.component.html',",
        '})',
        'export class HeadlessListboxPriorityTailwindExampleComponent {',
        '  readonly priorityOptions = PRIORITY_OPTIONS;',
        "  readonly selectedPriorities = signal<readonly PriorityId[]>(['low']);",
        '  readonly selectedSummary = computed(() => {',
        '    const labels = this.selectedPriorities()',
        '      .map((value) => this.priorityOptions.find((option) => option.id === value)?.label)',
        "      .filter((label): label is string => label !== undefined);",
        '',
        "    return labels.length > 0 ? labels.join(', ') : 'none';",
        '  });',
        '',
        '  onSelectedPrioritiesChange(value: string | readonly string[] | null): void {',
        '    this.selectedPriorities.set(this.toArray(value));',
        '  }',
        '',
        '  private toArray(value: string | readonly string[] | null): readonly PriorityId[] {',
        '    if (value === null) {',
        '      return [];',
        '    }',
        '',
        "    const values = typeof value === 'string' ? [value] : value;",
        '    return values.filter(isPriorityId);',
        '  }',
        '}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'listbox-examples-tailwind.component.html',
      code: [
        '<section class="grid w-full max-w-[30rem] gap-3 rounded-xl border border-slate-200 bg-white p-4 text-slate-900 shadow-sm [color-scheme:light]">',
        '  <div',
        '    tngListbox',
        '    tabindex="0"',
        '    class="grid gap-2 rounded-xl border border-slate-200 bg-slate-50 p-3 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-200"',
        '    [multiple]="true"',
        '    [value]="selectedPriorities()"',
        '    (valueChange)="onSelectedPrioritiesChange($event)"',
        '  >',
        '    @for (option of priorityOptions; track option.id) {',
        '      <div',
        '        tngOption',
        '        class="grid gap-1 rounded-lg border border-slate-200 bg-white px-3 py-2.5 transition data-[active]:border-blue-500 data-[selected]:border-blue-200 data-[selected]:bg-blue-50 data-[disabled]:cursor-not-allowed data-[disabled]:opacity-60"',
        '        [tngValue]="option.id"',
        '        [disabled]="option.disabled === true"',
        '      >',
        '        <p class="m-0 text-sm font-semibold text-slate-900">{{ option.label }}</p>',
        '        <p class="m-0 text-sm leading-6 text-slate-600">{{ option.description }}</p>',
        '      </div>',
        '    }',
        '  </div>',
        '  <p class="m-0 text-xs text-slate-600">Selected: {{ selectedSummary() }}</p>',
        '</section>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'listbox-examples-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  protected onPlainValueChange(value: ListboxModel): void {
    this.plainValue.set(this.toArray(value));
  }

  protected onTailwindValueChange(value: ListboxModel): void {
    this.tailwindValue.set(this.toArray(value));
  }

  protected onDualPlainChannelAValueChange(value: ListboxModel): void {
    this.dualPlainChannelValueA.set(this.toArray(value));
  }

  protected onDualPlainChannelBValueChange(value: ListboxModel): void {
    this.dualPlainChannelValueB.set(this.toArray(value));
  }

  protected onDualTailwindChannelAValueChange(value: ListboxModel): void {
    this.dualTailwindChannelValueA.set(this.toArray(value));
  }

  protected onDualTailwindChannelBValueChange(value: ListboxModel): void {
    this.dualTailwindChannelValueB.set(this.toArray(value));
  }

  public ngOnDestroy(): void {
    this.colorSchemeObserver?.disconnect();
  }

  private toArray(value: ListboxModel): readonly string[] {
    if (value === null) {
      return [];
    }

    if (typeof value === 'string') {
      return [value];
    }

    return value;
  }

  private formatSelection(values: readonly string[]): string {
    const labels = values
      .map((value) => this.optionLabelById.get(value))
      .filter((label): label is string => label !== undefined);
    if (labels.length === 0) {
      return 'none';
    }

    return labels.join(', ');
  }

}
