import { DOCUMENT } from '@angular/common';
import {
  Component,
  inject,
  signal,
  type OnDestroy,
} from '@angular/core';
import { TngCodeBlockComponent } from '@tailng-ui/components';
import { TngIcon } from '@tailng-ui/icons';
import {
  bindTngDatepicker,
  createDatepickerController,
  TngDatepickerDayCell,
  TngDatepickerDayGrid,
  TngDatepickerHost,
  TngDatepickerInput,
  TngDatepickerMonthGrid,
  TngDatepickerMonthOption,
  TngDatepickerNextButton,
  TngDatepickerOverlay,
  TngDatepickerPeriodButton,
  TngDatepickerPrevButton,
  TngDatepickerTrigger,
  TngDatepickerYearOption,
  TngDatepickerYearGrid,
} from '@tailng-ui/primitives';
import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import {
  observeDocsCodeThemeChanges,
  resolveDocsCodeBlockTheme,
} from '../../../../../../shared/util';
import { stackblitzTailwindUrl, stackblitzVanillaUrl } from '../../datepicker.util';

function createCodeTabs(
  baseName: string,
  tsCode: string,
  htmlCode: string,
  cssCode: string,
): readonly DocsExampleCodeTab[] {
  return Object.freeze([
    { value: 'ts', label: 'TS', language: 'ts', title: `${baseName}.component.ts`, code: tsCode },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: `${baseName}.component.html`,
      code: htmlCode,
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: `${baseName}.component.css`,
      code: cssCode,
    },
  ]);
}

const headlessSharedCssCode = [
  '.headless-datepicker-demo {',
  '  display: block;',
  '  inline-size: 18.5rem;',
  '  max-inline-size: 100%;',
  '}',
  '.headless-datepicker-field {',
  '  display: grid;',
  '  gap: 0.2rem;',
  '}',
  '.headless-datepicker-anchor { position: relative; }',
  '.docs-headless-datepicker-overview-demo {',
  '  color-scheme: light;',
  '  --tng-datepicker-radius: 1.1rem;',
  '  --tng-datepicker-field-height: 2.95rem;',
  '  --tng-datepicker-overlay-gap: 0.56rem;',
  '  --tng-datepicker-day-cell-size: 2.2rem;',
  '  --tng-datepicker-picker-cell-size: 2.3rem;',
  '  --tng-datepicker-grid-gap: clamp(0.14rem, 1.15%, 0.28rem);',
  '  --tng-datepicker-inline-gap: 0.36rem;',
  '  --tng-datepicker-overlay-padding: 0.72rem;',
  '  --tng-datepicker-nav-size: 1.95rem;',
  '  --tng-datepicker-shadow:',
  '    0 22px 40px rgba(15, 23, 42, 0.14),',
  '    0 10px 18px rgba(15, 23, 42, 0.08);',
  '}',
  '.headless-datepicker-shell {',
  '  display: flex;',
  '  align-items: stretch;',
  '  min-inline-size: 0;',
  '  inline-size: 100%;',
  '  min-height: var(--tng-datepicker-field-height);',
  '  overflow: hidden;',
  '  box-sizing: border-box;',
  '  border: 1px solid color-mix(in srgb, var(--tng-datepicker-border) 84%, var(--tng-datepicker-canvas) 16%);',
  '  border-radius: var(--tng-datepicker-radius);',
  '  background:',
  '    linear-gradient(',
  '      180deg,',
  '      color-mix(in srgb, var(--tng-datepicker-canvas) 58%, var(--tng-datepicker-surface) 42%),',
  '      color-mix(in srgb, var(--tng-datepicker-canvas) 74%, var(--tng-datepicker-surface) 26%)',
  '    );',
  '  box-shadow: 0 1px 2px rgba(15, 23, 42, 0.04);',
  '  transition:',
  '    border-color 150ms ease,',
  '    box-shadow 150ms ease,',
  '    background-color 150ms ease;',
  '}',
  '.headless-datepicker-shell[data-open="true"] {',
  '  border-color: color-mix(in srgb, var(--tng-datepicker-brand) 72%, var(--tng-datepicker-border) 28%);',
  '  box-shadow: var(--tng-datepicker-focus-shadow);',
  '}',
  '.headless-datepicker-shell:focus-within {',
  '  border-color: color-mix(in srgb, var(--tng-datepicker-brand) 62%, var(--tng-datepicker-border) 38%);',
  '  box-shadow: var(--tng-datepicker-focus-shadow);',
  '}',
  '.headless-datepicker-shell[data-invalid="true"] {',
  '  border-color: color-mix(in srgb, #dc2626 70%, var(--tng-datepicker-border) 30%);',
  '  box-shadow: 0 0 0 3px rgba(220, 38, 38, 0.14);',
  '}',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-input-shell"] {',
  '  box-shadow: 0 1px 2px rgba(15, 23, 42, 0.04);',
  '}',
  '.headless-datepicker-input {',
  '  flex: 1 1 auto;',
  '  min-inline-size: 0;',
  '  min-height: 100%;',
  '  box-sizing: border-box;',
  '  border: 0;',
  '  outline: none;',
  '  background: transparent;',
  '  box-shadow: none;',
  '  color: var(--tng-datepicker-fg);',
  '  font: inherit;',
  '  font-size: 0.98rem;',
  '  line-height: 1.35;',
  '  padding: 0.72rem 0.96rem;',
  '  appearance: none;',
  '  -webkit-appearance: none;',
  '}',
  '.headless-datepicker-input::placeholder {',
  '  color: color-mix(in srgb, var(--tng-datepicker-muted) 82%, transparent);',
  '  opacity: 1;',
  '}',
  '.headless-datepicker-input:focus,',
  '.headless-datepicker-input:focus-visible {',
  '  outline: none;',
  '  box-shadow: none;',
  '}',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-input"],',
  '.headless-datepicker-input {',
  '  caret-color: var(--tng-datepicker-brand);',
  '  font-weight: 600;',
  '  letter-spacing: 0.01em;',
  '}',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-input"]::placeholder,',
  '.headless-datepicker-input::placeholder {',
  '  font-weight: 500;',
  '}',
  '.headless-datepicker-trigger {',
  '  flex: 0 0 auto;',
  '  min-width: calc(var(--tng-datepicker-nav-size) + 1.02rem);',
  '  padding-inline: 0.78rem;',
  '  display: inline-flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  gap: 0.34rem;',
  '  border: 0;',
  '  border-inline-start: 1px solid color-mix(in srgb, var(--tng-datepicker-border) 72%, var(--tng-datepicker-canvas) 28%);',
  '  background:',
  '    linear-gradient(',
  '      180deg,',
  '      color-mix(in srgb, var(--tng-datepicker-brand) 3%, var(--tng-datepicker-canvas) 97%),',
  '      color-mix(in srgb, var(--tng-datepicker-brand) 5%, var(--tng-datepicker-surface) 95%)',
  '    );',
  '  color: var(--tng-datepicker-fg);',
  '  cursor: pointer;',
  '  font: inherit;',
  '  appearance: none;',
  '  -webkit-appearance: none;',
  '  transition:',
  '    background-color 150ms ease,',
  '    color 150ms ease;',
  '}',
  '.headless-datepicker-trigger:hover {',
  '  background: color-mix(in srgb, var(--tng-datepicker-brand) 9%, var(--tng-datepicker-surface));',
  '}',
  '.headless-datepicker-trigger:focus,',
  '.headless-datepicker-trigger:focus-visible {',
  '  outline: none;',
  '  box-shadow: none;',
  '  background: color-mix(in srgb, var(--tng-datepicker-brand) 9%, var(--tng-datepicker-surface));',
  '}',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-trigger"] {',
  '  min-width: calc(var(--tng-datepicker-nav-size) + 1.02rem);',
  '  padding-inline: 0.78rem;',
  '}',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-overlay"] {',
  '  inline-size: min(20rem, calc(100vw - 2rem));',
  '}',
  '.headless-datepicker-overlay {',
  '  box-sizing: border-box;',
  '  display: grid;',
  '  gap: 0.68rem;',
  '  inline-size: min(20rem, calc(100vw - 2rem));',
  '  border: 1px solid color-mix(in srgb, var(--tng-datepicker-border) 86%, var(--tng-datepicker-canvas) 14%);',
  '  border-radius: calc(var(--tng-datepicker-radius) + 0.18rem);',
  '  background:',
  '    linear-gradient(',
  '      180deg,',
  '      color-mix(in srgb, var(--tng-datepicker-surface) 95%, var(--tng-datepicker-canvas) 5%),',
  '      color-mix(in srgb, var(--tng-datepicker-surface) 98%, var(--tng-datepicker-canvas) 2%)',
  '    );',
  '  color: var(--tng-datepicker-fg);',
  '  padding: var(--tng-datepicker-overlay-padding);',
  '  box-shadow: var(--tng-datepicker-shadow);',
  '}',
  '.headless-datepicker-trigger,',
  '.headless-datepicker-nav,',
  '.headless-datepicker-period,',
  '.headless-datepicker-cell,',
  '.headless-datepicker-picker-cell {',
  '  font: inherit;',
  '}',
  '.headless-datepicker-trigger-icon {',
  '  width: 1.05rem;',
  '  height: 1.05rem;',
  '}',
  '.headless-datepicker-trigger-chevron,',
  '.headless-datepicker-period-chevron {',
  '  font-size: 0.68rem;',
  '  line-height: 1;',
  '  color: var(--tng-datepicker-muted);',
  '}',
  '.headless-datepicker-header {',
  '  display: grid;',
  '  gap: 0.5rem;',
  '}',
  '.headless-datepicker-header-row {',
  '  display: grid;',
  '  grid-template-columns: var(--tng-datepicker-nav-size) minmax(0, 1fr) var(--tng-datepicker-nav-size);',
  '  gap: 0.34rem;',
  '  align-items: center;',
  '}',
  '.headless-datepicker-period {',
  '  align-items: center;',
  '  display: inline-flex;',
  '  gap: 0.24rem;',
  '  justify-content: center;',
  '  min-inline-size: 0;',
  '  width: 100%;',
  '}',
  '.headless-datepicker-period-title {',
  '  overflow: hidden;',
  '  text-overflow: ellipsis;',
  '  white-space: nowrap;',
  '}',
  '.headless-datepicker-nav {',
  '  inline-size: var(--tng-datepicker-nav-size);',
  '  min-height: var(--tng-datepicker-nav-size);',
  '  padding: 0;',
  '  font-size: 1.1rem;',
  '  line-height: 1;',
  '}',
  '.headless-datepicker-period {',
  '  min-height: var(--tng-datepicker-nav-size);',
  '  padding-inline: 0.72rem;',
  '  font-weight: 600;',
  '}',
  '.headless-datepicker-nav,',
  '.headless-datepicker-period,',
  '.headless-datepicker-cell,',
  '.headless-datepicker-picker-cell {',
  '  box-sizing: border-box;',
  '  border: 1px solid color-mix(in srgb, var(--tng-datepicker-border) 84%, var(--tng-datepicker-canvas) 16%);',
  '  border-radius: 0.82rem;',
  '  background: color-mix(in srgb, var(--tng-datepicker-canvas) 78%, var(--tng-datepicker-surface) 22%);',
  '  color: var(--tng-datepicker-fg);',
  '  cursor: pointer;',
  '  appearance: none;',
  '  -webkit-appearance: none;',
  '  transition:',
  '    border-color 150ms ease,',
  '    box-shadow 150ms ease,',
  '    background-color 150ms ease,',
  '    color 150ms ease;',
  '}',
  '.headless-datepicker-nav:hover,',
  '.headless-datepicker-period:hover {',
  '  background: color-mix(in srgb, var(--tng-datepicker-brand) 7%, var(--tng-datepicker-surface));',
  '}',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-nav-button"] {',
  '  inline-size: var(--tng-datepicker-nav-size);',
  '  min-height: var(--tng-datepicker-nav-size);',
  '  padding: 0;',
  '}',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-period-button"] {',
  '  min-height: var(--tng-datepicker-nav-size);',
  '  padding-inline: 0.72rem;',
  '}',
  '.headless-datepicker-weekdays,',
  '.headless-datepicker-day-grid {',
  '  display: grid;',
  '  grid-template-columns: repeat(7, minmax(0, 1fr));',
  '  gap: var(--tng-datepicker-grid-gap);',
  '}',
  '.headless-datepicker-picker-grid {',
  '  display: grid;',
  '  grid-template-columns: repeat(4, minmax(0, 1fr));',
  '  gap: var(--tng-datepicker-grid-gap);',
  '}',
  '.headless-datepicker-cell {',
  '  min-height: var(--tng-datepicker-day-cell-size);',
  '}',
  '.headless-datepicker-picker-cell {',
  '  min-height: var(--tng-datepicker-picker-cell-size);',
  '}',
  '.headless-datepicker-weekdays [data-slot="datepicker-weekday"] { text-align: center; }',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-weekday"],',
  '.headless-datepicker-weekdays [data-slot="datepicker-weekday"] {',
  '  color: color-mix(in srgb, var(--tng-datepicker-muted) 92%, white 8%);',
  '  font-size: 0.68rem;',
  '  font-weight: 600;',
  '  letter-spacing: 0.02em;',
  '}',
  '.headless-datepicker-cell[data-active],',
  '.headless-datepicker-picker-cell[data-active],',
  '.headless-datepicker-overlay [data-slot="datepicker-month"][data-active],',
  '.headless-datepicker-overlay [data-slot="datepicker-year"][data-active] {',
  '  border-color: color-mix(in srgb, var(--tng-datepicker-brand) 36%, var(--tng-datepicker-border) 64%);',
  '  background: color-mix(in srgb, var(--tng-datepicker-brand) 9%, var(--tng-datepicker-surface) 91%);',
  '  box-shadow: 0 0 0 1px color-mix(in srgb, var(--tng-datepicker-brand) 14%, transparent);',
  '}',
  '.headless-datepicker-cell[data-selected],',
  '.headless-datepicker-picker-cell[data-selected],',
  '.headless-datepicker-overlay [data-slot="datepicker-month"][data-selected],',
  '.headless-datepicker-overlay [data-slot="datepicker-year"][data-selected] {',
  '  border-color: color-mix(in srgb, var(--tng-datepicker-brand) 44%, var(--tng-datepicker-border) 56%);',
  '  background: color-mix(in srgb, var(--tng-datepicker-brand) 18%, var(--tng-datepicker-canvas) 82%);',
  '  color: color-mix(in srgb, var(--tng-datepicker-brand) 78%, #0f172a 22%);',
  '}',
  '.headless-datepicker-cell[data-selected][data-active],',
  '.headless-datepicker-picker-cell[data-selected][data-active],',
  '.headless-datepicker-overlay [data-slot="datepicker-month"][data-selected][data-active],',
  '.headless-datepicker-overlay [data-slot="datepicker-year"][data-selected][data-active] {',
  '  border-color: color-mix(in srgb, var(--tng-datepicker-brand) 62%, var(--tng-datepicker-border) 38%);',
  '  background: color-mix(in srgb, var(--tng-datepicker-brand) 24%, var(--tng-datepicker-canvas) 76%);',
  '  box-shadow:',
  '    inset 0 1px 0 rgba(255, 255, 255, 0.8),',
  '    0 0 0 1px color-mix(in srgb, var(--tng-datepicker-brand) 18%, transparent);',
  '}',
  '.headless-datepicker-cell[aria-current="date"]:not([data-selected]) {',
  '  border-color: color-mix(in srgb, var(--tng-datepicker-brand) 30%, var(--tng-datepicker-border) 70%);',
  '  box-shadow: inset 0 0 0 1px color-mix(in srgb, var(--tng-datepicker-brand) 12%, transparent);',
  '}',
  '.headless-datepicker-cell:not([data-in-month]) {',
  '  color: color-mix(in srgb, var(--tng-datepicker-muted) 84%, white 16%);',
  '  opacity: 0.58;',
  '}',
  '.headless-datepicker-cell[data-disabled],',
  '.headless-datepicker-picker-cell[data-disabled],',
  '.headless-datepicker-overlay [data-slot="datepicker-month"][data-disabled],',
  '.headless-datepicker-overlay [data-slot="datepicker-year"][data-disabled] {',
  '  box-shadow: none;',
  '  opacity: 0.48;',
  '}',
  '',
].join('\n');

function createHeadlessTsCode(className: string): string {
  return [
    "import { Component, type OnDestroy } from '@angular/core';",
    "import { TngIcon } from '@tailng-ui/icons';",
    'import {',
    '  bindTngDatepicker,',
    '  createDatepickerController,',
    '  TngDatepickerDayCell,',
    '  TngDatepickerDayGrid,',
    '  TngDatepickerHost,',
    '  TngDatepickerInput,',
    '  TngDatepickerMonthGrid,',
    '  TngDatepickerMonthOption,',
    '  TngDatepickerNextButton,',
    '  TngDatepickerOverlay,',
    '  TngDatepickerPeriodButton,',
    '  TngDatepickerPrevButton,',
    '  TngDatepickerTrigger,',
    '  TngDatepickerYearOption,',
    '  TngDatepickerYearGrid,',
    "} from '@tailng-ui/primitives';",
    '',
    '@Component({',
    '  standalone: true,',
    '  imports: [',
    '    TngIcon,',
    '    TngDatepickerHost,',
    '    TngDatepickerOverlay,',
    '    TngDatepickerInput,',
    '    TngDatepickerTrigger,',
    '    TngDatepickerPrevButton,',
    '    TngDatepickerPeriodButton,',
    '    TngDatepickerNextButton,',
    '    TngDatepickerDayGrid,',
    '    TngDatepickerDayCell,',
    '    TngDatepickerMonthGrid,',
    '    TngDatepickerMonthOption,',
    '    TngDatepickerYearGrid,',
    '    TngDatepickerYearOption,',
    '  ],',
    `  templateUrl: './${className}.component.html',`,
    `  styleUrl: './${className}.component.css',`,
    '})',
    `export class ${toPascalCase(className)}Component implements OnDestroy {`,
    '  protected readonly controller = createDatepickerController<Date>({',
    "    value: '2024-04-22',",
    "    today: '2024-04-18',",
    "    minDate: '2024-04-01',",
    "    maxDate: '2026-03-31',",
    '    closeOnSelect: true,',
    '    trapFocus: true,',
    '    showOutsideDays: true,',
    '  });',
    '',
    '  protected readonly datepicker = bindTngDatepicker(this.controller);',
    '',
    '  public ngOnDestroy(): void {',
    '    this.controller.destroy();',
    '  }',
    '}',
    '',
  ].join('\n');
}

function createHeadlessHtmlCode(
  containerOpen: string,
  labelLine: string,
  demoClassName: string,
  containerClose: string,
): string {
  return [
    containerOpen,
    `  ${labelLine}`,
    `  <section class="headless-datepicker-demo docs-headless-datepicker-overview-demo ${demoClassName}" [tngDatepickerHost]="controller">`,
    `    <div class="headless-datepicker-field" data-slot="datepicker-field">`,
    `      <div #anchorShell class="headless-datepicker-anchor">`,
    `        <div`,
    `          class="headless-datepicker-shell"`,
    `          data-slot="datepicker-input-shell"`,
    `          [attr.data-invalid]="datepicker.outputs().validationError !== null ? 'true' : null"`,
    `          [attr.data-open]="datepicker.outputs().getTriggerAttributes()['data-open']"`,
    `        >`,
    `          <input`,
    `            class="headless-datepicker-input"`,
    `            [tngDatepickerInput]="controller"`,
    `            type="text"`,
    `            inputmode="numeric"`,
    `            placeholder="MM-DD-YYYY"`,
    `            aria-label="Overview invoice date"`,
    `          />`,
    ``,
    `          <button`,
    `            type="button"`,
    `            class="headless-datepicker-trigger"`,
    `            [tngDatepickerTrigger]="controller"`,
    `            tabindex="-1"`,
    `            aria-label="Open calendar"`,
    `          >`,
    `            <tng-icon icon="calendar-days" class="headless-datepicker-trigger-icon" />`,
    `            <span class="headless-datepicker-trigger-chevron" aria-hidden="true">▾</span>`,
    `          </button>`,
    `        </div>`,
    ``,
    `        <section`,
    `          [tngDatepickerOverlay]="controller"`,
    `          [tngDatepickerOverlayAnchor]="anchorShell"`,
    `          class="headless-datepicker-overlay"`,
    `        >`,
    `          <header class="headless-datepicker-header" data-slot="datepicker-header">`,
    `            <div class="headless-datepicker-header-row">`,
    `              <button type="button" class="headless-datepicker-nav" [tngDatepickerPrevButton]="controller">‹</button>`,
    `              <button`,
    `                type="button"`,
    `                class="headless-datepicker-period"`,
    `                [tngDatepickerPeriodButton]="controller"`,
    `              >`,
    `                <span class="headless-datepicker-period-title">{{ datepicker.periodLabel() }}</span>`,
    `                @if (datepicker.outputs().view !== 'year') {`,
    `                  <span class="headless-datepicker-period-chevron" aria-hidden="true">▾</span>`,
    `                }`,
    `              </button>`,
    `              <button type="button" class="headless-datepicker-nav" [tngDatepickerNextButton]="controller">›</button>`,
    `            </div>`,
    `          </header>`,
    ``,
    `          @if (datepicker.outputs().view === 'day') {`,
    `            <div class="headless-datepicker-weekdays" data-slot="datepicker-weekdays" aria-hidden="true">`,
    `              @for (label of datepicker.outputs().weekdayLabels; track label) {`,
    `                <span data-slot="datepicker-weekday">{{ label }}</span>`,
    `              }`,
    `            </div>`,
    ``,
    `            <div`,
    `              class="headless-datepicker-day-grid"`,
    `              [tngDatepickerDayGrid]="controller"`,
    `            >`,
    `              @for (cell of datepicker.outputs().cells; track cell.id) {`,
    `                <button`,
    `                  type="button"`,
    `                  class="headless-datepicker-cell"`,
    `                  [tngDatepickerDayCell]="cell"`,
    `                >`,
    `                  {{ cell.label }}`,
    `                </button>`,
    `              }`,
    `            </div>`,
    `          }`,
    ``,
    `          @if (datepicker.outputs().view === 'month') {`,
    `            <div class="headless-datepicker-picker-grid" [tngDatepickerMonthGrid]="controller">`,
    `              @for (option of datepicker.outputs().monthOptions; track option.id) {`,
    `                <button`,
    `                  type="button"`,
    `                  class="headless-datepicker-picker-cell"`,
    `                  [tngDatepickerMonthOption]="option"`,
    `                >`,
    `                  {{ option.label }}`,
    `                </button>`,
    `              }`,
    `            </div>`,
    `          }`,
    ``,
    `          @if (datepicker.outputs().view === 'year') {`,
    `            <div class="headless-datepicker-picker-grid" [tngDatepickerYearGrid]="controller">`,
    `              @for (option of datepicker.outputs().yearOptions; track option.id) {`,
    `                <button`,
    `                  type="button"`,
    `                  class="headless-datepicker-picker-cell"`,
    `                  [tngDatepickerYearOption]="option"`,
    `                >`,
    `                  {{ option.label }}`,
    `                </button>`,
    `              }`,
    `            </div>`,
    `          }`,
    `        </section>`,
    `      </div>`,
    `    </div>`,
    `  </section>`,
    containerClose,
    '',
  ].join('\n');
}

function createHeadlessTailwindHtmlCode(
  containerOpen: string,
  labelLine: string,
  containerClose: string,
): string {
  return [
    containerOpen,
    `  ${labelLine}`,
    `  <section class="block w-[18.5rem] max-w-full [color-scheme:light]" [tngDatepickerHost]="controller">`,
    `    <div class="grid gap-[0.2rem]" data-slot="datepicker-field">`,
    `      <div #anchorShell class="relative">`,
    `        <div`,
    `          class="flex min-h-[2.95rem] min-w-0 w-full overflow-hidden rounded-[1.1rem] border border-slate-300/90 bg-[linear-gradient(180deg,#ffffff_0%,#f8fafc_100%)] shadow-[0_1px_2px_rgba(15,23,42,0.04)] transition-[border-color,box-shadow,background-color] duration-150 focus-within:border-slate-400 focus-within:shadow-[0_0_0_3px_rgba(148,163,184,0.14)] data-[open=true]:border-teal-700 data-[open=true]:shadow-[0_0_0_3px_rgba(15,118,110,0.16)] data-[invalid=true]:border-rose-600 data-[invalid=true]:shadow-[0_0_0_3px_rgba(225,29,72,0.16)]"`,
    `          data-slot="datepicker-input-shell"`,
    `          [attr.data-invalid]="datepicker.outputs().validationError !== null ? 'true' : null"`,
    `          [attr.data-open]="datepicker.outputs().getTriggerAttributes()['data-open']"`,
    `        >`,
    `          <input`,
    `            class="min-h-full min-w-0 flex-1 appearance-none border-0 bg-transparent px-[0.96rem] py-[0.72rem] text-[0.98rem] font-semibold tracking-[0.01em] text-slate-950 outline-none ring-0 focus:outline-none focus:ring-0 placeholder:font-medium placeholder:text-slate-400"`,
    `            [tngDatepickerInput]="controller"`,
    `            type="text"`,
    `            inputmode="numeric"`,
    `            placeholder="MM-DD-YYYY"`,
    `            aria-label="Overview invoice date"`,
    `          />`,
    ``,
    `          <button`,
    `            type="button"`,
    `            class="inline-flex min-w-[3.25rem] shrink-0 items-center justify-center gap-[0.34rem] border-l border-slate-300/80 bg-[linear-gradient(180deg,#ffffff_0%,#f0fdfa_100%)] px-[0.78rem] text-slate-950 transition-colors duration-150 hover:bg-teal-50"`,
    `            [tngDatepickerTrigger]="controller"`,
    `            tabindex="-1"`,
    `            aria-label="Open calendar"`,
    `          >`,
    `            <tng-icon icon="calendar-days" class="size-[1.05rem] shrink-0 text-slate-950" />`,
    `            <span class="text-[0.68rem] leading-none text-slate-500" aria-hidden="true">▾</span>`,
    `          </button>`,
    `        </div>`,
    ``,
    `        <section`,
    `          [tngDatepickerOverlay]="controller"`,
    `          [tngDatepickerOverlayAnchor]="anchorShell"`,
    `          class="grid w-[min(20rem,calc(100vw-2rem))] gap-[0.68rem] rounded-[1.28rem] border border-slate-300/90 bg-[linear-gradient(180deg,#ffffff_0%,#f0fdfa_100%)] p-[0.72rem] text-slate-950 shadow-[0_22px_40px_rgba(15,23,42,0.14),0_10px_18px_rgba(15,23,42,0.08)]"`,
    `        >`,
    `          <header class="grid gap-2" data-slot="datepicker-header">`,
    `            <div class="grid grid-cols-[1.95rem_minmax(0,1fr)_1.95rem] items-center gap-[0.34rem]">`,
    `              <button type="button" class="inline-flex size-[1.95rem] items-center justify-center rounded-[0.82rem] border border-slate-300/90 bg-white/80 text-[1.1rem] leading-none text-slate-950 transition-colors duration-150 hover:bg-teal-50" [tngDatepickerPrevButton]="controller">‹</button>`,
    `              <button`,
    `                type="button"`,
    `                class="inline-flex min-h-[1.95rem] min-w-0 items-center justify-center gap-[0.24rem] rounded-[0.82rem] border border-slate-300/90 bg-white/80 px-[0.72rem] font-semibold text-slate-950 transition-colors duration-150 hover:bg-teal-50"`,
    `                [tngDatepickerPeriodButton]="controller"`,
    `              >`,
    `                <span class="truncate">{{ datepicker.periodLabel() }}</span>`,
    `                @if (datepicker.outputs().view !== 'year') {`,
    `                  <span class="text-[0.68rem] leading-none text-slate-500" aria-hidden="true">▾</span>`,
    `                }`,
    `              </button>`,
    `              <button type="button" class="inline-flex size-[1.95rem] items-center justify-center rounded-[0.82rem] border border-slate-300/90 bg-white/80 text-[1.1rem] leading-none text-slate-950 transition-colors duration-150 hover:bg-teal-50" [tngDatepickerNextButton]="controller">›</button>`,
    `            </div>`,
    `          </header>`,
    ``,
    `          @if (datepicker.outputs().view === 'day') {`,
    `            <div class="grid grid-cols-7 gap-[0.26rem]" data-slot="datepicker-weekdays" aria-hidden="true">`,
    `              @for (label of datepicker.outputs().weekdayLabels; track label) {`,
    `                <span class="text-center text-[0.68rem] font-semibold tracking-[0.02em] text-slate-500" data-slot="datepicker-weekday">{{ label }}</span>`,
    `              }`,
    `            </div>`,
    ``,
    `            <div class="grid grid-cols-7 gap-[0.26rem]" [tngDatepickerDayGrid]="controller">`,
    `              @for (cell of datepicker.outputs().cells; track cell.id) {`,
    `                <button`,
    `                  type="button"`,
    `                  class="min-h-[2.2rem] rounded-[0.82rem] border border-slate-300/90 bg-white/80 text-slate-950 transition-[border-color,box-shadow,background-color,color,opacity] duration-150 hover:bg-teal-50 data-[active=true]:border-teal-300 data-[active=true]:bg-teal-50 data-[active=true]:shadow-[0_0_0_1px_rgba(15,118,110,0.14)] data-[selected=true]:border-teal-400 data-[selected=true]:bg-teal-100 data-[selected=true]:text-teal-800 aria-[current=date]:border-teal-300 aria-[current=date]:shadow-[inset_0_0_0_1px_rgba(15,118,110,0.12)] data-[disabled=true]:cursor-not-allowed data-[disabled=true]:opacity-45"`,
    `                  [tngDatepickerDayCell]="cell"`,
    `                >`,
    `                  {{ cell.label }}`,
    `                </button>`,
    `              }`,
    `            </div>`,
    `          }`,
    ``,
    `          @if (datepicker.outputs().view === 'month') {`,
    `            <div class="grid grid-cols-4 gap-[0.26rem]" [tngDatepickerMonthGrid]="controller">`,
    `              @for (option of datepicker.outputs().monthOptions; track option.id) {`,
    `                <button`,
    `                  type="button"`,
    `                  class="min-h-[2.3rem] rounded-[0.82rem] border border-slate-300/90 bg-white/80 text-slate-950 transition-[border-color,box-shadow,background-color,color,opacity] duration-150 hover:bg-teal-50 data-[active=true]:border-teal-300 data-[active=true]:bg-teal-50 data-[active=true]:shadow-[0_0_0_1px_rgba(15,118,110,0.14)] data-[selected=true]:border-teal-400 data-[selected=true]:bg-teal-100 data-[selected=true]:text-teal-800 data-[disabled=true]:cursor-not-allowed data-[disabled=true]:opacity-45"`,
    `                  [tngDatepickerMonthOption]="option"`,
    `                >`,
    `                  {{ option.label }}`,
    `                </button>`,
    `              }`,
    `            </div>`,
    `          }`,
    ``,
    `          @if (datepicker.outputs().view === 'year') {`,
    `            <div class="grid grid-cols-4 gap-[0.26rem]" [tngDatepickerYearGrid]="controller">`,
    `              @for (option of datepicker.outputs().yearOptions; track option.id) {`,
    `                <button`,
    `                  type="button"`,
    `                  class="min-h-[2.3rem] rounded-[0.82rem] border border-slate-300/90 bg-white/80 text-slate-950 transition-[border-color,box-shadow,background-color,color,opacity] duration-150 hover:bg-teal-50 data-[active=true]:border-teal-300 data-[active=true]:bg-teal-50 data-[active=true]:shadow-[0_0_0_1px_rgba(15,118,110,0.14)] data-[selected=true]:border-teal-400 data-[selected=true]:bg-teal-100 data-[selected=true]:text-teal-800 data-[disabled=true]:cursor-not-allowed data-[disabled=true]:opacity-45"`,
    `                  [tngDatepickerYearOption]="option"`,
    `                >`,
    `                  {{ option.label }}`,
    `                </button>`,
    `              }`,
    `            </div>`,
    `          }`,
    `        </section>`,
    `      </div>`,
    `    </div>`,
    `  </section>`,
    containerClose,
    '',
  ].join('\n');
}

function toPascalCase(value: string): string {
  return value
    .split('-')
    .filter((part) => part.length > 0)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');
}

@Component({
  selector: 'app-headless-datepicker-overview-page',
  imports: [
    TngCodeBlockComponent,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
    TngDatepickerHost,
    TngDatepickerInput,
    TngDatepickerTrigger,
    TngDatepickerPrevButton,
    TngDatepickerPeriodButton,
    TngDatepickerNextButton,
    TngDatepickerDayGrid,
    TngDatepickerDayCell,
    TngDatepickerMonthGrid,
    TngDatepickerMonthOption,
    TngDatepickerYearGrid,
    TngDatepickerYearOption,
    TngDatepickerOverlay,
    TngIcon,
  ],
  templateUrl: './datepicker-overview-page.component.html',
  styleUrl: './datepicker-overview-page.component.css',
})
export class HeadlessDatepickerOverviewPageComponent implements OnDestroy {
  private readonly documentRef = inject(DOCUMENT);

  public readonly codeBlockTheme = signal<'github-dark' | 'github-light'>(
    resolveDocsCodeBlockTheme(this.documentRef),
  );
  private readonly colorSchemeObserver = observeDocsCodeThemeChanges(
    this.documentRef,
    this.codeBlockTheme,
  );

  protected readonly stackblitzVanillaUrl = stackblitzVanillaUrl;
  protected readonly stackblitzTailwindUrl = stackblitzTailwindUrl;

  protected readonly importsCode = [
    "import {",
    "  bindTngDatepicker,",
    "  createDatepickerController,",
    "  TngDatepickerDayCell,",
    "  TngDatepickerDayGrid,",
    "  TngDatepickerHost,",
    "  TngDatepickerInput,",
    "  TngDatepickerMonthGrid,",
    "  TngDatepickerMonthOption,",
    "  TngDatepickerNextButton,",
    "  TngDatepickerOverlay,",
    "  TngDatepickerPeriodButton,",
    "  TngDatepickerPrevButton,",
    "  TngDatepickerTrigger,",
    "  TngDatepickerYearOption,",
    "  TngDatepickerYearGrid,",
    "} from '@tailng-ui/primitives';",
    "import { TngIcon } from '@tailng-ui/icons';",
    '',
  ].join('\n');

  protected readonly usageBaselineCode = [
    'readonly controller = createDatepickerController<Date>({',
    "  ownerDocument: document,",
    "  value: '2024-04-22',",
    "  today: '2024-04-18',",
    "  minDate: '2024-04-01',",
    "  maxDate: '2026-03-31',",
    '  closeOnSelect: true,',
    '  trapFocus: true,',
    '  showOutsideDays: true,',
    '});',
    '',
    'readonly datepicker = bindTngDatepicker(controller);',
    '',
    '// Use the host/input/trigger/nav/grid/cell directives to forward',
    '// the common field, calendar, and keyboard wiring into the primitive.',
    '',
  ].join('\n');

  protected readonly plainController = createDatepickerController<Date>({
    closeOnSelect: true,
    ownerDocument: this.documentRef,
    showOutsideDays: true,
    today: '2024-04-18',
    trapFocus: true,
    value: '2024-04-22',
    minDate: '2024-04-01',
    maxDate: '2026-03-31',
  });

  protected readonly tailwindController = createDatepickerController<Date>({
    closeOnSelect: true,
    ownerDocument: this.documentRef,
    showOutsideDays: true,
    today: '2024-04-18',
    trapFocus: true,
    value: '2024-04-22',
    minDate: '2024-04-01',
    maxDate: '2026-03-31',
  });

  protected readonly plain = bindTngDatepicker(this.plainController);
  protected readonly tailwind = bindTngDatepicker(this.tailwindController);

  protected readonly plainCodeTabs = createCodeTabs(
    'headless-datepicker-overview-plain',
    createHeadlessTsCode('headless-datepicker-overview-plain'),
    createHeadlessHtmlCode(
      '<section class="docs-headless-datepicker-overview-plain-card">',
      '<span class="docs-headless-datepicker-overview-plain-label">Invoice date</span>',
      'docs-headless-datepicker-overview-demo--plain',
      '</section>',
    ),
    [
      headlessSharedCssCode,
      '.docs-headless-datepicker-overview-plain-card {',
      '  display: inline-grid;',
      '  gap: 0.75rem;',
      '  inline-size: max-content;',
      '  max-inline-size: 100%;',
      '  box-sizing: border-box;',
      '  padding-block: 1rem;',
      '  padding-inline: 1rem 2.15rem;',
      '  border: 1px solid #cbd5e1;',
      '  border-radius: 1.25rem;',
      '  background: linear-gradient(180deg, #ffffff 0%, #f8fafc 100%);',
      '  color: #0f172a;',
      '  color-scheme: light;',
      '  box-shadow: 0 14px 34px rgba(15, 23, 42, 0.08);',
      '  justify-items: start;',
      '}',
      '.docs-headless-datepicker-overview-plain-label {',
      '  color: #64748b;',
      '  font-size: 0.8rem;',
      '  font-weight: 700;',
      '  letter-spacing: 0.02em;',
      '}',
      '.docs-headless-datepicker-overview-demo--plain {',
      '  --tng-datepicker-border: #cbd5e1;',
      '  --tng-datepicker-border-strong: #94a3b8;',
      '  --tng-datepicker-bg: #ffffff;',
      '  --tng-datepicker-surface: #f8fafc;',
      '  --tng-datepicker-canvas: #ffffff;',
      '  --tng-datepicker-fg: #0f172a;',
      '  --tng-datepicker-muted: #64748b;',
      '  --tng-datepicker-brand: #2563eb;',
      '  --tng-datepicker-focus: #2563eb;',
      '  --tng-datepicker-focus-shadow: 0 0 0 3px rgba(37, 99, 235, 0.16);',
      '}',
      '',
    ].join('\n'),
  );

  protected readonly tailwindCodeTabs = createCodeTabs(
    'headless-datepicker-overview-tailwind',
    createHeadlessTsCode('headless-datepicker-overview-tailwind'),
    createHeadlessTailwindHtmlCode(
      '<div class="mx-auto grid w-fit max-w-full justify-items-start gap-3 rounded-[1.5rem] border border-slate-200/90 bg-[linear-gradient(180deg,#ffffff_0%,#f8fafc_100%)] p-4 text-slate-900 shadow-[0_18px_38px_rgba(15,23,42,0.10)] [color-scheme:light]">',
      '<span class="text-xs font-semibold uppercase tracking-[0.22em] text-slate-500">Invoice date</span>',
      '</div>',
    ),
    '/* No custom CSS required. Tailwind utilities fully style the field and overlay. */\n',
  );

  public ngOnDestroy(): void {
    this.colorSchemeObserver?.disconnect();

    this.plainController.destroy();
    this.tailwindController.destroy();
  }
}
