import { DOCUMENT } from '@angular/common';
import {
  Component,
  inject,
  signal,
  type OnDestroy,
} from '@angular/core';
import { TngCodeBlockComponent } from '@tailng-ui/components';
import { TngIcon } from '@tailng-ui/icons';
import {
  bindTngDatepicker,
  createDatepickerController,
  TngDatepickerDayCell,
  TngDatepickerDayGrid,
  TngDatepickerHost,
  TngDatepickerInput,
  TngDatepickerMonthGrid,
  TngDatepickerMonthOption,
  TngDatepickerNextButton,
  TngDatepickerOverlay,
  TngDatepickerPeriodButton,
  TngDatepickerPrevButton,
  TngDatepickerTrigger,
  TngDatepickerYearOption,
  TngDatepickerYearGrid,
} from '@tailng-ui/primitives';
import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import {
  observeDocsCodeThemeChanges,
  resolveDocsCodeBlockTheme,
} from '../../../../../../shared/util';
import { stackblitzTailwindUrl, stackblitzVanillaUrl } from '../../datepicker.util';

function createCodeTabs(
  baseName: string,
  tsCode: string,
  htmlCode: string,
  cssCode: string,
): readonly DocsExampleCodeTab[] {
  return Object.freeze([
    { value: 'ts', label: 'TS', language: 'ts', title: `${baseName}.component.ts`, code: tsCode },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: `${baseName}.component.html`,
      code: htmlCode,
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: `${baseName}.component.css`,
      code: cssCode,
    },
  ]);
}

const headlessSharedCssCode = [
  '.headless-datepicker-demo {',
  '  display: block;',
  '  width: min(100%, 18.5rem);',
  '  max-width: 18.5rem;',
  '}',
  '.headless-datepicker-field {',
  '  display: grid;',
  '  gap: 0.2rem;',
  '}',
  '.headless-datepicker-anchor { position: relative; }',
  '.docs-headless-datepicker-overview-demo {',
  '  color-scheme: light;',
  '  --tng-datepicker-radius: 1.1rem;',
  '  --tng-datepicker-field-height: 2.95rem;',
  '  --tng-datepicker-overlay-gap: 0.56rem;',
  '  --tng-datepicker-day-cell-size: 2.2rem;',
  '  --tng-datepicker-picker-cell-size: 2.3rem;',
  '  --tng-datepicker-grid-gap: clamp(0.14rem, 1.15%, 0.28rem);',
  '  --tng-datepicker-inline-gap: 0.36rem;',
  '  --tng-datepicker-overlay-padding: 0.72rem;',
  '  --tng-datepicker-nav-size: 1.95rem;',
  '  --tng-datepicker-shadow:',
  '    0 22px 40px rgba(15, 23, 42, 0.14),',
  '    0 10px 18px rgba(15, 23, 42, 0.08);',
  '}',
  '.headless-datepicker-shell { display: flex; min-inline-size: 0; inline-size: 100%; }',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-input-shell"] {',
  '  box-shadow: 0 1px 2px rgba(15, 23, 42, 0.04);',
  '}',
  '.headless-datepicker-input {',
  '  min-inline-size: 0;',
  '}',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-input"] {',
  '  caret-color: var(--tng-datepicker-brand);',
  '  font-weight: 600;',
  '  letter-spacing: 0.01em;',
  '}',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-input"]::placeholder {',
  '  font-weight: 500;',
  '}',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-trigger"] {',
  '  min-width: calc(var(--tng-datepicker-nav-size) + 0.9rem);',
  '  padding-inline: 0.72rem;',
  '}',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-overlay"] {',
  '  inline-size: min(20rem, calc(100vw - 2rem));',
  '}',
  '.headless-datepicker-overlay { inline-size: min(20rem, calc(100vw - 2rem)); }',
  '.headless-datepicker-trigger,',
  '.headless-datepicker-nav,',
  '.headless-datepicker-period,',
  '.headless-datepicker-cell,',
  '.headless-datepicker-picker-cell {',
  '  font: inherit;',
  '}',
  '.headless-datepicker-trigger-icon {',
  '  width: 1rem;',
  '  height: 1rem;',
  '}',
  '.headless-datepicker-trigger-chevron,',
  '.headless-datepicker-period-chevron {',
  '  font-size: 0.75rem;',
  '  line-height: 1;',
  '}',
  '.headless-datepicker-header {',
  '  display: grid;',
  '  gap: 0.42rem;',
  '}',
  '.headless-datepicker-overlay {',
  '  inline-size: min(20rem, calc(100vw - 2rem));',
  '}',
  '.headless-datepicker-header-row {',
  '  display: grid;',
  '  grid-template-columns: var(--tng-datepicker-nav-size) minmax(0, 1fr) var(--tng-datepicker-nav-size);',
  '  gap: 0.34rem;',
  '  align-items: center;',
  '}',
  '.headless-datepicker-period {',
  '  align-items: center;',
  '  display: inline-flex;',
  '  gap: 0.24rem;',
  '  justify-content: center;',
  '  min-inline-size: 0;',
  '  width: 100%;',
  '}',
  '.headless-datepicker-period-title {',
  '  overflow: hidden;',
  '  text-overflow: ellipsis;',
  '  white-space: nowrap;',
  '}',
  '.headless-datepicker-nav {',
  '  inline-size: var(--tng-datepicker-nav-size);',
  '  min-height: var(--tng-datepicker-nav-size);',
  '  padding: 0;',
  '}',
  '.headless-datepicker-period {',
  '  min-height: var(--tng-datepicker-nav-size);',
  '  padding-inline: 0.72rem;',
  '}',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-nav-button"] {',
  '  inline-size: var(--tng-datepicker-nav-size);',
  '  min-height: var(--tng-datepicker-nav-size);',
  '  padding: 0;',
  '}',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-period-button"] {',
  '  min-height: var(--tng-datepicker-nav-size);',
  '  padding-inline: 0.72rem;',
  '}',
  '.headless-datepicker-weekdays,',
  '.headless-datepicker-day-grid {',
  '  display: grid;',
  '  grid-template-columns: repeat(7, minmax(0, 1fr));',
  '  gap: var(--tng-datepicker-grid-gap);',
  '}',
  '.headless-datepicker-picker-grid {',
  '  display: grid;',
  '  grid-template-columns: repeat(4, minmax(0, 1fr));',
  '  gap: var(--tng-datepicker-grid-gap);',
  '}',
  '.headless-datepicker-cell {',
  '  min-height: var(--tng-datepicker-day-cell-size);',
  '}',
  '.headless-datepicker-picker-cell {',
  '  min-height: var(--tng-datepicker-picker-cell-size);',
  '}',
  '.headless-datepicker-weekdays [data-slot="datepicker-weekday"] { text-align: center; }',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-weekday"] {',
  '  color: color-mix(in srgb, var(--tng-datepicker-muted) 92%, white 8%);',
  '  font-size: 0.68rem;',
  '}',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-cell"][data-active],',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-month"][data-active],',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-year"][data-active] {',
  '  border-color: color-mix(in srgb, var(--tng-datepicker-brand) 36%, var(--tng-datepicker-border) 64%);',
  '  background: color-mix(in srgb, var(--tng-datepicker-brand) 9%, var(--tng-datepicker-surface) 91%);',
  '  box-shadow: 0 0 0 1px color-mix(in srgb, var(--tng-datepicker-brand) 14%, transparent);',
  '}',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-cell"][data-selected],',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-month"][data-selected],',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-year"][data-selected] {',
  '  border-color: color-mix(in srgb, var(--tng-datepicker-brand) 44%, var(--tng-datepicker-border) 56%);',
  '  background: color-mix(in srgb, var(--tng-datepicker-brand) 18%, var(--tng-datepicker-canvas) 82%);',
  '  color: color-mix(in srgb, var(--tng-datepicker-brand) 78%, #0f172a 22%);',
  '}',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-cell"][data-selected][data-active],',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-month"][data-selected][data-active],',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-year"][data-selected][data-active] {',
  '  border-color: color-mix(in srgb, var(--tng-datepicker-brand) 62%, var(--tng-datepicker-border) 38%);',
  '  background: color-mix(in srgb, var(--tng-datepicker-brand) 24%, var(--tng-datepicker-canvas) 76%);',
  '  box-shadow:',
  '    inset 0 1px 0 rgba(255, 255, 255, 0.8),',
  '    0 0 0 1px color-mix(in srgb, var(--tng-datepicker-brand) 18%, transparent);',
  '}',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-cell"][aria-current="date"]:not([data-selected]) {',
  '  border-color: color-mix(in srgb, var(--tng-datepicker-brand) 30%, var(--tng-datepicker-border) 70%);',
  '  box-shadow: inset 0 0 0 1px color-mix(in srgb, var(--tng-datepicker-brand) 12%, transparent);',
  '}',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-cell"]:not([data-in-month]) {',
  '  color: color-mix(in srgb, var(--tng-datepicker-muted) 84%, white 16%);',
  '  opacity: 0.58;',
  '}',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-cell"][data-disabled],',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-month"][data-disabled],',
  '.docs-headless-datepicker-overview-demo [data-slot="datepicker-year"][data-disabled] {',
  '  box-shadow: none;',
  '  opacity: 0.48;',
  '}',
  '',
].join('\n');

function createHeadlessTsCode(className: string): string {
  return [
    "import { Component, type OnDestroy } from '@angular/core';",
    "import { TngIcon } from '@tailng-ui/icons';",
    'import {',
    '  bindTngDatepicker,',
    '  createDatepickerController,',
    '  TngDatepickerDayCell,',
    '  TngDatepickerDayGrid,',
    '  TngDatepickerHost,',
    '  TngDatepickerInput,',
    '  TngDatepickerMonthGrid,',
    '  TngDatepickerMonthOption,',
    '  TngDatepickerNextButton,',
    '  TngDatepickerOverlay,',
    '  TngDatepickerPeriodButton,',
    '  TngDatepickerPrevButton,',
    '  TngDatepickerTrigger,',
    '  TngDatepickerYearOption,',
    '  TngDatepickerYearGrid,',
    "} from '@tailng-ui/primitives';",
    '',
    '@Component({',
    '  standalone: true,',
    '  imports: [',
    '    TngIcon,',
    '    TngDatepickerHost,',
    '    TngDatepickerOverlay,',
    '    TngDatepickerInput,',
    '    TngDatepickerTrigger,',
    '    TngDatepickerPrevButton,',
    '    TngDatepickerPeriodButton,',
    '    TngDatepickerNextButton,',
    '    TngDatepickerDayGrid,',
    '    TngDatepickerDayCell,',
    '    TngDatepickerMonthGrid,',
    '    TngDatepickerMonthOption,',
    '    TngDatepickerYearGrid,',
    '    TngDatepickerYearOption,',
    '  ],',
    `  templateUrl: './${className}.component.html',`,
    `  styleUrl: './${className}.component.css',`,
    '})',
    `export class ${toPascalCase(className)}Component implements OnDestroy {`,
    '  protected readonly controller = createDatepickerController<Date>({',
    "    value: '2024-04-22',",
    "    today: '2024-04-18',",
    "    minDate: '2024-04-01',",
    "    maxDate: '2026-03-31',",
    '    closeOnSelect: true,',
    '    trapFocus: true,',
    '    showOutsideDays: true,',
    '  });',
    '',
    '  protected readonly datepicker = bindTngDatepicker(this.controller);',
    '',
    '  public ngOnDestroy(): void {',
    '    this.controller.destroy();',
    '  }',
    '}',
    '',
  ].join('\n');
}

function createHeadlessHtmlCode(
  containerOpen: string,
  labelLine: string,
  demoClassName: string,
  containerClose: string,
): string {
  return [
    containerOpen,
    `  ${labelLine}`,
    `  <section class="headless-datepicker-demo docs-headless-datepicker-overview-demo ${demoClassName}" [tngDatepickerHost]="controller">`,
    `    <div class="headless-datepicker-field" data-slot="datepicker-field">`,
    `      <div #anchorShell class="headless-datepicker-anchor">`,
    `        <div`,
    `          class="headless-datepicker-shell"`,
    `          data-slot="datepicker-input-shell"`,
    `          [attr.data-invalid]="datepicker.outputs().validationError !== null ? 'true' : null"`,
    `          [attr.data-open]="datepicker.outputs().getTriggerAttributes()['data-open']"`,
    `        >`,
    `          <input`,
    `            class="headless-datepicker-input"`,
    `            [tngDatepickerInput]="controller"`,
    `            type="text"`,
    `            inputmode="numeric"`,
    `            placeholder="MM-DD-YYYY"`,
    `            aria-label="Overview invoice date"`,
    `          />`,
    ``,
    `          <button`,
    `            type="button"`,
    `            class="headless-datepicker-trigger"`,
    `            [tngDatepickerTrigger]="controller"`,
    `            aria-label="Open calendar"`,
    `          >`,
    `            <tng-icon icon="calendar-days" class="headless-datepicker-trigger-icon" />`,
    `            <span class="headless-datepicker-trigger-chevron" aria-hidden="true">▾</span>`,
    `          </button>`,
    `        </div>`,
    ``,
    `        <section`,
    `          [tngDatepickerOverlay]="controller"`,
    `          [tngDatepickerOverlayAnchor]="anchorShell"`,
    `          class="headless-datepicker-overlay"`,
    `        >`,
    `          <header class="headless-datepicker-header" data-slot="datepicker-header">`,
    `            <div class="headless-datepicker-header-row">`,
    `              <button type="button" class="headless-datepicker-nav" [tngDatepickerPrevButton]="controller">‹</button>`,
    `              <button`,
    `                type="button"`,
    `                class="headless-datepicker-period"`,
    `                [tngDatepickerPeriodButton]="controller"`,
    `              >`,
    `                <span class="headless-datepicker-period-title">{{ datepicker.periodLabel() }}</span>`,
    `                @if (datepicker.outputs().view !== 'year') {`,
    `                  <span class="headless-datepicker-period-chevron" aria-hidden="true">▾</span>`,
    `                }`,
    `              </button>`,
    `              <button type="button" class="headless-datepicker-nav" [tngDatepickerNextButton]="controller">›</button>`,
    `            </div>`,
    `          </header>`,
    ``,
    `          @if (datepicker.outputs().view === 'day') {`,
    `            <div class="headless-datepicker-weekdays" data-slot="datepicker-weekdays" aria-hidden="true">`,
    `              @for (label of datepicker.outputs().weekdayLabels; track label) {`,
    `                <span data-slot="datepicker-weekday">{{ label }}</span>`,
    `              }`,
    `            </div>`,
    ``,
    `            <div`,
    `              class="headless-datepicker-day-grid"`,
    `              [tngDatepickerDayGrid]="controller"`,
    `            >`,
    `              @for (cell of datepicker.outputs().cells; track cell.id) {`,
    `                <button`,
    `                  type="button"`,
    `                  class="headless-datepicker-cell"`,
    `                  [tngDatepickerDayCell]="cell"`,
    `                >`,
    `                  {{ cell.label }}`,
    `                </button>`,
    `              }`,
    `            </div>`,
    `          }`,
    ``,
    `          @if (datepicker.outputs().view === 'month') {`,
    `            <div class="headless-datepicker-picker-grid" [tngDatepickerMonthGrid]="controller">`,
    `              @for (option of datepicker.outputs().monthOptions; track option.id) {`,
    `                <button`,
    `                  type="button"`,
    `                  class="headless-datepicker-picker-cell"`,
    `                  [tngDatepickerMonthOption]="option"`,
    `                >`,
    `                  {{ option.label }}`,
    `                </button>`,
    `              }`,
    `            </div>`,
    `          }`,
    ``,
    `          @if (datepicker.outputs().view === 'year') {`,
    `            <div class="headless-datepicker-picker-grid" [tngDatepickerYearGrid]="controller">`,
    `              @for (option of datepicker.outputs().yearOptions; track option.id) {`,
    `                <button`,
    `                  type="button"`,
    `                  class="headless-datepicker-picker-cell"`,
    `                  [tngDatepickerYearOption]="option"`,
    `                >`,
    `                  {{ option.label }}`,
    `                </button>`,
    `              }`,
    `            </div>`,
    `          }`,
    `        </section>`,
    `      </div>`,
    `    </div>`,
    `  </section>`,
    containerClose,
    '',
  ].join('\n');
}

function toPascalCase(value: string): string {
  return value
    .split('-')
    .filter((part) => part.length > 0)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');
}

@Component({
  selector: 'app-headless-datepicker-overview-page',
  imports: [
    TngCodeBlockComponent,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
    TngDatepickerHost,
    TngDatepickerInput,
    TngDatepickerTrigger,
    TngDatepickerPrevButton,
    TngDatepickerPeriodButton,
    TngDatepickerNextButton,
    TngDatepickerDayGrid,
    TngDatepickerDayCell,
    TngDatepickerMonthGrid,
    TngDatepickerMonthOption,
    TngDatepickerYearGrid,
    TngDatepickerYearOption,
    TngDatepickerOverlay,
    TngIcon,
  ],
  templateUrl: './datepicker-overview-page.component.html',
  styleUrl: './datepicker-overview-page.component.css',
})
export class HeadlessDatepickerOverviewPageComponent implements OnDestroy {
  private readonly documentRef = inject(DOCUMENT);

  public readonly codeBlockTheme = signal<'github-dark' | 'github-light'>(
    resolveDocsCodeBlockTheme(this.documentRef),
  );
  private readonly colorSchemeObserver = observeDocsCodeThemeChanges(
    this.documentRef,
    this.codeBlockTheme,
  );

  protected readonly stackblitzVanillaUrl = stackblitzVanillaUrl;
  protected readonly stackblitzTailwindUrl = stackblitzTailwindUrl;

  protected readonly importsCode = [
    "import {",
    "  bindTngDatepicker,",
    "  createDatepickerController,",
    "  TngDatepickerDayCell,",
    "  TngDatepickerDayGrid,",
    "  TngDatepickerHost,",
    "  TngDatepickerInput,",
    "  TngDatepickerMonthGrid,",
    "  TngDatepickerMonthOption,",
    "  TngDatepickerNextButton,",
    "  TngDatepickerOverlay,",
    "  TngDatepickerPeriodButton,",
    "  TngDatepickerPrevButton,",
    "  TngDatepickerTrigger,",
    "  TngDatepickerYearOption,",
    "  TngDatepickerYearGrid,",
    "} from '@tailng-ui/primitives';",
    "import { TngIcon } from '@tailng-ui/icons';",
    '',
  ].join('\n');

  protected readonly usageBaselineCode = [
    'readonly controller = createDatepickerController<Date>({',
    "  ownerDocument: document,",
    "  value: '2024-04-22',",
    "  today: '2024-04-18',",
    "  minDate: '2024-04-01',",
    "  maxDate: '2026-03-31',",
    '  closeOnSelect: true,',
    '  trapFocus: true,',
    '  showOutsideDays: true,',
    '});',
    '',
    'readonly datepicker = bindTngDatepicker(controller);',
    '',
    '// Use the host/input/trigger/nav/grid/cell directives to forward',
    '// the common field, calendar, and keyboard wiring into the primitive.',
    '',
  ].join('\n');

  protected readonly plainController = createDatepickerController<Date>({
    closeOnSelect: true,
    ownerDocument: this.documentRef,
    showOutsideDays: true,
    today: '2024-04-18',
    trapFocus: true,
    value: '2024-04-22',
    minDate: '2024-04-01',
    maxDate: '2026-03-31',
  });

  protected readonly tailwindController = createDatepickerController<Date>({
    closeOnSelect: true,
    ownerDocument: this.documentRef,
    showOutsideDays: true,
    today: '2024-04-18',
    trapFocus: true,
    value: '2024-04-22',
    minDate: '2024-04-01',
    maxDate: '2026-03-31',
  });

  protected readonly plain = bindTngDatepicker(this.plainController);
  protected readonly tailwind = bindTngDatepicker(this.tailwindController);

  protected readonly plainCodeTabs = createCodeTabs(
    'headless-datepicker-overview-plain',
    createHeadlessTsCode('headless-datepicker-overview-plain'),
    createHeadlessHtmlCode(
      '<section class="docs-headless-datepicker-overview-plain-card">',
      '<span class="docs-headless-datepicker-overview-plain-label">Invoice date</span>',
      'docs-headless-datepicker-overview-demo--plain',
      '</section>',
    ),
    [
      headlessSharedCssCode,
      '.docs-headless-datepicker-overview-plain-card {',
      '  display: grid;',
      '  gap: 0.75rem;',
      '  width: min(100%, 22rem);',
      '  margin-inline: auto;',
      '  padding: 1rem;',
      '  border: 1px solid #cbd5e1;',
      '  border-radius: 1.25rem;',
      '  background: linear-gradient(180deg, #ffffff 0%, #f8fafc 100%);',
      '  color: #0f172a;',
      '  color-scheme: light;',
      '  box-shadow: 0 14px 34px rgba(15, 23, 42, 0.08);',
      '}',
      '.docs-headless-datepicker-overview-plain-label {',
      '  color: #64748b;',
      '  font-size: 0.8rem;',
      '  font-weight: 700;',
      '  letter-spacing: 0.02em;',
      '}',
      '.docs-headless-datepicker-overview-demo--plain {',
      '  --tng-datepicker-border: #cbd5e1;',
      '  --tng-datepicker-border-strong: #94a3b8;',
      '  --tng-datepicker-bg: #ffffff;',
      '  --tng-datepicker-surface: #f8fafc;',
      '  --tng-datepicker-canvas: #ffffff;',
      '  --tng-datepicker-fg: #0f172a;',
      '  --tng-datepicker-muted: #64748b;',
      '  --tng-datepicker-brand: #2563eb;',
      '  --tng-datepicker-focus: #2563eb;',
      '  --tng-datepicker-focus-shadow: 0 0 0 3px rgba(37, 99, 235, 0.16);',
      '}',
      '',
    ].join('\n'),
  );

  protected readonly tailwindCodeTabs = createCodeTabs(
    'headless-datepicker-overview-tailwind',
    createHeadlessTsCode('headless-datepicker-overview-tailwind'),
    createHeadlessHtmlCode(
      '<div class="mx-auto grid w-full max-w-[22rem] gap-3 rounded-[1.5rem] border border-slate-200/90 bg-[linear-gradient(180deg,#ffffff_0%,#f8fafc_100%)] p-4 text-slate-900 shadow-[0_18px_38px_rgba(15,23,42,0.10)] [color-scheme:light]">',
      '<span class="text-xs font-semibold uppercase tracking-[0.22em] text-slate-500">Invoice date</span>',
      'docs-headless-datepicker-overview-demo--tailwind',
      '</div>',
    ),
    [
      headlessSharedCssCode,
      '.docs-headless-datepicker-overview-demo--tailwind {',
      '  --tng-datepicker-border: #cbd5e1;',
      '  --tng-datepicker-border-strong: #94a3b8;',
      '  --tng-datepicker-bg: #ffffff;',
      '  --tng-datepicker-surface: #f0fdfa;',
      '  --tng-datepicker-canvas: #ffffff;',
      '  --tng-datepicker-fg: #0f172a;',
      '  --tng-datepicker-muted: #5f6f88;',
      '  --tng-datepicker-brand: #0f766e;',
      '  --tng-datepicker-focus: #0f766e;',
      '  --tng-datepicker-focus-shadow: 0 0 0 3px rgba(15, 118, 110, 0.16);',
      '}',
      '',
    ].join('\n'),
  );

  public ngOnDestroy(): void {
    this.colorSchemeObserver?.disconnect();

    this.plainController.destroy();
    this.tailwindController.destroy();
  }
}
