import { Component } from '@angular/core';
import { TngCodeBlockComponent } from '@tailng-ui/components';

@Component({
  selector: 'app-headless-stepper-styling-page',
  imports: [TngCodeBlockComponent],
  templateUrl: './stepper-styling-page.component.html',
  styleUrls: ['./stepper-styling-page.component.css'],
})
export class HeadlessStepperStylingPageComponent {
  protected readonly cssStarterCode = [
    '[data-slot="stepper"] {',
    '  display: grid;',
    '  gap: 0.75rem;',
    '}',
    '',
    '[data-slot="stepper-item"] {',
    '  border: 1px solid var(--tng-semantic-border-subtle);',
    '  border-radius: 0.5rem;',
    '  padding: 0.75rem;',
    '}',
    '',
    '[data-slot="stepper-trigger"] {',
    '  align-items: center;',
    '  appearance: none;',
    '  background: transparent;',
    '  border: 0;',
    '  color: inherit;',
    '  display: inline-flex;',
    '  gap: 0.5rem;',
    '}',
    '',
    '[data-slot="stepper-trigger"]:focus-visible {',
    '  outline: 2px solid var(--tng-semantic-accent-brand);',
    '  outline-offset: 3px;',
    '}',
    '',
    '[data-slot="stepper-item"][data-state="current"] {',
    '  border-color: var(--tng-semantic-accent-brand);',
    '}',
    '',
    '[data-slot="stepper-item"][data-state="completed"] {',
    '  border-color: var(--tng-semantic-accent-success);',
    '}',
    '',
    '[data-slot="stepper-item"][data-state="error"] {',
    '  border-color: var(--tng-semantic-accent-danger);',
    '}',
  ].join('\n');
}
